### ISSUE TITLE
[typescript-node] Runtime error when using array definitions

### ISSUE THREAD

**Issue by lupus92** [swagger-api/swagger-codegen#10000]
#### Description
When using arrays in definitions (swagger 2.0), an error occures when calling the api via the generated code (typescript-node):
```
TypeError: typeMap[type].getAttributeTypeMap is not a function
    at Function.deserialize ((...)\generated-client\api.ts:128:48)
    at Request.localVarRequest [as _callback] ((...)\generated-client\api.ts:653:45)
    at Request.self.callback ((...)\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> ((...)\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> ((...)\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
at the following code line:
`let attributeTypes = typeMap[type].getAttributeTypeMap();`

The requested definition `typeMap[type]` is `LocationGetResponse`, which is an array (see below). So the error is comprehensible because the class definition is
`export class LocationGetResponse extends Array<LocationGetResponseInner>`
-> getAttributeTypeMap only exists for the array elements, not the array itself.

#### Swagger-codegen version

Same error with current master (2.4.13) and older versions (2.4.9 - 2.4.12)

#### Swagger declaration file content or url

```yaml
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "MyAPI"``

paths:
  /location:
    get:
      x-swagger-router-controller: "location"
      operationId: "location_get"
      summary: "..."
      description: ""
      parameters:
        - name: "input"
          in: "query"
          description: "search string"
          required: true
          pattern: '^.+$'
          type: "string"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationGetResponse"

definitions:
  LocationGetResponse:
    type: "array"
    items:
      type: "object"
      required:
        - id
        - text
      properties:
        id:
          type: "string"
          description: "ID of location"
        text:
          type: "string"
          description: "Name of location"
```
#### Command line used for generation

`java -jar swagger-codegen-cli-2.4.12.jar generate --input-spec api.yaml --lang typescript-node --config typescript-node.json`

with typescript-node.json:
```json
{
    "supportsES6": true
}
```
#### Steps to reproduce

You need at least a small dummy server which produces request results.

1. generate `api.ts` via swagger-codegen
2. Try to call the location method

#### Suggest a fix/enhancement

Maybe checking for array type before reaching the throwing line...

PS: I'm looking forward generating typescript-node for openapi3 :)

**Comment by Deborah-Digges** [comment]
+1 also facing this while generating a client for the Strava API using swagger code-gen👍 

Details:
1. Swagger Spec: https://developers.strava.com/swagger/swagger.json
2. Command used to generate client: `swagger-codegen generate --input-spec https://developers.strava.com/swagger/swagger.json --lang typescript-node`
3. Error: Same as listed above: `TypeError: typeMap[type].getAttributeTypeMap is not a function`

**Comment by arimus** [comment]
I think I found the root cause of this. There was another patch to handle dealing with arrays models, which disabled the needed function. I was able to patch the mustache file and rebuild, which appears to have resolved the issue. I've attached the diff against master. Hope this helps someone else:

```
diff --git a/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache b/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
index 0cd9eb781..0dc5bf6f2 100644
--- a/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
+++ b/modules/swagger-codegen/src/main/resources/typescript-node/api.mustache
@@ -151,6 +151,22 @@ export class {{classname}} {{#parent}}extends {{{parent}}} {{/parent}}{
     static discriminator: string | undefined = undefined;
     {{/discriminator}}
 
+    {{#isArrayModel}}
+    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
+        {{#vars}}
+        {
+            "name": "{{name}}",
+            "baseName": "{{baseName}}",
+            "type": "{{#isEnum}}{{{datatypeWithEnum}}}{{/isEnum}}{{^isEnum}}{{{datatype}}}{{/isEnum}}"
+        }{{#hasMore}},
+        {{/hasMore}}
+        {{/vars}}
+    ];
+
+    static getAttributeTypeMap() {
+        return {{classname}}.attributeTypeMap;
+    }
+    {{/isArrayModel}}    
     {{^isArrayModel}}
     static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
         {{#vars}}
```
