### ISSUE TITLE
[Python] NameError: name 'Category' is not defined from the generated flask server

### ISSUE THREAD

**Issue by kannkyo** [swagger-api/swagger-codegen#10193]
##### Description

When I run flask-server, I get bellow ImportError.

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/swagger_server/__main__.py", line 5, in <module>
    from swagger_server import encoder
  File "/usr/src/app/swagger_server/encoder.py", line 4, in <module>
    from swagger_server.models.base_model_ import Model
  File "/usr/src/app/swagger_server/models/__init__.py", line 9, in <module>
    from swagger_server.models.pet import Pet
  File "/usr/src/app/swagger_server/models/pet.py", line 12, in <module>
    class Pet(Model):
  File "/usr/src/app/swagger_server/models/pet.py", line 18, in Pet
    def __init__(self, id: int=None, category: Category=None, name: str=None, photo_urls: List[str]=None, tags: List[Tag]=None, status: str=None):  # noqa: E501
NameError: name 'Category' is not defined
```

##### Swagger-codegen version

2.4.13

##### Swagger declaration file content or url

https://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

I generate from swagger-editor.

##### Steps to reproduce

```shell
docker build -t swagger_server .
docker run -p 8080:8080 swagger_server
```

##### Related issues/PRs

nothing

##### Suggest a fix/enhancement

I can fix this bug when adding two line in `./swagger_server/models/pet.py` .

```diff
  from swagger_server.models.base_model_ import Model
+ from swagger_server.models.category import Category
+ from swagger_server.models.tag import Tag
  from swagger_server import util
```

**Comment by fastchain** [comment]
Same issue

**Comment by babyalgebraist** [comment]
Same issue to report

- using SwaggerUI on SwaggerHub with GitHub integration to export python-flask server stub with Swagger Codegen, which I understand uses [generator.swagger.io](https://generator.swagger.io) which is at time of writing is  **v2.4.15**.  

- Successful responses have a JSON body referencing, `#/definitions/MainThingy`, an object containing three properties. The third of these properties takes an array of `Thingy` objects. As defined:

```yaml
MainThingy:
    description: The defacto body of the response sent back to Piecemeal
    type: object
    required:    
    - MainProp1
    - MainProp2
    - MainProp3
    properties:
      MainProp1:
        type: string
        format: date
        example: "2020-06-16 19:10:02"
      MainProp2:
        type: number
        format: float
        example: 24.99
      MainProp3:
        type: array
        items:
          $ref: '#/definitions/Thingy'
  
  Thingy:
    type: object
    required:    
    - prop1
    - prop2
    - prop3
    properties:
      prop1:
        type: string
        example: "1234"
      prop2:
        type: string
        example: "abcd"
      prop3:
        type: array
        items:
            type: string
```

By using workaround from @kannkyo, the server runs as expected with the exception of visiting the **ui** url throwing a 404/Not Found. 

The workaround is:
> ##### Suggest a fix/enhancement
> I can fix this bug when adding two line in `./swagger_server/models/pet.py` .
> 
> ```diff
>   from swagger_server.models.base_model_ import Model
> + from swagger_server.models.category import Category
> + from swagger_server.models.tag import Tag
>   from swagger_server import util
> ```

My case:
```diff
# ./swagger_server/models/main_thingy.py
# importing `Thingy` in the model definition in `MainThingy` the composed model definition

from swagger_server.models.base_model_ import Model
from swagger_server.models.thingy import (
    Thingy,
)
from swagger_server import util
```

**Comment by jick68** [comment]
same issue when attempting to deploy a python-flask-server dockerfile generated from the swagger-editor

**Comment by bizulk** [comment]
confirmed also with me, with the python generated code for server.

**Comment by ramdyne** [comment]
It looks like the generated types from definitions in the specification are not imported by the "functionality" models.  I'll look into changes that might relate to this, because it suggests that no-one has ever used the Flask generator on a little more complex API (with this version?). Somehow I find that hard to believe.

> java -jar swagger-codegen-cli.jar version
2.4.25
>

I also had the same issue with the online version.
