### ISSUE TITLE
[Swift5] Can't use templates

### ISSUE THREAD

**Issue by lmvdev** [swagger-api/swagger-codegen#10267]
##### Description
There is the error FileNotFoundException when I use -t parameter for language Swift5

command line log:
```Exception in thread "Thread-0" java.lang.RuntimeException: Could not generate model 'AdditionalInfoModel'
at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:451)
at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:369)
at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.FileNotFoundException: handlebars/swift5/model.mustache
at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:438)
at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:419)
at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getHandlebars(HandlebarTemplateEngine.java:48)
at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:24)
at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:795)
at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:438)
... 3 more
```

##### Swagger-codegen version
3.0.20

##### Command line used for generation
`swagger-codegen generate -i PATH_TO_JSON -l swift5 -t PATH_TO_TEMPLATES -o OUTPUT_PATH`

##### Steps to reproduce
Run the command above

##### Related issues/PRs
https://github.com/swagger-api/swagger-codegen/issues/10107

##### Suggest a fix/enhancement
https://github.com/swagger-api/swagger-codegen-generators/commit/1149e58bc6a54b54f3ac232a6f4e7e5ed5912f0b
Make similar changes to the swift5 codegen file

**Comment by HugoMario** [comment]
fixed by [swagger-codegen-generators#721](https://app.zenhub.com/workspace/o/swagger-api/swagger-codegen-generators/issues/721)
