### ISSUE TITLE
[typescript-fetch] Error generating api.ts when there is an enum type schema

### ISSUE THREAD

**Issue by mikealameh** [swagger-api/swagger-codegen#10274]
##### Description

When I define an enum type schema under `schemas`, I get the following error during codegen for language `typescript-fetch`:

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
	templateFile: api.mustache
	folder: 
	destinationFilename: api.ts
'
	at io.swagger.codegen.v3.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:663)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:786)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:369)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/typescript-fetch/modelEnum.mustache:9:37: found: '-last', expected: 'no viable alternative at input '{{^-last''
    {{{name}}} = <any> {{{value}}}{{^-last}},{{/-last}}
                                     ^
	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at com.github.jknack.handlebars.internal.antlr.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at com.github.jknack.handlebars.internal.antlr.Parser.notifyErrorListeners(Parser.java:544)
	at com.github.jknack.handlebars.internal.antlr.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportNoViableAlternative(HbsErrorStrategy.java:166)
	at com.github.jknack.handlebars.internal.antlr.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at com.github.jknack.handlebars.internal.HbsParser.elseBlock(HbsParser.java:982)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:681)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:337)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:673)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:337)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:86)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:513)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:490)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:214)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.Options.fn(Options.java:433)
	at com.github.jknack.handlebars.helper.IfHelper.apply(IfHelper.java:53)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.Options.fn(Options.java:445)
	at com.github.jknack.handlebars.helper.WithHelper.apply(WithHelper.java:58)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:73)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:25)
	at io.swagger.codegen.v3.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:634)
	... 3 more
```

##### Swagger-codegen version

3.0.20

##### Swagger declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
  description: Test API
paths:
  '/test':
    get:
      tags:
        - Test
      summary: Test route
      operationId: getTestItem
      responses:
        '200':
          $ref: '#/components/responses/TestResponse'
components:
  schemas:
    MyEnum:
      type: string
      enum:
        - "value1"
        - "value2"
  responses:
    TestResponse:
      description: The OK response for retrieving the test item.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MyEnum'
```

##### Command line used for generation

`java -jar swagger-codegen-cli-3.0.20.jar generate -i swagger.yml -l typescript-fetch`

**Comment by HugoMario** [comment]
Hey guys, the error is not because enumeration, it's an error on template syntax.
And it was fixed on [this commit](https://github.com/swagger-api/swagger-codegen-generators/commit/8526e0efcee819365d73e976c47ae5f0068b5aaf)
