### ISSUE TITLE
java.lang.NullPointerException when running config-help

### ISSUE THREAD

**Issue by jasonpolites** [swagger-api/swagger-codegen#10365]
##### Description

The documentation at https://github.com/swagger-api/swagger-codegen#getting-started seems incorrect, and the CLI command surface for the `config-help` command seems broken. I was just trying to find out what String to use for the "language" to be able to generate a client API for Node.js

##### Swagger-codegen version

3.0.20

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

At first I followed the README and executed this command:

```
java -jar swagger-codegen-cli.jar help generate
```

This produces an error:

```
swagger-codegen: error: invalid choice: 'help' (choose from 'generate', 'config-help', 'meta', 'langs', 'version')
```

OK.. so maybe I'll try `config-help`..

```
java -jar swagger-codegen-cli.jar config-help
```

This also results in an error:

```
Exception in thread "Thread-1" java.lang.NullPointerException
        at java.lang.String.concat(String.java:2027)
        at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
        at io.swagger.codegen.v3.cli.cmd.ConfigHelp.run(ConfigHelp.java:17)
        at java.lang.Thread.run(Thread.java:748)
```

Finally realized there's a `langs` command, but sadly swagger-codegen doesn't support generating client APIs for node.js :(

(which seems odd btw)

**Comment by alanboy** [comment]
That documentation url is not for version 3 of codegen. Codegen version 3 documentation can be found here: https://github.com/swagger-api/swagger-codegen/tree/3.0.0#getting-started.

The v3 docs have the correct arguments:

> To get a list of general options available, please run java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate --help

I do think it's not ideal that the command should crash on `config-help`:

```
java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar config-help

Exception in thread "Thread-1" java.lang.NullPointerException
        at java.lang.String.concat(String.java:2027)
        at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
        at io.swagger.codegen.v3.cli.cmd.ConfigHelp.run(ConfigHelp.java:17)
        at java.lang.Thread.run(Thread.java:745)
```

This is happening because that command seems to require the language argument; if we add it, it works:

```
java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar config-help -l typescript-angular

CONFIG OPTIONS
        sortParamsByRequiredFlag
            Sort method arguments to place required parameters before optional parameters. (Default: true)

        ensureUniqueParams
            Whether to ensure parameter names are unique in an operation (rename parameters that are not). (Default: true)

        <... truncated ...>
```

I'll see how easy is to send a PR to make this better.

**Comment by alanboy** [comment]
Here it is: https://github.com/swagger-api/swagger-codegen/pull/10398
