### ISSUE TITLE
[JAVA SPRING] Null pointer exception when specification doesn't have components

### ISSUE THREAD

**Issue by tnpradeep** [swagger-api/swagger-codegen#10370]
##### Description

when the open API specification doesn't contain components then null pointer exception is thrown while generating models.
Error:
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:334)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
	at org.specocode.codegen.CodeGenerator.generateServerStub(CodeGenerator.java:73)
	at org.specocode.codegen.CodeGenerator.main(CodeGenerator.java:207)

##### Swagger-codegen version

3.0.20

##### Swagger declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Swagger Isuite
  description: '<p>This is a sample server Petstore server. You can find out more
    about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/). For this sample, you can use the api key `special-key`
    to test the authorization filters.</p>'
  version: 1.0.0
servers:
- url: https://api.pethub.com/pethub
- url: http://api.pethub.com/pethub
paths:
  /store:
    description: store details
    get:
      description: get all stores
      responses:
        200:
          description: store information details
          content:
            'application/json':
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  location:
                    type: string
                  pincode:
                    type: number
```

##### Steps to reproduce

1. Parse json and get OpenAPI object
2. Config used for codegen is as below,
    CodegenConfig config = CodegenConfigLoader.forName(language);
    ((SpringCodegen) config).setApiPackage("api");
    ((SpringCodegen) config).setArtifactId("org.specocode.pet");
    ((SpringCodegen) config).setBasePackage("org.specocode");
    ((SpringCodegen) config).setArtifactVersion("1.0.0");
    ((SpringCodegen) config).setModelPackage("model");
    ((SpringCodegen) config).setConfigPackage("config");
    ((SpringCodegen) config).setGroupId("org.specocode");
    ((SpringCodegen) config).setJava8(true);
    ((SpringCodegen) config).setLibrary("spring-boot");
    ((SpringCodegen) config).setDelegatePattern(true);
    config.additionalProperties().put("basePackage", "org.specocode");
    config.setOutputDir("someOutputfolder");

**Comment by ElpyazYasarla** [comment]
Yes the issue is due to no components attribute in the yaml file.  Add  components: { }  at the end of yaml.  My issue got resolved after adding this.
