### ISSUE TITLE
swagger-codegen 3.0.23 build issue

### ISSUE THREAD

**Issue by chenrui333** [swagger-api/swagger-codegen#10543]
👋  run into some OSX build issue the error log is as below.

```
12:21:09.078 [main] INFO  i.s.v.g.online.GeneratorController - using destination path 
12:21:09.152 [main] DEBUG i.s.v.g.online.GeneratorController - generate start - lang: java, version: V3, specURL: null, spec: {
  "openapi" : "3.0.0",
  "servers" : [, 
12:21:09.153 [main] ERROR i.s.v.g.u.FileAccessSecurityManager - Blocking attempt to write to not allowed directory for file /var/folders/g4/hmj3z8n96sb6nldr3_0gm7040000gp/T/codegen-4708154575602983896-tmp
java.lang.SecurityException: Unable to create temporary file
```

relates to https://github.com/Homebrew/homebrew-core/pull/63950

**Comment by MZar2019** [comment]
Same issue building 3.0.24-SNAPSHOT on Windows 10 x64.

08:02:51.227 [main] INFO  i.s.v.g.online.GeneratorController - using destination path
08:02:51.664 [main] DEBUG i.s.v.g.online.GeneratorController - generate start - lang: java, version: V3, specURL: null, spec: {
  "openapi" : "3.0.0",
  "servers" :,
08:02:51.668 [main] ERROR i.s.v.g.u.FileAccessSecurityManager - Blocking attempt to write to not allowed directory for file C:\Users\zarlenm\AppData\Local\Temp\codegen-9046667022939908369-tmp
java.lang.SecurityException: Unable to create temporary file
...
08:02:51.675 [main] INFO  i.s.v.g.online.GeneratorController - using destination path testoutputFolder
08:02:51.678 [main] ERROR i.s.v.g.u.FileAccessSecurityManager - Blocking attempt to write to not allowed directory for file C:\Users\zarlenm\AppData\Local\Temp\codegen-397002244363719941-tmp
java.lang.SecurityException: Unable to create temporary file
...
[INFO] Reactor Summary for swagger-codegen-project 3.0.24-SNAPSHOT:
[INFO]
[INFO] swagger-codegen-project ............................ SUCCESS [ 24.516 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [02:40 min]
[INFO] swagger-codegen (executable) ....................... SUCCESS [ 33.909 s]
[INFO] swagger-codegen (maven-plugin) ..................... SUCCESS [ 23.161 s]
[INFO] swagger-generator .................................. FAILURE [01:18 min]
[INFO] ------------------------------------------------------------------------

**Comment by crisim** [comment]
same problem on window with GIT Bash

[INFO] Running io.swagger.v3.generator.online.GeneratorControllerTest
10:49:27,340 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:49:27,340 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:49:27,340 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/Development/swagger/swagger-codegen/modules/swagger-generator/target/classes/logback.xml]
10:49:27,340 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
10:49:27,340 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/D:/Development/swagger/swagger-codegen/modules/swagger-generator/target/classes/logback.xml]
10:49:27,340 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/Users/Cristian/.m2/repository/io/swagger/codegen/v3/swagger-codegen-generators/1.0.23/swagger-codegen-generators-1.0.23.jar!/logback.xml]
10:49:27,387 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:49:27,387 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:49:27,387 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:49:27,387 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
10:49:27,402 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.swagger] to ERROR
10:49:27,402 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty.server] to INFO
10:49:27,402 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [io.swagger.v3.generator.online] to DEBUG
10:49:27,402 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
10:49:27,402 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:49:27,402 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:49:27,402 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5d0bf09b - Registering current configuration as safe fallback point

10:49:27.494 [main] DEBUG i.s.v.g.online.GeneratorController - Parsed hidden options config
10:49:27.494 [main] DEBUG i.s.v.g.online.GeneratorController - Hidden clients: [ada, bash, eiffel, elixir, erlang-client, haskell-http-client, lua, powershell, r, rust, scalaz, typescript-aurelia, typescript-jquery, elm]
10:49:27.509 [main] DEBUG i.s.v.g.online.GeneratorController - Hidden servers: [finch, java-play-framework, java-vertx, jaxrs-resteasy-eap, php-symfony, pistache-server, restbed, rust-server, ze-ph, ada-server, java-pkmst, scala-lagom-server]
10:49:27.509 [main] DEBUG i.s.v.g.online.GeneratorController - Hidden clientsV3: [html]
10:49:27.509 [main] DEBUG i.s.v.g.online.GeneratorController - Hidden serversV3: []
10:49:27.978 [main] DEBUG i.s.v.g.online.GeneratorController - generate start - lang: bash, version: V2, specURL: null, spec: {
  "swagger" : "2.0",
  "info" : {
 ,
10:49:27.978 [main] ERROR i.s.v.g.u.FileAccessSecurityManager - Blocking attempt to write to not allowed directory for file C:\Users\Cristian\AppData\Local\Temp\codegen-113049821228939730-tmp
java.lang.SecurityException: Unable to create temporary file
        at java.io.File.createTempFile(File.java:2018)
        at java.io.File.createTempFile(File.java:2070)
        at io.swagger.v3.generator.online.GeneratorController.getTmpFolder(GeneratorController.java:484)
        at io.swagger.v3.generator.online.GeneratorController.generate(GeneratorController.java:434)

**Comment by chenrui333** [comment]
Ping @HugoMario @frantuma
