### ISSUE TITLE
Unable to load RELATIVE ref: ../../models/BadRequest.yaml path: /

### ISSUE THREAD

**Issue by 4n70w4** [swagger-api/swagger-codegen#10542]
##### Description

This works:

```yaml
  responses:
    200:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../../models/GetSessionListResponse.yaml'
```

This also work:

```yaml
  responses:
    400:
      $ref: './openapi/models/BadRequest.yaml'
```

But this don't work:

```yaml
  responses:
    400:
      $ref: '../../models/BadRequest.yaml'
```

```
19:09:07.732 [Thread-0] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.RuntimeException: Unable to load RELATIVE ref: ../../models/BadRequest.yaml path: /
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:239)
        at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:119)
        at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalResponse(ExternalRefProcessor.java:344)
        at io.swagger.v3.parser.processors.ResponseProcessor.processReferenceResponse(ResponseProcessor.java:84)
        at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:41)
        at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:56)
        at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
        at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:172)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:153)
        at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at io.swagger.codegen.v3.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:517)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:376)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Could not find ../../models/BadRequest.yaml on the classpath
        at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:233)
        ... 14 common frames omitted
19:09:07.737 [Thread-0] WARN  io.swagger.v3.parser.OpenAPIV3Parser - Exception while resolving:
java.lang.RuntimeException: Unable to load RELATIVE ref: ../../models/BadRequest.yaml path: /
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:239)
        at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:119)
        at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalResponse(ExternalRefProcessor.java:344)
        at io.swagger.v3.parser.processors.ResponseProcessor.processReferenceResponse(ResponseProcessor.java:84)
        at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:41)
        at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:56)
        at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
        at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
        at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:172)
        at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:153)
        at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at io.swagger.codegen.v3.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:526)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:376)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.RuntimeException: Could not find ../../models/BadRequest.yaml on the classpath
        at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:233)
        ... 14 common frames omitted
Exception in thread "Thread-0" java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.Components.getSchemas()" because the return value of "io.swagger.v3.oas.models.OpenAPI.getComponents()" is null
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:334)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:378)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

##### Swagger-codegen version

swagger-codegen-cli-3.0.22.jar

##### Swagger declaration file content or url

```yaml
openapi: 3.0.1

paths:
  /system/getSessionList:
    $ref: './paths/system/getSessionList.yaml'
```

paths/system/getSessionList.yaml:

```yaml
get:
  tags:
  - system
  summary: Get session list
  description: Multiple values
  operationId: getSessionList
  responses:
    200:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../../models/GetSessionListResponse.yaml'
    400:
      $ref: '../../models/BadRequest.yaml'
```

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local -w /local openjdk java -jar swagger-codegen-cli.jar generate --input-spec /local/openapi.yaml --lang openapi-yaml --output /local/out/ -c /local/openapi-codegen-php.json
```

**Comment by JanChytry** [comment]
I have the same problem on 3.0.27.

**Comment by thebpmgroup** [comment]
Any update on this?

**Comment by ena1106** [comment]
Same error happened to me because I was referencing the wrong kind of object (in my case a parameter instead of a schema).
