### ISSUE TITLE
In golang, Int enums with named fields generate errors

### ISSUE THREAD

**Issue by YurShaz** [swagger-api/swagger-codegen#10583]
##### Description

If we have an enum definition
```
definitions:
  MyEnumType:
    type: integer
    format: int32
    x-numerical-enum: true
    enum:
    - Value
    - AnotherValue
    - Whatever
```

On v3.0.20 this produces a Java exception:
```
Exception in thread "Thread-1" java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Number` from String "Value": not a valid number                                         
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.media.IntegerSchema["enum"]->java.util.ArrayList[0])                                                         
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3938)                                                                                                                     
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3869)                                                                                                                 
        at io.swagger.v3.core.util.ModelDeserializer.deserialize(ModelDeserializer.java:53)                                                                                                                 
        at io.swagger.v3.core.util.ModelDeserializer.deserialize(ModelDeserializer.java:28)                                                                                                                 
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3933)                                                                                                                     
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3869)                                                                                                                 
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1204)                                                                                                              
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:260)                                                                                                               
        at io.swagger.v3.parser.converter.SwaggerConverter.readResult(SwaggerConverter.java:110)                                                                                                           
        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:91)                                                                                                           
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)                                                                                                                              
        at io.swagger.codegen.v3.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:517)                                                                                                  
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:367)                                                                                                                                    
        at java.lang.Thread.run(Thread.java:748)                                                                                                                                                            
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Number` from String "Value": not a valid number                                       
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: io.swagger.v3.oas.models.media.IntegerSchema["enum"]->java.util.ArrayList[0])                                                         
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)                                                                                                   
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1679)                                                                                     
        at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:935)                                                                                    
        at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$NumberDeserializer.deserialize(NumberDeserializers.java:826)                                                                        
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)                                                                                     
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)                                                                                     
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)                                                                                      
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)                                                                                              
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)                                                                                              
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)                                                                                                     
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3933)                                                                                                                     
        ... 13 more                                                                                                                           
```

On v2.4.2 this compiles, but produces code that doesn't compile:
```
package swagger

type MyEnumType int32

// List of MyEnumType
const (
        VALUE MyEnumType = "Value"
        ANOTHER_VALUE MyEnumType = "AnotherValue"
        WHATEVER MyEnumType = "Whatever"
)
```

##### Swagger-codegen version

2.4.2, 3.0.20

**Comment by cbrom** [comment]
Any update on this issue? or workaround?
