### ISSUE TITLE
Getting an error that is fixed in swagger-parser

### ISSUE THREAD

**Issue by nikhiljindal** [swagger-api/swagger-codegen#1066]
Generating a client from swagger spec is giving me the following error:
```
2960 [main] ERROR io.swagger.models.properties.PropertyBuilder - no property for null, null
```
I see that it was fixed in https://github.com/swagger-api/swagger-parser/issues/60 but am still getting that error when using swagger-codegen on HEAD.

Here is the command I am running:
```
java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ./kubernetes/api/swagger-spec/v1.json -l python -o ./k8sapi
```
And this is my swagger-spec: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json

Any ideas on how can I get past that error?
Thanks!

cc @madhuri-rai07

**Comment by wing328** [comment]
@nikhiljindal using `develop_2.0` branch, I couldn't repeat the error you got and I got a different error as follows:
```
writing file /var/tmp/python/test/swagger_client/models/v1_pod.py
writing file /var/tmp/python/test/swagger_client/models/v1_node_spec.py
writing file /var/tmp/python/test/swagger_client/models/v1_endpoint_address.py
java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:49)
	at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:467)
	at io.swagger.codegen.languages.PythonClientCodegen.getSwaggerType(PythonClientCodegen.java:151)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:623)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1040)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:869)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:414)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:386)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:162)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:129)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

I'll look into the error (null pointer exception) and keep the community posted.

**Comment by wing328** [comment]
@nikhiljindal using the latest `develop_2.0`, I no longer see those "no property for null" error but I got the following exception instead:
```
writing file /var/tmp/python/test/swagger_client/models/v1_endpoint_address.py
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.swagger.models.properties.RefProperty["$ref"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:647)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
	at io.swagger.util.Json.pretty(Json.java:23)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:621)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1040)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:869)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:414)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:386)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:162)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:129)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:53)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	... 13 more
java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:53)
	at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:467)
	at io.swagger.codegen.languages.PythonClientCodegen.getSwaggerType(PythonClientCodegen.java:151)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:623)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1040)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:869)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:414)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:386)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:162)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:129)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```
I'm still looking into the exception.

**Comment by wing328** [comment]
@nikhiljindal I was able to identify two issues in the spec:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json#L5896
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json#L5974

Both have `"type": ""`. After changing the type to `string`, I'm able to generate python client without any exception/error.

(As you probably aware, the type `any` (e.g. [v1.json#L11005](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/api/swagger-spec/v1.json#L11005)) is also not valid according to Swagger spec 1.2, ref: https://github.com/GoogleCloudPlatform/kubernetes/issues/4700)

**Comment by nikhiljindal** [comment]
Thanks a lot @wing328 for prompt reply.
Am fixing it in https://github.com/GoogleCloudPlatform/kubernetes/pull/12507

**Comment by wing328** [comment]
@nikhiljindal do you need further help from us?  I believe you've an issue opened in kubernetes as well for tracking so we'll close this one if no concern from you.

**Comment by nikhiljindal** [comment]
Yes. Closing this one
Thanks for the help!

**Comment by wing328** [comment]
@nikhiljindal No problem. Feel free to ping us again if you've any question or feedback on Swagger-Codegen.

**Comment by LINxu233** [comment]
solution is where
