### ISSUE TITLE
exception in deserialize of python client: 'DateTime' is referenced as 'datetime'

### ISSUE THREAD

**Issue by yzats** [swagger-api/swagger-codegen#1085]
In models generated for objects with date-time field, swagger_types dictionary contains 'DateTime' , but api_client.py  expects 'datetime' -- this produces exception when running generated code on attempt to deserialize (see api_client.py:deserialize function).

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "foo\apis\bar_api.py", line 297, in get_bar_info
    response='barInfo', auth_settings=auth_settings)
  File "foo\api_client.py", line 105, in call_api
    return self.deserialize(response_data, response)
  File "foo\api_client.py", line 209, in deserialize
    setattr(instance, attr, self.deserialize(value, attr_type))
  File "foo\api_client.py", line 174, in deserialize
    obj_class = eval('models.' + obj_class)
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'DateTime'
```

**Comment by yzats** [comment]
This appears to be addressed in develop_2.0 branch of codegen.
