### ISSUE TITLE
NodeJs Server Generator creates broken stub

### ISSUE THREAD

**Issue by ralpheichelberger** [swagger-api/swagger-codegen#10867]
- OS:  ubuntu 18.04.1
 - Browser: chrome
 - Version: 
 - Method of installation: docker container
 - Swagger-Editor version: 3.14.7
 - Swagger/OpenAPI version: OpenAPI 3.0

There are several problems because of changes of dependend libraries that can be fixed by editing the index.js of the generated server stub. But after that I hit a wall with a problem I can't debug into.

Is there a updated version of the nodejs-server-genrerator?

The problem I got, after several trivial roadblocks is that the express crashes while answering a post request with a request body holding a simple object. At some point the req object gets lost and req ist undefined. I found serveral simmilar problems with express in a google search but couldn't find a solution. 

How can I get in touch with the developer who created the generator to fix the problem?

Here is the error message:

> 
> node index.js

  Mock mode: disabled
Your server is listening on port 8080 (http://localhost:8080)
Swagger-ui is available on http://localhost:8080/docs
(node:19366) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'writeHead' of undefined
    at Object.exports.writeJson (/home/ralph/workspace/rapi/utils/writer.js:41:12)
    at /home/ralph/workspace/rapi/controllers/Default.js:12:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:19366) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19366) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
POST /v0.1/item - - ms - -

**Comment by ralpheichelberger** [comment]
not interested anymore
