### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!

### ISSUE THREAD

**Issue by bu4ak** [swagger-api/swagger-codegen#10917]
##### Description

Doesn't work with local files

##### Swagger-codegen version

docker (latest)

##### Command line used for generation

```bash
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
    -i /local/output/full/openapi3.json \
    -l cwiki
```
##### Steps to reproduce

inside `documentation`:
![image](https://user-images.githubusercontent.com/17143820/108712395-0005a680-7517-11eb-80cd-20c91f18f80e.png)

run 
```bash
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
    -i /local/output/full/openapi3.json \
    -l cwiki

[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/output/full/openapi3.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/output/full/openapi3.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:766)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:299)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

```

## When replace with url:

`/local/output/full/openapi3.json` with `https://petstore.swagger.io/v2/swagger.json` works fine

## When path really invalid:

```bash
 docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
    -i /local/output/full/adsf.json \     
    -l cwiki

[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/output/full/adsf.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/output/full/adsf.json
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
java.lang.RuntimeException: Could not find /local/output/full/adsf.json on the classpath
        at io.swagger.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:207)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:96)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:437)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:297)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:766)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:299)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by filiplindqvist-netlight** [comment]
👍 I experience the same thing!

**Comment by vsaiprakash** [comment]
I am also facing the same issue.

**Comment by benderillo** [comment]
@vsaiprakash Are you saying this generator does not support OpenAPI 3.x?

**Comment by vsaiprakash** [comment]
I think here swagger codegen old version is being using, there is a new version available but its package name will V3 example:- io.swagger.codegen.V3.*  This applies to swagger parser also io.swagger.parser.V3.*.

Here as we see the error message posted by @bu4ak "io.swagger.parser.Swagger20Parser" is being used which supports V2 or lower. It should have used "io.swaggee.parser.OpenAPIV3Parser" which supports V3, and lower versions ...

**Comment by MrSuicideParrot** [comment]
@bu4ak You should use v3 docker image (`swaggerapi/swagger-codegen-cli-v3`)  and not the v2. The v3 branch of this project supports v2 and v3 files and the master only supports v2 files (Souce: https://github.com/swagger-api/swagger-codegen/tree/3.0.0#swagger-codegen-3x-300-branch).

**Comment by GrayedFox** [comment]
This is still a problem with `swaggerapi/swagger-codegen-cli-v3` image, getting the same exception:

```
15:27:28.592 [Thread-1] ERROR i.s.c.v3.config.CodegenConfigurator - Unable to read URL: ./docs/explorer-api.json
java.lang.RuntimeException: Could not find ./docs/explorer-api.json on the classpath
	at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
	at io.swagger.codegen.v3.config.CodegenConfigurator.loadSpecContent(CodegenConfigurator.java:482)
	at io.swagger.codegen.v3.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:587)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:386)
	at java.lang.Thread.run(Thread.java:748)
```
