### ISSUE TITLE
[PYTHON] AttributeError: module 'swagger_client.models' has no attribute 'Object'

### ISSUE THREAD

**Issue by Straktisie** [swagger-api/swagger-codegen#11006]
##### Description
Hello, 
when receiving the response for a rest call containing additionalProperties (see example below) the swagger-client crashes with following error message:

> Traceback (most recent call last):
  File "/home/johannes/PycharmProjects/hvrpython/main.py", line 44, in <module>
    api_response2 = api_instance.hubserver_props_get()
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api/hub_server_interface_api.py", line 236, in hubserver_props_get
    (data) = self.hubserver_props_get_with_http_info(**kwargs)  # noqa: E501
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api/hub_server_interface_api.py", line 293, in hubserver_props_get_with_http_info
    return self.api_client.call_api(
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api_client.py", line 160, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api_client.py", line 232, in deserialize
    return self.__deserialize(data, response_type)
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api_client.py", line 253, in __deserialize
    return {k: self.__deserialize(v, sub_kls)
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api_client.py", line 253, in <dictcomp>
    return {k: self.__deserialize(v, sub_kls)
  File "/home/johannes/.local/lib/python3.8/site-packages/swagger_client/api_client.py", line 260, in __deserialize
    klass = getattr(swagger_client.models, klass)
AttributeError: module 'swagger_client.models' has no attribute 'Object'

Other rest calls not containing additionalProperties or only on the request side are working fine.

##### Swagger-codegen version

3.0.25

##### Swagger declaration file content or url

```yaml
  /api/v0/hubserver/props:
    get:
      operationId: hubserver_props_get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: hubserver_props_get_resp
                type: object
                description: prop
                additionalProperties:
                  oneOf:
                    - type: integer
                    - type: string
```

##### Command line used for generation

The client was generated by [editor.swagger.io](https://editor.swagger.io/)

**Comment by bgibers** [comment]
I am also running into this via the latest codegen jar, my api spec clearly has object lowercase 
```
          "additional_metadata": {
            "type": "object",
            "additionalProperties": { },
            "description": "To see the list of available properties for this transform,\r\nrefer to the Relationship Type definition",
            "nullable": true
          }
```
But the generated python client seems to make object uppercase in every instance
```
    @additional_metadata.setter
    def additional_metadata(self, additional_metadata):
        """Sets the additional_metadata of this TransformationApi.

        To see the list of available properties for this transform,  refer to the Relationship Type definition  # noqa: E501

        :param additional_metadata: The additional_metadata of this TransformationApi.  # noqa: E501
        :type: dict(str, Object)
        """
```
The issue seems to be stemming from instances of swagger_types containing the capitalized object
```
    swagger_types = {
        'name': 'str',
        'value': 'Object',
        'date_added': 'str'
    }
```

**Comment by bgibers** [comment]
@HugoMario seems to be completing most of the python PRs here

**Comment by ezk84** [comment]
Also running into this right now.

If I edit the generated model from:

```python
class Site(object):
    # ...
    swagger_types = {
        # ...
        'custom': 'dict(str, Object)'
    }
```

to 

```python
class Site(object):
    # ...
    swagger_types = {
        # ...
        'custom': 'dict(str, object)'
    }
```

It starts working as expected.
