### ISSUE TITLE
 NullPointerException when  generating simple yaml with discriminator mapping

### ISSUE THREAD

**Issue by garpinc** [swagger-api/swagger-codegen#11049]
Description
When generating I get a NullPointerException. It's a pretty simple yaml so not sure why. Removing the discriminator mapping: section resolves the issue

Swagger-codegen version
3.0.26

Command line used for generation
mvn generate-sources

Swagger declaration file content
```yaml
openapi: 3.0.0
info:
  title: Test API
  description: Anzo REST API
  contact:
    email: support@test.com
  version: 1.0.0
servers:
  - url: 'https://localhost:8443'
    description: Mock Testing Server
tags:
  - name: sysadmin
    description: Sysadmin Only Calls
  - name: developers
    description: Operations available to regular developers
paths:
  /foos:
    get:
      summary: Retrieves a collection of Foos
      description: |
        Retrieves a collection of Foos
      operationId: retrieveFoos
      tags:
        - developers
      responses:
        '200':
          description: The collection of Foos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Thing'
        '201':
          description: Created
        '404':
          description: matching foo not found
components:
  schemas:
    Thing:
      type: object
      properties:
        uri:
          type: string
          format: uri
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          'http://test.com/ontologies/Bar': '#/components/schemas/Bar'
          Bar: '#/components/schemas/Bar'
          'http://test.com/ontologies/Foo': '#/components/schemas/Foo'
          Foo: '#/components/schemas/Foo'
    URI:
      type: object
      required:
        - uri
      properties:
        uri:
          type: string
    Bar:
      allOf:
        - $ref: '#/components/schemas/Thing'
        - type: object
          properties:
            description2:
              type: string
    Foo:
      allOf:
        - $ref: '#/components/schemas/Bar'
        - type: object
          properties:
            ontology2:
              type: string
```

results in 
```
java.lang.NullPointerException
	at io.swagger.codegen.v3.generators.java.SpringCodegen.modelInheritanceSupport(SpringCodegen.java:879)
	at io.swagger.codegen.v3.generators.java.SpringCodegen.postProcessAllModels(SpringCodegen.java:857)
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:405)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
	at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute_(CodeGenMojo.java:554)
	at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute(CodeGenMojo.java:319)
```

**Comment by cawright00** [comment]
Upon further debugging we have observed the following: a Parent Class must have at least one Child Class whose name comes alphabetically before the name of the Parent Class. For example, in the above file, if the name of Foo is changed to AFoo, it works. Additionally, if Foo is kept as is and a new Child Class called Alpha is introduced, it will also work, both Foo and the new Alpha class.

**Comment by cawright00** [comment]
And also, as mentioned above, removing the Discriminator does fix the problem as well, though it seems orthogonal to the actual issue.

**Comment by HugoMario** [comment]
npe has been fixed with https://github.com/swagger-api/swagger-codegen-generators/pull/929 PR
