### ISSUE TITLE
[Javascript] using browersify on javascript client

### ISSUE THREAD

**Issue by gregb502** [swagger-api/swagger-codegen#11189]
##### Description

I tried to follow the instruction present in the README.md file generated by the generator, in order to get a client that is usable in the browser

	browserify index.js > bundle.js

but the command failed indicating

	Error: Parsing file /home/.../petstore/javascript/src/index.js: 'import' and 'export' may appear only with 'sourceType: module' (16:0)
		at Deps.parseDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:519:15)
		at getDeps (/usr/lib/node_modules/browserify/node_modules/module-deps/index.js:447:44)
		at /usr/lib/node_modules/browserify/node_modules/module-deps/index.js:430:38
		at ConcatStream.<anonymous> (/usr/lib/node_modules/browserify/node_modules/concat-stream/index.js:37:43)
		at emitNone (events.js:111:20)
		at ConcatStream.emit (events.js:208:7)
		at finishMaybe (/usr/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:630:14)
		at endWritable (/usr/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:638:3)
		at ConcatStream.Writable.end (/usr/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:594:41)
		at DuplexWrapper.onend (/usr/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:577:10)

##### Swagger-codegen version

The version is 3.0.27

	java -jar swagger-codegen-cli.jar version
	3.0.27

##### Swagger declaration file content or url

I'm using the petstore api
https://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

	java -jar swagger-codegen-cli.jar generate -i swagger.json -l javascript -o javascript

##### Steps to reproduce

	cd javascript/src
	browserify index.js > bundle.js

##### Related issues/PRs

No

**Comment by gregb502** [comment]
It seems that adding

	  "browserify": {
	    "transform": [["babelify", { "presets": ["@babel/preset-env"] }]]
	  }

in the package.json file resolve the error

Greg
