### ISSUE TITLE
Missing OpenAPI input

### ISSUE THREAD

**Issue by RicardoPhilippe** [swagger-api/swagger-codegen#11200]
Using this command:

`java -jar swagger-codegen-cli-3.0.28.jar generate -i https://app.vindi.com.br/api/v1/docs -l csharp -o chsarp_client -c config.json`

Config file:
`{
	"packageGuid": "7b60b737-097c-4cac-91ee-2e241468029b",
	"packageName": "GuruMatchSdk.Billing.Vindi",
	"netCoreProjectFile" : true
}
`

Error:
`12:42:50.898 [Thread-1] INFO  i.s.c.v.i.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "Thread-1" java.lang.RuntimeException: missing OpenAPI input!
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:768)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
        at java.lang.Thread.run(Unknown Source)`

Using the validator on "https://validator.swagger.io/" to check the schemas looks like it has errors, is there a way  to solve it?

**Comment by douglasg14b** [comment]
I also get this, same WSL env as a coworker, and they don't have this issue.

When I validate the schema, it is valid.
