### ISSUE TITLE
Swagger CodeGen Error- More than one inline schema specified in allOf:. Only the first one is recognized. All others are ignored

### ISSUE THREAD

**Issue by suryadip08** [swagger-api/swagger-codegen#11259]
I have a file provMnS.yaml and it is referring to some other file nrNrm.yaml where SubNetwork-Single model definition is present. But due to allOf in the definition SubNetwork-Single model is not getting generated. If I change allOf to oneOf then the model is generated. I have to use allOf only as per the specification yaml. Please help me to resolve it.

**Yaml snippet:**

  ```
SubNetwork-Single:
          allOf:
            - $ref: 'C:\Users\xxxx\Documents\Docs\Project\yyyy\tasks\2504\Latest16th-MnS-Rel-16-SA-91\MnS-Rel-16-SA-91\OpenAPI\genericNrm.yaml#/components/schemas/Top-Attr'
            - type: object
              properties:
                attributes:
                  allOf:
                    - $ref: 'C:\Users\xxxx\Documents\Docs\Project\yyyy\tasks\2504\Latest16th-MnS-Rel-16-SA-91\MnS-Rel-16-SA-91\OpenAPI\genericNrm.yaml#/components/schemas/SubNetwork-Attr'
            - $ref: 'C:\Users\xxxx\Documents\Docs\Project\yyyy\tasks\2504\Latest16th-MnS-Rel-16-SA-91\MnS-Rel-16-SA-91\OpenAPI\genericNrm.yaml#/components/schemas/SubNetwork-ncO'
            - type: object
              properties:
                SubNetwork:
                  $ref: '#/components/schemas/SubNetwork-Multiple'
```

**Error and Exception while running swagger-codegen-cli jar:**

```
C:\Users\xxxx\Documents\Docs\SWs\open api generator>java -jar swagger-codegen-cli-3.0.29.jar generate -i C:/Users/xxxx/Documents/Docs/Project/yyyy/tasks/2504/Latest16th-MnS-Rel-16-SA-91/MnS-Rel-16-SA-91/OpenAPI/provMnS.yaml -l spring

23:18:22.457 [Thread-1] WARN  i.s.c.v.g.DefaultCodegenConfig - String to be sanitized is null. Default to Object
23:18:22.470 [Thread-1] WARN  i.s.c.v.g.DefaultCodegenConfig - More than one inline schema specified in allOf:. Only the first one is recognized. All others are ignored.
Exception in thread "Thread-1" java.lang.RuntimeException: Could not process model 'SubNetwork-Single'.Please make sure that your schema is correct!
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:386)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addProperties(DefaultCodegenConfig.java:1527)
```

version- swagger-codegen-cli-3.0.29.jar

**Comment by consultantleon** [comment]
I found this issue today, suffering from the same problem.
My conclusion is that swagger codegen v3 does not support (yet) the allOf composed models.
This means that for our upgrade from v2 to v3 we lose a large number of fields in the generated models.
As this issue appears to be unhandled I suspect swagger codegen v3 is a failure and can be considered as unsupported and an incomplete implementation.
I'm considering to put my bets on the forked codegen from the OpenAPITools project (https://github.com/OpenAPITools) - as it does appear to support OpenAPI V3 definitions (and that was the main reason for us to upgrade away from Swagger CodeGen v2).
