### ISSUE TITLE
Cannot use format: password for string in body parameter

### ISSUE THREAD

**Issue by arnested** [swagger-api/swagger-codegen#1159]
If I create a simple API specification with path having POST with a body parameter and the body object has a string parameter with the format set to _password_ will make swagger-codegen throw a NullPointerException (at least when trying to generate static HTML).

The minimal example:
```yaml
---
swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
paths:
  /:
    post:
      parameters:
        - name: bodyInput
          description: Some body input
          in: body
          required: true
          schema:
            $ref: "#/definitions/BodyInput"
      responses:
        200:
          description: OK
definitions:
  BodyInput:
    type: object
    required:
      - someThing
    properties:
      someThing:
        type: string
        format: password
```

Running:
```sh
java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i minimal.yaml -o ~/docs -l html
```

Results in:
```
reading from minimal.yaml
499 [main] WARN io.swagger.util.PropertyDeserializer - no property from string, password, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=string, FORMAT=password, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["someThing"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["bodyInput"])
reading from minimal.yaml
510 [main] WARN io.swagger.util.PropertyDeserializer - no property from string, password, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=string, FORMAT=password, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["someThing"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["bodyInput"])
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: minimal.yaml; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserBase.reportUnexpectedNumberChar(ParserBase.java:939)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleInvalidNumberStart(UTF8StreamJsonParser.java:2487)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1245)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:82)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:135)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:60)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:136)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

Dropping the format or changing it to _email_ avoids the NullPointerException.

**Comment by webron** [comment]
As you mentioned, #1166 is a duplicate, but since the talk is over there, we'll close this one.
