### ISSUE TITLE
[Spring] convert applicaion/jose to text/plain

### ISSUE THREAD

**Issue by im-Lily** [swagger-api/swagger-codegen#11661]
Description

Exception when calling InquiryApi#paymentAction20ActionPost
io.swagger.client.ApiException: Not Found
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:930)
	at io.swagger.client.ApiClient.execute(ApiClient.java:844)
	at io.swagger.client.api.InquiryApi.paymentAction20ActionPostWithHttpInfo(InquiryApi.java:138)
	at io.swagger.client.api.InquiryApi.paymentAction20ActionPost(InquiryApi.java:124)
	at Main.main(Main.java:64)

**I'm working on swagger hub.
openapi version: 3.0.0**

requestBody:
        content:
          text/plain; charset=utf-8:
            schema:
              $ref: '#/components/schemas/InquiryRequest'
      responses:
        200:
          description: Success
          content:
            text/plain; charset=utf-8:
              schema:
                $ref: '#/components/schemas/InquiryResponse'

**I set response body content-type: text/plain, but response content-type is application/jose.
Also, i received this message "Unrecognized response type; displaying content as text.". so ApiClient Exception is 404 Not Found.
I want to set response body content-type: text/plain, how can i setting?**

**Comment by im-Lily** [comment]
I solved this issue about content-type: text/plain. Content-type: application/jose is not related.
