### ISSUE TITLE
JavaSpring custom template code generation fails on version 3.0.33

### ISSUE THREAD

**Issue by xa4atur** [swagger-api/swagger-codegen#11715]
##### Description

I want to generate stubs using custom templates. I downloaded templates then I started code generation, but it fails even without changing any template:

```
Caused by: com.github.jknack.handlebars.HandlebarsException: D:\...\JavaSpring\queryParams.mustache:1:233: found: 
'-last', expected: 'no viable alternative at input '{{^-last''

	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at com.github.jknack.handlebars.internal.antlr.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at com.github.jknack.handlebars.internal.antlr.Parser.notifyErrorListeners(Parser.java:544)
	at com.github.jknack.handlebars.internal.antlr.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportNoViableAlternative(HbsErrorStrategy.java:166)
	at com.github.jknack.handlebars.internal.antlr.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at com.github.jknack.handlebars.internal.HbsParser.elseBlock(HbsParser.java:982)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:681)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:337)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:673)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:337)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:673)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:337)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:86)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:513)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:490)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:214)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:73)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:73)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.Options.fn(Options.java:445)
	at com.github.jknack.handlebars.helper.WithHelper.apply(WithHelper.java:58)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:22)
	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:795)
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:538)
	... 3 more
```

Here is code from my build.gradle:

```
plugins {
    id "org.hidetake.swagger.generator" version "2.19.1"
}

dependencies {
    swaggerCodegen 'io.swagger.codegen.v3:swagger-codegen-cli:3.0.33'
}

task prepareTemplates(type: Sync) {
    into file('templates')
    from({ configurations.swaggerCodegen.collect { zipTree(it) } }) {
        include 'JavaSpring/'
        into 'codegen3'
    }
}

swaggerSources {
    interactions {
        inputFile = file("${projectDir}/../schemas/swagger.yaml")
        code {
            language = 'spring'
            templateDir = file("$rootDir/templates/codegen3/JavaSpring")
            library = 'spring-boot'
            jvmArgs = ['--add-opens=java.base/java.util=ALL-UNNAMED']
            additionalProperties = [
                    dateLibrary            : 'java8',
                    hateoas                : "false",
                    fullJavaUtil           : "true",
                    hideGenerationTimestamp: "true",
                    useTags                : "true",
                    useOptional            : "true",
                    interfaceOnly          : "true",
                    skipDefaultInterface   : "true",
                    unhandledException     : "true",
                    useBeanValidation      : "false",
                    modelNameSuffix        : "Dto"
            ]
        }
    }
}

swaggerSources*.code*.dependsOn 'prepareTemplates'
```

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/7330

**Comment by HugoMario** [comment]
hey @xa4atur 

codegen v3 uses handlebars instead mustache for templates. That's why you got that error. To fix this, you need to change `-last` for `@last`.

Gonna close this, if you get any other error please let me know.

**Comment by HugoMario** [comment]
@xa4atur 

in case you need to use mustache template syntax only. You could use an option to work with mustache engine instead handlebars:

```
--additional-properties templateEngine=mustache
```

**Comment by nprasovict** [comment]
What worked for me was:
```
--template-engine mustache
```
parameter.
Codegen version `3.0.34-SNAPSHOT`

**Comment by aabdelli03** [comment]
@nprasovict is swagger codegen 3.0.34 compatible with springboot 2.7.18. I'm preparing for upgrading to springBoot 3.0 but i started with upgrade from jdk11 to jdk17. at that state i was demanded to upgrade swagger codegen from 19 to 34+.
Unfortunately i have issues with Apis interfaces generated from swagger (openApi 3.0.1) and i'm blocked on that . I got new templates from github (for javaspring) but it does not resolve the problem) any help plz

**Comment by aabdelli03** [comment]
@nprasovict  where sould i add this ? i work with maven and springboot with jdk 17
