### ISSUE TITLE
[Bug] "Could not process model" for string enumeration

### ISSUE THREAD

**Issue by mikeb26** [swagger-api/swagger-codegen#11991]
##### Description

wagger-codegen-cli fails with ''Could not process model 'VariantKey'.Please make sure that your schema is correct!" The definition of VariantKey in the schemas section is below:

```
  "components": {
    "schemas": {
      "VariantKey": {
        "type": "string",
        "enum": [
          "standard",
          "chess960",
          "crazyhouse",
          "antichess",
          "atomic",
          "horde",
          "kingOfTheHill",
          "racingKings",
          "threeCheck",
          "fromPosition"
        ],
        "example": "standard",
        "default": "standard"
      },
...
```

##### Swagger-codegen version

3.0.36

##### Swagger declaration file content or url

https://github.com/mikeb26/lichess-go-sdk/blob/285cd412550179208649530859434e3b812cf231/openapi.json

##### Command line used for generation

```
java -jar swagger-codegen-cli.jar generate --lang go  -o ./openapi --git-user-id mikeb26 --git-repo-id lichess-go-sdk -i ./openapi.json 
16:47:24.134 [Thread-0] INFO  i.s.c.v.i.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "Thread-0" java.lang.RuntimeException: Could not process model 'VariantKey'.Please make sure that your schema is correct!
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:386)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:788)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "codegenModel.dataType" is null
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1473)
        at io.swagger.codegen.v3.generators.go.AbstractGoCodegen.fromModel(AbstractGoCodegen.java:565)
        at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:1019)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:375)
        ... 3 more
```

##### Steps to reproduce

```
wget https://github.com/mikeb26/lichess-go-sdk/blob/285cd412550179208649530859434e3b812cf231/openapi.json
wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.36/swagger-codegen-cli-3.0.36.jar -O swagger-codegen-cli.jar
java -jar swagger-codegen-cli.jar generate --lang go  -o ./openapi --git-user-id mikeb26 --git-repo-id lichess-go-sdk -i ./openapi.json 
```

**Comment by majoshi1** [comment]
Any update on this issue?

**Comment by yu-iskw** [comment]
I have the same issue.

**Comment by HugoMario** [comment]
Hello, the error is because the openapi document has version set `3.1.0`. Which is not fully supported by codegen yet.

Switching to open `3.0.0` makes the generator works.

**Comment by mikeb26** [comment]
@HugoMario any chance the error returned to the user could state this explicitly?
