### ISSUE TITLE
[javascript] bug generating code with template

### ISSUE THREAD

**Issue by everpan** [swagger-api/swagger-codegen#12097]
##### Description

when I generating, I got:
19:40:31.609 [Thread-0] INFO  i.s.c.v.i.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
19:40:31.610 [Thread-0] INFO  i.s.c.v.g.j.JavaScriptClientCodegen - Using JS ES5 templates
Exception in thread "Thread-0" java.lang.RuntimeException: Could not generate model 'AppDataDTO'
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:457)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:788)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:388)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.github.jknack.handlebars.HandlebarsException: /Users/ever/git/wiztop/wiz-apis/swagger/template/Javascript/partial_model_generic.mustache:18:72: found: '-last', expected: 'no viable alternative at input '{{^-last''

##### Swagger-codegen version
swagger-codegen-cli-3.0.42-20230216.174441-1.jar

##### Swagger declaration file content or url

any

##### Command line used for generation

executable=./packages/tools/bin/swagger-codegen-cli-3.0.42-20230216.174441-1.jar
export JAVA_OPTS="${JAVA_OPTS} -Xmx1024M" # -DloggerPath=conf/log4j.properties
ags="generate -t swagger/template/Javascript -i swagger/files/grown/easc3/swagger.json -l javascript -o packages/easc3  --additional-properties useES6=false $@"
java $JAVA_OPTS -jar $executable $ags

##### Suggest a fix/enhancement

none

**Comment by everpan** [comment]
has a similar issue/PR been closed https://github.com/swagger-api/swagger-codegen/issues/12097
