### ISSUE TITLE
[python-flask] __init__.py contains NUL characters

### ISSUE THREAD

**Issue by ACMCMC** [swagger-api/swagger-codegen#12221]
##### Description

When generating for `python-flask`, `swagger_server/__init__.py` contains four `NUL` characters that cause the following error:

```
% python -m swagger_server            
Traceback (most recent call last):
  File ".../python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File ".../python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File ".../python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
ValueError: source code string cannot contain null bytes
```

##### Swagger-codegen version
swagger-codegen: stable 3.0.46 (installed via Homebrew)
OS: Mac OS Ventura 13.4

##### Swagger declaration file content or url

Any declaration file works.

If you post the code inline, please wrap it with
```yaml
openapi: '3.0.2'
info:
  title: Test
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /method1:
    post:
      summary: Method 1
      responses:
        '200':
          description: OK
```

##### Command line used for generation

swagger-codegen generate -i test.yml -l python-flask -o .

##### Steps to reproduce

Just try to run the app as usual. 

##### Related issues/PRs

Searched; none found.

##### Suggest a fix/enhancement

TBD

**Comment by JPugetGil** [comment]
I am experimenting the same problem.
My workaround : use the web version of [swagger generator](https://hub.docker.com/r/swaggerapi/swagger-generator/)

**Comment by Lenormju** [comment]
I reported the same problem in another issue : swagger-api/swagger-codegen-generators#1262
