### ISSUE TITLE
Broken image on dockerhub - Java Runtime support up to v.52 but was compiled with v.55

### ISSUE THREAD

**Issue by rosenbjerg** [swagger-api/swagger-codegen#12271]
##### Description

Image on dockerhub is broken.

I simply tried: `docker run --rm -it swaggerapi/swagger-codegen-cli-v3 --help`

which gave the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.slf4j.LoggerFactory.safelyInstantiate(LoggerFactory.java:148)
	at org.slf4j.LoggerFactory.findServiceProviders(LoggerFactory.java:129)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:190)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:182)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:490)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:476)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:425)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:451)
	at io.swagger.codegen.v3.cli.SwaggerCodegen.<clinit>(SwaggerCodegen.java:40)
```

##### Swagger-codegen version

`3.0.50` which is currently `latest`

##### Swagger declaration file content or url

N/A

##### Command line used for generation

`--help`

##### Steps to reproduce

Run `docker run --rm -it swaggerapi/swagger-codegen-cli-v3:3.0.50 --help`

##### Related issues/PRs

#12242 was opened a month ago but has not gotten any response

##### Suggest a fix/enhancement

Seems like it is some misconfiguration of the build pipeline responsible for the image.

**Comment by rosenbjerg** [comment]
Closed as duplicate of #12240
