### ISSUE TITLE
Latest docker image uses an old version of Swagger Codgen : 2.4.43 instead of the last stable one 3.x

### ISSUE THREAD

**Issue by enimiste** [swagger-api/swagger-codegen#12453]
Command to show the installed version on the latest version of Swagger Codegen docker image :
```shell
docker run --rm -v .:/app swaggerapi/swagger-codegen-cli version
```
It outputs :
`2.4.43`

**Issue :**
**Unable** to generate code from **OpenAPI v3** documentation file. The command that i used is :
```shell
docker run --rm -v .:/app swaggerapi/swagger-codegen-cli generate \
    -i /app/openapi_hermes_v1.10.0.json \
    -l html2 \
    -o /app/output
```

**Error** that i got when running the command : 
```shell
[main] INFO io.swagger.parser.Swagger20Parser - reading from /app/openapi_hermes_v1.10.0.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /app/openapi_hermes_v1.10.0.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:766)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:307)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

On **Stackoverflow** forum, i found that the 2.x version supports only the swagger schema.

**Comment by defurn** [comment]
you can use this one: https://hub.docker.com/r/swaggerapi/swagger-codegen-cli-v3/
