### ISSUE TITLE
Missing model types cause a NullPointerException

### ISSUE THREAD

**Issue by bedag-moo** [swagger-api/swagger-codegen#1267]
If a parameter type refers to a missing model:

    "operations" : [ {
      "method" : "POST",
      "nickname" : "updateIssue",
      "type" : "Issue",
      "parameters" : [ {
        "type" : "UUID",
        "paramType" : "path",
        "name" : "id",
        "required" : true
      }, {
        "type" : "IssueEditCommand",
        "paramType" : "body",
        "name" : "issue",
        "required" : true
      } ],
      "summary" : "Updates an existing issue."
    } ]

Code generation fails with a NullPointerException:

    java.lang.NullPointerException
            at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:53)
            at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:470)
            at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:280)
            at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:626)
            at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1051)
            at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:880)
            at ch.bedag.eng.various.rcg.SimpleJavaClientCodegen.fromOperation(SimpleJavaClientCodegen.java:29)
            at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:448)
            at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:401)
            at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:170)

Ideally, the exception message would identify the problematic operation, so we don't have to debug the maven plugin to find out where the swagger documentation is incomplete.

**Comment by bedag-moo** [comment]
Fixing #1266 has somewhat improved matters, but the stack trace is not very readable, and does not identify the missing model:

	[ERROR] Error while trying to get Config from Operation for tag(issue)
			Resource: post /issue/{id}/status
			Operation:io.swagger.models.Operation@41b7cbf6
			Definitions: {Ref=io.swagger.models.ModelImpl@1ce79d8c, IssueTransitionCommand=io.swagger.models.ModelImpl@9cc58
	885, User=io.swagger.models.ModelImpl@6b4dd805, Issue=io.swagger.models.ModelImpl@23a6b440, TechId=io.swagger.models.Mod
	elImpl@a45b3e6e, IssueEditCommand=io.swagger.models.ModelImpl@529c85bf, Label=io.swagger.models.ModelImpl@a2ecc544, Pers
	on=io.swagger.models.ModelImpl@e74ab578}

	java.lang.NullPointerException
			at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
			at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:487)
			at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:300)
			at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:646)
			at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1185)
			at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:999)
			at ch.bedag.eng.various.rcg.SimpleJavaClientCodegen.fromOperation(SimpleJavaClientCodegen.java:29)
			at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:470)
			at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:418)
			at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:184)
			at ch.bedag.eng.various.rcg.RestClientGeneratorMojo.execute(RestClientGeneratorMojo.java:62)
			at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
			at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
			at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
			at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
			at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
			at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
			at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
	java:51)
			at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
			at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
			at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
			at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
			at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
			at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
			at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:483)
			at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
			at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
			at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
			at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by bedag-moo** [comment]
I don't understand swagger-model well enough to fix this efficiently.

**Comment by wing328** [comment]
@bedag-moo thanks for the detailed error messages. I tried repeating the issue by removing schema from https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.json#L44 (so that the body parameter refers to a missing model) but in vain.

Am I repeating the issue in the right way?

**Comment by bedag-moo** [comment]
@wing328: No :-)

Here is the full spec for my testcase:

    {
      "apiVersion" : "1",
      "swaggerVersion" : "1.2",
      "basePath" : "/api",
      "resourcePath" : "/issue",
      "apis" : [ {
        "path" : "/issue",
        "operations" : [ {
          "method" : "POST",
          "nickname" : "createIssue",
          "type" : "Issue",
          "parameters" : [ {
            "type" : "IssueEditCommand",
            "paramType" : "body",
            "name" : "dto",
            "required" : true
          } ],
          "summary" : "Creates a new issue, and returns it."
        } ]
      }, {
        "path" : "/issue/assignedToMe",
        "operations" : [ {
          "method" : "GET",
          "nickname" : "getAssignedToMe",
          "type" : "array",
          "items" : {
            "$ref" : "Issue"
          },
          "summary" : "Returns a list of issues assigned to the current user."
        } ]
      }, {
        "path" : "/issue/reportedByMe",
        "operations" : [ {
          "method" : "GET",
          "nickname" : "getReportedByMe",
          "type" : "array",
          "items" : {
            "$ref" : "Issue"
          },
          "summary" : "Returns a list of issues reported by the current user."
        } ]
      }, {
        "path" : "/issue/{id}",
        "operations" : [ {
          "method" : "POST",
          "nickname" : "updateIssue",
          "type" : "Issue",
          "parameters" : [ {
            "type" : "TechId",
            "paramType" : "path",
            "name" : "id",
            "required" : true
          }, {
            "type" : "IssueEditCommand",
            "paramType" : "body",
            "name" : "dto",
            "required" : true
          } ],
          "summary" : "Updates an existing issue."
        } ]
      }, {
        "path" : "/issue/{id}/status",
        "operations" : [ {
          "method" : "POST",
          "nickname" : "perform",
          "type" : "Issue",
          "parameters" : [ {
            "type" : "TechId",
            "paramType" : "path",
            "name" : "id",
            "required" : true
          }, {
            "type" : "IssueTransitionCommand",
            "paramType" : "body",
            "name" : "cmd",
            "required" : true
          } ],
          "summary" : "Performs the given transition."
        } ]
      } ],
      "models" : {
        "Ref" : {
          "id" : "Ref",
          "properties" : {
            "id" : {
              "type" : "TechId"
            }
          }
        },
        "IssueTransitionCommand" : {
          "id" : "IssueTransitionCommand",
          "properties" : {
            "issueId" : {
              "type" : "TechId"
            },
            "transition" : {
              "type" : "string",
              "enum" : [ "startProgress", "stopProgress", "resolve", "reopen", "close" ]
            }
          }
        },
        "Issue" : {
          "id" : "Issue",
          "properties" : {
            "id" : {
              "type" : "TechId"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "reporter" : {
              "type" : "User"
            },
            "assignee" : {
              "type" : "User"
            },
            "subject" : {
              "type" : "string"
            },
            "description" : {
              "type" : "string"
            },
            "status" : {
              "type" : "string",
              "enum" : [ "open", "inProgress", "resolved", "closed" ]
            },
            "labels" : {
              "type" : "array",
              "items" : {
                "$ref" : "Label"
              }
            },
            "availableTransitions" : {
              "type" : "array",
              "items" : {
                "type" : "string",
                "enum" : [ "startProgress", "stopProgress", "resolve", "reopen", "close" ]
              }
            }
          }
        },
        "User" : {
          "id" : "User",
          "properties" : {
            "id" : {
              "type" : "TechId"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "openId" : {
              "type" : "string"
            },
            "fullName" : {
              "type" : "string"
            },
            "role" : {
              "type" : "string",
              "enum" : [ "system", "admin", "developer", "user" ]
            }
          },
          "required" : [ "openId", "fullName", "role" ]
        },
        "TechId" : {
          "id" : "TechId",
          "properties" : {
            "uuid" : {
              "type" : "UUID"
            }
          }
        },
        "IssueEditCommand" : {
          "id" : "IssueEditCommand",
          "properties" : {
            "id" : {
              "type" : "TechId"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "subject" : {
              "type" : "string"
            },
            "description" : {
              "type" : "string"
            },
            "assignee" : {
              "type" : "Ref"
            }
          }
        },
        "Label" : {
          "id" : "Label",
          "properties" : {
            "id" : {
              "type" : "TechId"
            },
            "version" : {
              "type" : "integer",
              "format" : "int64"
            },
            "name" : {
              "type" : "string"
            }
          }
        }
      }
    }

The type UUID has no entry under "model".

**Comment by wing328** [comment]
@bedag-moo ok. I'll give it a try tomorrow and fix the NPE in a branch that I'm working on.

**Comment by wing328** [comment]
@bedag-moo I noticed that some "path" parameters have the type "TechId". Replacing it with "string" can workaround the issue before we put in place better handling of the NPE.

For path parameters, I don't think we should use model, which can have more than 1 property and currently there's no way for codegen (or other tool) to figure out which property to substitute the path parameter (e.g. {id}).

**Comment by bedag-moo** [comment]
I agree about path parameters, and have since changed their type to string. 

Still, a more descriptive exception would be nice.

**Comment by wing328** [comment]
PR merged.
