### ISSUE TITLE
ComposedModel class-cast exception

### ISSUE THREAD

**Issue by msh321** [swagger-api/swagger-codegen#1286]
I have tried to run the codegen on the following Swagger Spec:

```yaml
swagger: '2.0'
info:
  description: TODO
  version: 0.0.1
  title: TODO
basePath: /v2
schemes:
  - http
paths:
  /se/{id}:
    get:
      tags:
      - todo
      summary: Get
      description: 'Some user documentation'
      operationId: get se
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: 'identifier'
          required: true
          type: string
      responses:
        '200':
          description: response
          schema:
            $ref: '#/definitions/Resp'
        '405':
          description: Invalid data
definitions:
  Resp:
    type: object
    properties:
      st:
        type: string
      catalog:
        $ref: '#/definitions/Comp'
  Comp:
    type: object
    allOf:
      - $ref: '#/definitions/Comp2'
      - properties:
          name:
            type: string
          version:
            type: string
  Comp2:
    type: object
    properties:
      id:
        type: string
      type:
        type: string
```

The codegen gives the following error:

```
java -jar swagger-codegen-cli-2.1.0-M2.jar generate -l java -i ex1.yml -o out
reading from ex1.yaml
writing file /tmp/ex1/out/src/main/java/io/swagger/client/model/Resp.java
java.lang.ClassCastException: com.wordnik.swagger.models.ComposedModel cannot be cast to com.wordnik.swagger.models.ModelImpl
	at com.wordnik.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:455)
	at com.wordnik.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:408)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:125)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:77)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
```

If I do ___not___ use the `allOf` element (under `Comp`), then everything seems fine.

Can this be a bug in codegen?  Or should the error message just be better?

(I need to be able to express inheritance in the generated Java code, so using `allOf` is the correct way, I guess... Or is it???)

**Comment by msh321** [comment]
Sorry, I can see that this issue is fixed.  I accidentally used an old codegen version.  With 2.1.4-SNAPSHOT the aforementioned exception does not occur.

Can I close my own issue?
