### ISSUE TITLE
Recursive Type Exception

### ISSUE THREAD

**Issue by jeusdi** [swagger-api/swagger-codegen#1292]
I've created a DTO that contains a list of objects of the same class:

    class Dto {
        private String id;
        private List<Dto> subDtos;
        //...
    }

When I remove this property, codegen works fine. It seems the problem is around that.

> Exception in thread "main" java.lang.RuntimeException: Could not generate model
'DigitalResourceDTO'
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:17
4)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.languages.CSharpClientCodegen.getSwaggerType(CShar
pClientCodegen.java:230)
        at io.swagger.codegen.DefaultCodegen.getTypeDeclaration(DefaultCodegen.j
ava:521)
        at io.swagger.codegen.languages.CSharpClientCodegen.getTypeDeclaration(C
SharpClientCodegen.java:223)
        at io.swagger.codegen.languages.CSharpClientCodegen.getTypeDeclaration(C
SharpClientCodegen.java:216)
        at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:78
9)
        at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:1433)
        at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:624)
        at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.ja
va:608)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:14
8)
        ... 2 more

**Comment by wing328** [comment]
@jeusdi  The issue should have been addressed before #728 

Are you using the latest version of swagger-codegen (master)? Do you mind sharing the swagger spec for repeating the issue?

I did a test trying to repeat the issue but couldn't.

**Comment by wing328** [comment]
@jeusdi we're closing this issue for now as we've not heard from you.
