### ISSUE TITLE
[JAVA] [allOf] fails when generating code

### ISSUE THREAD

**Issue by tabetan** [swagger-api/swagger-codegen#1342]
Hi,

I have a problem when generating code for my swagger.yaml.

My swagger.yaml is valid, validated against validator-badge tool. Plus the editor doesn't raise any problem.
 
customerUpdate object extends customerCreate object using allOf. But the allOf feature seems to create a problem when generating code for Java. Is it possible to use allOf when generating Java code?

### Yaml extraction:
```
  customerUpdate:
    type: object
    allOf:
      - $ref: '#/definitions/customerCreate'
    properties:
      homePhone:
        type: string
        pattern: '/^[+]?[0-9]*$/i'
        maxLength: 20
```

### The error when generating code for Java:

```
writing file /gen/eshopws/src/main/java/io/swagger/client/model/CreateUser.java
writing file /gen/eshopws/src/main/java/io/swagger/client/model/CustomerCreate.java
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'customerUpdate'
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:174)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:588)
        at io.swagger.codegen.languages.JavaClientCodegen.fromModel(JavaClientCodegen.java:340)
        at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:609)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:148)
        ... 2 more
```

thank you

**Comment by fehguy** [comment]
Hi, the allOf syntax isn't quite right.  It should be more like this:

```yaml
  customerUpdate:
    allOf:
      - $ref: '#/definitions/customerCreate'
      - type: object
        properties:
          homePhone:
            type: string
            pattern: '/^[+]?[0-9]*$/i'
            maxLength: 20
```

**Comment by tabetan** [comment]
Thank you very much. It is working now.
