### ISSUE TITLE
python client problem - ApiClient 

### ISSUE THREAD

**Issue by inska** [swagger-api/swagger-codegen#1346]
Hi,

Anyone can you guess below problem? This is my situation:
 - Python client generated
 - some function works well (GET) (Sever returns its valid response)
 - some function returns below error (GET or POST) (Never requested to server)

Python client generated from codegen cli. 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 12, in <module>
    marmotte.create_project('name')
  File "./marmotte.py", line 45, in create_project
    project = self.project_api.create_project(name)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/swagger_client-1.0.0-py3.5.egg/team_sdk/apis/project_api.py", line 123, in create_project
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/swagger_client-1.0.0-py3.5.egg/team_sdk/api_client.py", line 320, in call_api
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/swagger_client-1.0.0-py3.5.egg/team_sdk/api_client.py", line 147, in __call_api
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/swagger_client-1.0.0-py3.5.egg/team_sdk/api_client.py", line 356, in request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/swagger_client-1.0.0-py3.5.egg/team_sdk/rest.py", line 192, in POST
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/swagger_client-1.0.0-py3.5.egg/team_sdk/rest.py", line 132, in request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.12-py3.5.egg/urllib3/request.py", line 72, in request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.12-py3.5.egg/urllib3/request.py", line 149, in request_encode_body
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.12-py3.5.egg/urllib3/poolmanager.py", line 161, in urlopen
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.12-py3.5.egg/urllib3/connectionpool.py", line 559, in urlopen
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.12-py3.5.egg/urllib3/connectionpool.py", line 353, in _make_request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1123, in _send_request
    self.putheader(hdr, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1059, in putheader
    if _is_illegal_header_value(values[i]):
* TypeError: expected string or bytes-like object *

**Comment by wing328** [comment]
@inska it would be hard to guess without the spec. Can you share the swagger spec with us to reproduce the issue?

**Comment by inska** [comment]
@wing328 Can I share a swagger spec to your e-mail in github profile?

**Comment by wing328** [comment]
@inska sure (I won't share with others)

**Comment by wing328** [comment]
@inska As discussed, the latest version of Swagger-Codegen works for you without the issue you reported above.
