### ISSUE TITLE
java.lang.RuntimeException: missing swagger input or config!  (parse error?)

### ISSUE THREAD

**Issue by siliconcow** [swagger-api/swagger-codegen#1351]
Seem to be getting an exception generating a client from https://loanpro.simnang.com/api/rest.json

```
+ docker run -it -w /gen -v /Users/dec/projects/swagger-codegen:/gen -v /Users/dec/.m2/repository:/root/.m2/repository maven:3-jdk-7 java -jar /gen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://loanpro.simnang.com/api/rest.json -l java -o rubyclient
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["error"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Error-OData"])
reading from https://loanpro.simnang.com/api/rest.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
(was java.lang.NullPointerException) (through reference chain: io.swagger.models.ModelImpl["properties"]->java.util.LinkedHashMap["error"]) (through reference chain: io.swagger.models.Swagger["definitions"]->java.util.LinkedHashMap["Error-OData"])
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:63)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

Is this an issue with the service or swagger?

```

**Comment by xhh** [comment]
I've tried it on my local and confirmed that the problem is in the "Error-OData" model in the spec:

```json
"definitions":{
  "Error-OData": {
    "properties": {
      "error": {
        "message": {
          "lang": {"type": "string"},
          "value": {"type":"string"}
        }
      }
    }
  },
  ...
}
```

The `properties` should contain property entries with either `type` or `$ref`, but the **error** property's structure is not as expected. Correcting it could fix the issue.

**Comment by fehguy** [comment]
If you have other questions, please reopen.
