### ISSUE TITLE
API Factory and Impl classes are generated in incorrect folders on Windows

### ISSUE THREAD

**Issue by rbhunt** [swagger-api/swagger-codegen#1391]
When generating a JAX-RS service on Windows the factory and impl classes are written to \factories\io\swagger\api and \impl\io\swagger\api instead of \io\swagger\api\factories and io\swagger\api\impl respectively.

Here's the output from running codegen.  Looks like the use of \ as a separator in the package names could be confusing the code inserting factories and impl into the paths?

*writing file generated-code/jaxrs/src/gen/java/impl/io\swagger\api\SecurityApiServiceImpl.java
writing file generated-code/jaxrs/src/gen/java/factories/io\swagger\api\SecurityApiServiceFactory.java
writing file generated-code/jaxrs/src/gen/java/impl/io\swagger\api\RegisterApiServiceImpl.java
writing file generated-code/jaxrs/src/gen/java/factories/io\swagger\api\RegisterApiServiceFactory.java*

Edit: This was observed using 2.1.3

**Comment by wing328** [comment]
@rbhunt can you please pull the latest version and see if you still encounter the same issue?

**Comment by rbhunt** [comment]
Yes, just cloned and built the project and encountered the same issue.

**Comment by wing328** [comment]
@rbhunt Can you share the spec for reproducing the issue?

**Comment by rbhunt** [comment]
Sure thing, have provided a cut down sample spec that reproduces the issue here:

https://drive.google.com/file/d/0B5B0A4cdndFMNjdQbTJleGZ5Rkk/view?usp=sharing

Would have just attached it here but don't seem to have permission - I'm new to GitHub so sorry if I've missed something obvious.  Here's the command I'm using to generate:

java -jar C:/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l jaxrs -i sample.yaml

**Comment by wing328** [comment]
@rbhunt I've tried to fix the issue and would need your help to test the fix (under Windows environment) as follows:
```
git clone https://github.com/wing328/swagger-codegen.git
cd swagger-codegen
git checkout jaxrs_fix_path_separator
mvn clean package
```
then run the command you provided to generate the code for JaxRS to see if the same issue persists. 

If the fix works, I'l submit a PR.

**Comment by rbhunt** [comment]
Now seeing an exception:

Exception in thread "main" java.util.ServiceConfigurationError: io.swagger.codegen.CodegenConfig: Provider io.swagger.codegen.languages.JaxRSServerCodegen could not be instantiated
        at java.util.ServiceLoader.fail(Unknown Source)
        at java.util.ServiceLoader.access$100(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
        at java.util.ServiceLoader$1.next(Unknown Source)
        at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:19)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:286)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:186)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at io.swagger.codegen.languages.JaxRSServerCodegen.<init>(JaxRSServerCodegen.java:28)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        ... 7 more

**Comment by rbhunt** [comment]
This looks like it might be similar to #268

**Comment by wing328** [comment]
Updated the branch `jaxrs_fix_path_separator`. Can you please give it another try?

**Comment by rbhunt** [comment]
I've retested but we're back to the original issue - incorrect paths are being generated.  Now that I know the class in question is JaxRSServerCodegen I'll try to find some time in the next few days to poke around and take a look - probably easier than you trying to guess how it will behave on Windows.
