### ISSUE TITLE
NullPointerException with Tizen generator on Kubernetes API

### ISSUE THREAD

**Issue by ms705** [swagger-api/swagger-codegen#1578]
I ran swagger-codegen v2.1.4 (the stable release) on the Kubernetes API spec (v1.1, see [here](http://kubernetes.io/third_party/swagger-ui/)) with the Tizen generator (to generate C++ code), but I get the following error:

```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://localhost:8080/swaggerapi -l tizen -o test
writing file /tmp/swagger-codegen/test/client/SamiV1.EndpointAddress.h
writing file /tmp/swagger-codegen/test/client/SamiV1.EndpointAddress.cpp
writing file /tmp/swagger-codegen/test/client/SamiV1.DaemonEndpoint.h
writing file /tmp/swagger-codegen/test/client/SamiV1.DaemonEndpoint.cpp
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: apiv1
  Operation: readNamespacedPodLog
  Resource: get /api/v1/namespaces/{namespace}/pods/{name}/log
  Definitions: {v1.Node=io.swagger.models.ModelImpl@609d77ee, v1.PersistentVolumeClaimList=io.swagger.models.ModelImpl@13051164, v1beta1.Job=io.swagger.models.ModelImpl@b53985ba, [... snip ...], v1.DaemonEndpoint=io.swagger.models.ModelImpl@4b3e470e}
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:609)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:496)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:238)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.languages.TizenClientCodegen.toModelName(TizenClientCodegen.java:184)
	at io.swagger.codegen.languages.TizenClientCodegen.toDefaultValue(TizenClientCodegen.java:228)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:658)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1238)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1052)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:551)
	... 4 more
```

Looking at the code, I can't immediately tell what the problem is. I'll investigate further -- the `/api/v1/namespaces/{namespace}/pods/{name}/log` resource doesn't seem to have any particularly notable properties (#877 doesn't seem immediately relevant here, for example).

The failing line is the `else` branch in the following:
```c++
        if (typeMapping.keySet().contains(type) ||
                typeMapping.values().contains(type) ||
                foundationClasses.contains(type) ||
                importMapping.values().contains(type) ||
                defaultIncludes.contains(type) ||
                languageSpecificPrimitives.contains(type)) {
            return type;
        } else {
            return PREFIX + Character.toUpperCase(type.charAt(0)) + type.substring(1);
        }
```
... presumably `type` is null?

I'll keep investigating, but I'm not at all familiar with the source, so someone else might be able to find the issue more quickly.

**Comment by wing328** [comment]
@ms705 thanks for reporting the issue. We're looking into this.

**Comment by wing328** [comment]
In the method `connectGetNamespacedPodExec` defined in http://kubernetes.io/swagger-spec/api/v1/, I found the following parameter with invalid type (empty string)
```
{
  type: "",
  paramType: "query",
  name: "command",
  description: "Command is the remote command to execute. argv array. Not executed within a shell.",
  required: false,
  allowMultiple: false
},
```
In GitHub, I found that the type is defined as `string` 
https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json#L6111

I've reported the issue to Kubernetes team [here](https://github.com/kubernetes/kubernetes/issues/17351)

**Comment by wing328** [comment]
Kubernets tema fixed the issue. I rerun the command and the NPE is gone.
