### ISSUE TITLE
Java generater post without form throw IllegalStateException

### ISSUE THREAD

**Issue by wangzilong** [swagger-api/swagger-codegen#1624]
My code
```java
@POST
  @Path("/access_token")
  @ApiOperation(
    value = "Get access_token",
    notes = "More notes about this method",
    response = String.class
  )
  @Consumes("application/x-www-form-urlencoded")
  @Produces("application/json")
  @Override
  public Response postAccessToken(@Context HttpServletRequest request,
                                 @QueryParam("code") final String code,
                                 @QueryParam("refresh_token") final String refresh_token,
                                 @QueryParam("client_id") final String client_id,
                                 @QueryParam("client_secret") final String client_secret,
                                 @ApiParam(value = "grant type", required = true, allowableValues ="authorization_code,refresh_token,password,client_credentials")
                                 @QueryParam("grant_type") final String grant_type) {
    return oauthService.postAccessToken(request);
  }
```

swagger-spec
```json
 "/oauth/access_token": {
            "post": {
                "tags": [
                    "oauth"
                ],
                "summary": "Get access_token",
                "description": "More notes about this method",
                "operationId": "postAccessToken",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "code",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "refresh_token",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "client_id",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "client_secret",
                        "in": "query",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "name": "grant_type",
                        "in": "query",
                        "description": "grant type",
                        "required": true,
                        "type": "string",
                        "enum": [
                            "authorization_code",
                            "refresh_token",
                            "password",
                            "client_credentials"
                        ]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
```

Client code that generater by codegen with  {"library": "okhttp-gson"}
```java
public String postAccessToken(String grantType, String code, String refreshToken, String clientId, String clientSecret) throws ApiException {
    Call call = postAccessTokenCall(grantType,code,refreshToken,clientId,clientSecret, null, null);
    Type returnType = new TypeToken<String>(){}.getType();
    return apiClient.execute(call, returnType);
  }
```

When call this API ,throw : 
```java
java.lang.IllegalStateException: Form encoded body must have at least one part.
	at com.squareup.okhttp.FormEncodingBuilder.build(FormEncodingBuilder.java:58)
	at io.swagger.client.ApiClient.buildRequestBodyFormEncoding(ApiClient.java:893)
	at io.swagger.client.ApiClient.buildCall(ApiClient.java:807)
	at io.swagger.client.api.OauthApi.postAccessTokenCall(OauthApi.java:91)
	at io.swagger.client.api.OauthApi.postAccessToken(OauthApi.java:105)
	at io.swagger.client.util.Token.refresh(Token.java:56)
	at io.swagger.client.util.BaseTest.obtToken(BaseTest.java:126)
	at io.swagger.client.util.BaseTest.initToken(BaseTest.java:89)
	at io.swagger.client.util.BaseTest.init(BaseTest.java:77)
	at io.swagger.client.util.BaseTest.setup(BaseTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
```

**Comment by wing328** [comment]
@wangzilong if it's still an issue, please let us know.  Closing for now.
