### ISSUE TITLE
Ref to enum generates non-compiling Java Client

### ISSUE THREAD

**Issue by jeffjcrowe** [swagger-api/swagger-codegen#1707]
### Summary
An enum defined in the 'definitions' section and referenced from the api definition generate Java Client code that fails to compile.
No code is generated for the shared enum definition.

### Example Schema
```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Enum Reuse Example
schemes:
  - https
paths:
  /api:
    post:
      operationId: post
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              someArg:
                type: string
              enumValue:
                $ref: '#/definitions/MyEnum'

      responses:
        '200':
          description: ok
          schema:
            type: object
            properties:
              otherArg:
                type: string
              enumValue:
                $ref: '#/definitions/MyEnum'

definitions:
  MyEnum:
    type: string
    enum: 
     - VALUE1
     - VALUE2
```

### Output
Module classes:
* Body
* InlineResponse200

#### Error
Both contain a reference to class MyEnum which does not exist.

### Environment:
* language: java
* swagger-codegen: master (2bb2ab6cad314c2a2ed97b0489049917c9386f22)
* swagger-parser: 1.0.12 and 1.0.14-SNAPSHOT

**Comment by jeffjcrowe** [comment]
Part of the issue seems to be that SwaggerDeserializer should be calling setType(type) instead of setType(value) which will always be null.
https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/util/SwaggerDeserializer.java#L662

This only partially fixes the problem since it just causes a completely empty MyEnum class to be generated instead (with no properties or possible way to set a value)

**Comment by fehguy** [comment]
Yes, there is a fix in swagger-models which is required to address this. The codegen should be updated shortly

**Comment by jeffjcrowe** [comment]
Good to know, thanks! Do you have a link to an issue or pull request I can reference by chance?

**Comment by jeffjcrowe** [comment]
Are there any known workarounds that achieve the same result in the mean time? I tried the following, but got an error running the generator:
```text
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'RequestBody'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:215)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
...
Caused by: java.lang.ClassCastException: io.swagger.models.ModelImpl cannot be cast to io.swagger.models.RefModel
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:789)
```

```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Enum Reuse Example
schemes:
  - https
paths:
  /api:
    post:
      operationId: post
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/RequestBody'
      responses:
        '200':
          description: ok
          schema:
            $ref: '#/definitions/ResponseBody'
definitions:
  RequestBody:
    allOf:
    - type: object
      properties:
        otherArg:
          type: string
    - $ref: '#/definitions/HasEnum'
  ResponseBody:
    allOf:
    - type: object
      properties:
        otherArg:
          type: string
    - $ref: '#/definitions/HasEnum'
  HasEnum:
    type: object
    properties:
      MyEnum:
        type: string
        enum: 
         - VALUE1
         - VALUE2

```

**Comment by fehguy** [comment]
Yes, it's a bug, but you can get around it like such:

```yaml
info: 
  version: "1.0.0"
  title: "Enum Reuse Example"
paths: 
  /api: 
    post: 
      operationId: "post"
      consumes: 
        - "application/json"
      responses: 
        200: 
          description: "ok"
          schema: 
            $ref: "#/definitions/ResponseBody"
      parameters: 
        - in: "body"
          name: "body"
          schema: 
            $ref: "#/definitions/RequestBody"
      produces: 
        - "application/json"
swagger: "2.0"
schemes: 
  - "https"
definitions: 
  RequestBody: 
    allOf: 
      - $ref: "#/definitions/HasEnum"
      - $ref: "#/definitions/Other"
  ResponseBody: 
    allOf: 
      - $ref: "#/definitions/HasEnum"
      - $ref: "#/definitions/Other"
  Other: 
    type: "object"
    properties: 
      otherArg: 
        type: "string"
  HasEnum: 
    type: "object"
    properties: 
      MyEnum: 
        enum: 
          - "VALUE1"
          - "VALUE2"
        type: "string"
```

The issue seems to be that the `allOf` construct _must_ have `$ref` items in the array.  It cannot have objects.  Again this is a bug, but what I'm suggesting is a work-around.

**Comment by jeffjcrowe** [comment]
Thanks for the workaround @fehguy! I'll use that until the issue is resolved.

**Comment by jeffjcrowe** [comment]
@fehguy This appears to be fixed in the most recent version. Safe to close the issue?

**Comment by fehguy** [comment]
done!
