### ISSUE TITLE
Unknown command line arguments throw an exception

### ISSUE THREAD

**Issue by seanfarley** [swagger-api/swagger-codegen#1717]
Shouldn't this display help (similar to that in the `README`)?

```shell
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar --help
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [--help]
	at io.airlift.airline.Cli.validate(Cli.java:148)
	at io.airlift.airline.Cli.parse(Cli.java:116)
	at io.airlift.airline.Cli.parse(Cli.java:97)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by wing328** [comment]
Please run this instead:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar help generate
```

Ref: https://github.com/swagger-api/swagger-codegen#to-generate-a-sample-client-library

**Comment by seanfarley** [comment]
Well, hopefully this prompts some fixes in UI experience.

**Comment by Soben** [comment]
I'm getting this same error, but when I'm trying to generate via homebrew... 

`$ swagger-codegen generate -i schema/swagger.json -l slim public
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [public]
	at io.airlift.airline.Cli.validate(Cli.java:148)
	at io.airlift.airline.Cli.parse(Cli.java:116)
	at io.airlift.airline.Cli.parse(Cli.java:97)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)`

It seems that I'm likely just calling this incorrectly... and I'll continue tinkering in the meantime.

**Comment by luktar** [comment]
The help info in swagger-codegen installed by homebrew on my mac works with the following command:

`swagger-codegen help generate`
