### ISSUE TITLE
lang.NullPointerException in "main"

### ISSUE THREAD

**Issue by illukarl23** [swagger-api/swagger-codegen#1753]
Hi,
I get an NullPointerException when trying to generate C# client Code.
Exception:
```
Exception in thread "main" java.lang.NullPointerException
        at io.swagger.codegen.DefaultGenerator.generateParameterId(DefaultGenerator.java:616)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:542)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:496)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:238)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

I get some C# Classes, but some are missing.
Unfortunately I can't post my swagger spec here, for what should i look after to get this running?
I am using Version 2.1.4 of Codegen.

**Comment by wing328** [comment]
@illukarl23 please use the latest master, which contains bug fixes and enhancements to the C# client and see if you still encounter the NPE.

**Comment by wing328** [comment]
Also you can use editor.swagger.io to validate your swagger spec.

**Comment by wing328** [comment]
@illukarl23 closing this as there's no update from you. Please reopen if needed.

**Comment by illukarl23** [comment]
Sorry that I didn't write back, I was occupied with other problems.
The swagger spec seems to be valid in the swagger editor, but if I try to generate the client in the editor I get "Unable to build target: null"
Details:    Object
                code: 1
                type: "error"
                message: "Unable to build target: null"
Unfortunately I no longer have the option to user Swagger CodeGen as an Application, I have to use the online editor.

**Comment by wing328** [comment]
Can you send the spec to the email address in my Github profile page and I'll try to troubleshoot the issue?

**Comment by illukarl23** [comment]
Ok, I will send you the spec.
Thank You!
