### ISSUE TITLE
[python] swagger responses versus API behavior

### ISSUE THREAD

**Issue by rbpasker** [swagger-api/swagger-codegen#1796]
my swagger.json has:

````		
"responses" : {
    "200" : {},
    "400": {}
}
````

but the python API ( https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/rest.mustache#L176 ) has:

````
        if r.status not in range(200, 206):
            raise ApiException(http_resp=r)
````

which means that when a web service generates a 400,  the machinery in the generated client code that converts the JSON response in the body into the swagger-generated response object never happens.

**Comment by rbpasker** [comment]
Here's an example where I expect the generated code to look for a '400' http-response-code and convert the payload into a message. instead, it just throws an exception, and doesn't deserialize the payload.

````
$ python 
>>> from swagger_client import DefaultApi
>>> api = DefaultApi()
>>> api.me_get()
Traceback (most recent call last):
  File "bad400.py", line 4, in <module>
    api.me_get()
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/swagger_client/apis/default_api.py", line 117, in me_get
    callback=params.get('callback'))
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/swagger_client/api_client.py", line 320, in call_api
    response_type, auth_settings, callback)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/swagger_client/api_client.py", line 147, in __call_api
    post_params=post_params, body=body)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/swagger_client/api_client.py", line 340, in request
    headers=headers)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/swagger_client/rest.py", line 184, in GET
    query_params=query_params)
  File "/Users/rbp/Projects/jupiter/default/lib/python2.7/site-packages/swagger_client/rest.py", line 177, in request
    raise ApiException(http_resp=r)
swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Length': '167', 'X-FB-Trace-ID': 'H7rLn7f2TtE', 'Expires': 'Sat, 01 Jan 2000 00:00:00 GMT', 'Vary': 'Accept-Encoding', 'WWW-Authenticate': 'OAuth "Facebook Platform" "invalid_request" "An active access token must be used to query information about the current user."', 'X-FB-Rev': '2114582', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-store', 'Date': 'Mon, 04 Jan 2016 18:09:32 GMT', 'Facebook-API-Version': 'v2.0', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json', 'X-FB-Debug': 'UGKA8PeaClQhh3tWMv+pjpaCAO+Py7dQc5tX9HAfNN1reHdaBjf5v3x8XiVqWnrKSJ9OUlbcQs17uQD3BB/xwg=='})
HTTP response body: {"error":{"message":"An active access token must be used to query information about the current user.","type":"OAuthException","code":2500,"fbtrace_id":"H7rLn7f2TtE"}}

````

here's the associated swagger file:

````
{
    "swagger": "2.0",
    "info": {
	"version": "0.0.1",
	"title": "<Bad400 API>"
    },
    "host": "graph.facebook.com/",
    "schemes":[
	"https"],
    "paths": {
	"/me" : { 
	    "get" : {
		"description": "gets the graph for a particular user", 
		"produces" : [ "application/json" ],
		"responses" : {
		    "400" : {
			
			"description" : "error",
			"schema" : {
			    "type" : "object", 
			    "properties":{
				"error" : {
				    "schema": {
					"type" : "object",
					"properties":{
					    "message" : "string",
					    "type" : "string",
					    "code" : "string",
					    "fbtrace_id" : "string"
					}
				    }
				}
			    }
			}
		    }
		}
	    }
	}
    }
}

````

**Comment by webron** [comment]
Regardless of the potential issue, that's not a valid definition. Your response schema is malformed.

Should be:
```json
"schema" :{
  "type": "object",
  "properties": {
    "error": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "fbtrace_id": {
          "type": "string"
        }
      }
    }
  }
}
```

**Comment by rbpasker** [comment]
good catch. fixed

**Comment by wing328** [comment]
@rbpasker yes, there's a limitation that the error object defined in the spec is not used in the Python.

Currently, ApiException contains status, reason, body and headers. Are you expecting another field to store the Error object, which is deserialised from the HTTP body of the response?

**Comment by rbpasker** [comment]
its not just the python codegen. the Java codegen has the same behavior.

**Comment by jaykwonpark** [comment]
Is it fixed on v2.2.2?
It seems the code is still there.

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/python/rest.mustache#L196
