### ISSUE TITLE
"Cookie" parameters are not supported - java.lang.Exception: Unknown parameter type: cookie

### ISSUE THREAD

**Issue by GuiSim** [swagger-api/swagger-codegen#181]
My REST API has a call that supports a parameter of type "Cookie". Swagger seems to handle it well when it comes to generating the server-side api-docs (using JAX-RS) and the JavaScript documentation is generated correctly.

Sadly, when it comes to generating a client, the operation fails with the following stacktrace:

```
java.lang.Exception: Unknown parameter type: cookie
        at com.wordnik.swagger.codegen.Codegen$$anonfun$apiToMap$2.apply(Codegen.scala:305)
        at com.wordnik.swagger.codegen.Codegen$$anonfun$apiToMap$2.apply(Codegen.scala:238)
        at com.wordnik.swagger.codegen.Codegen.apiToMap(Codegen.scala:238)
        at com.wordnik.swagger.codegen.Codegen$$anonfun$generateSource$2$$anonfun$apply$4.apply(Codegen.scala:83)
        at com.wordnik.swagger.codegen.Codegen$$anonfun$generateSource$2$$anonfun$apply$4.apply(Codegen.scala:77)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at com.wordnik.swagger.codegen.Codegen$$anonfun$generateSource$2.apply(Codegen.scala:77)
        at com.wordnik.swagger.codegen.Codegen$$anonfun$generateSource$2.apply(Codegen.scala:74)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at com.wordnik.swagger.codegen.Codegen.generateSource(Codegen.scala:74)
        at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$bundleToSource$1$$anonfun$apply$8.apply(BasicGenerator.scala:216)
        at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$bundleToSource$1$$anonfun$apply$8.apply(BasicGenerator.scala:215)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
        at com.wordnik.swagger.codegen.BasicGenerator.bundleToSource(BasicGenerator.scala:214)
        at com.wordnik.swagger.codegen.BasicGenerator.generateClientWithoutExit(BasicGenerator.scala:104)
        at com.wordnik.swagger.codegen.BasicGenerator.generateClient(BasicGenerator.scala:47)
        at com.wordnik.swagger.codegen.BasicPythonGenerator$.main(BasicPythonGenerator.scala:24)
        at com.wordnik.swagger.codegen.BasicPythonGenerator.main(BasicPythonGenerator.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
        at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
        at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
        at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
        at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by webron** [comment]
FWIW, cookie parameters are not technically supported by the spec.

**Comment by GuiSim** [comment]
Practically they are though ;)
Overall, a simple INFO instead of a crash would be sufficient.

**Comment by webron** [comment]
No, practically they're not.

**Comment by GuiSim** [comment]
Then why are the parameters correctly documented by swagger-core (with JAX-RS) and correctly handled by swagger-ui? From my point of view they are perfectly supported in this very standard scenario.

Generating a python client was the first time I ever encountered an issue with a Cookie parameter.

**Comment by wing328** [comment]
@GuiSim are you using Swagger spec 1.2? If yes, the issue may be similar to #594, which has been resolved in the branch `develop_2.0`.

Please give it another try with the branch `develop_2.0` and see if the issue persists.

**Comment by webron** [comment]
@GuiSim - The spec is the source of truth. If one library or another (yes, even core and ui) do something beyond it, it doesn't make it 'supported'. There are reasons why it is not officially supported mostly because it is not well defined yet. No point having people complain about things that don't work as expected because of that.

**Comment by GuiSim** [comment]
Alright, if the crash is as designed, I'll close this.
Thanks for your time.

**Comment by webron** [comment]
That's definitely not what I said. I said the spec does not support it. The application shouldn't crash where possible, and also, since it *is* produced by core, we may support it here as well, but the consistency of support may not be 100% the same. Also, in terms of priorities, we may deal with other issues first. I just wanted to clarify that officially, it is not part of the spec.

Feel free to reopen the issue, I really don't see a reason to close it.

**Comment by Boscop** [comment]
How can I pass cookies retrieved from the login request to all later requests with a swagger-codegen generated java client?
Do I have to modify the code manually every time I generate the code? Or does it support this already?
