### ISSUE TITLE
Tests error in the codegen module

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-codegen#1887]
I just re-cloned the repository from the branch master, and I'm getting an error while building the project. The error seems to concern the PerlClient

Stack trace:
```
checkOptionsHelp(io.swagger.codegen.perl.PerlClientOptionsTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:762)
	at java.util.regex.Matcher.replaceAll(Matcher.java:906)
	at java.lang.String.replaceAll(String.java:2162)
	at io.swagger.codegen.languages.PerlClientCodegen.<init>(PerlClientCodegen.java:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

checkOptionsProcessing(io.swagger.codegen.perl.PerlClientOptionsTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:658)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:762)
	at java.util.regex.Matcher.replaceAll(Matcher.java:906)
	at java.lang.String.replaceAll(String.java:2162)
	at io.swagger.codegen.languages.PerlClientCodegen.<init>(PerlClientCodegen.java:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Failed tests: 
  PerlClientOptionsTest.checkOptionsHelp » StringIndexOutOfBounds String index o...
  PerlClientOptionsTest.checkOptionsProcessing » StringIndexOutOfBounds String i...

Tests run: 186, Failures: 2, Errors: 0, Skipped: 3
```

**Comment by wing328** [comment]
@hiveship are you getting these errors on Windows?

**Comment by hiveship** [comment]
@wing328 it'es right, I'm on Windows 7

**Comment by wing328** [comment]
Due to #1867 

A workaround for the time being is to use `-DskipTests` when doing `mvn package`

**Comment by hiveship** [comment]
It's exactly what i'm currently doing !

**Comment by wing328** [comment]
Submitted https://github.com/swagger-api/swagger-codegen/pull/1897 to fix it.

Please help do a test when you've time.

**Comment by hiveship** [comment]
@wing328 I updated my repo and I can confirm it's now OK on Windows ! Good job :)
