### ISSUE TITLE
NullPointerException parsing JSON

### ISSUE THREAD

**Issue by tjuchniewicz** [swagger-api/swagger-codegen#1896]
`NullPointerExeption` is thrown when parsing specific Swagger definition. JSON file is generated using [Springfox](https://github.com/springfox/springfox).

Exampe file: [swagger.json.txt](https://github.com/swagger-api/swagger-codegen/files/91462/swagger.json.txt)

```
java -jar swagger-codegen-cli.jar generate -i swagger.json -l jaxrs -o generated/spring-mvc

reading from swagger.json
writing file generated\spring-mvc/src/gen/java/io/swagger/model\CommandServiceStatus
.java
writing file generated\spring-mvc/src/gen/java/io/swagger/model\Vin.java
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.swagger.models.properties.RefPr
operty["$ref"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:647)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
        at io.swagger.util.Json.pretty(Json.java:23)
        at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:902)
        at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1521)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1298)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:548)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:493)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:226)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
        at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
        ... 13 more
[main] WARN io.swagger.codegen.DefaultCodegen - Error obtaining the datatype from RefProperty:io.swagger.models.properties.RefProperty@dec188bd. Datat
ype default to Object
java.lang.NullPointerException
        at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
        at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:657)
        at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:427)
        at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:906)
        at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1521)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1298)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:548)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:493)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:226)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
[main] WARN io.swagger.codegen.DefaultCodegen - Error obtaining the datatype from RefProperty:io.swagger.models.properties.RefProperty@dec188bd. Datat
ype default to Object
java.lang.NullPointerException
        at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
        at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:657)
        at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:427)
        at io.swagger.codegen.DefaultCodegen.getTypeDeclaration(DefaultCodegen.java:711)
        at io.swagger.codegen.languages.JavaClientCodegen.getTypeDeclaration(JavaClientCodegen.java:356)
        at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1045)
        at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1521)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1298)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:548)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:493)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:226)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by wing328** [comment]
@tjuchniewicz https://editor.swagger.io reports 2 errors with swagger.json.txt. Please fix those and give it another try.

**Comment by tjuchniewicz** [comment]
I see it. This is probably bug in Springfox. Generated code is incompatible with Swagger specification. Thanks!
