### ISSUE TITLE
Generated nodejs server does not include `x-swagger-router-controller` or `operationId` attributes in `swagger.yaml`

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#1932]
_From @kmd-jamesgauld on January 20, 2016 13:59_

Swagger Router middleware requires that a `x-swagger-router-controller` attribute be present to help route requests to the correct controller, and an `operationId` attribute to route to a specific method.

Currently, when exporting a nodejs server app, the editor does not include these attributes in the `api/swagger.yaml` file which, when making a request to the nodejs server, throws the following error:

```
Error: Cannot resolve the configured swagger-router handler: undefined
    at swaggerRouter (/var/www/mock-api/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at call (/var/www/mock-api/node_modules/connect/index.js:239:7)
    at next (/var/www/mock-api/node_modules/connect/index.js:183:5)
    at /var/www/mock-api/node_modules/swagger-tools/middleware/swagger-validator.js:350:30
    at /var/www/mock-api/node_modules/async/lib/async.js:52:16
    at /var/www/mock-api/node_modules/async/lib/async.js:361:13
    at /var/www/mock-api/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/var/www/mock-api/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/var/www/mock-api/node_modules/async/lib/async.js:355:9)
    at Object.map (/var/www/mock-api/node_modules/async/lib/async.js:337:20)
```

Partial yaml config:

```
...
paths:
  /users:
    get:
      summary: "Get Users."
...
```

There exists a `controllers/User.js` file with relevant content:

```
...
module.exports.usersGet = function usersGet (req, res, next) {
  User.usersGet(req.swagger.params, res, next);
};
...
```

Adding the missing attributes fixes the problem:

```
...
paths:
  x-swagger-router-controller: User
  /users:
    get:
      operationId: usersGet
      summary: "Get Users."
...
```

_Copied from original issue: swagger-api/swagger-editor#784_

**Comment by djskinner** [comment]
Is there a workaround for this or some documentation? I have created an API using the swagger spec and am now trying to get a mock nodejs server running. However I just end up with the above error. Adding in x-swagger-router-controller: hello_world does not work for me as just get a slightly different error:

```
Error: Cannot resolve the configured swagger-router handler: Transactions_get
```

**Comment by wing328** [comment]
@kmd-jamesgauld @djskinner  if you can help confirm using the latest master of swagger-codegen and still encounter the same issue, I can take a look over the weekend.

**Comment by djskinner** [comment]
For me, using `NODE_ENV=development node index` to run the generated node.js server got things working and allowed the server to serve up stub data.

**Comment by wing328** [comment]
@djskinner is it correct to say that it's no longer an issue ?

**Comment by djskinner** [comment]
For me, yes.

**Comment by wing328** [comment]
Thanks for the confirmation. We'll incorporate your solution above when updating the README.md for `nodejs`.

**Comment by djskinner** [comment]
Yes that would be useful. I also had to install cors so that the mock server could correctly respond to OPTIONS requests etc. Not sure if this also worth mentioning. If you can point me in the right direction I can help with the contribution / discussion on this change

**Comment by wing328** [comment]
@djskinner thanks for offering help to contribute. A good starting point is here:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/nodejs/README.mustache

After updating the mustache template, please run `./bin/nodejs-petstore-server.sh` to update the Pestore sample for NodeJS server and then you can verify the updated README.md

**Comment by djskinner** [comment]
Thanks. I have done a bit more digging and have narrowed down the issue: https://github.com/swagger-api/swagger-codegen/issues/2423

My use of `NODE_ENV=development` above simply causes swagger-router to serve up mock data when it cannot find a controller.
