### ISSUE TITLE
nodejs server swagger-router handler error

### ISSUE THREAD

**Issue by sohelsd** [swagger-api/swagger-codegen#2001]
I am unable to hit the endpoint. Results in Error:

`Error: Cannot resolve the configured swagger-router handler: undefined
    at swaggerRouter (/home/ubuntu/workspace/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at call (/home/ubuntu/workspace/node_modules/connect/index.js:239:7)
    at next (/home/ubuntu/workspace/node_modules/connect/index.js:183:5)
    at /home/ubuntu/workspace/node_modules/swagger-tools/middleware/swagger-validator.js:350:30
    at /home/ubuntu/workspace/node_modules/swagger-tools/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/workspace/node_modules/swagger-tools/node_modules/async/lib/async.js:361:13
    at /home/ubuntu/workspace/node_modules/swagger-tools/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/home/ubuntu/workspace/node_modules/swagger-tools/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/home/ubuntu/workspace/node_modules/swagger-tools/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/ubuntu/workspace/node_modules/swagger-tools/node_modules/async/lib/async.js:337:20)`

**Comment by fehguy** [comment]
More details, please.

**Comment by sohelsd** [comment]
I think its related to https://github.com/apigee-127/swagger-tools/issues/274

I tried specifying x-swagger-router-controller but still didnt work for me. Getting an error: 
`Error: Cannot resolve the configured swagger-router handler: Appz_get`
<pre><code>/test:
    get:
      x-swagger-router-controller: Appz
      summary: test
      description: >
        test.
      tags:
        - Appz
      responses:
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
</code></pre>
