### ISSUE TITLE
Node.js Heroku app start error

### ISSUE THREAD

**Issue by sohelsd** [swagger-api/swagger-codegen#2069]
When I try to deploy the code generated app to heroku, I immediately see this in the logs. While the app seems to work fine on localhost. Am I missing anything? My Swagger file does not have any securityDefinitions defined since there is none needed.

<code>
2016-02-08T16:33:58.926765+00:00 app[web.1]: Starting process with command `node index.js`
2016-02-08T16:33:58.926765+00:00 app[web.1]: TypeError: Cannot read property 'securityDefinitions' of undefined at validateSwagger2_0 (/app/node_modules/swagger-tools/lib/specs.js:949:3)
at processDocument (/app/node_modules/swagger-tools/lib/specs.js:370:35)
at validateSemantically (/app/node_modules/swagger-tools/lib/specs.js:1033:5)
at /app/node_modules/swagger-tools/lib/specs.js:1226:7
at /app/node_modules/swagger-tools/lib/specs.js:712:12
at /app/node_modules/swagger-tools/lib/specs.js:1066:29
at process._tickCallback (node.js:401:9)
at /app/node_modules/swagger-tools/lib/specs.js:688:9
at Function.Module.runMain (module.js:449:11)
at startup (node.js:139:18)
2016-02-08T16:33:58.924252+00:00 app[web.1]: Error initializing middleware
2016-02-08T16:33:59.700847+00:00 heroku[web.1]: State changed from starting to crashed
2016-02-08T16:33:59.690130+00:00 heroku[web.1]: Process exited with status 1
</code>

**Comment by wing328** [comment]
Not an expert in Heroku myself but as you said it works locally so it might has to do with the Heroku environment.

Another way to troubleshoot is to use the Petstore example (https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/nodejs) to see if works in Heroku
(petstore contains `securityDefinitions` so it can help confirm if the issue you're seeing has to do with absence of `securityDefinitions` in your spec)

**Comment by wing328** [comment]
@sohelsd may I know if you've resolved the issue?

**Comment by wing328** [comment]
Closing this as there's no update from you.
