### ISSUE TITLE
yml file contains no errors but code generation fails

### ISSUE THREAD

**Issue by vbash** [swagger-api/swagger-codegen#2187]
yaml file I tried to generate java JAX-RS server from is attached to the defect
[swagger-6 (1).txt](https://github.com/swagger-api/swagger-codegen/files/138170/swagger-6.1.txt)

Steps to reproduce:
1. Open editor.swagger.io
2. Paste the attached swagger yml
3. Try to generate java JAX-RS server

Expected result:
  - server stub is generated

Actual result:
  - an error message shown

**Comment by wing328** [comment]
@vbash I got the following error when trying to generate a Java API client using later master of swagger-codegen:
```
swagger-codegen|master⚡ ⇒     java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
>    -i ~/Downloads/swagger-6.1.yml -l java \
>    -o /var/tmp/java/jaxrs/
reading from /Users/williamcheng/Downloads/swagger-6.1.yml
Exception in thread "main" java.lang.RuntimeException: An exception was thrown while trying to deserialize the contents of http://tract-swagger.s3.amazonaws.com/public/common/2.0/shared.yml into a JsonNode tree
	at io.swagger.parser.util.DeserializationUtils.deserializeIntoTree(DeserializationUtils.java:24)
	at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:102)
	at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:27)
	at io.swagger.parser.processors.PropertyProcessor.processRefProperty(PropertyProcessor.java:33)
	at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:21)
	at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:23)
	at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:44)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:72)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:317)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:186)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'definitions': was expecting ('true', 'false' or 'null')
 at [Source: definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
```
The error message suggests the issue has to do with `http://tract-swagger.s3.amazonaws.com/public/common/2.0/shared.yml` and I got some errors when pasting `shared.yml` in editor.swagger.io.

**Comment by wing328** [comment]
@vbash issue closed as we've not heard any update from you.
