### ISSUE TITLE
Exception when generating Perl SDK

### ISSUE THREAD

**Issue by HipZena** [swagger-api/swagger-codegen#2203]
When using swagger-codegen (latest master) to generate Perl SDK for https://www.neutrinoapi.com/api/swagger.json, I got exceptions/errors related to default value. For example
```
[main] WARN io.swagger.models.parameters.AbstractSerializableParameter - Illegal DefaultValue 6.0 for parameter type integer
java.lang.NumberFormatException: For input string: "6.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.valueOf(Long.java:540)
	at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:193)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
	at io.swagger.util.Json.pretty(Json.java:23)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1553)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1389)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:624)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:571)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:279)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```
The type is integer but default value is 6.0 (which is technically not an integer).

What about converting 6.0 to integer (6) to prevent the exception?

**Comment by wing328** [comment]
@HipZena thanks for the suggestion. The issue is with swagger-core (another project) at the following line
```
    at io.swagger.models.parameters.AbstractSerializableParameter.getDefault(AbstractSerializableParameter.java:193)
```

I'll take a look and submit a PR with the suggested enhancement to swagger-core.

**Comment by wing328** [comment]
Filed #1673 in swagger core to better handle the exception.

**Comment by HipZena** [comment]
Thanks! I've manually fixed those default values for the time being.

**Comment by wing328** [comment]
@HipZena as discussed with the core team, the user should be notified of the issue with the spec (via the exception) so I would suggest to notify the owner of the spec to fix it there as other 3rd-party tools for Swagger may run into the same issue.
