### ISSUE TITLE
NPE when generating API client

### ISSUE THREAD

**Issue by HipZena** [swagger-api/swagger-codegen#2331]
Using the latest master, I got the following NPE when generating Perl, Java and ObjC
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
>   -i https://api.luno.io/swagger.json \
>   -l perl \
>   -o /tmp/client/
reading from https://api.luno.io/swagger.json
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:20)
	at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:44)
	at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:72)
	at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:41)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:339)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:193)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```

I removed "default: null" from swagger.json so that there's no error shown in editor.swagger.io but still got the same exception above.

**Comment by wing328** [comment]
@HipZena thanks for reporting the issue. From the exception report, it seems like the issue has to do with responses. We'll look into this more.

**Comment by wing328** [comment]
@HipZena I tried with the latest master of swagger codegen and no longer encounter the issue. Please give it a try with the latest master.

Closing this issue for now.

**Comment by HipZena** [comment]
thanks for the update. will let you know if i still encounter the issue.

________________________________
