### ISSUE TITLE
NPE in JavaClientCodegen.toModelName

### ISSUE THREAD

**Issue by degroves** [swagger-api/swagger-codegen#2499]
I cloned the swagger-codegen repository this morning.  Commit 02c713c90d37acc462398ec0ba0836c035fd9c7b is the most recent commit in my local copy of the swagger-codegen repository.  I received an NPE using my locally produced swagger codegen on [this JSON spec](https://gist.github.com/degroves/d0916635d5b33c208185f717b9bbf4a1).

java -jar swagger-codegen-cli-2.1.6-SNAPSHOT.jar generate -i npe.json -l java -o target
[main] INFO io.swagger.parser.Swagger20Parser - reading from npe.json
[main] WARN io.swagger.util.PropertyDeserializer - no property from null, null, {ENUM=null, TITLE=null, DESCRIPTION=null, DEFAULT=null, PATTERN=null, DESCRIMINATOR=null, MIN_ITEMS=null, MAX_ITEMS=null, MIN_PROPERTIES=null, MAX_PROPERTIES=null, MIN_LENGTH=null, MAX_LENGTH=null, MINIMUM=null, MAXIMUM=null, EXCLUSIVE_MINIMUM=null, EXCLUSIVE_MAXIMUM=null, UNIQUE_ITEMS=null, EXAMPLE=null, TYPE=null, FORMAT=null, READ_ONLY=null, VENDOR_EXTENSIONS={}}
[main] ERROR io.swagger.codegen.languages.JavaClientCodegen - No Type defined for Property null
Exception in thread "main" java.lang.RuntimeException: Could not process model 'NpeResponse'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:244)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.languages.JavaClientCodegen.toModelName(JavaClientCodegen.java:401)
	at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:514)
	at io.swagger.codegen.DefaultCodegen.getTypeDeclaration(DefaultCodegen.java:862)
	at io.swagger.codegen.languages.JavaClientCodegen.getTypeDeclaration(JavaClientCodegen.java:428)
	at io.swagger.codegen.languages.JavaClientCodegen.toDefaultValue(JavaClientCodegen.java:441)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1083)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2232)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2206)
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1000)
	at io.swagger.codegen.languages.JavaClientCodegen.fromModel(JavaClientCodegen.java:538)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:799)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:237)
	... 2 more

**Comment by fehguy** [comment]
Hi, the issue is your `arrayofstuff` cannot have an array for `items`--it should be an object:

```json
    "NpeResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/response"
        },
        {
          "type": "object",
          "properties": {
            "arrayofstuff": {
              "type": "array",
              "items":
                {
                  "$ref": "#/definitions/stuff"
                }
              
            }
          }
        }
      ]
    }
```

I agree the NPE isn't nice, but your definition isn't valid.

**Comment by degroves** [comment]
@fehguy : Thanks for your help.  We didn't realize our schema was incorrect.  We're fixing it now.

The generator should handle a bad schema more gracefully, but I think fixing this bug can be a low priority.
