### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by webron** [swagger-api/swagger-codegen#2525]
_From @VishnuGShephertz on April 7, 2016 11:30_

I am able to build swagger client, but while calling API I am getting Exception  **java.lang.ExceptionInInitializerError** in APIInvoker class.
Let me know the solution how can I resolve this here is stacktrace.

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.Project31.api.FinalTestApi.<init>(FinalTestApi.java:20)
	at com.Project31.api.FinalTestApi.main(FinalTestApi.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: Stub!
	at org.apache.http.conn.ssl.SSLSocketFactory.<init>(SSLSocketFactory.java:9)
	at com.Project31.ApiInvoker$2.<init>(ApiInvoker.java:425)
	at com.Project31.ApiInvoker.initConnectionManager(ApiInvoker.java:425)
	at com.Project31.ApiInvoker.<init>(ApiInvoker.java:195)
	at com.Project31.ApiInvoker.<clinit>(ApiInvoker.java:58)
	... 7 more

_Copied from original issue: swagger-api/swagger.io#96_

**Comment by VishnuGShephertz** [comment]
As Android has deprecated apache client, So I think we should use default connection API provided by java itself

**Comment by wing328** [comment]
@VishnuGShephertz  please refer to https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-generate-an-android-sdk
