### ISSUE TITLE
auto-generated Node.js server code has a error if the API path contains underline(_)

### ISSUE THREAD

**Issue by lienhua34** [swagger-api/swagger-codegen#2621]
I have a swagger api spec file, which content is
```
swagger: '2.0'
info:
  version: "0.0.0"
  title: "Hello World API"
paths:
  /hello/{user_id}:
    get:
      description: |
        Returns a greeting to the user
      parameters:
        -
          name: user_id
          in: path
          description: The name of the user to greet
          required: true
          type: string
      responses:
        200:
          description: Return the greeting.
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.
```
I edit this file in http://editor.swagger.io, and use “generate server --> Node.js” to generate Node.js server stub code.

After I start the server, I open another terminal and use the following command to call the api,
   $ curl http://localhost:8080/hello/lienhua34

The server responses a error. The error is 
```
lienhua34@nodejs-server-server$ node index.js 
Your server is listening on port 8080 (http://localhost:8080)
Swagger-ui is available on http://localhost:8080/docs
Error: Cannot resolve the configured swagger-router handler: Default_helloUser_idGET
    at swaggerRouter (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at call (/home/lienhua34/Downloads/nodejs-server-server/node_modules/connect/index.js:239:7)
    at next (/home/lienhua34/Downloads/nodejs-server-server/node_modules/connect/index.js:183:5)
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-validator.js:350:30
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:52:16
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:361:13
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:337:20)
Error: Cannot resolve the configured swagger-router handler: Default_helloUser_idGET
    at swaggerRouter (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-router.js:414:18)
    at call (/home/lienhua34/Downloads/nodejs-server-server/node_modules/connect/index.js:239:7)
    at next (/home/lienhua34/Downloads/nodejs-server-server/node_modules/connect/index.js:183:5)
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-validator.js:350:30
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:52:16
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:361:13
    at /home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:236:30)
    at _asyncMap (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:355:9)
    at Object.map (/home/lienhua34/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/async/lib/async.js:337:20)
```
**I open the api/swagger.yaml file, and find that the operationId for /hello/{user_id} is “helloUser_idGET”. But in the controllers/Default.js file, the route handler function is “helloUserIdGET”.**

**Comment by wing328** [comment]
I think it's similar to this issue: https://github.com/swagger-api/swagger-codegen/issues/2409

**Comment by kolyjjj** [comment]
A temporary solution is to add `operationId: getHelloByUserId`

Below is what I used for generating, and it works fine after I download it.
```
swagger: '2.0'
info:
  version: "0.0.0"
  title: "Hello World API"
paths:
  /hello/{user_id}:
    get:
      description: |
        Returns a greeting to the user
      operationId: getHelloByUserId
      parameters:
        -
          name: user_id
          in: path
          description: The name of the user to greet
          required: true
          type: string
      responses:
        200:
          description: Return the greeting.
          schema:
            type: string
        400:
          description: Invalid characters in "user" were provided.
```

**Comment by wing328** [comment]
PR merged into master. Issue closed.
