### ISSUE TITLE
Error happened when the name of properties of Model is "property" of Python client

### ISSUE THREAD

**Issue by WillaLuo** [swagger-api/swagger-codegen#2644]
Hi, Does anyone know why this happened,

The Model defined like this:
```
"StorageSnapshot-response": {
            "properties": {
                "status": {
                    "type": "string"
                }, 
                "start_timestamp": {
                    "type": "string"
                }, 
                "name": {
                    "type": "string"
                }, 
                "snapshot_timestamp": {
                    "type": "string"
                }, 
                "description": {
                    "type": "string"
                }, 
                "tags": {
                    "items": {
                        "type": "string"
                    }, 
                    "type": "array"
                }, 
                "uri": {
                    "type": "string"
                }, 
                "status_detail": {
                    "type": "string"
                }, 
                "volume": {
                    "type": "string"
                }, 
                "snapshot_id": {
                    "type": "string"
                }, 
                "status_timestamp": {
                    "type": "string"
                }, 
                "account": {
                    "type": "string"
                }, 
                "property": {
                    "type": "string"
                }, 
                "size": {
                    "type": "string"
                }
            }
        }
```

And this the error message:
```
(virtualenv2.7)-bash-4.1$ python
Python 2.7.8 (default, Mar 16 2016, 01:07:52)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import swagger_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "swagger_client/__init__.py", line 4, in <module>
    from .models.account_discover_response import AccountDiscoverResponse
  File "swagger_client/models/__init__.py", line 84, in <module>
    from .storage_snapshot_response import StorageSnapshotResponse
  File "swagger_client/models/storage_snapshot_response.py", line 25, in <module>
    class StorageSnapshotResponse(object):
  File "swagger_client/models/storage_snapshot_response.py", line 374, in StorageSnapshotResponse
    @property
TypeError: 'property' object is not callable

```

**Comment by wing328** [comment]
I think it's complaining about the property with the name "property". If you manually change it to something else (e.g. _property), the compilation error should go away.

We can fix it permanently by updating the reserved keyword list defined for the Python code generator.

**Comment by wing328** [comment]
@WillaLuo I've filed https://github.com/swagger-api/swagger-codegen/pull/2661 to fix it

**Comment by wing328** [comment]
PR merged into master. Please pull the latest and let us know if you still see the same issue.
