### ISSUE TITLE
Code generation fails with "java.lang.Double/Integer cannot be cast to java.lang.String"

### ISSUE THREAD

**Issue by maciejmakowski** [swagger-api/swagger-codegen#2688]
After upgrading from the 2.1.5 to 2.1.6 our code generation is failing with (we actually have it both failing on a Double and Integer conversion, example here with Double):
```
  Exception: java.lang.Double cannot be cast to java.lang.String
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:720)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:612)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:339)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:283)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1867)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1518)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:668)
	... 25 more
```

After some digging I figured it comes down to a property like this (this time example with integer):
```
          {
            "name": "limit",
            "in": "query",
            "description": "Max amount of results per request",
            "required": false,
            "type": "integer",
            "x-example": 5
          },
```

If I change the "x-example" line like this, the problem goes away:
```
            "x-example": "5"
```

The problem is however that this schema is generated from swagger annotations, and it turns out that we don't have any control over this. We also don't want to just remove the examples. So I think the only real solution is to fix the code.

I'm pretty sure I can nail this down to this cast:
```
        // set the example value
        // if not specified in x-example, generate a default value
        if (p.vendorExtensions.containsKey("x-example")) {
            p.example = (String) p.vendorExtensions.get("x-example");
        } else if (Boolean.TRUE.equals(p.isString)) {
```

The problem here is that apparently we can't be just blindly be casting to string that way (specifically when Double or Integer is the actual type of the "x-example"), we have to convert things to a string.

I would suggest changing this to something like this instead:
```
            p.example = Objects.toString(p.vendorExtensions.get("x-example"));
```

**Comment by wing328** [comment]
@maciejmakowski thanks for reporting the issue with the suggested fix. I've filed #2689 to fix it.

Have a nice weekend.
