### ISSUE TITLE
Order of allOf's elements affect to success of Generate Server (Sinatra)

### ISSUE THREAD

**Issue by saharj** [swagger-api/swagger-codegen#2729]
_From @orangeudav on April 26, 2016 21:45_

Hi! I have swagger-editor@2.9.9
This work fine:
```
  Client:
    type: object
    allOf:
      - $ref: "#/definitions/ClientFactory"
      - properties:
          id:
            description: Id of client
            type: integer
            format: int32
```
but if i change order like this
```
  Client:
    type: object
    allOf:
      - properties:
          id:
            description: Id of client
            type: integer
            format: int32
      - $ref: "#/definitions/ClientFactory"
```
i get 
```
Code Generator Error
Unable to build target: Could not process model 'Client'

Details:

 Object
code: 1
type:  "error"
message:  "Unable to build target: Could not process model 'Client'"
```
Is it normal behavior ?

_Copied from original issue: swagger-api/swagger-editor#894_

**Comment by saharj** [comment]
_From @orangeudav on April 27, 2016 10:7_

Good yaml
```
swagger: '2.0'
info:
  title: xxx
  description: xxx
  version: 1.0.0
  contact:
    name: xxx
    email: xxx@xxx.xxx
  license:
    name: xxx
host: xxx
schemes:
  - https
basePath: /
produces:
  - application/json
consumes:
  - application/json
paths:
  /feedback: {}
definitions:
  ClientFactory:
    type: object
    properties:
      name:
        type: string
      enabled:
        type: boolean      
  Client:
    type: object
    allOf:
      - $ref: "#/definitions/ClientFactory"
      - properties:
          id:
            description: Id of client
            type: integer
            format: int32
```
Result of swagger-generate:
```
swagger-codegen generate  -l swagger -i good.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from good.yaml
[main] INFO io.swagger.codegen.DefaultGenerator - writing file /Users/orangeudav/test_swagger/./README.md
```
Result of swagger-editor generate sinatra server: OK, got zip-file


Bad yaml (changed order of allOf's content)
```
swagger: '2.0'
info:
  title: xxx
  description: xxx
  version: 1.0.0
  contact:
    name: xxx
    email: xxx@xxx.xxx
  license:
    name: xxx
host: xxx
schemes:
  - https
basePath: /
produces:
  - application/json
consumes:
  - application/json
paths:
  /feedback: {}
definitions:
  ClientFactory:
    type: object
    properties:
      name:
        type: string
      enabled:
        type: boolean
  Client:
    type: object
    allOf:
      - properties:
          id:
            description: Id of client
            type: integer
            format: int32
      - $ref: "#/definitions/ClientFactory"
```
Result of swagger-generate:
```
swagger-codegen generate  -l swagger -i bad.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from bad.yaml
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Client'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:244)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.ClassCastException: io.swagger.models.ModelImpl cannot be cast to io.swagger.models.RefModel
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:955)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:799)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:237)
	... 2 more
```
Result of swagger-editor generate sinatra server:
```
Unable to build target: Could not process model 'Client'
Details:
 Object
code: 1
type:  "error"
message:  "Unable to build target: Could not process model 'Client'"
```
