### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')

### ISSUE THREAD

**Issue by NadaBen** [swagger-api/swagger-codegen#2891]
Hello,
when i try to run this command 
`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i E:\TCTSUmons\swagger.yml -l swagger`

it shows me this error:
`[main] INFO io.swagger.parser.Swagger20Parser - reading from E:/TCTSUmons/swagger.yml
[main] INFO io.swagger.parser.Swagger20Parser - reading from E:/TCTSUmons/swagger.yml
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: E:\TCTSUmons\swagger.yml; line: 1, column: 9]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:72)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:390)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:89)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)`

and my swagger.yml file is as follows: 

`swagger: "2.0"

info:
  version: 1.0.0
  title: API
  description: An API to 

schemes:
  - https
host: simple.api
basePath: http://localhost/test/web/app_dev.php

paths:
  /v1/photos/bymachinetags:
    get:
      summary: Gets photos
      description: Returns a list of photos with possibility of filtring by machine tags. The list supports paging.
      parameters:
       - name: page
         in: query
         description: Page number
         type: integer
       - name: machinetags
         in: query
         description: list of machine tags 
         type: string
      responses:
        200:
          description: A list of Photos
          schema:
            type: array
            items:
              required:
                - id
              properties:
                created_at:
                  type: string
				  format: date
                tags:
                  type: string
                machinetags:
                  type: string

  /v1/photos:
    post:
      summary: Creates a photo
      description: Adds a new photo to the photos list.
      parameters:
        - name: photo
          in: body
          description: The photo to create.
          schema:
            required:
              - id
            properties:
              tags:
                type: string
              machinetags:
                type: string
              image:
                type: string
				format: byte
      responses:
        204:
          description: Photo succesfully created.
        400:
          description: Photo couldn't have been created.`

**Comment by wing328** [comment]
@NadaBen have you used tools like https://editor.swagger.io to validate your swagger spec?

**Comment by NadaBen** [comment]
I tried to install it, but when i run npm start it shows me:
`C:\Windows\System32\swagger-editor>npm start

> swagger-editor@2.10.1 start C:\Windows\System32\swagger-editor
> node server.js

Development server started at http://127.0.0.1:8080
Opening the browser

WARNING in ./~/json-schema-view-js/dist/bundle.js
Critical dependencies:
1:487-494 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/json-schema-view-js/dist/bundle.js 1:487-494
Child worker:

Child worker:

Child extract-text-webpack-plugin:
`

**Comment by NadaBen** [comment]
and when i validate it with an other validator, it shows me 
`E:\TCTSUmons\Tools\wget-1.17.1-win64\swagger-codegen>java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i E:\TCTSUmons\swagger.yaml -l swagger
[main] INFO io.swagger.parser.Swagger20Parser - reading from E:/TCTSUmons/swagger.yaml
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: post /v1/photos. Renamed to auto-generated operationId: v1PhotosPost
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: get /v1/photos/bymachinetags. Renamed to auto-generated operationId: v1PhotosBymachinetagsGet
[main] INFO io.swagger.codegen.DefaultGenerator - writing file E:\TCTSUmons\Tools\wget-1.17.1-win64\swagger-codegen\.\README.md`

**Comment by NadaBen** [comment]
solved , i had a problem of my yaml file, format of parameters was uncleard..

**Comment by fizxmike** [comment]
Sorry to re-open a closed issue, but I encountered a very similar problem. It happens with the the [boilerplate example](https://swagger.io/docs/specification/basic-structure/):

# YAML
```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /patientSummaries:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

# Result
```
> java -jar..\..\swagger-codegen-cli-2.3.1.jar generate -l swagger -i .\swagger.yaml -v -o test
[main] INFO io.swagger.codegen.config.CodegenConfigurator -
VERBOSE MODE: ON. Additional debug options are injected
 - [debugSwagger] prints the swagger specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.yaml
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.yaml
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'openapi': was expecting ('true', 'false' or 'null')
 at [Source: .\swagger.yaml; line: 1, column: 9]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3528)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2447)
        at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:189)
        at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:75)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:731)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by fizxmike** [comment]
The solution for me was to add the following two lines to the YAML file.
```yml
definitions:
  none:
```

**Comment by egch** [comment]
> The solution for me was to add the following two lines to the end of the YAML file.
> 
> ```yaml
> definitions:
>   none:
> ```

I tried it but didn't work :(

**Comment by shail123kec** [comment]
I was facing the same issue but it seems for me YAML( formatting) is the culprit for this error.

**Comment by danielbartsch** [comment]
Pasting my yaml file into https://editor.swagger.io revealed that one property had wrong indentation, which caused the issue for me. Fixing the indentation fixed it.
