### ISSUE TITLE
Making new codegen module - Unexpected parameter

### ISSUE THREAD

**Issue by luciasarni** [swagger-api/swagger-codegen#3059]
##### Description

I´m following the instructions from [here](https://github.com/swagger-api/swagger-codegen#making-your-own-codegen-modules) and I get this error:

```
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [\]
        at io.airlift.airline.Cli.validate(Cli.java:148)
        at io.airlift.airline.Cli.parse(Cli.java:116)
        at io.airlift.airline.Cli.parse(Cli.java:97)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
```

##### Command line used for generation

`java -jar swagger-codegen-cli.jar meta \ -o output/myLibrary -n myClientCodegen -p com.my.company.codegen`

**Comment by rahulearl** [comment]
Hey, can you please share how did this get resolved ? I am also stuck with same exception unfortunately.

**Comment by lsarni** [comment]
@rahulearl Just remove `\` after `meta`:

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar meta -o output/myLibrary -n myClientCodegen -p com.my.company.codegen`
