### ISSUE TITLE
[JAVA, JS] Exception during generation when parameter's schema has allOf

### ISSUE THREAD

**Issue by danadam** [swagger-api/swagger-codegen#3161]
##### Description

The code generator fails with exception when processing valid swagger definition file:

```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: default
  Operation: bla
  Resource: get /example
  Definitions: {foo=io.swagger.models.ModelImpl@75731c0b}
  Exception: null
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:785)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:677)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:365)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.DefaultCodegen.isDataTypeBinary(DefaultCodegen.java:2254)
        at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2237)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1839)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:733)
```
##### Swagger-codegen version

`cc5e79cd0d19 (2016-06-17 19:36:24 +0800) wing328 - move server stub doc to wiki`
##### Swagger declaration file content or url

``` yaml
swagger: "2.0"
info:
    version: "0.1.0"
    title: bla
host: example.com
paths:
    /example:
        get:
            operationId: bla
            parameters:
            -   name: MyParam
                in: body
                schema:
                    type: object
                    allOf:
                    -   $ref: '#/definitions/foo'
            responses:
                default:
                    description: bla

definitions:
    foo:
        type: object
        properties:
            elem:
                type: string
```
##### Command line used for generation

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i bug.yaml -l java -o bla`

**Comment by wing328** [comment]
We don't support `allOf` in method's parameters at the moment.

As a workaround, please define the models without `allOf` for the time being.

**Comment by JLLeitschuh** [comment]
I don't know if this seems like it would be valid according to the open api specification.

What would the intended effect be?

**Comment by fehguy** [comment]
Please take a look at the OAI spec.  There is no support for `schema` in any parameters except `in: body`.  In the 3.0 spec that'll change.
