### ISSUE TITLE
okhttp-gson Java client in Android gives NetworkOnMainThreadException

### ISSUE THREAD

**Issue by sidhantgoyal** [swagger-api/swagger-codegen#3335]
##### Description

I am using the swagger generated java client (using okhttp-gson library) in Android. Recieving android.os.NetworkOnMainThreadException

##### Swagger-codegen version
I am using the current master branch 

##### Client code in Android 

```java

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;

import com.x.x.api.ProductLookupApi;
import com.x.x.models.Item;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ProductLookupApi productLookupApiInstance = new ProductLookupApi();
        try {
            Item item = productLookupApiInstance.getItem("12345567");
            Log.d("Main Activity", item.getName());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

##### Stacktrace 

```
Failed writing handshake bytes (-1 of 14): Broken pipe
07-11 15:23:25.282 3152-3160/com.x.x W/art: Suspending all threads took: 10.713ms
07-11 15:23:25.314 3152-3152/com.x.x W/System: ClassLoader referenced unknown path: /data/app/com.x.x-1/lib/x86_64
07-11 15:23:27.483 3152-3152/com.x.x W/System: ClassLoader referenced unknown path: /data/app/com.x.x-1/lib/x86_64
07-11 15:23:27.723 3152-3152/com.x.x W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
07-11 15:23:27.823 3152-3152/com.x.x W/System.err: android.os.NetworkOnMainThreadException
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:286)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:80)
07-11 15:23:27.823 3152-3152/com.x.x W/System.err:     at com.x.x.ApiClient.execute(ApiClient.java:980)
```

**Comment by wing328** [comment]
Would the following help?

http://stackoverflow.com/questions/6343166/how-to-fix-android-os-networkonmainthreadexception

**Comment by sidhantgoyal** [comment]
Thanks.. I noticed there are async functions as well in generated code. Using them works fine.
