### ISSUE TITLE
Head fails to build due to test error

### ISSUE THREAD

**Issue by bluemmc** [swagger-api/swagger-codegen#3369]
##### Description

Can not build latest version on windows due to test error.

##### Swagger-codegen version

Latest version from head.

##### Swagger declaration file content or url

Tests run: 514, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 18.913 sec <<< FAILURE! - in TestSuite
testSkipOverwrite(io.swagger.codegen.DefaultGeneratorTest)  Time elapsed: 1.263 sec  <<< FAILURE!
java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
        templateFile: gradle-wrapper.jar
        folder: gradle\wrapper
        destinationFilename: gradle-wrapper.jar
'
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:577)
        at io.swagger.codegen.DefaultGeneratorTest.testSkipOverwrite(DefaultGeneratorTest.java:180)

Results :

Failed tests:
  DefaultGeneratorTest.testSkipOverwrite:180 » Runtime Could not generate suppor...

   <test-method status="FAIL" signature="testSkipOverwrite()[pri:0, instance:io.swagger.codegen.DefaultGeneratorTest@3cb1ffe6]" name="testSkipOverwrite" duration-ms="1253" started-at="2016-07-14T14:16:24Z" finished-at="2016-07-14T14:16:25Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Could not generate supporting file 'SupportingFile:
	templateFile: gradle-wrapper.jar
	folder: gradle\wrapper
	destinationFilename: gradle-wrapper.jar
']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
	templateFile: gradle-wrapper.jar
	folder: gradle\wrapper
	destinationFilename: gradle-wrapper.jar
'
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:593)
	at io.swagger.codegen.DefaultGeneratorTest.testSkipOverwrite(DefaultGeneratorTest.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.io.FileNotFoundException: C:\Users\UW4J\AppData\Local\Temp\junit5719672984201658963\gradle\wrapper\gradle-wrapper.jar (The requested operation cannot be performed on a file with a user-mapped section open)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:577)
	... 10 more
]]>
            </full-stacktrace>
          </exception> 
          <reporter-output>
          </reporter-output>
        </test-method> 

##### Command line used for generation

mvn package

##### Steps to reproduce

git pull
mvn clean
mvn package

**Comment by wing328** [comment]
@bluemmc thanks for reporting the issue. We now do have CI (provided by AppVeyor) to cover tests in Windows environment. Here is the link to the build result:

https://ci.appveyor.com/project/WilliamCheng/swagger-codegen-wh2wu

Do you mind cloning the git repo into another temp directory to see if the issue goes away?

**Comment by bluemmc** [comment]
Just tried again with a fresh clone of git clone "https://github.com/swagger-api/swagger-codegen.git"
followed my "mvn package"

Got the same error. I don't know why your CI is working. The problem is about file creation (see previous msg). Maybe the build is trying to create a file at an absolute path (outside the cloned folder) that is not permitted on my machine.

**Comment by wing328** [comment]
I just did a test in Windows7 and `mvn clean package` works for me without issue.

As a workaround, you can skip the tests with 'mvn clean package -DskipTests`

**Comment by bluemmc** [comment]
I suspect the problem is that the file "gradle-wrapper.jar" is created at a location that is illegal on my machine (maybe at a root folder). Can you search the entire Windows7 machine drive and see if the test in the build placed the file at a strange location ?

**Comment by wing328** [comment]
If it's still an issue, we'll reopen this issue.
