### ISSUE TITLE
Could not generate model exception

### ISSUE THREAD

**Issue by bernhardwaidacher** [swagger-api/swagger-codegen#3545]
##### Description

I get an "Could not generate model" exception when trying to use the swagger codegen.

> Exception in thread "main" java.lang.RuntimeException: Could not generate model 'Account'
>   at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:358)
>   at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
>   at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
> Caused by: java.io.FileNotFoundException: /output/SwaggerClient/Classes/Swaggers/Models/Account.swift (No such file or directory)
>   at java.io.FileOutputStream.open0(Native Method)
>   at java.io.FileOutputStream.open(FileOutputStream.java:270)
>   at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
>   at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
>   at io.swagger.codegen.AbstractGenerator.writeToFile(AbstractGenerator.java:31)
>   at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:647)
>   at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:317)
>   ... 2 more
##### Swagger-codegen version

Newest version, just installed a few minutes ago with Homebrew
##### Swagger declaration file content or url

```
swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /account:
    x-swagger-router-controller: account_controller
    get:
      operationId: getAllAccounts
      description: Returns all accounts
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetAccountsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      operationId: addAccount
      description: Add an account
      parameters:
        - name: name
          description: name of the account
          in: body
          required: true
          schema:
            $ref: "#/definitions/Account"
      responses:
        200:
            description: Success
            schema:
              $ref: "#/definitions/InsertionResponse"
        default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /account/{id}:
    x-swagger-router-controller: account_controller
    put:
      operationId: changeAccount
      description: updates a movie
      # define the parameters
      parameters:
        - name: id
          description: id of the account to be changed
          type: string
          in: path
          required: true
        - name: title
          description: new name of the account
          in: body
          required: true
          schema:
            $ref: "#/definitions/Account"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ChangeResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: deleteAccount
      description: deletes an account
      parameters:
        - name: id
          description: id of the account to be changed
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeleteResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GetAccountsResponse:
    required:
      - accounts
    properties:
      # The array of movies
      accounts:
        type: array
        items: 
          type: object
          properties:
            id:
              type: number
            name:
              type: string
  InsertionResponse:
    type: object
    properties:
      id:
        type: number
        description: id of the newly inserted object
      description:
        type: string
        description: a short comment 
    required:
      - id
      - description
  ChangeResponse:
    type: object
    properties:
      id:
        type: number
        description: id of the changed object
      description:
        type: string
        description: a short comment 
    required:
      - id
      - description
  DeleteResponse:
    type: object
    properties:
      description:
        type: string
        description: a short comment 
    required:
      - description
  Account:
    type: object
    properties:
      id:
        type: number
        description: account id
      name:
        type: string
        description: name of the account
    required:
      - name
```
##### Command line used for generation

swagger-codegen generate -i /Users/Bernhard1/Documents/ausgabenbackend/ausgabenbackend/api/swagger/swagger.yaml -l swift -o /output/

**Comment by wing328** [comment]
I could not repeat the issue using the latest master. Please try with the latest master and let us know if you still experience the issue.

**Comment by bernhardwaidacher** [comment]
I found out that I have to use sudo to make it work. 
Is there anything I could do to make it work without sudo?

I also discovered some other bugs
In "APIs.swift", the basePath was set wrong. 
It was
`public static var basePath = "http://localhost:10010/"`
instead of 
`public static var basePath = "http://localhost:10010"`

If I want to use a get method, for example like this:
```
DefaultAPI.getAllAccounts({data, error in
            print(error)
        })
```

I get an exception:

> Could not cast value of type '__NSCFArray' (0x10a96bd68) to 'NSDictionary' (0x10a96bfe8).


In this method: (Models.swift) 
```
Decoders.addDecoder(clazz: GetAccountsResponse.self) { (source: AnyObject) -> GetAccountsResponse in
                let sourceDictionary = source as! [NSObject:AnyObject] //here is the exception
                let instance = GetAccountsResponse()
                instance.accounts = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["accounts"])
                return instance
            }
```
