### ISSUE TITLE
[nodejs-server] "ENOENT: no such file or directory, scandir './controllers" error at start with a very simple API

### ISSUE THREAD

**Issue by simonwoo** [swagger-api/swagger-codegen#3557]
##### Description

When I generate the node server code with swagger editor and launch it , it does not work.

##### Swagger-codegen version

2.2.0

##### Swagger declaration file content or url
 ```json  
 {
  "swagger": "2.0",
  "info": {
    "description": "No description",
    "version": "1.0.0",
    "title": "Simple",
    "contact": {}
  },
  "tags": [],
  "paths": {
    "/user": {
      "get": {
        "tags": [],
        "summary": "Get",
        "consumes": [],
        "produces": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}
 ```
 
##### Error
```
Error initializing middleware
Error: ENOENT: no such file or directory, scandir './controllers'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at /Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-router.js:75:15
    at arrayEach (/Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/lodash-compat/index.js:1421:13)
    at Function.<anonymous> (/Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/node_modules/lodash-compat/index.js:3482:13)
    at handlerCacheFromDir (/Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-router.js:74:5)
    at Object.module.exports [as swaggerRouter] (/Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/middleware/swagger-router.js:377:20)
    at /Users/wuchong/Downloads/nodejs-server-server/index.js:30:22
    at /Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/index.js:85:7
    at cbWrapper (/Users/wuchong/Downloads/nodejs-server-server/node_modules/swagger-tools/lib/specs.js:1035:5)
```

**Comment by wing328** [comment]
Closing this as there's no update.
