### ISSUE TITLE
followed instructions but sbt assembly fails everytime. I need some help

### ISSUE THREAD

**Issue by cantecim** [swagger-api/swagger-codegen#367]
Using;
JDK 1.7
Scala 2.10.4
Maven 3.2.5
sbt from the its own website (Used msi package to install it)

I cloned repo and started terminal went into the root directory of repo
Ran sbt assembly.. and the output is below

```
[info] Loading project definition from D:\swagger-codegen\project
[info] Set current project to swagger-codegen (in build file:/D:/swagger-codegen/)
[warn] Credentials file C:\Users\Can\.ivy2\.credentials does not exist
[info] SwaggerModelTest:
[info] Swagger Model
[info] - should deserialize ResourceListing
[info] - should deserialize ApiListing
[info] - should deserialize ApiListing with AllowableValues
[info] - should maintain model property order when deserializing
[info] - should deserialize models
17:46:57,249 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:46:57,249 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:46:57,249 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/swagger-codegen/target/scala-2.10/classes/logback.xml]
17:46:57,297 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:46:57,298 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:46:57,304 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:46:57,341 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
17:46:57,341 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
17:46:57,341 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
17:46:57,342 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.wordnik] to DEBUG
17:46:57,342 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
17:46:57,342 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
17:46:57,342 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:46:57,343 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@28c2b9e7 - Registering current configuration as safe fallback point

[info] BasicGeneratorTest:
[info] BasicGenerator
[info] - should get operations
[info] - should verify ops are grouped by path correctly
[info] - should create a model map
[info] - should create a model file
[info] CoreUtilsTest:
[info] CoreUtils
[info] - should verify models are extracted
[info] - should verify operation names
[info] - should find required models
[info] - should find required models from a nested list
[info] BasicCSharpGeneratorTest:
[info] BasicCSharpGenerator
[info] - should perserve the name date
[info] - should process a string array
[info] ResourceExtractorTest:
[info] ResourceExtractor
[info] - should get 3 apis from a resource listing
[info] ApiExtractorTest:
[info] ApiExtractor
[info] - should verify the deserialization of the store api
[info] BasicScalaGeneratorTest:
[info] BasicScalaGenerator
[info] - should process a response declaration
[info] - should process a string response
[info] - should process a string array
[info] - should process an unmapped response type
[info] - should get the invoker package
[info] - should get the api package
[info] - should get the model package
[info] - should convert to a declared type
[info] - should convert a string a declaration
[info] - should honor the import mapping
[info] - should quote a reserved var name
[info] - should create a declaration with a List of strings
[info] - should create a declaration with a List of ints
[info] - should create a declaration with a List of floats
[info] - should create a declaration with a List of doubles
[info] - should create a declaration with a List of complex objects
[info] - should verify an api map with query params
[info] - should verify an api map with query params with default values
[info] - should create an api file
[info] ResourceListingSerializersTest:
[info] - should deserialize an ResourceListing with no apis
[info] - should serialize an ApiListingReference with no apis
[info] - should deserialize an ResourceListing
[info] - should serialize an ApiListingReference
[info] ApiListingReferenceSerializersTest:
[info] - should deserialize an ApiListingReference
[info] - should serialize an ApiListingReference
[info] ApiDescriptionSerializersTest:
[info] - should deserialize an ApiDescription with no ops
[info] - should serialize an ApiDescription with no operations
[info] - should deserialize an ApiDescription
[info] - should serialize an ApiDescription
[info] OperationSerializersTest:
[info] - should deserialize an Operation
[info] - should serialize an operation
[info] ErrorResponseSerializersTest:
[info] - should deserialize an ResponseResponse
[info] - should serialize an operation
[info] ParameterSerializersTest:
[info] - should deserialize another param
[info] - should deserialize a parameter
[info] - should serialize a parameter
[info] ModelSerializationTest:
[info] - should deserialize a model
[info] - should serialize a model
[info] ModelRefSerializationTest:
[info] - should deserialize a model ref
[info] - should serialize a model ref
[info] ModelPropertySerializationTest:
[info] - should deserialize a model property with allowable values and ref
[info] - should serialize a model property with allowable values and ref
[info] - should deserialize a model property with allowable values
[info] - should serialize a model property with allowable values
[info] - should deserialize a model property
[info] - should serialize a model property
[info] AllowableValuesSerializersTest:
[info] - should deserialize allowable value list
[info] - should serialize allowable values list
[info] - should deserialize allowable values range
[info] - should serialize allowable values range
[info] CodegenConfigTest:
[info] PathUtil
[info] - should convert an api name
[info] - should convert a path
[info] CodegenConfig
[info] - should process a response declaration
[info] - should process an unchanged response
[info] - should process an mapped response type
[info] - should get the invoker package
[info] - should get the api package
[info] - should get the model package
[info] - should convert to a declared type
[info] - should honor the import mapping
[info] - should quote a reserved var name
[info] BasicJavaGeneratorTest:
[info] BasicJavaGenerator
[info] - should process a response declaration
[info] - should process a string response
[info] - should process a string array
[info] - should process an upper-case string array
[info] - should process an unmapped response type
[info] - should get the invoker package
[info] - should get the api package
[info] - should get the model package
[info] - should convert to a declared type
[info] - should convert a string a declaration
[info] - should honor the import mapping
[info] - should quote a reserved var name
[info] - should create a declaration with a List of strings
[info] - should create a declaration with a List of ints
[info] - should create a declaration with a List of floats
[info] - should create a declaration with a List of doubles
[info] - should create a declaration with a List of complex objects
[info] CodegenTest:
[info] Codegen
[info] - should recognize the returnContainer as a List
[info] CoreUtilsTest:
[info] CoreUtils
[info] - should verify models are extracted
[info] - should verify operation names
[info] - should find required models
[info] - should find required models from a nested list
[info] ResourceListingValidationTest:
[info] - should not have base path
[info] - should fail resource listing without apiVersion
[info] - should fail with missing paths in a ResourceListing
[info] ApiListingReferenceValidationTest:
[info] - should deserialize an ApiListingReference
[info] - should serialize an ApiListingReference
[info] ApiDescriptionValidationTest:
[info] - should fail to deserialize an ApiDescription with path, method, return type
[info] OperationValidationTest:
[info] - should fail to deserialize an Operation with missing param type
[info] - should serialize an operation
[info] ResponseMessageValidationTest:
[info] - should deserialize an ResponseMessage
[info] - should serialize an operation
[info] ParameterValidationTest:
[info] - should deserialize another param
[info] - should deserialize a parameter
[info] - should serialize a parameter
[info] ModelValidationTest:
[info] - should deserialize a model
[info] - should serialize a model
[info] ModelRefValidationTest:
[info] - should deserialize a model ref
[info] - should serialize a model ref
[info] ModelPropertyValidationTest:
[info] - should deserialize a model property with allowable values and ref
[info] - should serialize a model property with allowable values and ref
[info] - should deserialize a model property with allowable values
[info] - should serialize a model property with allowable values
[info] - should deserialize a model property
[info] - should serialize a model property
[info] AllowableValuesValidationTest:
[info] - should deserialize allowable value list
[info] - should serialize allowable values list
[info] - should deserialize allowable values range
[info] - should serialize allowable values range
[info] ResourceExtractorTest:
[info] ResourceExtractor
[info] - should get 3 apis from a resource listing
[info] ApiExtractorTest:
[info] ApiExtractor
[info] - should verify the deserialization of the store api
[info] ResourceListingSerializersTest:
[info] - should deserialize an ResourceListing with no apis
[info] - should deserialize an ResourceListing
[info] ApiListingReferenceSerializersTest:
[info] - should deserialize an ApiListingReference
[info] - should serialize an ApiListingReference
[info] ApiListingSerializersTest:
[info] - should deserialize an ApiListing
[info] - should serialize an ApiListing
[info] ApiDescriptionSerializersTest:
[info] - should deserialize an ApiDescription with no ops
[info] - should serialize an ApiDescription with no operations
[info] - should deserialize an ApiDescription
[info] - should serialize an ApiDescription
[info] OperationSerializersTest:
[info] - should deserialize an Operation
[info] - should deserialize an Operation with an array property
[info] - should serialize an operation
[info] - should deserialize an Operation with array
[info] ErrorResponseSerializersTest:
[info] - should deserialize an Response
[info] - should serialize an operation
[info] ParameterSerializersTest:
[info] - should deserialize another param
[info] - should deserialize a parameter
[info] - should serialize a parameter
[info] ModelSerializationTest:
[info] - should deserialize a model
[info] - should deserialize a model with a set
[info] - should serialize a model
[info] ModelRefSerializationTest:
[info] - should deserialize a model ref
[info] - should serialize a model ref
[info] ModelPropertySerializationTest:
[info] - should deserialize a model property with allowable values and ref
[info] - should serialize a model property with allowable values and ref
[info] - should deserialize a model property with allowable values
[info] - should serialize a model property with allowable values
[info] - should deserialize a model property
[info] - should serialize a model property
[info] - should extract model properties
[info] - should extract model properties with arrays
[info] AllowableValuesSerializersTest:
[info] - should deserialize allowable value list
[info] - should serialize allowable values list
[info] - should deserialize allowable values range
[info] - should serialize allowable values range
[info] PathUtilTest:
[info] PathUtil
[info] - should convert an api name
[info] - should convert a path
[info] - should get determine the basePath implicitly
[info] ResourceListingValidationTest:
[info] - should fail resource listing without base path
[info] - should fail resource listing without apiVersion
[info] - should fail with missing paths in a ResourceListing
[info] ApiListingReferenceValidationTest:
[info] - should deserialize an ApiListingReference
[info] - should serialize an ApiListingReference
[info] ApiDescriptionValidationTest:
[info] - should fail to deserialize an ApiDescription with path, method, return type
[info] OperationValidationTest:
[info] - should fail to deserialize an Operation with missing param type
[info] - should serialize an operation
[info] ResponseMessageValidationTest:
[info] - should deserialize an ResponseMessage
[info] - should serialize an operation
[info] ParameterValidationTest:
[info] - should deserialize another param
[info] - should deserialize a parameter
[info] - should serialize a parameter
[info] ModelValidationTest:
[info] - should deserialize a model
[info] - should serialize a model
[info] ModelRefValidationTest:
[info] - should deserialize a model ref
[info] - should serialize a model ref
[info] ModelPropertyValidationTest:
[info] - should deserialize a model property with allowable values and ref
[info] - should serialize a model property with allowable values and ref
[info] - should deserialize a model property with allowable values
[info] - should serialize a model property with allowable values
[info] - should deserialize a model property
[info] - should serialize a model property
[info] AllowableValuesValidationTest:
[info] - should deserialize allowable value list
[info] - should serialize allowable values list
[info] - should deserialize allowable values range
[info] - should serialize allowable values range
[info] Run completed in 4 seconds, 277 milliseconds.
[info] Total number of tests run: 195
[info] Suites: completed 55, aborted 0
[info] Tests: succeeded 195, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Including from cache: scalate-util_2.10-1.7.0.jar
[info] Including from cache: json4s-jackson_2.10-3.2.10.jar
[info] Including from cache: commons-io-2.3.jar
[info] Including from cache: base64-2.3.8.jar
[info] Including from cache: jackson-annotations-2.3.0.jar
[info] Including from cache: jackson-core-2.3.1.jar
[info] Including from cache: slf4j-api-1.6.1.jar
[info] Including from cache: scalap-2.10.0.jar
[info] Including from cache: json4s-ast_2.10-3.2.10.jar
[info] Including from cache: jackson-databind-2.3.1.jar
[info] Including from cache: scala-inflector_2.10-1.3.5.jar
[info] Including from cache: scallop_2.10-0.9.5.jar
[info] Including from cache: paranamer-2.6.jar
[info] Including from cache: json4s-core_2.10-3.2.10.jar
[info] Including from cache: scalate-core_2.10-1.7.0.jar
[info] Including from cache: scala-reflect.jar
[info] Including from cache: scala-library.jar
[info] Including from cache: scala-compiler.jar
java.lang.RuntimeException: deduplicate: different file contents found in the following:
C:\Users\Can\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\bundles\jackson-annotations-2.3.0.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.3.1.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\bundles\jackson-databind-2.3.1.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\com.thoughtworks.paranamer\paranamer\jars\paranamer-2.6.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\commons-io\commons-io\jars\commons-io-2.3.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\io.backchat.inflector\scala-inflector_2.10\jars\scala-inflector_2.10-1.3.5.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\net.iharder\base64\jars\base64-2.3.8.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.json4s\json4s-ast_2.10\jars\json4s-ast_2.10-3.2.10.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.json4s\json4s-core_2.10\jars\json4s-core_2.10-3.2.10.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.json4s\json4s-jackson_2.10\jars\json4s-jackson_2.10-3.2.10.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.rogach\scallop_2.10\jars\scallop_2.10-0.9.5.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.scala-lang\scalap\jars\scalap-2.10.0.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.scalatra.scalate\scalate-core_2.10\bundles\scalate-core_2.10-1.7.0.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.scalatra.scalate\scalate-util_2.10\bundles\scalate-util_2.10-1.7.0.jar:META-INF/MANIFEST.MF
C:\Users\Can\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.6.1.jar:META-INF/MANIFEST.MF
C:\Users\Can\.sbt\boot\scala-2.10.4\lib\scala-compiler.jar:META-INF/MANIFEST.MF
C:\Users\Can\.sbt\boot\scala-2.10.4\lib\scala-library.jar:META-INF/MANIFEST.MF
C:\Users\Can\.sbt\boot\scala-2.10.4\lib\scala-reflect.jar:META-INF/MANIFEST.MF
	at sbtassembly.Plugin$Assembly$.sbtassembly$Plugin$Assembly$$applyStrategy$1(Plugin.scala:205)
	at sbtassembly.Plugin$Assembly$$anonfun$11.apply(Plugin.scala:219)
	at sbtassembly.Plugin$Assembly$$anonfun$11.apply(Plugin.scala:217)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
	at sbtassembly.Plugin$Assembly$.applyStrategies(Plugin.scala:221)
	at sbtassembly.Plugin$Assembly$.apply(Plugin.scala:171)
	at sbtassembly.Plugin$.sbtassembly$Plugin$$assemblyTask(Plugin.scala:157)
	at sbtassembly.Plugin$$anonfun$baseAssemblySettings$6.apply(Plugin.scala:369)
	at sbtassembly.Plugin$$anonfun$baseAssemblySettings$6.apply(Plugin.scala:368)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] C:\Users\Can\.ivy2\cache\com.fasterxml.jackson.core\jackson-annotations\bundles\jackson-annotations-2.3.0.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\com.fasterxml.jackson.core\jackson-core\bundles\jackson-core-2.3.1.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\com.fasterxml.jackson.core\jackson-databind\bundles\jackson-databind-2.3.1.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\com.thoughtworks.paranamer\paranamer\jars\paranamer-2.6.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\commons-io\commons-io\jars\commons-io-2.3.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\io.backchat.inflector\scala-inflector_2.10\jars\scala-inflector_2.10-1.3.5.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\net.iharder\base64\jars\base64-2.3.8.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.json4s\json4s-ast_2.10\jars\json4s-ast_2.10-3.2.10.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.json4s\json4s-core_2.10\jars\json4s-core_2.10-3.2.10.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.json4s\json4s-jackson_2.10\jars\json4s-jackson_2.10-3.2.10.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.rogach\scallop_2.10\jars\scallop_2.10-0.9.5.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.scala-lang\scalap\jars\scalap-2.10.0.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.scalatra.scalate\scalate-core_2.10\bundles\scalate-core_2.10-1.7.0.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.scalatra.scalate\scalate-util_2.10\bundles\scalate-util_2.10-1.7.0.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.ivy2\cache\org.slf4j\slf4j-api\jars\slf4j-api-1.6.1.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.sbt\boot\scala-2.10.4\lib\scala-compiler.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.sbt\boot\scala-2.10.4\lib\scala-library.jar:META-INF/MANIFEST.MF
[error] C:\Users\Can\.sbt\boot\scala-2.10.4\lib\scala-reflect.jar:META-INF/MANIFEST.MF
[error] Total time: 7 s, completed 08.Oca.2015 17:47:02
```

**Comment by webron** [comment]
Honestly, I'd recommend you use the develop_2.0 branch. It's pure java, supports all spec versions, and generally easier to use.

**Comment by cantecim** [comment]
I ended up adding these lines to end of the build.sbt

```
excludedFiles in assembly <<=
(excludedFiles in assembly) {
  (old) => (bases) =>
    old(bases) ++ (bases flatMap (base =>
      (base / "META-INF/MANIFEST.MF").get)) ++ (bases flatMap (base =>
      (base / "META-INF/NOTICE").get)) ++ (bases flatMap (base =>
      (base / "META-INF/LICENSE").get))
}
```

First there was the problem only with META-INF/MANIFEST.MF so i added these lines

```
excludedFiles in assembly <<=
(excludedFiles in assembly) {
  (old) => (bases) =>
    old(bases) ++ (bases flatMap (base =>
      (base / "META-INF/MANIFEST.MF").get))
}
```

But another problem came up on second try so i added the every file which became problem

For example the file META/NOTICE

added **++ (bases flatMap (base =>
      (base / "META-INF/LICENSE").get))**
```
excludedFiles in assembly <<=
(excludedFiles in assembly) {
  (old) => (bases) =>
    old(bases) ++ (bases flatMap (base =>
      (base / "META-INF/MANIFEST.MF").get)) ++ (bases flatMap (base =>
      (base / "META-INF/LICENSE").get))
}

```

Hope it helps everyone
