### ISSUE TITLE
[Scala] Path parameters not handled correctly in Scalatra server

### ISSUE THREAD

**Issue by jtnystrom** [swagger-api/swagger-codegen#3686]
##### Description

Path parameters lead to generated code that produces exceptions at runtime.
E.g. this kind of parameter:

```
/assays/{assayId}:
  get:
      summary: "Information about a single assay."
      parameters:
        - name: assayId
          in: path
```

Produces this code in the Scalatra server:
```
  get("/assays/{assayId}",operation(assaysAssayIdGetOperation)) {

```

Which gives this exception at runtime:

```
java.util.regex.PatternSyntaxException: Illegal repetition near index 8
^/assays/{assayId}$
        ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.closure(Pattern.java:3157)
	at java.util.regex.Pattern.sequence(Pattern.java:2134)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at scala.util.matching.Regex.<init>(Regex.scala:191)
	at scala.collection.immutable.StringLike$class.r(StringLike.scala:255)
	at scala.collection.immutable.StringOps.r(StringOps.scala:29)
	at scala.collection.immutable.StringLike$class.r(StringLike.scala:244)
	at scala.collection.immutable.StringOps.r(StringOps.scala:29)
	at org.scalatra.RegexPathPatternParser$PartialPathPattern.toPathPattern(pathPatternParsers.scala:53)
	at org.scalatra.SinatraPathPatternParser.apply(pathPatternParsers.scala:69)

```

The correct generated code, to avoid this exception, is probably:

```
  get("/assays/:assayId",operation(assaysAssayIdGetOperation)) {

```

This is in the latest snapshot from GitHub.

**Comment by wing328** [comment]
@jtnystrom thanks for reporting the issue. I've a fix which should address the issue. Will submit a PR soon but would need your help to verify the fix.

**Comment by wing328** [comment]
@jtnystrom #3694 merged into master. Please pull the latest master and give it another try.

**Comment by jtnystrom** [comment]
Thanks for your quick fix - I can confirm that this problem has been solved.
