### ISSUE TITLE
Swift language generation error

### ISSUE THREAD

**Issue by razalur** [swagger-api/swagger-codegen#3693]
##### Description

Hello! I'm trying to generate swift code such as:
```bash
swagger-codegen generate -i file.json -l swift -o /tmp/test/
```

But I have an error:
```bash
Exception in thread "main" java.lang.RuntimeException: Could not process model 'MyModel'.Please make sure that your schema is correct!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:290)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at io.swagger.codegen.languages.SwiftCodegen.fromProperty(SwiftCodegen.java:339)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2695)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2666)
	at io.swagger.codegen.DefaultCodegen.addVars(DefaultCodegen.java:2652)
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1268)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:868)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:283)
	... 2 more
```

Can't understand why so. My json is valid and the same operation for objective-c language was finished correctly.

My swagger-codegen's version is 2.2.2

**Comment by Edubits** [comment]
Thanks for reporting the issue @razalur. Could you attach the relevant part of the Swagger json?

**Comment by razalur** [comment]
I'm trying to generate by this json code:
```json
{
  "basePath": "/myPath",
  "definitions": {
    "SomeValue": {
      "properties": {
        "level": {
          "description": "word (1 = Simple1 , 2 = Simple2 , 3 = Simple3 , 4 = Simple4 )",
          "enum": [
            1,
            2,
            3,
            4
          ],
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    }
  },
  "paths": {},
  "swagger": "2.0"
}
```

**Comment by razalur** [comment]
Do you fix this n the near future?

**Comment by Edubits** [comment]
Thanks for providing us with the swagger.json, @razalur. Could you try the latest master? The code causing the error is changed and locally I'm now able to generate Swift code for your Swagger definition. Hope it works for you as well!

**Comment by razalur** [comment]
@Edubits Thank you! Now it's work.
