### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by KevinColemanInc** [swagger-api/swagger-codegen#370]
Anyone have any ideas as to why its having trouble with this host name?  My computer's name is eagle1, but I have no idea why it would be trying to talk to it when trying to build the codegen

Java version 1.7

    11:18:09 ~/Downloads/swagger-codegen-master $ java -version
    java version "1.7.0_71"
    Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

mvn version 3.25

    11:18:17 ~/Downloads/swagger-codegen-master $ mvn --version
    Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T11:29:23-06:00)
    Maven home: /usr/local/Cellar/maven/3.2.5/libexec
    Java version: 1.6.0_65, vendor: Apple Inc.
    Java home: /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    Default locale: en_US, platform encoding: MacRoman
    OS name: "mac os x", version: "10.10.1", arch: "x86_64", family: "mac"

scala version 2.11.4

    11:18:18 ~/Downloads/swagger-codegen-master $ brew info scala
    scala: stable 2.11.4 (bottled)
    http://www.scala-lang.org/
    /usr/local/Cellar/scala/2.11.4 (46 files, 29M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/scala.rb
    ==> Options
    --with-docs
      Also install library documentation
    --with-src
      Also install sources for IDE support
    ==> Caveats
    To use with IntelliJ, set the Scala home to:
      /usr/local/opt/scala/idea

    Bash completion has been installed to:
      /usr/local/etc/bash_completion.d
    11:18:18 ~/Downloads/swagger-codegen-master $ scala
    Welcome to Scala version 2.11.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_71).
    Type in expressions to have them evaluated.
    Type :help for more information.

    scala> 11:18:20 ~/Downloads/swagger-codegen-master 

Error I get when running $ ./sbt assembly

    $11:18:21 ~/Downloads/swagger-codegen-master $ ./sbt assembly
    [info] Loading project definition from /Users/kcoleman/Downloads/swagger-codegen-master/project
    [info] Set current project to swagger-codegen (in build file:/Users/kcoleman/Downloads/swagger-codegen-master/)
    [warn] Credentials file /Users/kcoleman/.ivy2/.credentials does not exist
    java.net.UnknownHostException: eagle1: eagle1: nodename nor servname provided, or not known
      at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
      at sbt.JUnitXmlTestsListener.<init>(JUnitXmlTestsListener.scala:18)
      at sbt.plugins.JUnitXmlReportPlugin$$anonfun$projectSettings$1.apply(JUnitXmlReportPlugin.scala:27)
      at sbt.plugins.JUnitXmlReportPlugin$$anonfun$projectSettings$1.apply(JUnitXmlReportPlugin.scala:27)
      at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
      at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
      at sbt.std.Transform$$anon$4.work(System.scala:64)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
      at sbt.Execute.work(Execute.scala:244)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
      at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:745)
    Caused by: java.net.UnknownHostException: eagle1: nodename nor servname provided, or not known
      at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
      at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
      at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
      at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
      at sbt.JUnitXmlTestsListener.<init>(JUnitXmlTestsListener.scala:18)
      at sbt.plugins.JUnitXmlReportPlugin$$anonfun$projectSettings$1.apply(JUnitXmlReportPlugin.scala:27)
      at sbt.plugins.JUnitXmlReportPlugin$$anonfun$projectSettings$1.apply(JUnitXmlReportPlugin.scala:27)
      at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
      at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
      at sbt.std.Transform$$anon$4.work(System.scala:64)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
      at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
      at sbt.Execute.work(Execute.scala:244)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
      at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
      at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
      at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
      at java.util.concurrent.FutureTask.run(FutureTask.java:262)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:745)
    [error] (*:testListeners) java.net.UnknownHostException: eagle1: eagle1: nodename nor servname provided, or not known
    [error] Total time: 1 s, completed Jan 9, 2015 11:18:32 PM

**Comment by KevinColemanInc** [comment]
Per this slashdot question http://stackoverflow.com/questions/7714696/scala-hello-world-script-does-not-work

you have to set your hosts file to point to your local ip address

**Comment by fehguy** [comment]
Thanks, never saw that one!

**Comment by KevinColemanInc** [comment]
@fehguy I wish I read this first...

http://laurent.sarrazin.io/2014/07/how-to-install-swagger-codegen-on-mac-os-x.html

Maybe link to it in your readme?

**Comment by fehguy** [comment]
Thank you for that.  I will say that the develop_2.0 branch is much easier to build.
