### ISSUE TITLE
Java Codegen's Feign Client SimpleDateFormat is incompatible with Android 

### ISSUE THREAD

**Issue by natami** [swagger-api/swagger-codegen#3753]
Generating a Feign Client using Swagger Codegen v.2.2.1, results in the following exception upon including and running the Client on android with API 23.

`FATAL EXCEPTION: main
                                                                                  Process: com.brightware.iot.clients.android, PID: 1778
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.brightware.iot.clients.android/com.brightware.iot.clients.android.activities.LoginActivity_}: java.lang.IllegalArgumentException: Unknown pattern character 'X'
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
                                                                                      at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
                                                                                      at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
                                                                                      at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
                                                                                      at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)`

**Comment by cbornet** [comment]
Yes, see #3727. Fix is in progress.
Meanwhile, you have several solutions:
* use joda as dateLibrary
* configure the ApiClient to use Jackson's ISO8601DateFormat ```apiClient.getObjectMapper().setDateFormat(new ISO8601DateFormat())```

**Comment by natami** [comment]
The client is using Joda as datelib.

Addin apiClient.getObjectMapper().setDateFormat(new ISO8601DateFormat()) to the mix does no difference :/

**Comment by cbornet** [comment]
Then it shouldn't try to use SimpleDateFormat... Do you have java.util.Date types somewhere in your models ?

**Comment by cbornet** [comment]
On a side note, for android, I would prefer Retrofit2. Feign is more oriented towards server/micro-service

**Comment by cbornet** [comment]
@natami can you paste the full stacktrace ? Is it crashing when instanciating the ObjectMapper ?

**Comment by cbornet** [comment]
I can't find a SimpleDateFormat with 'X' in the code we generate nor in Jackson. Are you sure it's not in your own code ?

**Comment by cbornet** [comment]
Found it in FormAwareEncoder !

**Comment by cbornet** [comment]
You can replace
```
this.dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
```
by
```
this.dateFormat = new ISO8601DateFormat();
```
in FormAwareEncoder.
Unfortunately you have to modify the generated code for now...

**Comment by natami** [comment]
Hi, Christophe!

I'll give it a go - thanks for your time ;)
