### ISSUE TITLE
[C#] Base class with enum field causes NullPointerException

### ISSUE THREAD

**Issue by att741** [swagger-api/swagger-codegen#3795]
##### Description

Base class with enum field causes NullPointerException:

Exception in thread "main" java.lang.RuntimeException: Could not process model 'TestNs.TestClass2'.Please make sure that
 your schema is correct!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:297)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1176)
        at io.swagger.codegen.languages.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:313)
        at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1158)
        at io.swagger.codegen.languages.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:316)
        at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:875)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:290)
        ... 2 more

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

    ```json
 {
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "TestNs"
  },
  "host": "localhost:80",
  "schemes": [ "https" ],
  "paths": {
    "/Test": {
      "get": {
        "tags": [ "Test" ],
        "summary": "Tests the method.",
        "operationId": "TestMethod",
        "consumes": [ ],
        "produces": [ "application/json", "text/json", "application/xml", "text/xml" ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": { "$ref": "#/definitions/TestNs.TestClass" }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "TestNs.TestClass": {
      "required": [ "$Type" ],
      "type": "object",
      "properties": {
        "Enum": {
          "enum": [ "Value1", "Value2" ],
          "type": "string"
        },
        "$Type": {
          "description": "The discriminator.",
          "type": "string"
        }
      },
      "discriminator": "$Type"
    },
    "TestNs.TestClass2": {
      "type": "object",
      "allOf": [
        { "$ref": "#/definitions/TestNs.TestClass" },
        {
          "type": "object",
          "properties": { }
        }
      ],
      "properties": { }
    }
  }
}
    ```
##### Command line used for generation

java -jar Tools\swagger-codegen-cli-2.2.1.jar generate -i $swaggerEndpoint -l csharp -D packageName=$projectName -o $clientFolder

**Comment by RowanJKWalker** [comment]
Hi @jimschubert and @wing328,

I am also getting this error but when the enum is in the schema inheriting from the schema with a discriminator. I haven't had time to look into the swagger-codegen code to see what the potential issue would be. Is this a known issues and know what the fix would be?

Thanks.

**Comment by fonix232** [comment]
This issue should be looked into. I'm experiencing the same on a proprietary spec where we have a base return type and multiple inheriting objects using discriminator in the parent to decide type, and various enum fields on the inheriting types.

No matter where the enum is, `swagger-codegen` crashes with pretty much every generator where the model is processed. This definitely happens after the spec is processed (since the debug output shows the model to be perfectly fine, and the crash happens in `DefaultCodegen.java`'s `fromModel(String name, Model model, Map<String,Model> allDefinitions)` call, specifically where the `CodegenModel` output's title is set (i.e. first time accessing the parameter model). The issue happens before this call is run, Model itself is null, which happens in the `fromParameter`, where a check is run if `param` is `BodyParameter`, then the schema is converted to a `ModelImpl`, which ends up as null.

**Comment by jimschubert** [comment]
I believe this issue as reported was fixed in 2.2.3?

The schema in the above issue builds correctly on current master.

There's been a longstanding issue with the C# client generator in which enums referenced as top-level objects weren't being treated in the same way C# treats enums. I believe this is partially due to Swagger Codegen's original target being JVM languages, in which enums are true objects rather than syntactic sugar for integral types.

I've opened #6851 to treat enums consistently, whether defined as top-level objects or inlined enum properties.

As for the issues described by @RowanJKWalker and @fonix232, it would be helpful to include a minimum schema to repro with expected outputs. Again, I generated the schema in this issue against the C# client generator and the output looks correct and compiles cleanly.

Probably a point of note is that there will be some limitations to the current C# client generator code. For instance, if you have multiple `allOf` definitions which define a property of the same name (e.g. `Enum`), the generator currently considers only the parent's `Enum` property as the enum.  That is, if you were to add a new `Enum` field with values `Value3` and `Value4` to the above schema, the C# generator will generate:

```
/// <summary>
/// TestNsTestClass
/// </summary>
[DataContract]
[JsonConverter(typeof(JsonSubtypes), "$Type")]
[JsonSubtypes.KnownSubType(typeof(TestNsTestClass2), "TestNs.TestClass2")]
public partial class TestNsTestClass :  IEquatable<TestNsTestClass>, IValidatableObject
{
    /// <summary>
    /// Gets or Sets _Enum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EnumEnum
    {
       
        /// <summary>
        /// Enum Value1 for "Value1"
        /// </summary>
        [EnumMember(Value = "Value1")]
        Value1,
        
        /// <summary>
        /// Enum Value2 for "Value2"
        /// </summary>
        [EnumMember(Value = "Value2")]
        Value2
    }

    /// <summary>
    /// Gets or Sets _Enum
    /// </summary>
    [DataMember(Name="Enum", EmitDefaultValue=false)]
    public EnumEnum? _Enum { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="TestNsTestClass" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected TestNsTestClass() { }

    /// <summary>
    /// Initializes a new instance of the <see cref="TestNsTestClass" /> class.
    /// </summary>
    /// <param name="_Enum">_Enum.</param>
    /// <param name="Type">The discriminator. (required).</param>
    public TestNsTestClass(EnumEnum? _Enum = default(EnumEnum?), string Type = default(string))
    {
        // to ensure "Type" is required (not null)
        if (Type == null)
        {
            throw new InvalidDataException("Type is a required property for TestNsTestClass and cannot be null");
        }
        else
        {
            this.Type = Type;
        }
        this._Enum = _Enum;
    }
    
    /// <summary>
    /// The discriminator.
    /// </summary>
    /// <value>The discriminator.</value>
    [DataMember(Name="$Type", EmitDefaultValue=false)]
    public string Type { get; set; }
   
    // etc…
}
```

and 

```
/// <summary>
/// TestNsTestClass2
/// </summary>
[DataContract]
public partial class TestNsTestClass2 : TestNsTestClass,  IEquatable<TestNsTestClass2>, IValidatableObject
{
    /// <summary>
    /// Initializes a new instance of the <see cref="TestNsTestClass2" /> class.
    /// </summary>
    [JsonConstructorAttribute]
    protected TestNsTestClass2() { }
    /// <summary>
    /// Initializes a new instance of the <see cref="TestNsTestClass2" /> class.
    /// </summary>
    public TestNsTestClass2(EnumEnum? _Enum = default(EnumEnum?), string Type = default(string)) : base()
    {
    }
    
    // etc…
}
```

Another point, based on the schema in this issue, is that namespaced definition names aren't supported. This isn't clearly documented anywhere that I could see in JSON Schema or Swagger Specification 2.0. But, it's not supported in the C# generator (and most likely not in others since the model name sanitization is used almost everywhere).

Per OpenAPI 2.0:

> Swagger allows combining and extending model definitions using the allOf property of JSON Schema, in effect offering model composition. allOf takes in an array of object definitions that are validated independently but together compose a single object.
> 
> While composition offers model extensibility, it does not imply a hierarchy between the models. To support polymorphism, Swagger adds the support of the discriminator field. When used, the discriminator will be the name of the property used to decide which schema definition is used to validate the structure of the model. As such, the discriminator field MUST be a required field. The value of the chosen property has to be the friendly name given to the model under the definitions property. As such, inline schema definitions, which do not have a given id, cannot be used in polymorphism.

This means that the code generated by C# contains:

```
[JsonSubtypes.KnownSubType(typeof(TestNsTestClass2), "TestNs.TestClass2")]
```

Which should cause `$Type = "TestNs.TestClass2"` to construct an instance of `TestNsTestClass2`.  I don't know if this is fully supported in all generators.
