### ISSUE TITLE
Several clients break due to model 'break'

### ISSUE THREAD

**Issue by karussell** [swagger-api/swagger-codegen#3846]
##### Description

For two clients Sinatra&Dart I get a problem that model 'break' is not allowed, but e.g. Java, .Net or Python just renames break to ModelBreak. E.g.

```txt
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Break'.Please make sure that your schema is correct!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:297)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.RuntimeException: Break (reserved word) cannot be used as a model name
        at io.swagger.codegen.languages.SinatraServerCodegen.toModelName(SinatraServerCodegen.java:185)

Exception in thread "main" java.lang.RuntimeException: Could not process model 'Vehicle'.Please make sure that your schema is correct!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:297)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.RuntimeException: Break (reserved word) cannot be used as a model name
        at io.swagger.codegen.languages.DartClientCodegen.toModelName(DartClientCodegen.java:212)
        at io.swagger.codegen.languages.DartClientCodegen.getSwaggerType(DartClientCodegen.java:267)
```

##### Swagger-codegen version

swagger-codegen-cli-2.2.1.jar

##### Swagger declaration file content or url

https://graphhopper.com/api/1/vrp/swagger.json

##### Command line used for generation

https://github.com/graphhopper/directions-api-clients-route-optimization/blob/master/create.sh

##### Steps to reproduce

```bash
git clone https://github.com/graphhopper/directions-api-clients-route-optimization
cd directions-api-clients-route-optimization
./create.sh
```

**Comment by wing328** [comment]
@karussell thanks for reporting the issue.

Would you have time to apply the same fix to Sinatra and Dart generator: https://github.com/swagger-api/swagger-codegen/blob/569997b0733acb42903531dbab696f28efb746e1/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/PythonClientCodegen.java#L393-L397

**Comment by karussell** [comment]
Sorry, lack of time and skills in this language area :/

**Comment by wing328** [comment]
Fixed via #4023. Please pull the latest master to give it a try.

**Comment by karussell** [comment]
Thanks a lot!

For dart it works but for sinatra I get an exception although it says 'renamed to ModelBreak':

```bash
java -jar swagger-codegen-cli-master.jar generate -i https://graphhopper.com/api/1/vrp/swagger.json -l sinatra -o ./sinatra
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://graphhopper.com/api/1/vrp/swagger.json
[main] WARN io.swagger.codegen.languages.SinatraServerCodegen - Break (reserved word) cannot be used as model filename. Renamed to ModelBreak
Exception in thread "main" java.lang.RuntimeException: Could not process model 'Break'.Please make sure that your schema is correct!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:298)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
Caused by: java.lang.RuntimeException: Break (reserved word) cannot be used as a model name
        at io.swagger.codegen.languages.SinatraServerCodegen.toModelFilename(SinatraServerCodegen.java:198)
        at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1214)
        at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:887)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:291)
        ... 2 more
```

**Comment by wing328** [comment]
@karussell sorry I forgot to commit the remaining change. #4024 should fix it (will merge it after passing the CI tests)

**Comment by wing328** [comment]
#4024 merged into master. Please kindly give it another try.

Sorry for the inconvenience caused.

**Comment by karussell** [comment]
I highly appreciate your work&time! (btw: no need to sorry :)!)
This works now and have added two new languages for our API clients - nice!
