### ISSUE TITLE
Error while trying to generate node.js server code from 2.0 swagger spec

### ISSUE THREAD

**Issue by amarzavery** [swagger-api/swagger-codegen#387]
Hi I am trying to generate server code in node.js from a 2.0 swagger spec.
I followed the documentation over here: https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples/server-generator/node 

After cloning the git repo and installing mvn, when I execute mvn package from the root folder of the respository it throws an error that it could not find pom.xml. This is correct because the file does not exist over there. Did I misunderstand the documentation or is this an actual issue?

```
$ mvn package -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.072 s
[INFO] Finished at: 2015-01-21T18:55:19-08:00
[INFO] Final Memory: 13M/489M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (d:\sdk\swagger-codegen). Please verify you invoked
 Maven from the correct directory. -> [Help 1]
org.apache.maven.lifecycle.MissingProjectException: The goal you specified requires a project to execute but there is no POM in this directory (d:\sdk
\swagger-codegen). Please verify you invoked Maven from the correct directory.
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:80)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
amzavery@ZAVERA /d/sdk/swagger-codegen (trial)
```

**Comment by anjsimmo** [comment]
Swagger 2.0 spec is only supported on the develop_2.0 branch. The develop_2.0 branch does include a pom.xml in the root of the repository. Try running `git checkout develop_2.0` and ensure that it looks like https://github.com/swagger-api/swagger-codegen/tree/develop_2.0

**Comment by amarzavery** [comment]
@anjsimmo - You are right. I forgot to checkout the develop_2.0 branch. 
However, I am failing in the next step after that.
The doc says:
```
./bin/runscala.sh samples/server-generator/node/NodeServerFromSpec.scala http://petstore.swagger.wordnik.com/api/api-docs special-key
```
However, there is no file named runscala.sh in the bin folder. There is a script named runscala.sh in the async-2.0 branch but not in the develop_2.0 branch.

Can you please confirm what should be the right script to use?

**Comment by anjsimmo** [comment]
@amarzavery It seems that the instructions you are using need to be updated. Try the "To build a server stub" section of https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/README.md

**Comment by fehguy** [comment]
Here's how you build the nodejs server stub:

```
java -cp target/swagger-codegen-2.1.0-SNAPSHOT.jar:target/lib/* \
  com.wordnik.swagger.codegen.Codegen \
  -i ./src/test/resources/petstore.json \
  -l nodejs \
  -o ./outputDir
```

**Comment by fehguy** [comment]
This is affecting the output though:

https://github.com/swagger-api/swagger-codegen/issues/389

**Comment by amarzavery** [comment]
Getting the following error:
```
$ java -cp target/swagger-codegen-2.1.0-SNAPSHOT.jar:target/lib/*   com.wordnik.swagger.codegen.Codegen   -i ./src/test/resources/petstore.json   -l
nodejs   -o ./outputDir
Error: Could not find or load main class com.wordnik.swagger.codegen.Codegen
```

I did build the packages again before executing the above command and that was successful

**Comment by fehguy** [comment]
be sure of the following:

1) You're using the develop_2.0 branch
2) You've run `mvn package` before executing the command

You should see the file `./target/swagger-codegen-2.1.0-SNAPSHOT.jar`

**Comment by amarzavery** [comment]
Yes. I am running from the develop_2.0 branch.
As I mentioned I did run mvn package before running the java command.
I do see the jar file "./target/swagger-codegen-2.1.0-SNAPSHOT.jar".

However, I still get the error

**Comment by fehguy** [comment]
Assuming you're on a unix machine, please try this (no newlines):

```
$ java -cp target/swagger-codegen-2.1.0-SNAPSHOT.jar:target/lib/* com.wordnik.swagger.codegen.Codegen -i ./src/test/resources/petstore.json -l nodejs -o ./outputDir
```

**Comment by amarzavery** [comment]
I was running from git bash on windows. I tried the same from the windows cmd prompt. But still have the same issue

**Comment by amarzavery** [comment]
I do see the file Codegen.java over here
D:\sdk\swagger-codegen\src\main\java\com\wordnik\swagger\codegen

**Comment by fehguy** [comment]
ok for windows, try this:

```
java -cp target\swagger-codegen-2.1.0-SNAPSHOT.jar;target/lib/* com.wordnik.swagger.codegen.Codegen -i src\test\resources\petstore.json -l nodejs -o outputDir

**Comment by amarzavery** [comment]
Oh, the windows requires a semiclon instead of a colon. Now I see the following error:

```
D:\sdk\swagger-codegen>java -cp target\swagger-codegen-2.1.0-SNAPSHOT.jar;target/lib/* com.wordnik.swagger.codegen.Codegen -i src\test\resources\petstore.json -l nodejs -o outputDir
reading from src\test\resources\petstore.json
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.lang.String.charAt(Unknown Source)
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at com.wordnik.swagger.codegen.languages.NodeJSServerCodegen.apiFileFolder(NodeJSServerCodegen.java:61)
        at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:116)
        at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:84)

D:\sdk\swagger-codegen>
```

**Comment by amarzavery** [comment]
I did git pull upstream develop_2.0 and found that there were some changes in DefaultGenerator.java..

```
amzavery@ZAVERA /d/sdk/swagger-codegen (trial_2.0)
$ git pull upstream develop_2.0
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 21 (delta 3), reused 17 (delta 2)
Unpacking objects: 100% (21/21), done.
From github.com:swagger-api/swagger-codegen
 * branch            develop_2.0 -> FETCH_HEAD
Updating a15eb6f..53e8683
Fast-forward
 .../java/com/wordnik/swagger/codegen/DefaultGenerator.java | 14 +++++++++-----
 1 file changed, 9 insertions(+), 5 deletions(-)
```

Just letting you know, incase that helps :).

Thanks for helping me out. Appreciate your efforts :+1:

**Comment by fehguy** [comment]
ok great

**Comment by amarzavery** [comment]
Found the problem and the solution

"Back slash \ must be escaped twice: once of regular expressions engine and once for java itself."

After modifying the code for these two methods, I was able to successfully generate the server code.

```
 @Override
  public String apiFileFolder() {
    return outputFolder + File.separator + apiPackage().replaceAll("\\\\.", File.separator);
  }

  public String modelFileFolder() {
    return outputFolder + File.separator + modelPackage().replaceAll("\\\\.", File.separator);
  }
```

**Comment by fehguy** [comment]
The problem with this change is that it causes the build to fail on Macs.  I don't see how it should work even on windows.  If you have more input, please post back.
