### ISSUE TITLE
sbt assembly fail with nullpointerexception in widows

### ISSUE THREAD

**Issue by balamanian** [swagger-api/swagger-codegen#390]
i tried to run the sample swagger-codegen project. when i run sbt assembly. it will give the below stack trace. Please help me to solve this.

[info] Loading project definition from C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\project
[info] Updating {file:/C:/Users/bponmari/Downloads/swagger/swagger-codegen-master/swagger-codegen-master/project/}swagger-codegen-master-build...
[info] Resolving com.typesafe.sbt#sbt-pgp;0.8.2 ...
  [info] Resolving com.jsuereth#gpg-library_2.10;0.8.2 ...
  [info] Resolving org.scala-lang#scala-library;2.10.2 ...
  [info] Resolving org.bouncycastle#bcpg-jdk15on;1.49 ...
  [info] Resolving org.bouncycastle#bcprov-jdk15on;1.49 ...
  [info] Resolving net.databinder#dispatch-http_2.10;0.8.10 ...
  [info] Resolving net.databinder#dispatch-core_2.10;0.8.10 ...
  [info] Resolving org.apache.httpcomponents#httpclient;4.1.3 ...
  [info] Resolving org.apache.httpcomponents#httpcore;4.1.4 ...
  [info] Resolving commons-logging#commons-logging;1.1.1 ...
  [info] Resolving commons-codec#commons-codec;1.4 ...
  [info] Resolving net.databinder#dispatch-futures_2.10;0.8.10 ...
  [info] Resolving org.scala-lang#scala-actors;2.10.2 ...
  [info] Resolving com.eed3si9n#sbt-assembly;0.9.1 ...
  [info] Resolving org.scala-lang#scala-library;2.10.4 ...
  [info] Resolving org.scala-sbt#sbt;0.13.5 ...
  [info] Resolving org.scala-sbt#main;0.13.5 ...
  [info] Resolving org.scala-sbt#actions;0.13.5 ...
  [info] Resolving org.scala-sbt#classpath;0.13.5 ...
  [info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
  [info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
  [info] Resolving org.scala-sbt#launcher-interface;0.13.5 ...
  [info] Resolving org.scala-sbt#interface;0.13.5 ...
  [info] Resolving org.scala-sbt#io;0.13.5 ...
  [info] Resolving org.scala-sbt#control;0.13.5 ...
  [info] Resolving org.scala-sbt#completion;0.13.5 ...
  [info] Resolving org.scala-sbt#collections;0.13.5 ...
  [info] Resolving jline#jline;2.11 ...
  [info] Resolving org.scala-sbt#api;0.13.5 ...
  [info] Resolving org.scala-sbt#compiler-integration;0.13.5 ...
  [info] Resolving org.scala-sbt#incremental-compiler;0.13.5 ...
  [info] Resolving org.scala-sbt#logging;0.13.5 ...
  [info] Resolving org.scala-sbt#process;0.13.5 ...
  [info] Resolving org.scala-sbt#relation;0.13.5 ...
  [info] Resolving org.scala-sbt#compile;0.13.5 ...
  [info] Resolving org.scala-sbt#persist;0.13.5 ...
  [info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
  [info] Resolving org.scala-sbt#classfile;0.13.5 ...
  [info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.5 ...
  [info] Resolving org.scala-sbt#ivy;0.13.5 ...
  [info] Resolving org.scala-sbt#cross;0.13.5 ...
  [info] Resolving org.apache.ivy#ivy;2.3.0 ...
  [info] Resolving com.jcraft#jsch;0.1.46 ...
  [info] Resolving org.scala-sbt#run;0.13.5 ...
  [info] Resolving org.scala-sbt#task-system;0.13.5 ...
  [info] Resolving org.scala-sbt#tasks;0.13.5 ...
  [info] Resolving org.scala-sbt#tracking;0.13.5 ...
  [info] Resolving org.scala-sbt#cache;0.13.5 ...
  [info] Resolving org.scala-sbt#testing;0.13.5 ...
  [info] Resolving org.scala-sbt#test-agent;0.13.5 ...
  [info] Resolving org.scala-sbt#test-interface;1.0 ...
  [info] Resolving org.scala-sbt#main-settings;0.13.5 ...
  [info] Resolving org.scala-sbt#apply-macro;0.13.5 ...
  [info] Resolving org.scala-sbt#command;0.13.5 ...
  [info] Resolving org.scala-sbt#logic;0.13.5 ...
  [info] Resolving org.scala-sbt#compiler-interface;0.13.5 ...
  [info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.5 ...
  [info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.5 ...
  [info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.5 ...
  [info] Resolving org.scala-lang#jline;2.10.4 ...
  [info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to swagger-codegen (in build file:/C:/Users/bponmari/Downloads/swagger/swagger-codegen-master/swagger-codegen-master/)
[warn] Credentials file C:\Users\bponmari\.ivy2\.credentials does not exist
[info] Compiling 32 Scala sources to C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\target\scala-2.10\classes...
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\model\LegacySerializers.scala:60: non-variable type argument String in type pattern Map[String,com.wordnik.swagger.codegen.mo
[warn]           case e: Map[String, Model] if (e.size > 0) => Extraction.decompose(e)
[warn]                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\util\RemoteUrl.scala:14: match may not be exhaustive.
[warn] It would fail on the following input: Some((x: com.wordnik.swagger.codegen.model.AuthorizationValue forSome x not in com.wordnik.swagger.codegen.model.ApiKeyValue))
[warn]                  val conn: URLConnection = authorization match {
[warn]                                            ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicAndroidJavaClient.scala:22: method generateClient in class BasicGenerator is deprecated: please use the generate functio
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicCSharpGenerator.scala:22: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicGroovyGenerator.scala:20: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicJavaGenerator.scala:22: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicObjcGenerator.scala:22: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicPHPGenerator.scala:24: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicPython3Generator.scala:22: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicPythonGenerator.scala:24: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicRubyGenerator.scala:24: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\BasicScalaGenerator.scala:22: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] C:\Users\bponmari\Downloads\swagger\swagger-codegen-master\swagger-codegen-master\src\main\scala\com\wordnik\swagger\codegen\SwaggerDocGenerator.scala:25: method generateClient in class BasicGenerator is deprecated: please use the generate function
[warn]   def main(args: Array[String]) = generateClient(args)
[warn]                                   ^
[warn] there were 104 inliner warning(s); re-run with -Yinline-warnings for details
[warn] 14 warnings found
java.lang.NullPointerException
        at javax.xml.bind.DatatypeConverter.printBase64Binary(DatatypeConverter.java:547)
        at sbt.inc.TextAnalysisFormat$ObjectStringifier$$anonfun$objToString$2.apply(TextAnalysisFormat.scala:390)
        at sbt.inc.TextAnalysisFormat$ObjectStringifier$$anonfun$objToString$2.apply(TextAnalysisFormat.scala:390)
        at sbt.inc.FormatTimer$.aggregate(TextAnalysisFormat.scala:19)
        at sbt.inc.TextAnalysisFormat$ObjectStringifier$.objToString(TextAnalysisFormat.scala:390)
        at sbt.inc.TextAnalysisFormat$APIsF$$anonfun$14.apply(TextAnalysisFormat.scala:273)
        at sbt.inc.TextAnalysisFormat$APIsF$$anonfun$14.apply(TextAnalysisFormat.scala:273)
        at sbt.inc.TextAnalysisFormat$$anonfun$sbt$inc$TextAnalysisFormat$$writeMap$1.apply(TextAnalysisFormat.scala:444)
        at sbt.inc.TextAnalysisFormat$$anonfun$sbt$inc$TextAnalysisFormat$$writeMap$1.apply(TextAnalysisFormat.scala:440)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at sbt.inc.TextAnalysisFormat$.sbt$inc$TextAnalysisFormat$$writeMap(TextAnalysisFormat.scala:440)
        at sbt.inc.TextAnalysisFormat$APIsF$.write(TextAnalysisFormat.scala:276)
        at sbt.inc.TextAnalysisFormat$$anonfun$write$4.apply$mcV$sp(TextAnalysisFormat.scala:67)
        at sbt.inc.TextAnalysisFormat$$anonfun$write$4.apply(TextAnalysisFormat.scala:67)
        at sbt.inc.TextAnalysisFormat$$anonfun$write$4.apply(TextAnalysisFormat.scala:67)
        at sbt.inc.FormatTimer$.aggregate(TextAnalysisFormat.scala:19)
        at sbt.inc.FormatTimer$.time(TextAnalysisFormat.scala:26)
        at sbt.inc.TextAnalysisFormat$.write(TextAnalysisFormat.scala:67)
        at sbt.inc.FileBasedStore$$anon$1$$anonfun$set$1.apply(FileBasedStore.scala:13)
        at sbt.inc.FileBasedStore$$anon$1$$anonfun$set$1.apply(FileBasedStore.scala:13)
        at sbt.Using.apply(Using.scala:25)
        at sbt.inc.FileBasedStore$$anon$1.set(FileBasedStore.scala:13)
        at sbt.inc.AnalysisStore$$anon$1.set(AnalysisStore.scala:19)
        at sbt.inc.AnalysisStore$$anon$2.set(AnalysisStore.scala:30)
        at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:73)
        at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:46)
        at sbt.Compiler$.apply(Compiler.scala:75)
        at sbt.Compiler$.apply(Compiler.scala:66)
        at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:770)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762)
        at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
        at sbt.std.Transform$$anon$4.work(System.scala:64)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
        at sbt.Execute.work(Execute.scala:244)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:compile) java.lang.NullPointerException
[error] Total time: 38 s, completed Jan 23, 2015 5:18:19 PM

**Comment by webron** [comment]
Can you try using the develop_2.0 branch instead? It's java/maven based and should run with no issues.

**Comment by balamanian** [comment]
i am newbie. please guide me how to use develop_2.0 branch.

**Comment by webron** [comment]
newbie to git?

`git checkout developer_2.0` from the root of the cloned repository.

You can check the README here - https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/README.md.

**Comment by balamanian** [comment]
thanks for help to solve the issue.
