### ISSUE TITLE
Can not valid swag 2.0 spec

### ISSUE THREAD

**Issue by netroby** [swagger-api/swagger-codegen#408]
```
[netroby@localhost swagger-codegen]$ ./bin/validate.sh https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-expanded.json
java.lang.Exception: unable to read from https://raw.githubusercontent.com/swagger-api/swagger-spec/master/examples/v2.0/json/petstore-expanded.json
        at com.wordnik.swagger.codegen.spec.Validator$.main(Validator.scala:54)
        at com.wordnik.swagger.codegen.spec.Validator.main(Validator.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
        at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
        at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: com.wordnik.swagger.util.ValidationException: '' is not a valid Swagger version
        at com.wordnik.swagger.codegen.model.SwaggerSerializers$.formats(SwaggerModelSerializer.scala:98)
        at com.wordnik.swagger.codegen.util.ResourceExtractor$.fetchListing(ResourceExtractor.scala:37)
        at com.wordnik.swagger.codegen.spec.Validator$.main(Validator.scala:55)
        ... 19 more
```

**Comment by fehguy** [comment]
For swagger-2.0 spec files, you need to use the develop_2.0 branch of codegen.

**Comment by netroby** [comment]
Shall we add the tips for user in the readme.md of the default branch?

**Comment by fehguy** [comment]
I was hoping this covered it:

https://github.com/swagger-api/swagger-codegen#compatibility

But if you have suggestions on how to make things more clear, please pass it on.

**Comment by netroby** [comment]
That's ok, but i am not sure if the V2.0.18 the same with v2.0.17?

**Comment by webron** [comment]
@netroby - it is. You can assume 2.0.X applies to 1.1 and 1.2, and 2.1.X applies to 2.0 and below.
