### ISSUE TITLE
AbstractSerializableParameter - Illegal enum value null for parameter type number

### ISSUE THREAD

**Issue by wing328** [swagger-api/swagger-codegen#4194]
##### Description

```
[main] WARN io.swagger.models.parameters.AbstractSerializableParameter - Illegal enum value null for parameter type number
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:454)
	at java.lang.Integer.valueOf(Integer.java:582)
	at io.swagger.models.parameters.AbstractSerializableParameter.getEnumValue(AbstractSerializableParameter.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
	at io.swagger.util.Json.pretty(Json.java:23)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2192)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2025)
	at io.swagger.codegen.languages.RubyClientCodegen.fromOperation(RubyClientCodegen.java:265)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:761)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:705)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:377)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
[main] WARN io.swagger.models.parameters.AbstractSerializableParameter - Illegal enum value null for parameter type number
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:454)
	at java.lang.Integer.valueOf(Integer.java:582)
	at io.swagger.models.parameters.AbstractSerializableParameter.getEnumValue(AbstractSerializableParameter.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
	at io.swagger.util.Json.pretty(Json.java:23)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2192)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2025)
	at io.swagger.codegen.languages.RubyClientCodegen.fromOperation(RubyClientCodegen.java:265)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:761)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:705)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:377)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```
Seems like it's due to the upgrade to the latest parser.

##### Swagger-codegen version

Latest master

##### Steps to reproduce

mvn clean && ./bin/ruby-petstore.sh

##### Related issues

None

##### Suggest a Fix

We will need to add better exception handling in `fromParameter` (DefaultCodegen)

**Comment by hantuzun** [comment]
I've experienced the same issue as well.

**Comment by wing328** [comment]
@hantuzun as a workaround, please use the latest stable version 2.2.1 for the time being: https://github.com/swagger-api/swagger-codegen/releases

**Comment by wing328** [comment]
@hantuzun I was able to fix the issue by fixing the swagger spec.

Can you share the spec so that we can take a deeper look at the issue for your case?

**Comment by hantuzun** [comment]
Hi @wing328. Thanks for reporting the issue. Our spec is available at: https://github.com/suggestgrid/suggestgrid-rest/blob/master/spec/swagger.yaml

**Comment by wing328** [comment]
@hantuzun as discussed over email, you could no longer repeat the issue, which may have been changed/updated over the week.

If you still experience this exception, we'll reopen this issue for tracking and look into the issue further.
