### ISSUE TITLE
[Python] No way to handle exceptions in asyncronous code (with callback)

### ISSUE THREAD

**Issue by masterandrey** [swagger-api/swagger-codegen#4235]
##### Description

Produced by codegen Python code does not support handling of exceptions in anync mode (with callback).
If swagger client code raises exeption, callback will never be called.

##### Swagger-codegen version

5

##### Command line used for generation

-l python

##### Suggest a Fix

Catch all exceptions in generated swagger client and return special type of result in case of exceptions.

**Comment by wing328** [comment]
@masterandrey can you elaborate a bit on "return special type of result"? In your case, what exception did you get?

**Comment by masterandrey** [comment]
with callback I have this unhandled exception:

``
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/sorokin/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/sorokin/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/api_client.py", line 157, in __call_api
    post_params=post_params, body=body)
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/api_client.py", line 370, in request
    body=body)
  File "/home/sorokin/cottrep/api/stand/rest.py", line 242, in POST
    body=body)
  File "/home/sorokin/cottrep/api/stand/rest.py", line 210, in request
    raise ApiException(http_resp=r)
rest.ApiException: (404)
Reason: Handler not registered for  corresponding URI: /api/agentticketsapi/request_pay
HTTP response headers: HTTPHeaderDict({'Content-Type': 'text/html; charset=iso-8859-1', 'Connection': 'keep-alive', 'Content-Length': '0', 'Date': 'Wed, 23 Nov 2016 07:51:48 GMT', 'Server': 'nginx/1.11.1'})
``

without callback I can handle the exception in main thread:
``
Traceback (most recent call last):
  File "/home/sorokin/cottrep/api/stand/call_api.py", line 107, in call_api
    response = api_call(**args)
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/apis/default_api.py", line 392, in controllers_agent_tickets_request_pay
    (data) = self.controllers_agent_tickets_request_pay_with_http_info(card_num, **kwargs)
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/apis/default_api.py", line 470, in controllers_agent_tickets_request_pay_with_http_info
    _return_http_data_only=params.get('_return_http_data_only'))
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/api_client.py", line 334, in call_api
    response_type, auth_settings, callback, _return_http_data_only)
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/api_client.py", line 157, in __call_api
    post_params=post_params, body=body)
  File "/home/sorokin/cottrep/api/stand/swagger/agentticketsapi_client/api_client.py", line 370, in request
    body=body)
  File "/home/sorokin/cottrep/api/stand/rest.py", line 242, in POST
    body=body)
  File "/home/sorokin/cottrep/api/stand/rest.py", line 210, in request
    raise ApiException(http_resp=r)
rest.ApiException: (404)
Reason: Handler not registered for  corresponding URI: /api/agentticketsapi/request_pay
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 23 Nov 2016 07:53:49 GMT', 'Server': 'nginx/1.11.1', 'Connection': 'keep-alive', 'Content-Length': '0', 'Content-Type': 'text/html; charset=iso-8859-1'})
``

**Comment by wing328** [comment]
@masterandrey do you know how other API clients (e.g. Python Facebook SDK, Python Twitter SDK, etc) handle exceptions in async call?

Ref: 
- https://github.com/bear/python-twitter
- https://github.com/mobolic/facebook-sdk

**Comment by masterandrey** [comment]
I am not sure they use multi-threading.
But I do not know for sure.

BTW For me async-await works pretty good.

Current implementation of swagger python client uses multi-threading if callback parameter is provided.
IMHO that's strange - better just await urllib call to have async version of the swagger client.

**Comment by baartosz** [comment]
Only fix without BC breaks I can think of is possibility to pass another callback which will be called if ApiException is thrown.

**Comment by wing328** [comment]
@baartosz I think it's ok to introduce breaking changes to fix this issue if needed (the non-backward compatible fix should target 2.3.0 branch)

**Comment by baartosz** [comment]
I just looked at `multithreading` lib and its ThreadPools. Looks like it throws exceptions from sub-thread only when asked to get result from thread and its easier to get its response - no need for callbacks. Available in python 2.7 (as opposed to asyncio). 

So catching exceptions would roughly look like this:
```
thread = pet_api.get_pet(async=True)

try:
    pet = thread.get()
except Exception as e:
    raise e
```

additionally it could be wrapped in some abstraction (like returning `lazy_response` hiding thread object) so implementation can be changed in the future without BC breaks.

Thoughts?

**Comment by baartosz** [comment]
@masterandrey @wing328 

I just looked at `multithreading` lib and its ThreadPools. Looks like it throws exceptions from sub-thread only when asked to get result from thread and its easier to get its response - no need for callbacks. Available in python 2.7 (as opposed to asyncio). 

So catching exceptions would roughly look like this:
```
thread = pet_api.get_pet(async=True)

try:
    pet = thread.get()
except Exception as e:
    raise e
```

additionally it could be wrapped in some abstraction (like returning `lazy_response` hiding thread object) so implementation can be changed in the future without BC breaks.

Thoughts?

**Comment by wing328** [comment]
@masterandrey can you please test the fix by @baartosz by running the below?
```
git checkout -b baartosz-python_async_error_handling 2.3.0
git pull https://github.com/baartosz/swagger-codegen.git python_async_error_handling
mvn clean package
```
Then use the JAR (built locally) to generate Python API client

**Comment by strigazi** [comment]
FYI, after PR #5308 a compatibility issue with evenlet started to occur.

I came across this [1] problem when using the kubernetes python client 4.0.0 with eventlet. So, clients generated with swagger-api:2.3.0 are incompatible with eventlet.

I'm not sure if there is any action to do here or if it must be fixed in eventlet.

[1] https://github.com/eventlet/eventlet/issues/147

**Comment by hoangphuocbk** [comment]
@strigazi Hi, do you have any solution to fix that error? I also meet it, but I don't know how to fix it.

**Comment by strigazi** [comment]
@hoangphuocbk I don't think there is a solution to make eventlet work with multiprocessing. I think the solution will only come from the eventlet where it is seen as a bug. The only option we have now is to stop depend on eventlet or multiprocessing :-)
