### ISSUE TITLE
Missing android/enum_outer_doc.mustache

### ISSUE THREAD

**Issue by imgx64** [swagger-api/swagger-codegen#4350]
##### Description
When I try to generate an Android client with Volley, and the swagger declaration contains `enum`, the following exception is thrown:
```
[main] INFO io.swagger.parser.Swagger20Parser - reading from api-docs.yaml
[main] INFO io.swagger.codegen.languages.AndroidClientCodegen - CodegenConstants.SERIALIZABLE_MODEL = false
[main] INFO io.swagger.codegen.AbstractGenerator - writing file [redacted]/src/main/java/io\swagger\client\model\MyEnum.java
[main] ERROR io.swagger.codegen.AbstractGenerator - android/enum_outer_doc.mustache (The system cannot find the path specified)
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'MyEnum'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:326)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:646)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
Caused by: java.lang.RuntimeException: can't load template android\enum_outer_doc.mustache
        at io.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:63)
        at io.swagger.codegen.DefaultGenerator$5.getTemplate(DefaultGenerator.java:668)
        at com.samskivert.mustache.Mustache$IncludedTemplateSegment.execute(Mustache.java:744)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:852)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:863)
        at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
        at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:848)
        at com.samskivert.mustache.Template.executeSegs(Template.java:114)
        at com.samskivert.mustache.Template.execute(Template.java:91)
        at com.samskivert.mustache.Template.execute(Template.java:82)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:674)
        at io.swagger.codegen.DefaultGenerator.generateModelDocumentation(DefaultGenerator.java:196)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:323)
        ... 3 more
```

##### Swagger-codegen version
2.2.2-SNAPSHOT, built from git.

##### Swagger declaration file content or url
```yaml
swagger: '2.0'
info:
  title: api
  version: '1.0.0'
paths:
  /endpoint:
    get:
      responses:
        200:
          description: Operation successful
          schema:
            $ref: '#/definitions/MyResponse'
definitions:
  MyResponse:
    type: object
    properties:
      value:
        $ref: '#/definitions/MyEnum'
  MyEnum:
    type: string
    enum:
      - SomeValue
      - OtherValue
```

##### Command line used for generation
```
java -jar "${M2_REPO}/repository/io/swagger/swagger-codegen-cli/2.2.2-SNAPSHOT/swagger-codegen-cli-2.2.2-SNAPSHOT.jar" generate -i api-docs.yaml -l android -o output-api
```

##### Steps to reproduce
Use the above swagger declaration with the above command line.

##### Related issues
Searching for `enum_outer_doc.mustache` produced no results.

##### Suggest a Fix
Copy `https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/enum_outer_doc.mustache` ? I don't know if there are any other missing files apart from that.

**Comment by wing328** [comment]
@imgx64 as a workaround, please use the Java API client (which is compatible with Android) instead while we're looking into the issue.

https://github.com/swagger-api/swagger-codegen/wiki/FAQ#android

**Comment by imgx64** [comment]
Unfortunately, `-l java` doesn't support Volley, which is why I'm using `-l android`.

**Comment by wing328** [comment]
@imgx64 if using Android volley is a must, then you will have to wait for the fix. Otherwise, you can use the Java API client, which supports Retrofit 1.x, Retrofit 2.x, okhttp-gson and more.

**Comment by wing328** [comment]
@imgx64 fixed via #4381. Please pull the latest master to give it a try.

**Comment by imgx64** [comment]
@wing328 Seems to work now. The Enums are empty, but I guess that's a separate bug.

**Comment by wing328** [comment]
@imgx64 right. As I said, the Java (okhttp-gson) client has better support for doc and enum and would suggest you to use that one instead.

The Android (volley) API client still needs more work to make it comparable with the Java (okhttp-gson) API client.
