### ISSUE TITLE
Tests fail with swagger-parser set to 1.0.25-SNAPSHOT

### ISSUE THREAD

**Issue by tomekc** [swagger-api/swagger-codegen#4462]
##### Description

Test fail with current master codebase.

```
Failed tests:
  SwaggerMigratorTest.swaggerMigratorTest:14 » ClassCast java.math.BigDecimal ca...
  JavaScriptModelEnumTest.enumArrayMdoelTest:99 » NoSuchMethod io.swagger.models...
  JavaScriptModelEnumTest.enumMdoelValueTest:130 » NoSuchMethod io.swagger.model...
  ObjcModelTest.isArrayModelModelTest:297 » NoSuchMethod io.swagger.models.param...
  ObjcModelTest.mixedPropertiesDataModelTest:286 » NoSuchMethod io.swagger.model...
  ObjcModelTest.udidAndPasswordDataModelTest:272 » NoSuchMethod io.swagger.model...
  PhpModelTest.enumArrayMdoelTest:282 » NoSuchMethod io.swagger.models.parameter...
  PhpModelTest.enumMdoelValueTest:313 » NoSuchMethod io.swagger.models.parameter...
  TypeScriptFetchModelTest.enumArrayMdoelTest:192 » NoSuchMethod io.swagger.mode...
  TypeScriptFetchModelTest.enumMdoelValueTest:226 » NoSuchMethod io.swagger.mode...
```

They all seem to fail for the same reason:

```
enumArrayMdoelTest(io.swagger.codegen.javascript.JavaScriptModelEnumTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V
	at io.swagger.codegen.javascript.JavaScriptModelEnumTest.enumArrayMdoelTest(JavaScriptModelEnumTest.java:99)

enumMdoelValueTest(io.swagger.codegen.javascript.JavaScriptModelEnumTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V
	at io.swagger.codegen.javascript.JavaScriptModelEnumTest.enumMdoelValueTest(JavaScriptModelEnumTest.java:130)

isArrayModelModelTest(io.swagger.codegen.objc.ObjcModelTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.NoSuchMethodError: io.swagger.models.parameters.AbstractSerializableParameter.setMaximum(Ljava/math/BigDecimal;)V
	at io.swagger.codegen.objc.ObjcModelTest.isArrayModelModelTest(ObjcModelTest.java:297)
```

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Steps to reproduce

mvn clean package

##### Suggest a Fix

Revert swagger-parser to 1.0.24.

As a side note, if I may suggest: including SNAPSHOT dependencies in production code is very unsafe practice, as it may yield to unstable builds (SNAPSHOT dependency may become different build at any time).

**Comment by tomekc** [comment]
I saw that update to stable 1.0.25 did help. I consider it closed.
