### ISSUE TITLE
[JAVA] Compilation error, missing imports. DateTime

### ISSUE THREAD

**Issue by aorekhov** [swagger-api/swagger-codegen#4463]
##### Description

Swagger don't include import declaration in generated client.

I told about this:
import org.joda.time.DateTime;

This line is missing in generated client. And I face with compilation error.

##### Swagger-codegen version

2.2.1

##### Swagger declaration file content or url

https://preprod.selfishbeta.com/api/core-api-docs/swagger.json

##### Command line used for generation

java -jar swagger-codegen-cli-2.2.1.jar generate -l java -i api/core.json -o api/

**Comment by wing328** [comment]
@aorekhov I tried to reproduce the issue using the latest master but got the following exception about invalid spec: 
```
swagger-codegen|master⚡ ⇒   java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i https://preprod.selfishbeta.com/api/core-api-docs/swagger.json \
  -l java \
  -o /var/tmp/java/test/
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://preprod.selfishbeta.com/api/core-api-docs/swagger.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://preprod.selfishbeta.com/api/core-api-docs/swagger.json
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: ��k��6����8Isw�ܧM�-��6Av7��(�E�jd���������z��(�~%#qF��p8r���d>����������Q�����ȧl��4�#��������iH�O�,ٻ�Mx�x1Z�,�?W]%����p�ń���4^r�a�=I����9��m3��pDQ�`:��(-?�'a����S�tIV�Gy��a����D����O�,���^/i���!�%��JC��ɺ�` o��ňMtIa��E��؈?[q*0��x't,F>�V|dt��A��]���8$���i
$�$�y�\�헣;�@F�ԛŉ7��iB�SD�i�q8^�D������%؏�-t�w��4��8�jS6���)�c�Q�i�.`$B�@8�������L��rQ�&@�$��%���QA��O�����X6�}b�,���=��.$i%Wu��DS/c4���Vzq�oD�q���T
�e�*���d]�ь�� RP��x6c�/0R�6XR[�Xt���Tˑ���5�3��/c�΂(6~����~~��Bv��v�ο��9 ^�3o*Z��d���$��`J�%i�_1�%�D$M�t�jD�0]�qM��*�I�:N�����Z>����tB��w�E���^�u�ρ�A��M�b��är���-L�N�v�CP�,�����0῅�q�1_P��yE�����'���z�Y�/0��{�?vXj,��Zd��1�;X��s�ك�)���x�I�MK[������N��c���z�_�[�Y�K:
��4�nc��ʖ���d��xG��6�Iݒfh����\0vn&�]vR�!v^O�L�x��.F�5]�I�%;�{Vt�x|����
p�u��H�h�����ƛ�=ީ lW���B�Z�0]�~�{��.1�s�=�x6���57��͍��c��5ϖ�1 ���w��@�T�,�D������!���_Or��c�m|-��L�2���D��@MLC�&���!{� eJ���3����T�2N�b�b^HW���ku��7��|e�CF����݄�zؒ=���c�ڠ�L�����t�����6���\k[�T��BB8�/G3���n�z�k�/`^�fG3qp���G�8���ZW`s{e��i�
����h����r�C$RA��"�ӧ���s��Ή1��$������RQ�@�=��V�\��U���ůq���a���޼N�2eU�_��z�QU���l�G!���nr�{�K��(钸��v<}��;���I�[I��ܩ0F�p��&^D?{���"�����i|O7Q_��?�0���HMm��I��Db����e&]2{W�^T���0$���t�\�~��Դ[W�s|g�6�1��$�)�l�"�aI��n��_�N����E�|�ਇ�T�U�w�i��H/]pI�%4���+U�ߔ�5H�L��D��v����H@���4lFɛ(�Y��IH2�N�D�%w����]g�a�K�aL!�ϠIYz����0�:��Nw���2�B�-�_�-�Me�V���m�\z8Y�ir�ǵ�=u
'i[�Y@�.Ϣ�4��]������G�^��W�Q8=�U`{�O�5
��c�rM�c���0AY���W�/�j���ĩ�b��ؑ��R}��e����=�$]���vzG��+���ZL*�z�ck=1��v]zJ�e�?�����x��z�*i�b�h�s0��n��'�yL21���fJï�ց�+rPfYן4��<�}�i�9���O�o ����e��4��rտ�fݹ�E_�L�-�V���լz�)Z���AQ�$1�i�9n�?!��j'@��'�-t���랙�k�l��JV[ئ���/.F~��������O�xx�j8��s*�ea�Z��*up��Թ�uG����4rOF�m�X�2H��9�eɍ�yr[�`J�C��\���|��|��|�����T
��y�F�����%�a,+ԙ\kU�N� ��+:f���]�Z"8�U��#�@�7�,�%NY�69Wz�2�����f��(W��/}j�'��Hߗ�?M�ک̽�p}�@eJ�WK(b�÷U��o�{n�98��M���I��5��[,�u{��N�u������[��Y��GYv1�Oz.T+���i@y��$�"K&Э��F�(�Ű�U�,C$`�
(�2���t�=Y$�։]v����"�9̰u3lN�Z����-��X��֍w�X��C�ir&J3��"���⢃�)������Y��n��A6���ׅ>d/i^�z��>��MR�}wQ؉�Ytf��X�i-��[��s��B�%�7<������a'cB�����.v|�5�̹cZ-�-�7��qV򽔼���W|ر���Dg�W��+��)f���#�O�������jG�!�x��"N&:�r���y]:�zf�q��^�S������: ���^Wߝuv��G�^�J�gq�ˊ���FӺDn��{�e����[�l����V�8"����Ceg��I��lræ|�e�&�tB�T�+6L<���U `P�M�^�aX��;4�����*��C*؛�
q��wŰ�!1s�L�2)6#�?�4K"���9۽���/�`�cH�V$t���ݭ"�+D�n)�� �ߊ0�9N��"�D�.�D���+��H�9���ߒ.'��������l.����R5-l6����i8�w�x3��r�3��L����m�N��.j���%aB��Fs�Zs^(���j��2�.�`��r� �
A��{�h��ޯm^�n��wa8��,�������<8������6-��#m�K�}o�i��������0����s�p����v�ga��/2�H�Zm��-6
�·H�1�Bq4"��c�=�P/��e�S��Ģ,���5�<+����7������L��$�Q�����h�u��D�u����OY�=��޷3n�{��ഛX;����Pv�<��8
������Ŭ]ɏ�6A�N~U��2l+�b����<{�ɍ �F�)�XW*��Ζ�B���l%�B�Z����6�g���Mv�9 z��a���D8��ử������
:Y�9�i����[�(����,��ϼ���$�����Q4G���K��;�C4.K��krod�s�t�W�7|f��h+��A���~��J��ƍ�T�X�U�����#uKC�����M��Sq�o���ZD�uL�{`d�ĉŁ9��Z_�!�{ñS���
�v��#�Sq���³f�}E����%�W4E;�h&8�����@yr7����'�q�7sR�f$��'��Z�O��K��i��"�}�K]��;\�o��,%�p�~�鵣*Z�f� �_�ق��-�A��J|W�uO��q��$&�ϛ8�*c�Z�̰�,�s�����u��r4~�03_�e�ߛ4�d���y����b��w���j'��/w!�W�q�#��[�shVNϫ��I�`�f`r�v���� �8K��w2��@���c�;_SS�W3���"1ܺ˼��T�R�S�IzPTmf+�R���:.#�ƫ���>�G3���ޓ�;���~�a�:��EQ;��.���8B�;�r�ܗ��g19=1�)o�a�)�Q�� ��'�m����^�V`�� �E�mQ(Pm��ww]�fd���/���q���zk�vr������V�;���q��*S���-���1�ȷO�@k��T�2Px����������!ɮ��~IøU�����[�{*3c�*͌k��p�Y�f�c`�$�ls:+U�$�=��?�\=�Li"�i+|B�#|���A�:��ohH��-��d�9�=�f>��cc�uo�S�\6��}k�T.R���.`����ޚ�9�Z�.V��F��Es�%���se��KeNfF�Y��7Es�F��FZ��"�f�����N�e�{ᢘ�x"�wATN�T.����zN�:vl���+�?N�¤ʳ����5���QO��!�c�$"Y�J����r{,9ŉV9ri���B��=��������[O
��@ES}��h)�}MxΨ<\u���`+;���ѯ#��w��ZA�A��T-��w[���ي��X��jh�>,�Pf��j�ֹ�W0Z%4M��F�>��9Dk��%�Py��J?Zo��fC�Pާ)���ɴv%I�X���4�F���pڄQ�<!Ř_uQ&�����K�E�0��@Y�v�{]��h�&}`��.����ԖCF�!��,��ߴ�����py�۝{Hri���4sߠ�*�[�MJG�wc�_h*���n.F꒠��V\'�6�.��3[�ξz��着�_5h%�jh-t�$t������G�]W|^%�|v_����]��2Ch�+�E+WTC���;O�������M�������v���an�M�D;}��o^��$df�L��X%>n�#6۪OE��]tde�ɇ�a���>��&�`�귝ٙ�&_���[�JT���{���ESh�����L�W��� m2�,��H�X�j�����?5�-u����ػ���+�D8�fA�����fd�#=��h�a�{ �au�"ŹĪ���9-ą��@F�ܮ�Ats�V��[>��Y�"��q��p�Q�d!��/ׁ�?��IU��; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2381)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:187)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:72)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:391)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:635)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

I would suggest you to give it another try by building the JAR locally based on the latest master, which may have already addressed the issue.

**Comment by wing328** [comment]
Closing this as there's no update.
