### ISSUE TITLE
[python-flask] INFO io.swagger.parser.Swagger20Parser - reading from CETIC/MISSIONS/SiriusInsight/AddWYX.yml

### ISSUE THREAD

**Issue by SellamiRami** [swagger-api/swagger-codegen#4583]
##### Description
Dear all, 

I have already specified an API using Swagger-editor. The generated Yaml file does not contain any errors. 

 Now, I want to generate a python flask project to implement my API. To do so, I use the command `swagger-codegen` as follow: 

`swagger-codegen generate -i AddWYX.yml -l python-flask -o addwyx`

However, I get the following error message: 

`[main] INFO io.swagger.parser.Swagger20Parser - reading from AddWYX.yml
[main] INFO io.swagger.parser.Swagger20Parser - reading from AddWYX.yml
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: CETIC/MISSIONS/SiriusInsight/AddWYX.yml; line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1861)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:147)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:74)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:72)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:390)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:132)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)`

I checked the previous issues in relation with my problem. Nevertheless, it did not help me.

Could you please help in fixing my problem.

Best regards, 
Rami.

```yaml
 swagger: '2.0'
schemes: 
  - https
basePath: /addwyx
info:
  contact: 
    name: "CETIC"
    url: https://www.cetic.be/Contact
  version: "0.2"
  title: AddWYX API
  description: "This API enables to get the positions X and Y, and the mosaic code based on a given address"
consumes:
  - text/plain
  - text/csv
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
  - text/html
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: SIMPLE-API-KEY
  AdminSecurity:
    type: apiKey
    in: header
    name: ADMIN-API-KEY
  MediaSecurity:
    type: apiKey
    in: query
    name: media-api-key
security:
  - UserSecurity: []
paths:
  /referencepoint:
    post:
      description: |
        Get the X, Y coordinates and the mosaic code, based on a json input
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: address
          in: body
          description: Single address string
          required: true
          schema:
            $ref: "#/definitions/Request"
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Response"
          examples: 
            data:
              referencePoints:
              - inputAddress:	'Rue Francois Van Assche 1, 1140 Evere'
                StreetSegment: '21006A001003690AH32_2'
                PositionX: '4.3985262'	
                PositionY: '50.8766102'	
                Mosaic:	'H32'
                QualityCodeMosaic: '1'	
                QualityCodeLocalisation: '1'	
                QualityCodeINS9: '1'
            metadata: 'This is a metadata description'
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 400'
              description: 'this is the description of th error 400'
        402:
          description: "Valid request but quota exceeded"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 402'
              description: 'this is the description of th error 402'
        404:
          description: "Invalid API endpoint"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 404'
              description: 'this is the description of th error 404'
        410:
          description: "Not available requested resource and will not be available again"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 410'
              description: 'this is the description of th error 410'
        503:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 503'
              description: 'this is the description of th error 503'
    get:
      description: |
        Get the X, Y coordinates and the mosaic code, based on a **single address**
      parameters:
        - name: address
          in: query
          description: Single address string
          required: true
          type: string
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Response"
          examples: 
            data:
              referencePoints:
              - inputAddress:	'Rue Francois Van Assche 1, 1140 Evere'
                StreetSegment: '21006A001003690AH32_2'
                PositionX: '4.3985262'	
                PositionY: '50.8766102'	
                Mosaic:	'H32'
                QualityCodeMosaic: '1'	
                QualityCodeLocalisation: '1'	
                QualityCodeINS9: '1'
            metadata: 'This is a metadata description'
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 400'
              description: 'this is the description of th error 400'
        402:
          description: "Valid request but quota exceeded"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 402'
              description: 'this is the description of th error 402'
        404:
          description: "Invalid API endpoint"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 404'
              description: 'this is the description of th error 404'
        410:
          description: "Not available requested resource and will not be available again"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 410'
              description: 'this is the description of th error 410'
        503:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 503'
              description: 'this is the description of th error 503'
definitions:
  Request:
    properties: 
      Address:
        type: array
        items:
          type: object
          properties: 
            StreetName: 
              type: string
            StreetNumber: 
              type: string
            PostalCode: 
              type: string
            Locality:
              type: string
            Country: 
              type: string
  Response:
    properties:
      data: 
        type: object
        properties:
          referencePoints: 
            type: array
            items:
              type: object
              properties:
                inputAddress:
                  type: string
                StreetSegment:
                  type: string
                PositionX:
                  type: string
                PositionY:
                  type: string
                Mosaic:
                  type: string
                QualityCodeMosaic:
                  type: string
                QualityCodeLocalisation:
                  type: string
                QualityCodeINS9:
                  type: string
      metadata:
        type: string
  Error:
    properties: 
      error:
        type: object
        properties: 
          status: 
            type: string
          description: 
            type: string
parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of persons returned
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
 ```

**Comment by bkryza** [comment]
@SellamiRami 

You seem to have an unnecessary space before swagger token in the first line, try this:

```yaml
swagger: '2.0'
schemes: 
  - https
basePath: /addwyx
info:
  contact: 
    name: "CETIC"
    url: https://www.cetic.be/Contact
  version: "0.2"
  title: AddWYX API
  description: "This API enables to get the positions X and Y, and the mosaic code based on a given address"
consumes:
  - text/plain
  - text/csv
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
  - text/html
securityDefinitions:
  UserSecurity:
    type: apiKey
    in: header
    name: SIMPLE-API-KEY
  AdminSecurity:
    type: apiKey
    in: header
    name: ADMIN-API-KEY
  MediaSecurity:
    type: apiKey
    in: query
    name: media-api-key
security:
  - UserSecurity: []
paths:
  /referencepoint:
    post:
      description: |
        Get the X, Y coordinates and the mosaic code, based on a json input
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: address
          in: body
          description: Single address string
          required: true
          schema:
            $ref: "#/definitions/Request"
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Response"
          examples: 
            data:
              referencePoints:
              - inputAddress:	'Rue Francois Van Assche 1, 1140 Evere'
                StreetSegment: '21006A001003690AH32_2'
                PositionX: '4.3985262'	
                PositionY: '50.8766102'	
                Mosaic:	'H32'
                QualityCodeMosaic: '1'	
                QualityCodeLocalisation: '1'	
                QualityCodeINS9: '1'
            metadata: 'This is a metadata description'
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 400'
              description: 'this is the description of th error 400'
        402:
          description: "Valid request but quota exceeded"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 402'
              description: 'this is the description of th error 402'
        404:
          description: "Invalid API endpoint"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 404'
              description: 'this is the description of th error 404'
        410:
          description: "Not available requested resource and will not be available again"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 410'
              description: 'this is the description of th error 410'
        503:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 503'
              description: 'this is the description of th error 503'
    get:
      description: |
        Get the X, Y coordinates and the mosaic code, based on a **single address**
      parameters:
        - name: address
          in: query
          description: Single address string
          required: true
          type: string
        - $ref: "#/parameters/pageSize"
        - $ref: "#/parameters/pageNumber"
      
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/Response"
          examples: 
            data:
              referencePoints:
              - inputAddress:	'Rue Francois Van Assche 1, 1140 Evere'
                StreetSegment: '21006A001003690AH32_2'
                PositionX: '4.3985262'	
                PositionY: '50.8766102'	
                Mosaic:	'H32'
                QualityCodeMosaic: '1'	
                QualityCodeLocalisation: '1'	
                QualityCodeINS9: '1'
            metadata: 'This is a metadata description'
        400:
          description: "Invalid request"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 400'
              description: 'this is the description of th error 400'
        402:
          description: "Valid request but quota exceeded"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 402'
              description: 'this is the description of th error 402'
        404:
          description: "Invalid API endpoint"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 404'
              description: 'this is the description of th error 404'
        410:
          description: "Not available requested resource and will not be available again"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 410'
              description: 'this is the description of th error 410'
        503:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/Error"
          examples:
            error:
              status: 'Status 503'
              description: 'this is the description of th error 503'
definitions:
  Request:
    properties: 
      Address:
        type: array
        items:
          type: object
          properties: 
            StreetName: 
              type: string
            StreetNumber: 
              type: string
            PostalCode: 
              type: string
            Locality:
              type: string
            Country: 
              type: string
  Response:
    properties:
      data: 
        type: object
        properties:
          referencePoints: 
            type: array
            items:
              type: object
              properties:
                inputAddress:
                  type: string
                StreetSegment:
                  type: string
                PositionX:
                  type: string
                PositionY:
                  type: string
                Mosaic:
                  type: string
                QualityCodeMosaic:
                  type: string
                QualityCodeLocalisation:
                  type: string
                QualityCodeINS9:
                  type: string
      metadata:
        type: string
  Error:
    properties: 
      error:
        type: object
        properties: 
          status: 
            type: string
          description: 
            type: string
parameters:
  pageSize:
    name: pageSize
    in: query
    description: Number of persons returned
    type: integer
  pageNumber:
    name: pageNumber
    in: query
    description: Page number
    type: integer
```

**Comment by SellamiRami** [comment]
Thank you for your response @bkryza 

However, there is no space in the original yaml file. It is noteworthy that the yaml file is valid in the swagger-editor.

**Comment by bkryza** [comment]
@SellamiRami I think the answer is even more obvious but I didn't catch it somehow, I don't think Swagger Codegen accepts Yaml, as you can see in the stack trace it's trying to parse Json - could you convert your spec to Json (e.g. using http://editor.swagger.io/) and try again?

**Comment by fehguy** [comment]
codegen does accept yaml or json, btw...

**Comment by bkryza** [comment]
@fehguy you are right :-)

@SellamiRami I just tested your example, when I remove the space in the first line it works:
```shell
➜  swagger-codegen git:(master) ✗ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.yml -l python-flask -o output/flask
[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yml
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: GET /referencepoint. Renamed to auto-generated operationId: referencepointGET
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: POST /referencepoint. Renamed to auto-generated operationId: referencepointPOST
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/error.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/error_error.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/request.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/request_address.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/response.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/response_data.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/response_data_reference_points.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/controllers/default_controller.py
[main] INFO io.swagger.codegen.DefaultGenerator - File exists. Skipped overwriting /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/test/test_default_controller.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/README.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/setup.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/tox.ini
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/test-requirements.txt
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/requirements.txt
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/git_push.sh
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/.gitignore
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/.travis.yml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/__main__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/encoder.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/util.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/controllers/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/models/base_model_.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/test/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /Users/bartek/devel/swagger/swagger-codegen/output/flask/swagger_server/swagger/swagger.yaml
```

but when I copy your original example I get the same error as you reported:

```shell
➜  swagger-codegen git:(master) ✗ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.yml -l python-flask -o output/flask
[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yml
[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yml
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'swagger': was expecting ('true', 'false' or 'null')
 at [Source: test.yml; line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3524)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2431)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:189)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:74)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:408)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:225)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:635)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:227)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
```

 Can you double check your yaml file?

**Comment by SellamiRami** [comment]
@bkryza I am sure that there is no extra space in my yaml file. 

However, I remark thar we are not using the same way to do the code gen. Indeed, I am executing `swagger-codegen generate -i AddWYX.yml -l python-flask -o addwyx`. You are executing `swagger-codegen git:(master) ✗ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i test.yml -l python-flask -o output/flask`.

Do you think that is the source of the problem? Is there some other parameters that I should specify in my command?

**Comment by bkryza** [comment]
@SellamiRami One more thing, I'm not sure which codegen version you're using exactly, could try to use the latest codegen version from GitHub:

```
$ git clone https://github.com/swagger-api/swagger-codegen && cd swagger-codegen
$ mvn package
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i AddWYX.yml -l python-flask -o output/AddWYX
```

**Comment by SellamiRami** [comment]
@bkryza 
I tried your proposition. Nevertheless, it is in vain. I get the same error message.

Is there a problem of dependencies?

**Comment by bkryza** [comment]
@SellamiRami I don't think dependencies should be an issue in this case, the last thing that comes to my mind that could cause this would be some UTF encoding issues casued by some strange character on your first line, could you create a new file by pasting your yaml to http://editor.swagger.io/ and downloading a new yaml file from there?

**Comment by SellamiRami** [comment]
@bkryza 

First of all I want to thank you very much for your help and support. 

I fixed my problem. Actually, I start adding line by line in the specification file et I noticed that the problem appears when I add the `examples` bloc. There is an extra space there :-/ :-/.

Now I have my flask project and I can start implementing my API.

Have a nice day :-)
