### ISSUE TITLE
java.lang.Exception: reserved word "protected" not allowed

### ISSUE THREAD

**Issue by levinotik** [swagger-api/swagger-codegen#470]
Trying to create a BasicAndroidJavaClient using codegen. I pointed the generator to my swagger docs and got this exception. Here's the full stack trace:

```
java.lang.Exception: reserved word "protected" not allowed
	at com.wordnik.swagger.codegen.BasicJavaGenerator.escapeReservedWord(BasicJavaGenerator.scala:240)
	at com.wordnik.swagger.codegen.language.CodegenConfig.toVarName(CodegenConfig.scala:116)
	at com.wordnik.swagger.codegen.BasicJavaGenerator.toVarName(BasicJavaGenerator.scala:112)
	at com.wordnik.swagger.codegen.Codegen$$anonfun$modelToMap$1.apply(Codegen.scala:375)
	at com.wordnik.swagger.codegen.Codegen$$anonfun$modelToMap$1.apply(Codegen.scala:340)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.LinkedHashMap.foreach(LinkedHashMap.scala:139)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.wordnik.swagger.codegen.Codegen.modelToMap(Codegen.scala:340)
	at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$prepareModelMap$2.apply(BasicGenerator.scala:234)
	at com.wordnik.swagger.codegen.BasicGenerator$$anonfun$prepareModelMap$2.apply(BasicGenerator.scala:232)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at com.wordnik.swagger.codegen.BasicGenerator.prepareModelMap(BasicGenerator.scala:232)
	at com.wordnik.swagger.codegen.BasicGenerator.generate(BasicGenerator.scala:123)
	at com.wordnik.swagger.codegen.BasicGenerator.generateClientWithoutExit(BasicGenerator.scala:75)
	at com.wordnik.swagger.codegen.BasicGenerator.generateClient(BasicGenerator.scala:57)
	at com.wordnik.swagger.codegen.BasicAndroidJavaClient$.main(BasicAndroidJavaClient.scala:22)
	at com.wordnik.swagger.codegen.BasicAndroidJavaClient.main(BasicAndroidJavaClient.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by levinotik** [comment]
Digging in a bit further, it looks like the issue is caused by one of models (written in scala) having a propertly defined as ```val `protected`: Boolean``` using the special backtick syntax to allow use of otherwise reserved keywords in scala

**Comment by fehguy** [comment]
Please update to 2.1.2-M1.  It will make your life much easier.

**Comment by levinotik** [comment]
@fehguy thanks. Where can I get that?

**Comment by fehguy** [comment]
It's master, and also on maven central.

Executable jar
[swagger-codegen-distribution-2.1.2-M1](https://oss.sonatype.org/content/repositories/releases/com/wordnik/swagger-codegen-distribution/2.1.2-M1/)
Library
[swagger-codegen-2.1.2-M1](https://oss.sonatype.org/content/repositories/releases/com/wordnik/swagger-codegen/2.1.2-M1/)

**Comment by levinotik** [comment]
Thanks @fehguy! I tried running the jar with

```
java -jar swagger-codegen-distribution-2.1.2-M1.jar \
-h http://localhost:8080/api-docs \
-l android \
-o output
```

 and got:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
```

**Comment by levinotik** [comment]
I must be running the wrong command there... :(

**Comment by fehguy** [comment]
ah-- please run the -h command to get the opts.  Slightly different from 2.0.x

**Comment by levinotik** [comment]
Sorry, not sure I follow. What command should I run?

**Comment by levinotik** [comment]
nevermind, figured it out, thanks!!

**Comment by fehguy** [comment]
Get help like this:
```
java -jar swagger-codegen-distribution-2.1.2-M1.jar -h
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
usage: Codegen
 -a,--auth <arg>           adds authorization headers when fetching the
                           swagger definitions remotely. Pass in a
                           URL-encoded string of name:header with a comma
                           separating multiple values
 -d,--debug-info           prints additional info for debugging
 -h,--help                 shows this message
 -i,--input-spec <arg>     location of the swagger spec, as URL or file
 -l,--lang <arg>           client language to generate.
                           Available languages include:
                           [android, async-scala, java, jaxrs, nodejs,
                           objc, scalatra, scala, dynamic-html, html,
                           swagger, threepane, tizen, php, python]
 -o,--output <arg>         where to write the generated files
 -t,--template-dir <arg>   folder containing the template files
```

For your example then the command is:
```
java -jar swagger-codegen-distribution-2.1.2-M1.jar \
-i http://localhost:8080/api-docs \
-l android \
-o output
```

**Comment by levinotik** [comment]
Yup, got it working. Is the generated Android client meant to be used a library project in Android (with dependencies on Android) project or does it work as a standalone java lib?

**Comment by fehguy** [comment]
stand-alone, you should be able to compile with `mvn package`

**Comment by levinotik** [comment]
Looks like there are some Scala and Java interop issues :( 

Generated some code like this:
```
import io.swagger.client.model.List[com.grasswire.common.models.Event&lt;com.grasswire.common.json_models.TweetJsonModel&gt;];
```

**Comment by fehguy** [comment]
Hmm can you share your spec so I can investigate?  Email is fine if you prefer

**Comment by levinotik** [comment]
DM'd you on Twitter. Thanks so much.

**Comment by webron** [comment]
@levinotik, @fehguy - since you continued in private, is there any update for this issue?

**Comment by levinotik** [comment]
@webron there were a bunch of things we discussed. one way or another this went away, but don't remember exactly how. I'd say you can close this.

**Comment by webron** [comment]
@levinotik - thanks. Feel free to reopen (or submit a new issue) if needed.
