### ISSUE TITLE
[Python-flask] models/model_inline_response*.py file/import name mismatch

### ISSUE THREAD

**Issue by akihiro** [swagger-api/swagger-codegen#4728]
##### Description

Generated python-flask server code by swagger-codegen-cli.

Generated plain server code is tested in failure.

##### Swagger-codegen version

commit e8f11bc219e612ad10a2f843ddab16fd642d5eb5

##### Swagger declaration file content or url

https://gist.github.com/akihiro/4292156950309d723351bec6ef2fdcd1

##### Steps to reproduce

```
swagger-codegen$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /var/tmp/swagger.yaml -l python-flask -o /var/tmp/example
[main] INFO io.swagger.parser.Swagger20Parser - reading from /var/tmp/swagger.yaml
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Directory does not exist, or is inaccessible. No file will be evaluated.
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: GET /vlan/. Renamed to auto-generated operationId: vlanGET
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/models/inline_response_200.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/models/inline_response_200_ipv4.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/models/inline_response_200_ipv6.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/models/inline_response_default.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/controllers/default_controller.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/test/test_default_controller.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/README.md
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/setup.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/tox.ini
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/test-requirements.txt
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/requirements.txt
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/git_push.sh
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/.gitignore
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/.travis.yml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/__main__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/encoder.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/util.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/controllers/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/models/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/models/base_model_.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/test/__init__.py
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/swagger_server/swagger/swagger.yaml
[main] INFO io.swagger.codegen.AbstractGenerator - writing file /var/tmp/example/.swagger-codegen-ignore
swagger-codegen$ cd /var/tmp/example/
example$ tox -e py36
GLOB sdist-make: /var/tmp/example/setup.py
py36 inst-nodeps: /var/tmp/example/.tox/dist/swagger_server-1.0.0.zip
py36 installed: appdirs==1.4.0,click==6.7,clickclick==1.2.1,connexion==1.0.129,coverage==4.3.4,Flask==0.12,Flask-Testing==0.6.1,itsdangerous==0.24,Jinja2==2
.9.5,jsonschema==2.6.0,MarkupSafe==0.23,nose==1.3.7,packaging==16.8,pluggy==0.4.0,py==1.4.32,pyparsing==2.1.10,python-dateutil==2.6.0,PyYAML==3.12,randomize
==0.14,requests==2.13.0,six==1.10.0,strict-rfc3339==0.7,swagger-server==1.0.0,swagger-spec-validator==2.0.2,Werkzeug==0.11.15
py36 runtests: PYTHONHASHSEED='382082069'
py36 runtests: commands[0] | nosetests
EE
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'swagger_server.models.inline_response200_ipv4')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/tmp/example/.tox/py36/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/var/tmp/example/.tox/py36/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/tmp/example/swagger_server/models/__init__.py", line 5, in <module>
    from .inline_response_200 import InlineResponse200
  File "/var/tmp/example/swagger_server/models/inline_response_200.py", line 4, in <module>
    from swagger_server.models.inline_response200_ipv4 import InlineResponse200Ipv4
ModuleNotFoundError: No module named 'swagger_server.models.inline_response200_ipv4'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'swagger_server.models.inline_response200_ipv4')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/var/tmp/example/.tox/py36/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/var/tmp/example/.tox/py36/lib/python3.6/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/var/tmp/example/.tox/py36/lib/python3.6/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/tmp/example/swagger_server/test/__init__.py", line 2, in <module>
    from ..encoder import JSONEncoder
  File "/var/tmp/example/swagger_server/encoder.py", line 3, in <module>
    from swagger_server.models.base_model_ import Model
  File "/var/tmp/example/swagger_server/models/__init__.py", line 5, in <module>
    from .inline_response_200 import InlineResponse200
  File "/var/tmp/example/swagger_server/models/inline_response_200.py", line 4, in <module>
    from swagger_server.models.inline_response200_ipv4 import InlineResponse200Ipv4
ModuleNotFoundError: No module named 'swagger_server.models.inline_response200_ipv4'

----------------------------------------------------------------------
Ran 2 tests in 0.256s

FAILED (errors=2)
ERROR: InvocationError: '/var/tmp/example/.tox/py36/bin/nosetests'
_________________________________________________________________________ summary __________________________________________________________________________
ERROR:   py36: commands failed
```

##### Related issues

#4684

##### Suggest a Fix

inline_response file's import filename is differ from ```models/__init__.py```.
Same routines use?

```python
## /var/tmp/example/swagger_server/models/__init__.py
# coding: utf-8

from __future__ import absolute_import
# import models into model package
from .inline_response_200 import InlineResponse200
from .inline_response_200_ipv4 import InlineResponse200Ipv4
from .inline_response_200_ipv6 import InlineResponse200Ipv6
from .inline_response_default import InlineResponseDefault
```

```python
##  /var/tmp/example/swagger_server/models/inline_response_200.py (head 10 lines)
# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.inline_response200_ipv4 import InlineResponse200Ipv4
from swagger_server.models.inline_response200_ipv6 import InlineResponse200Ipv6
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model

```

I'm know java a little... I don't know where I fix .

**Comment by wing328** [comment]
@akihiro thanks for the details in reporting the issue. If anyone from the community wants to take a look, please go ahead.

I'll take a look after the 2.2.2. release.

**Comment by wing328** [comment]
Duplicated: https://github.com/swagger-api/swagger-codegen/issues/4684

Please pull the latest master or stable version (2.2.2) and give it a try.

**Comment by wing328** [comment]
The issue should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4958

Please pull the latest master to give it a try.
