### ISSUE TITLE
Swagger does not recognize .yml files as YAML

### ISSUE THREAD

**Issue by bklang** [swagger-api/swagger-codegen#478]
I was getting a parse error like the below. The fix was simply to rename `call_recorder_swagger.yml` to `call_recorder_swagger.yaml`.  I believe both suffixes should be recognized as YAML.

```
Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: call_recorder/docs/call_recorder_swagger.yml; line: 1, column: 3]
reading from call_recorder/docs/call_recorder_swagger.yml
Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: call_recorder/docs/call_recorder_swagger.yml; line: 1, column: 3]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value
 at [Source: call_recorder/docs/call_recorder_swagger.yml; line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserBase.reportUnexpectedNumberChar(ParserBase.java:939)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleInvalidNumberStart(UTF8StreamJsonParser.java:2487)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseNegNumber(UTF8StreamJsonParser.java:1245)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:777)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3090)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3036)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1846)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:125)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:58)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:87)
java.lang.RuntimeException: missing swagger input or config!
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:31)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)
```

**Comment by fehguy** [comment]
The spot to fix this is here:

https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java#L22-L25

The fix will simply be to trim the input and see that it starts with `{` for JSON, otherwise, YAML.  If you send a PR with some tests, I'll merge and do a snapshot today.

**Comment by fehguy** [comment]
fixed in https://github.com/swagger-api/swagger-parser/commit/ebfce84835236cb4cbd7dc19b119028067d4d8c8

**Comment by bklang** [comment]
Sorry I didn't get back to this, and thank you for the fix.
