### ISSUE TITLE
Online editor generated Python Flask server does not work according to README.md

### ISSUE THREAD

**Issue by wehnsdaefflae** [swagger-api/swagger-codegen#4789]
Using the online editor and a swagger YAML file, I generated a python flask rest server application.

According to the README.md included in the generated server zip file, I executed

    pip3 install -r requirements.txt
    python3 -m my_server

Instead of running the server, however, the second line gave me an exception.

    Traceback (most recent call last):
      File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main "__main__", mod_spec)
      File "/usr/lib/python3.5/runpy.py", line 85, in _run_code exec(code, run_globals)
      File "/home/projects/my_server/python-flask-server/swagger_server/__main__.py", line 4, in <module> from .encoder import JSONEncoder
      File "/home/projects/my_server/python-flask-server/swagger_server/encoder.py", line 3, in <module> from swagger_server.models.base_model_ import Model
      File "/home/projects/my_server/python-flask-server/swagger_server/models/__init__.py", line 5, in <module> from .inline_response_200 import InlineResponse200
      File "/home/projects/my_server/python-flask-erver/swagger_server/models/inline_response_200.py", line 4, in <module> from swagger_server.models.inline_response200_data import InlineResponse200Data
    ImportError: No module named 'swagger_server.models.inline_response200_data'

I followed the instructions precisely (all two steps...) and did not write or change any python code myself. Also my YAML file is correct according to the online editor (otherwise I wouldn't have been able to generate the server anyway, I guess).

Swagger Online Editor Version 2.10.3

```yaml
# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: 0.0.1
  title: ANN Tools
  description: |
    ## Description
    

paths:
  /file:
    post:
      description: Posts a new csv file to the server. File names are preserved. Existing files with the same name are replaced.
      
      consumes:
      - application/x-www-form-urlencoded

      parameters:
        - $ref: "#/parameters/UploadData"
          
      responses:
        500:
          $ref: "#/responses/Failure"

        201:
          $ref: "#/responses/Success"
        
    delete:
      description: Deletes a previously uploaded csv file from the server.
      
      parameters:
        - $ref: "#/parameters/DeleteFile"
        
      responses:
        default:
          $ref: "#/responses/Success"

  /files:
    get:
      description: Shows all the csv files currently uploaded to the server.
      
      responses:
        200:
          description: Array of uploaded files
          schema:
            type: object
            properties:
              status:
                description: success
                type: string
              data:
                description: array of uploaded files
                type: object
                properties:
                  filenames:
                    type: array
                    items:
                      type: string
                

  /progress:
    get:
      description: Returns a JSON object that contains the current progress and relevant payload from the running process.
    
      responses:
        default:
          description: Progress and payload
          schema:
            type: object
            properties:
              status:
                description: success
                type: string
              data:
                type: object
                properties:
                  progress:
                    type: number
                    format: float
                    description: progress indicated in [0, 1]
                  payload:
                    type: object
                    description: relevant information

  /abortProcess:
    put:
      description: Aborts the currently running process.
    
      responses:
        default:
          $ref: "#/responses/Success"
                
  /clipData:
    post:
      description: Clips the csv data file to a given date range and stores the result as a new file on the server.
      
      parameters:
        - $ref: "#/parameters/SourceFile"
        - $ref: "#/parameters/ProcessedFile"
        - $ref: "#/parameters/Delimiter"
        - $ref: "#/parameters/DateIndex"
        - $ref: "#/parameters/TimeFormat"
        - $ref: "#/parameters/StartDate"
        - $ref: "#/parameters/EndDate"
      
      responses:
        default:
          $ref: "#/responses/Success"

        500:
          $ref: "#/responses/Failure"
          
  
  /composeData:
    post:
      description: Combines input data from two sources into one according to a custom operator and sores the result as a new file on the server.
      
      parameters:
        - $ref: "#/parameters/SourceFileA"
        - $ref: "#/parameters/DateIndexA"
        - $ref: "#/parameters/ValueIndexA"
        - $ref: "#/parameters/SourceFileB"
        - $ref: "#/parameters/DateIndexB"
        - $ref: "#/parameters/ValueIndexB"
        - $ref: "#/parameters/ProcessedFile"
        - $ref: "#/parameters/Delimiter"
        - $ref: "#/parameters/TimeFormat"
        - $ref: "#/parameters/Operator"
      
      responses:
        500:
          $ref: "#/responses/Failure"
          
        default:
          $ref: "#/responses/Success"  
          

  /extractMonths:
    post:
      description: Extracts the name of the month from the full date in the input file.
      
      parameters:
        - $ref: "#/parameters/SourceFile"
        - $ref: "#/parameters/DateIndex"
        - $ref: "#/parameters/Delimiter"
        - $ref: "#/parameters/TimeFormat"
        - $ref: "#/parameters/ProcessedFile"
      
      responses:
        500:
          $ref: "#/responses/Failure"
          
        default:
          $ref: "#/responses/Success"  
  
  
  /interpolateData:
    post:
      description: Interpolates the values in a csv input data file such that it contains values for all the dates in a fixed interval.
      
      parameters:
        - $ref: "#/parameters/SourceFile"
        - $ref: "#/parameters/DateIndex"
        - $ref: "#/parameters/ValueIndex"
        - $ref: "#/parameters/Delimiter"
        - $ref: "#/parameters/TimeFormat"
        - $ref: "#/parameters/ProcessedFile"
        - $ref: "#/parameters/Interval"
        - $ref: "#/parameters/Interpolation"

      responses:
        500:
          $ref: "#/responses/Failure"
          
        default:
          $ref: "#/responses/Success"  


  /smoothData:
    post:
      description: Smooth the data in an csv input file.
      
      parameters:
        - $ref: "#/parameters/SourceFile"
        - $ref: "#/parameters/DateIndex"
        - $ref: "#/parameters/ValueIndex"
        - $ref: "#/parameters/ProcessedFile"
        - $ref: "#/parameters/Delimiter"
        - $ref: "#/parameters/Window"
        - $ref: "#/parameters/Method"
      
      responses:
        500:
          $ref: "#/responses/Failure"
          
        default:
          $ref: "#/responses/Success"  


  /optimize:
    put:
      description: Optimizes model parameters for a specific data set in a predefined range. Runs indefinitely or until aborted. The currently optimal parameters are in the payload of `/progress`.
      
      parameters:
        - $ref: "#/parameters/InputFiles"
        - $ref: "#/parameters/TargetFile"
        - $ref: "#/parameters/Horizon"
        - $ref: "#/parameters/SequenceRange"
        - $ref: "#/parameters/StructureRange"
        - $ref: "#/parameters/Threshold"

      responses:
        default:
          $ref: "#/responses/Cancelled"
          
        500:
          $ref: "#/responses/Failure"
  
  
  /train:
    put:
      description: Trains a model with the given parameters and on the given data set. Runs indefinitely or until aborted. The currently optimal model is stored on the server.
      
      parameters:
        - $ref: "#/parameters/InputFiles"
        - $ref: "#/parameters/TargetFile"
        - $ref: "#/parameters/Horizon"
        - $ref: "#/parameters/ModelFile"
      
      responses:
        default:
          $ref: "#/responses/Cancelled"
          
        500:
          $ref: "#/responses/Failure"


  /predict:
    put:
      description: Predicts target data from input data and a given model.
      
      parameters:
        - $ref: "#/parameters/InputFiles"
        - $ref: "#/parameters/ModelFile"
        - $ref: "#/parameters/Horizon"
      
      responses:
        500:
          $ref: "#/responses/Failure"
        
        
        default:
          description: Resulting prediction
          
          schema:
            type: object
            description: prediction response
            properties:
              status:
                type: string
                description: success
              data:
                type: object
                description: full prediction
                properties:
                  prediction:
                    type: array
                    description: each horizon
                    items:
                      type: array
                      description: each value
                      items:
                        type: number
                        format: float


  /relevance:
    put:
      description: Determines relevant data from given input data, a model, and target data.
      
      parameters:
        - $ref: "#/parameters/InputFiles"
        - $ref: "#/parameters/TargetFile"
        - $ref: "#/parameters/ModelFile"
        - $ref: "#/parameters/Horizon"

      responses:
        500:
          $ref: "#/responses/Failure"
        
        default:
          description: Resulting relevances
          
          schema:
            type: object
            description: relevance response
            properties:
              status:
                type: string
                description: success
              data:
                type: object
                description: relevance map
                properties:
                  input_datum:
                    type: number
                    format: float
                    description: relevance value



responses:

  Failure:
    description: Internal server error
    schema:
      type: object
      properties:
        status:
          description: fail
          type: string
    
  Success:
    description: Success
    schema:
      type: object
      properties:
        status:
          description: success
          type: string

  Cancelled:
    description: Cancelled by `/abortProcess`
          
          

parameters:

  ValueIndex:
    name: valueColumnIndex
    default: -1
    in: query
    description: the value index of the date
    type: number
    format: integer

  ValueIndexA:
    name: valueColumnIndexA
    default: -1
    in: query
    description: the value index of the date in the first data file
    type: number
    format: integer

  ValueIndexB:
    name: valueColumnIndexB
    default: -1
    in: query
    description: the value index of the date in the second data file
    type: number
    format: integer

  DeleteFile:
    name: filename
    required: true
    in: query
    description: the file to delete on the server
    type: string

  DateIndex:
    name: dateColumnIndex
    default: 0
    in: query
    description: the column index of the date
    type: number
    format: integer

  DateIndexA:
    name: dateColumnIndexA
    default: 0
    in: query
    description: the column index of the date in the first data file
    type: number
    format: integer

  DateIndexB:
    name: dateColumnIndexB
    default: 0
    in: query
    description: the column index of the date in the second data file
    type: number
    format: integer

  SourceFile:
    name: sourceFilename
    required: true
    in: query
    description: the csv data input file
    type: string
  
  SourceFileA:
    name: sourceFilenameA
    required: true
    in: query
    description: the first csv data input file
    type: string
  
  SourceFileB:
    name: sourceFilenameB
    required: true
    in: query
    description: the second csv data input file
    type: string
  
  ProcessedFile:
    name: processedFilename
    required: true
    in: query
    description: the target file name
    type: string

  InputFiles:
    name: inputFilenames
    required: true
    in: query
    description: the input files for the model
    type: array
    items:
      type: string
  
  Delimiter:
    name: delimiter
    default: "\t"
    in: query
    description: the csv delimiter
    type: string
    
  Window:
    name: window
    default: 200
    in: query
    description: the smoothing window
    type: number
    format: integer
  
  Method:
    name: method
    default: "mean"
    in: query
    description: the smoothing method
    type: string
    enum: ["mean", "median", "smear"]
  
  TimeFormat:
    name: timeFormat
    default: "%Y%m%d"
    in: query
    description: the time format used in the according column of the csv file
    type: string
  
  Interval:
    name: intervalSeconds
    default: 86400
    in: query
    description: the time interval in seconds
    type: number
    format: integer
  
  Horizon:
    name: horizon
    default: 200
    in: query
    description: the prediction horizon in set time intervals
    type: number
    format: integer
  
  Interpolation:
    name: continuousInterpolation
    default: false
    in: query
    description: whether intermediate values are interpolated
    type: boolean
  
  Operator:
    name: operator
    required: true
    in: query
    description: the operation on the data for each point in time, e.g. `a + b`
    type: string
  
  StartDate:
    name: startDate
    required: true
    in: query
    description: the date to start clipping from in the correct `timeFormat`
    type: string
    
  EndDate:
    name: endDate
    required: true
    in: query
    description: the date to end clipping at in the correct `timeFormat`
    type: string
  
  UploadData:
    name: filename
    in: formData
    description: The uploaded csv data file
    required: true
    type: file
  
  TargetFile:
    name: targetFilename
    required: true
    in: query
    description: the target csv datsa file
    type: string

  ModelFile:
    name: modelFilename
    required: true
    in: query
    description: the model file
    type: string

  SequenceRange:
    name: sequenceRange
    default: [30, 365]
    in: query
    description: the allowed range of sequence lengths
    type: array
    items:
      type: number
      format: integer
  
  StructureRange:
    name: structureRange
    default: [10, 1000]
    in: query
    description: the allowed structural range
    type: array
    items:
      type: number
      format: integer
   
  Threshold:
    name: threshold
    default: 0.025
    in: query
    description: the minimal training error to accept a test evaluation result
    type: number
    format: float
          ```

**Comment by wehnsdaefflae** [comment]
related to https://github.com/swagger-api/swagger-codegen/issues/4684

**Comment by wehnsdaefflae** [comment]
part of the problem can be resolved by deleting the `__init__.py` in the models folder.

**Comment by wing328** [comment]
@wehnsdaefflae thanks for reporting the issue. We'll look into it after the 2.2.2 release.

**Comment by wing328** [comment]
The issue should be fixed by https://github.com/swagger-api/swagger-codegen/pull/4958. Please pull the latest master to give it a try.
