### ISSUE TITLE
Unsupported major.minor version 52.0 (unable to load class io.swagger.api.ApiOriginFilter)

### ISSUE THREAD

**Issue by userara2** [swagger-api/swagger-codegen#4790]
Deployed Swagger generated code to Tomcat running Java 1.8 

##### Swagger-codegen version

using swagger: '2.0'

##### Command line used for generation

I used the online editor

##### Steps to reproduce

Deployed Swagger generated code to Tomcat running Java 1.8 

13-Feb-2017 23:46:44.758 SEVERE [localhost-startStop-5] org.apache.catalina.core.StandardContext.filterStart Exception starting filter ApiOriginFilter
 java.lang.UnsupportedClassVersionError: io/swagger/api/ApiOriginFilter : Unsupported major.minor version 52.0 (unable to load class io.swagger.api.ApiOriginFilter)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2271)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:811)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1254)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119)
	at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:520)
	at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:501)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:118)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:258)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4572)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by wing328** [comment]
Which Java server generator (e.g. spring, rest-easy, etc) did you use?

**Comment by wing328** [comment]
Closing this as there's no reply.
