### ISSUE TITLE
[PYTHON] Generating Flask Server with default.yaml

### ISSUE THREAD

**Issue by dsandersAzure** [swagger-api/swagger-codegen#4811]
##### Description

Unable to run a generated Flask server on MacOS. The generated server was generated from the latest official Docker image (swaggerapi/swagger-editor) and generated from within the editor. All installs okay but when running *python3 -m swagger_server*, generates the following error:

```
$ python3 -m swagger_server
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/davidsanders/Downloads/python-flask-server 3/swagger_server/__main__.py", line 4, in <module>
    from .encoder import JSONEncoder
  File "/Users/davidsanders/Downloads/python-flask-server 3/swagger_server/encoder.py", line 3, in <module>
    from swagger_server.models.base_model_ import Model
  File "/Users/davidsanders/Downloads/python-flask-server 3/swagger_server/models/__init__.py", line 5, in <module>
    from .activities import Activities
  File "/Users/davidsanders/Downloads/python-flask-server 3/swagger_server/models/activities.py", line 4, in <module>
    from swagger_server.models.activity import Activity
  File "/Users/davidsanders/Downloads/python-flask-server 3/swagger_server/models/activity.py", line 4, in <module>
    from .base_model_ import Model
  File "/Users/davidsanders/Downloads/python-flask-server 3/swagger_server/models/base_model_.py", line 2, in <module>
    from typing import TypeVar, Type
ImportError: cannot import name 'Type'
```

##### Swagger declaration file content or url

default.yaml

##### Steps to reproduce

Simply run the Docker container swaggerapi/swagger-editor and generate default.yaml as a Python flask server.

**Comment by wing328** [comment]
@dsandersAzure thanks for reporting the issue. Can you please try the "petstore_full.yaml" from the example in editor.swagger.io instead?

**Comment by dsandersAzure** [comment]
Hi @wing328,

Thanks for the response and suggestion. So I went to the example in editor.swagger.io and performed the following steps (and got the same error):

1. Generate Server -> Python Flask,
2. Downloaded the code to my mac
3. Unzipped and created a new virtualenv with -p python3
4. pip installed the requirements.txt file
5. Ran the example using `python3 -m swagger_server`

The error was the same as previously:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/davidsanders/Downloads/python-flask-server/swagger_server/__main__.py", line 4, in <module>
    from .encoder import JSONEncoder
  File "/Users/davidsanders/Downloads/python-flask-server/swagger_server/encoder.py", line 3, in <module>
    from swagger_server.models.base_model_ import Model
  File "/Users/davidsanders/Downloads/python-flask-server/swagger_server/models/__init__.py", line 5, in <module>
    from .activities import Activities
  File "/Users/davidsanders/Downloads/python-flask-server/swagger_server/models/activities.py", line 4, in <module>
    from swagger_server.models.activity import Activity
  File "/Users/davidsanders/Downloads/python-flask-server/swagger_server/models/activity.py", line 4, in <module>
    from .base_model_ import Model
  File "/Users/davidsanders/Downloads/python-flask-server/swagger_server/models/base_model_.py", line 2, in <module>
    from typing import TypeVar, Type
`
Hope this helps

David

**Comment by dsandersAzure** [comment]
Above, I did the default example by mistake. Re-doing above with petstore_full produced the same results.

David

**Comment by cbornet** [comment]
Weird: https://docs.python.org/3.5/library/typing.html#typing.Type

**Comment by dsandersAzure** [comment]
I just checked my version of Python and it's 3.5.1. I'm looking at the docs and trying to figure out if Type[c] is new to 3.5.3 or if it was available in 3.5.1. Any ideas or is there anything I can check at my end (it could be human error :) )

**Comment by cbornet** [comment]
Indeed, the Type appeared in version 3.5.2 (https://github.com/python/cpython/blob/v3.5.2/Lib/typing.py#L23).
I can't believe they introduce API changes between patch versions !!!
Can you upgrade your python ?

**Comment by dsandersAzure** [comment]
I can. I'll run a test in Docker first though with 3.5.3 and check it works there. Thanks for helping me track this down :) 👍

**Comment by dsandersAzure** [comment]
Ok, confirmed this works with Python 3.5.3 in Docker. The Dockerfile was:

```
FROM	python:3.5.3-alpine
RUN	mkdir /swagger-demo
COPY	requirements.txt /swagger-demo/
RUN	pip install -r /swagger-demo/requirements.txt
COPY	. /swagger-demo
WORKDIR	/swagger-demo
CMD	["python","-m", "swagger_server"]
```

swagger_server/\_\_main\_\_.py changed the following lines to enable access to the Container from the host:

```
before: app.run(port=8080)
after: app.run(host="0.0.0.0", port=8080)
```

All works fine. I will upgrade my local Python to 3.5.3.

Can we put some notification or text around the version of Python required?

Cheers,


David

**Comment by cbornet** [comment]
Or just remove the method from the base class. It's overloaded in the child classes anyway.

**Comment by dsandersAzure** [comment]
Okay. I'm happy to close the issue. I'd still recommend changing the docs (or better the dialog) to state 3.5.2 as a minimum requirement, but I'm happy to close out the issue.

Thank you for the help, it is much appreciated :) .

**Comment by wing328** [comment]
@dsandersAzure we'll update the auto-generated README accordingly. Thanks for your feedback.

**Comment by wing328** [comment]
Submitted https://github.com/swagger-api/swagger-codegen/pull/4844 to improve the README

**Comment by cbornet** [comment]
The Dockerfile is a good idea btw ! I'll add a generated one asap.

**Comment by dsandersAzure** [comment]
Adding a generated Dockerfile is an *awesome* idea! +1 from me. Using Docker with alpine makes for really lightweight, easy to start, and safe samples that run on Linux, MacOS, or Windows. I love Docker because of this; being able to explore concepts that are new to me (e.g. swagger) safely and without impacting anything I'm working on. Shout if you'd like any input from me on the Docker side.

David
