### ISSUE TITLE
Trust all certs using CLI in a non produnction environment

### ISSUE THREAD

**Issue by MMirabito** [swagger-api/swagger-codegen#4872]
Dear Swagger team,

I am using swagger-codegen-cli 2.2.1 for client code. I am trying to figure out if there is a way to tell the CLI that I do not want the JVM to very SSL certificates i.e. trust all for a "non-prod" environment.

I looked for a command line argument but could not spot one. I saw a couple of similar questions but somewhat inconclusive. Does any one know how to get around this?

Here is how I am using it and below is the exception 
java -jar swagger-codegen-cli-2.2.1.jar generate -l java -o /gen/UserService/java -i https://localhost:8443/Service/api/swagger.json -v

Thanks in advance
max

` - [debugSupportingFiles] prints additional data passed to the template engine
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://localhost:8443/Service/api/swagger.json
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.
provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java
:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
        at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:129)
        at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:81)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:64)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:390)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:221)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertP
athBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
        ... 16 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to reques
`

**Comment by MMirabito** [comment]
Never mind I figure it out I was looking at the wrong source files and it's also on the FAQs. For anyone else that needs it here is how you trust all certs from he command line -Dio.swagger.parser.util.RemoteUrl.trustAll=true

max

**Comment by philipbohannon** [comment]
I have the same question for C#, does anyone know if there is a configuration for that client, or should I open a separate issue?

**Comment by ePaul** [comment]
@philipbohannon as I understand @MMirabito's post, the mentioned property is for the generator, not for the generated client.

In general, I would recommend to not trust untrusted certificates – just install the certificate if you need to use a non-public one.

**Comment by MMirabito** [comment]
@ePaul  you are right  my original question was needing to know how the CLI could trust all certs when generating client code without the hassle of installing a cert.

On separate note the APIClient created by swagger codegen for a Java  has a method "setVerifyingSsl" and if you pass false it appears to tell the JVM trust all certs but when I look at the C# client I am un able to locate a similar method/option generated by the CLI.  I think @philipbohannon  might be referring to this issue. And while I agree it's not good to trust all certs it makes it a lot easier when just testing and messing around with code.

max

**Comment by wing328** [comment]
>  when I look at the C# client I am un able to locate a similar method/option generated by the CLI

C# client uses RestSharp. Please refer to http://stackoverflow.com/a/17234955/677735 to see if the solution helps.
