### ISSUE TITLE
Error with Jersey: java.text.ParseException: Expected separator ';' instead of ','

### ISSUE THREAD

**Issue by taimuri** [swagger-api/swagger-codegen#4892]
##### Description
My content-type is defined comma separated like:

It works fine with default okhttp but if we use Jersey2 we are seeing following error:
{
	"dateLibrary": "java8",
	"library": "jersey2",
}

Exception in thread "main" java.lang.IllegalArgumentException: Error parsing media type 'application/json,application/abc.def.ghi+json,application/abc.def.ghi.v1+json'
at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:92)
at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:60)
at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179)
at javax.ws.rs.client.Entity.entity(Entity.java:100)
at com.abc.client(ApiClient.java:490)
at cms.AccessTokensApiExample.main(AccessTokensApiExample.java:26)
Caused by: java.text.ParseException: Expected separator ';' instead of ','
at org.glassfish.jersey.message.internal.HttpHeaderReader.nextSeparator(HttpHeaderReader.java:146)
at org.glassfish.jersey.message.internal.HttpHeaderReader.readParameters(HttpHeaderReader.java:306)
at org.glassfish.jersey.message.internal.HttpHeaderReader.readParameters(HttpHeaderReader.java:296)
at org.glassfish.jersey.message.internal.MediaTypeProvider.valueOf(MediaTypeProvider.java:118)
at org.glassfish.jersey.message.internal.MediaTypeProvider.fromString(MediaTypeProvider.java:90)
... 7 more
##### Swagger-codegen version

2.2.0

**Comment by taimuri** [comment]
Added step to reproduce

**Comment by BogdanH95** [comment]
Did you came to a conclusion. I'm having the same problem and I don't know what to do

**Comment by taimuri** [comment]
It didn't work, I had to use okhttp for that
