### ISSUE TITLE
"resourcePath" : "/" causes NullPointerException

### ISSUE THREAD

**Issue by burmanm** [swagger-api/swagger-codegen#495]
If the generated json has:

  "resourcePath" : "/",

the code generation fails with the following error:

java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at com.wordnik.swagger.codegen.DefaultCodegen.snakeCase(DefaultCodegen.java:315)
    at com.wordnik.swagger.codegen.DefaultCodegen.toApiVarName(DefaultCodegen.java:138)
    at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:117)
    at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)

This happens because the tag parser removes "/" and only uses "" while the snakeCase calls for charAt(0) (return Character.toLowerCase(name.charAt(0)) + name.substring(1);) which isn't there.

**Comment by fehguy** [comment]
this is fixed in develop_2.0
