### ISSUE TITLE
Unicode text show in '\uxxxx' format

### ISSUE THREAD

**Issue by InLook** [swagger-api/swagger-codegen#5229]
In mac，
i do 
brew install swagger-codegen      
swagger-codegen generate -i {url} -l retrofit -o {dir} 

Log is
main] WARN io.swagger.codegen.DefaultCodegen - Error obtaining the datatype from RefProperty:io.swagger.models.properties.RefProperty@dec188bd. Datatype default to Object
[main] ERROR io.swagger.codegen.DefaultCodegen - null
java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
	at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:805)
	at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:502)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1256)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1755)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1518)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:668)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:612)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:339)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.swagger.models.properties.RefProperty["$ref"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:647)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
	at io.swagger.util.Json.pretty(Json.java:23)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1085)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1755)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1518)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:668)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:612)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:339)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	... 13 more

**Comment by ePaul** [comment]
Could you please include your API definition file (possibly minimized down to produce this error)?

Also, is your problem the quoted exception, or the title "\uxxxx" format?

**Comment by wing328** [comment]
Closing this as there's no update.
