### ISSUE TITLE
[JAVA] [Clojure] [Python] generating from 

### ISSUE THREAD

**Issue by kenrestivo** [swagger-api/swagger-codegen#5276]
##### Description

Attempt to generate a library from the Matrix client-server API swagger spec at https://matrix.org/docs/api/client-server/json/api-docs.json

##### Swagger-codegen version

2.2.2

##### Swagger declaration file content or url

```sh
 java -jar /usr/local/lib/java/swagger-codegen-cli.jar generate -i  https://matrix.org/docs/api/client-server/json/api-docs.json -l java
```
and then tried it with -l clojure and -l python and a few others, same error.

Ran into this:
```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Room participation
  Operation: null
  Resource: post /_matrix/client/r0/user/{userId}/filter
  Definitions: {Event_1=io.swagger.models.ModelImpl@c4f58da4, pusher=io.swagger.models.ModelImpl@4e48e2a3, body=io.swagger.models.ModelImpl@bdebc4e8, ThreePidCredentials=io.swagger.models.ModelImpl@7d2fa284, Invite3pid=io.swagger.models.Mo
delImpl@f39d9ec3, UnsignedData=io.swagger.models.ModelImpl@c4cce830, Unread Notification Counts=io.swagger.models.ModelImpl@fe7aa13e, roomInfo=io.swagger.models.ModelImpl@d605b555, Result=io.swagger.models.ModelImpl@8b6bdec7, RoomInfo_1=io
.swagger.models.ModelImpl@3fceed73, DeviceInfo=io.swagger.models.ModelImpl@b9cf7433, PusherData=io.swagger.models.ModelImpl@402de5d7, body_12=io.swagger.models.ModelImpl@8f679f30, body_13=io.swagger.models.ModelImpl@6a435cee, body_10=io.sw
agger.models.ModelImpl@8349f93d, body_11=io.swagger.models.ModelImpl@ea770a5f, inline_response_429=io.swagger.models.ModelImpl@2494e701, inline_response_200_9=io.swagger.models.ModelImpl@8dc0711c, inline_response_200_22=io.swagger.models.M
odelImpl@f22c7075, inline_response_200_21=io.swagger.models.ModelImpl@ac3490e2, inline_response_200_24=io.swagger.models.ModelImpl@4c42f377, inline_response_200_23=io.swagger.models.ModelImpl@bb5dc758, inline_response_200_5=io.swagger.mode
ls.ModelImpl@4a3c7dbd, inline_response_200_6=io.swagger.models.ModelImpl@3026bfef, Categories=io.swagger.models.ModelImpl@fad5297, Signed=io.swagger.models.ModelImpl@d128443d, inline_response_200_7=io.swagger.models.ModelImpl@a9b06a00, bod
y_14=io.swagger.models.ModelImpl@e662756b, inline_response_200_20=io.swagger.models.ModelImpl@6cc079a2, inline_response_200_8=io.swagger.models.ModelImpl@9bd42dda, Groupings=io.swagger.models.ModelImpl@1dcacf93, Room Events=io.swagger.mode
ls.ModelImpl@9b1c6ebc, body_15=io.swagger.models.ModelImpl@5adf49d7, Authentication response_flows=io.swagger.models.ModelImpl@1d2616fb, ThirdPartySigned=io.swagger.models.ModelImpl@c25f42db, Categories_1=io.swagger.models.ModelImp
l@f2070389, inline_response_200_1=io.swagger.models.ModelImpl@e6e76335, inline_response_200_2=io.swagger.models.ModelImpl@d5c1ac7e, inline_response_200_3=io.swagger.models.ModelImpl@6a3ceb74, ConnectionInfo=io.swagger.models.ModelImpl@34a72832, inline_response_200_4=io.swagger.models.ModelImpl@4aa7cb47, Event Context_1=io.swagger.models.ModelImpl@2f3466bc, inline_response_200_11=io.swagger.models.ModelImpl@575feeba, inline_response_200_10=io.swagger.models.ModelImpl@f5b5931d, typingState=io.swagger.models.ModelImpl@3be49c98, Group=io.swagger.models.ModelImpl@49b6c954, inline_response_200_13=io.swagger.models.ModelImpl@d24bd1f2, inline_response_200_12=io.swagger.models.ModelImpl@1585d4d7, presenceState=io.swagger.models.ModelImpl@958f4cbd, Room Event Results=io.swagger.models.ModelImpl@f936b33, displayName=io.swagger.models.ModelImpl@e6682a1b, inline_response_200_19=io.swagger.models.ModelImpl@464a8feb, SessionInfo=io.swagger.models.ModelImpl@8a63eecd, RoomInfo=io.swagger.models.ModelImpl@cb7fccc3, inline_response_200_18=io.swagger.models.ModelImpl@34e6d7ad, inline_response_200_15=io.swagger.models.ModelImpl@749fb0a4, User Profile=io.swagger.models.ModelImpl@c0f392e4, Pusher=io.swagger.models.ModelImpl@d5dfd386, inline_response_200_14=io.swagger.models.ModelImpl@6e17e76a, inline_response_200_17=io.swagger.models.ModelImpl@3bc35bb1, inline_response_200_16=io.swagger.models.ModelImpl@24309846, body_3=io.swagger.models.ModelImpl@8a14b8c0, body_4=io.swagger.models.ModelImpl@2c8f20be, body_1=io.swagger.models.ModelImpl@df0e6790, body_2=io.swagger.models.ModelImpl@a4d8bf87, third_party_signed_1=io.swagger.models.ModelImpl@59e2909d, inline_response_200=io.swagger.models.ModelImpl@e08d9e7c, body_9=io.swagger.models.ModelImpl@3d61600b, Authentication response=io.swagger.models.ModelImpl@fcb5d181, PaginationChunk=io.swagger.models.ModelImpl@65288f6b, body_7=io.swagger.models.ModelImpl@27d99077, body_8=io.swagger.models.ModelImpl@3fa1e71f, body_5=io.swagger.models.ModelImpl@92e7c307, body_6=io.swagger.models.ModelImpl@2bc8ec3a, Invited Room=io.swagger.models.ModelImpl@51fae40c, PusherData_1=io.swagger.models.ModelImpl@ec03e559, Left Room=io.swagger.models.ModelImpl@f5e49b8d, PublicRoomsChunk=io.swagger.models.ModelImpl@97186559, Rooms=io.swagger.models.ModelImpl@cf3a235f, avatar_url=io.swagger.models.ModelImpl@89bf18d, Results=io.swagger.models.ModelImpl@dd63d746, Third party identifier=io.swagger.models.ModelImpl@c687644c, Joined Room=io.swagger.models.ModelImpl@24886e61, Event=io.swagger.models.ModelImpl@ba6e10d, StateEvent=io.swagger.models.ModelImpl@293f5d12, Event Context=io.swagger.models.ModelImpl@23b31170, ThirdPartySigned_1=io.swagger.models.ModelImpl@7e8fbd1, presence_diff=io.swagger.models.ModelImpl@77b0591, third_party_signed=io.swagger.models.ModelImpl@3d922ff, pushrule=io.swagger.models.ModelImpl@d4402706}
  Exception: null
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:827)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:730)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:356)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:666)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:234)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:41)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.DefaultCodegen.isDataTypeBinary(DefaultCodegen.java:2590)
        at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2541)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2121)
        at io.swagger.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:937)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:774)
        ... 5 more
```

It's possible that codegen could be broken, but it may be something odd with the Matrix client-server Swagger file?  Not sure.

The Swagger spec fed to codegen appears to pass swagger validation.

##### Related issues

https://github.com/matrix-org/synapse/issues/2091

##### Suggest a Fix

Kind of dead in the water here.

**Comment by ePaul** [comment]
My opinion would be, however bad a API definition is, it should not result in a NullPointerException, but in a useful error message. So this is definitively a bug in swagger-codegen.

The same happens with latest master, so it is not already fixed.

**Comment by wing328** [comment]
FYI. I also used https://editor.swagger.io to load the spec but no error/warning was reported.

**Comment by ePaul** [comment]
I minimized the Matrix API to a smaller example which also shows this problem:

```yaml
swagger: "2.0"
paths:
  /filter:
     post:
       description: does something 
       summary: Upload a new filter. 
       parameters: 
        - description: "The filter to upload." 
          in: "body"
          name: "filter"
          required: true
          schema: 
            allOf:
             - properties: {} 
               type: object
            type: object
       responses: 
         "200":
           description: "The filter was created." 
       tags:
         -  "Room participation"
 ```

**Comment by ePaul** [comment]
(The original had several properties nested inside the `allOf` object.)

**Comment by ePaul** [comment]
swagger: "2.0"
paths:
  /filter:
     post:
       description: does something 
       summary: Upload a new filter. 
       parameters: 
        - description: "The filter to upload." 
          in: "body"
          name: "filter"
          required: true
          schema: 
            properties: {} 
            type: object
       responses: 
         "200":
           description: "The filter was created." 
       tags:
         -  "Room participation"
 

So it looks like Swagger-Codegen can't work with `allOf` in the top schema of a body parameter.

Removing this single `allOf` array in "/_matrix/client/r0/user/{userId}/filter" → post → parameters[1] → schema (and simply including its single element instead) seems to let the whole API generate.

**Comment by ePaul** [comment]
I created a simple unit test reproducing this problem (1cfad7e).

What happens here is that DefaultCodegen.fromParameter gets the body parameter's schema ([line 2465](https://github.com/swagger-api/swagger-codegen/blob/55b7db34563e4b8f601a8d12637200e286687a72/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2465)), and then has special-case handling for each of ModelImpl (a "normal" object model with properties), ArrayModel and RefModel (a $ref: ...), each time setting `p.dataType`. In the case of a `ComposedModel` (which happens here) `p.dataType` is not set.

Later ([line 2548](https://github.com/swagger-api/swagger-codegen/blob/55b7db34563e4b8f601a8d12637200e286687a72/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L2548)) we call `isDataTypeBinary(p.dataType)`, which will throw the NullPointerException if `p.dataType` is null.

**Comment by ePaul** [comment]
I looks like we need a special handling for ComposedModel, too. I'm not sure how this would look like, though, so I'll not work on this.

**Comment by ensirius** [comment]
I can confirm that after updating swagger to 2.3.0 this exception was fixed for me. I had the following scheme: 

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "test MainApiVerticle option"
  },
  "host": "localhost",
  "schemes": [
    "http"
  ],
  "paths": {
    "/object/{objectParam}": {
      "get": {
        "tags": [
          "Test"
        ],
        "summary": "test generator options",
        "operationId": "dummy",
        "parameters": [
          {
            "name": "objectParam",
            "in": "body",
            "type": "object",
            "required": true
          }
        ],
        "responses": {
          "default": {
            "schema":{
              "type":"string"
            },
            "description": "OK"
          }
        }
      }
    }
  }
}
```

**Comment by kenrestivo** [comment]
It works! Thanks!

**Comment by cs94njw** [comment]
Ditto!  Now works for me on Gradle, with old .json file.
