### ISSUE TITLE
Reusable parameters can't actually be reused

### ISSUE THREAD

**Issue by rbdixon** [swagger-api/swagger-codegen#552]
I've modified the [reusableParameters.json](https://github.com/swagger-api/swagger-spec/blob/master/fixtures/v2.0/json/resources/reusableParameters.json) example from the Swagger 2.0 spec. In the example the parameters limitParam and skipParam are not actually reused. I modified the example to use them again.

When I modified the example to use these parameters by simply duplicating the /pets path as /dup_pets  I get the following failure:

```
java.lang.ClassCastException: com.wordnik.swagger.models.parameters.RefParameter cannot be cast to com.wordnik.swagger.models.parameters.BodyParameter
	at com.wordnik.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:796)
	at com.wordnik.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:688)
	at com.wordnik.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:239)
	at com.wordnik.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:220)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:108)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:99)
```
Full example: https://gist.github.com/rbdixon/21fa977e4af15e7a0da7

I'm confused since this seems to be the purpose of having parameters refs. Where am I going wrong?

**Comment by jrcamp** [comment]
I'm having the exact same problem. Best I can tell it's to the spec but the codegen is broken.

**Comment by fehguy** [comment]
This is a bug.  If you remove the first operation it works fine, I believe this is a problem in the parser project.

https://github.com/swagger-api/swagger-parser/issues/33
