### ISSUE TITLE
Java Jersey2 SDK trying to use CXF classes

### ISSUE THREAD

**Issue by cesdperez** [swagger-api/swagger-codegen#5574]
We have a Spring Boot REST API for which we generated a *Java-Jersey2* SDK using *swagger-codegen-maven-plugin* (**v 2.2.2**).

Now we have this other project where we want to use this SDK, but we also consume some other services through CXF clients.

When we call any service from our Jersey2 SDK, we are getting this:

```
Caused by: javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class com.starmount.inventory.client.model.ShipmentsDto, ContentType: application/json;charset=UTF-8
	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:439)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:390)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:326)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:314)
	at com.starmount.inventory.client.invoker.ApiClient.deserialize(ApiClient.java:561)
	at com.starmount.inventory.client.invoker.ApiClient.invokeAPI(ApiClient.java:693)
	at com.starmount.inventory.client.api.ShipmentApi.search(ShipmentApi.java:368)
```

My guess is that, being CXF and Jersey in the classpath, it's picking CXF Response implementation when it should use Jersey's.

Is there a way to handle this without migrating our SDK to CXF?

**Comment by cesdperez** [comment]
It may be related to this https://github.com/swagger-api/swagger-codegen/issues/3170, but I'm actually using v 2.2.2

**Comment by wing328** [comment]
@cesdperez what about using the default Java API client (okhttp-gson) instead of `jersey2`?

**Comment by cesdperez** [comment]
It worked flawlessly with okhttp-gson. The only downside is that it doesn't generate factory methods for Enums (`#fromValue(String value)`) that we were using, but that is just a minor detail.

Thanks for your help.
