### ISSUE TITLE
[PYTHON] Python/flask codegen naming mismatch(es)

### ISSUE THREAD

**Issue by micha-shepher** [swagger-api/swagger-codegen#5601]
##### Description

Codegen generates the some files in the swagger/models directory. They names of the files are not what the generated code import expects.
generated                      import expected
------------                     ------------------
body_1.py                      from swagger.models.body1 import Body1
body_2.py                      from swagger.models.body2 import Body2
body_3.py                      from swagger.models.body3 import Body3
body_4.py                      from swagger.models.body4 import Body4
body_5.py                      from swagger.models.body5 import Body5
inline_response_200.py  from swagger.models.inline_response200 import ...
inline_response_200_1.py  from swagger.models.inline_response2001 import ...
inline_response_200_2.py  from swagger.models.inline_response2002 import ...
inline_response_200_3.py  from swagger.models.inline_response2003 import ...

##### Swagger-codegen version

hard to tell, I generated the code using the path
http://editor.swagger.io/#/

##### Swagger declaration file content or url

the petshop example

##### Command line used for generation

Us

##### Steps to reproduce

$ python -m venv myexample
$ source venv/bin/activate
$ cd swagger
$ pip install -r requirements.txt
$ python -m swagger_server

Failed to add operation for POST /v2/pet
Traceback (most recent call last):
  File "C:\Users\micha\swagger\lib\site-packages\connexion\api.py", line 237, in add_path                                                                                                                         s
    self.add_operation(method, path, endpoint, path_parameters)
  File "C:\Users\micha\swagger\lib\site-packages\connexion\api.py", line 189, in add_oper                                                                                                                         ation
    resolver=self.resolver)
  File "C:\Users\micha\swagger\lib\site-packages\connexion\operation.py", line 179, in __                                                                                                                         init__
    resolution = resolver.resolve(self)
  File "C:\Users\micha\swagger\lib\site-packages\connexion\resolver.py", line 39, in reso                                                                                                                         lve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id                                                                                                                         )
  File "C:\Users\micha\swagger\lib\site-packages\connexion\resolver.py", line 65, in reso                                                                                                                         lve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "swagger_s                                                                                                                         erver.controllers.pet_controller.add_pet"!>

ed online editor.

**Comment by luizcarlospedrosogomes** [comment]
help!!!!!!!!!!!!!!

**Comment by arnaudmiribel** [comment]
Same here !

I used *Brew* to download `swagger-codegen`. Version 2.2.2

**Comment by wing328** [comment]
Hi all, I believe the issue has been addressed in the latest master. Would you please pull the latest and build the JAR locally (or use docker image instead)?

**Comment by wing328** [comment]
Please try the latest stable release 2.2.3 and let us know if it's still an issue.
