### ISSUE TITLE
Which client language support XML payload (response)? 

### ISSUE THREAD

**Issue by FerrariAlberto** [swagger-api/swagger-codegen#5646]
As the title say Which client language support XML payload (response)?  i'm trying with the java client but i'm getting 
```
io.swagger.client.ApiException: Content type "application/xml" is not supported for type: class io.swagger.client.model.Collection
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:850)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:1045)
	at io.swagger.client.ApiClient.execute(ApiClient.java:972)
	at io.swagger.client.api.CatalogApi.restfulShoppingTagsGetWithHttpInfo(CatalogApi.java:304)
	at io.swagger.client.api.CatalogApi.restfulShoppingTagsGet(CatalogApi.java:289)
	at io.swagger.client.api.TestCall.main(TestCall.java:29)
```

**Comment by FerrariAlberto** [comment]
how can i work around it?

**Comment by wing328** [comment]
@FerrariAlberto For Java, would the following discussion help?

https://github.com/swagger-api/swagger-codegen/issues/3870

**Comment by FerrariAlberto** [comment]
@wing328 thanks for the reply, 
I had already seen that discussion, i've tried a similar fix but couldn't make it work

**Comment by wing328** [comment]
@FerrariAlberto what error did you get? and which Java API client (e.g. jersey2, retrofit) did you use? The default is `okhttp-gson`

**Comment by nalmeida84** [comment]
I'm using resteasy client and I have the same question about... It appears that the only client that support xml payload is the resttemplate. There is any way to use jersey, okhttp or resteasy client with xml responses? Thanks you!

**Comment by wing328** [comment]
@nalmeida84 we definitely welcome contribution to add XML support for other Java API clients (e.g. resteasy, etc)

Let me know if you've time to contribute the enhancement and I'll show you some good starting points.

**Comment by nalmeida84** [comment]
Yes, why not... I'll be on holidays until the beginning of the year but I can take a look.

**Comment by wing328** [comment]
@nalmeida84 the following PRs are good starting points:
- https://github.com/swagger-api/swagger-codegen/pull/5962
- https://github.com/swagger-api/swagger-codegen/pull/6150

Let me know if you've any question or need any help (e.g. testing).

Enjoy your vacation!
