### ISSUE TITLE
got error as parsing json

### ISSUE THREAD

**Issue by zzsoszz** [swagger-api/swagger-codegen#5708]
package io.swagger.client;

import java.io.File;

import java.io.IOException;
import java.nio.charset.Charset;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

import org.apache.commons.io.FileUtils;

import com.google.gson.reflect.TypeToken;

import android.app.Activity;
import io.swagger.client.api.UserApi;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;

public class Main {
	
	public static void main(String[] args) throws TimeoutException, ExecutionException, InterruptedException, ApiException, IOException {
//		UserApi api=new UserApi();
//		api.loginUser("13730666347","123456");
		String project=System.getProperty("user.dir");
		System.out.println(project);
		//aaa= new TypeToken<InlineResponse2001>(){}.getType();
		String json = FileUtils.readFileToString(new File("D:\\bxdev\\aliyun\\cloudbuy\\doc\\gen\\android\\src\\main\\java\\data.json"),Charset.forName("GBK"));
		System.out.println(json);
		InlineResponse2001 object = JsonUtil.deserializeToObject(json,InlineResponse200.class);
		System.out.println(object);
	}
	
}

{"total":1,"data":[{"id":33,"activityNumber":null,"winNumber":"111122223333","winuser":{"id":33,"userName":"qingtian","nickName":null,"email":null,"password":"123456","phone":"13730666347","userStatus":null,"level":"1"},"orders":[{"id":33,"orderActivity":[],"totalPrice":null,"status":"1","complete":true,"createBy":null}],"product":{"id":65,"name":"OPPO R9s Plus","introduction":"\n6.0英寸大屏，前后1600万像素，光学防抖！这一刻，更清晰！\n(颜色随机)Android 6.0系统，骁龙653处理器,本产品按照获得顺序和填写地址顺序发货哦~!","shortIntroduction":"6GB+64GB内存版 全网通4G手机 双卡双待 金色","detailUrl":"https://item.jd.com/4143446.html","price":3499,"priceType":"1","limitFlag":0,"limitMax":100,"total":35,"largePhotoUrls":"","photoUrls":"https://m.360buyimg.com/n12/jfs/t3982/272/122877612/84922/90018ce0/583d461fNc90d345f.jpg!q70.jpg;https://m.360buyimg.com/n12/jfs/t3565/80/2111927493/59996/3c417f/583d4625N40e85f59.jpg!q70.jpg;https://m.360buyimg.com/n12/jfs/t3952/281/108638797/47113/7a02ecea/583d4629N4cf4970d.jpg!q70.jpg;https://m.360buyimg.com/n12/jfs/t3310/201/2005678460/28838/a8e99bd8/583d462dNae5c8b65.jpg!q70.jpg;https://m.360buyimg.com/n12/jfs/t3871/70/74635942/54915/5037a87c/583d4636Nc1671f2b.jpg!q70.jpg","article":{"id":33,"name":"iphone7","richText":"新世纪电脑一层新"},"catagory":{"id":34,"name":"手机"},"tags":[]},"status":"1","avaliable":100,"begintime":"2017-05-26T01:57:17.159Z","endtime":"2017-05-26T01:57:17.159Z"}]}

Exception in thread "main" java.lang.NumberFormatException: For input string: "2017-05-26T01:57:17.159Z"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.google.gson.JsonPrimitive.getAsLong(JsonPrimitive.java:238)
	at io.swagger.client.JsonUtil$1.deserialize(JsonUtil.java:36)
	at io.swagger.client.JsonUtil$1.deserialize(JsonUtil.java:1)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at io.swagger.client.JsonUtil.deserializeToObject(JsonUtil.java:54)
	at io.swagger.client.Main.main(Main.java:29)

**Comment by wing328** [comment]
It looks to me the error is due to your spec not correctly describing the response model.
