### ISSUE TITLE
[Kotlin] Improve client generator functionality

### ISSUE THREAD

**Issue by jimschubert** [swagger-api/swagger-codegen#5730]
##### Description

This is a tracking issue for adding functionality to the Kotlin client generator.

- [ ] Support "default" responses. Currently 200 OK isn't handled, for example, in `PetApi#addPet`.
- [ ] Support enum type generation
- [ ] Support inline/embedded enums
- [ ] Support `collectionFormat` (multi)
- [ ] Test/Implement arrays of maps, arrays, objects
- [ ] Test/Implement maps of arrays/maps, objects
- [ ] Support allOf via composition
- [ ] Support allOf via inheritance
- [ ] (optional?) Per-request modification of headers,authorization
  - NOTE: ApiClient.defaultHeaders can be modified *once* to globally set headers for auth, user-agent, etc.
  - [ ] Test, or better implement basic auth support
   - [ ] Test, or better implement OAuth support
  - [ ] Test, or better implement apiKey auth
- [ ] Generate Api tests
- [ ] Generate Model tests
- [ ] Generate Api docs
- [ ] Generate Model docs
- [ ] Update README.md to be more project-specific rather than generic information about the generator/template

##### Related issues

* #5071

**Comment by ALander26** [comment]
+1 set defaultHeaders

**Comment by onionhammer** [comment]
Any plans for using [async](https://github.com/codepath/android_guides/wiki/Using-OkHttp#asynchronous-network-calls) ?

**Comment by olegivo** [comment]
> Add support for Retrofit library

+1

**Comment by 8secz-johndpope** [comment]
supposedly this branch has successfully spat out kotlin + retrofit 
https://github.com/kroegerama/kotlin-retrofit-generated/blob/master/petstore/src/main/java/com/kroegerama/petstore/RetrofitHolder.kt

using this branch https://github.com/kroegerama/openapi-generator/tree/kotlin-retrofit
@kroegerama


```shell
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate  \
   -i openapi.json \
   -g kotlin  --library=retrofit \
   -o kotlin_client
Exception in thread "main" java.lang.RuntimeException: Unknown library: retrofit
Available libraries:
  NONE
	at org.openapitools.codegen.DefaultCodegen.setLibrary(DefaultCodegen.java:3802)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:566)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:395)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)

```

but I'm not clear which parameters were invoked to get retrofit library working.

**Comment by coder82** [comment]
Has basic authentication for Kotlin been implemented for the generated clients?

**Comment by coder82** [comment]
For those coming after this, I made my kotlin client authenticate adding an interceptor globally:
```
        ApiClient.builder.addInterceptor {
            val request = it.request()
            val authenticatedRequest = request
                .newBuilder()
                .header("Authorization", Credentials.basic(user, pass)).build()
            it.proceed(authenticatedRequest)
        }
```

**Comment by EndermanAPM** [comment]
Any ETA on oauth implementation? (if planned)

**Comment by ogjtech** [comment]
@jimschubert @wing328 is this issue still active/maintained? As far as I can tell this is the only point of reference for checking the progress made on the generator (if there is another, do please reply with a link). My project at work depends on this generator, and would like to keep updated on any improvements made.
