### ISSUE TITLE
Wrong path for es6 template

### ISSUE THREAD

**Issue by oshirohugo** [swagger-api/swagger-codegen#5903]
##### Description

When trying to use -DuseES6 to generate javascript ES6 client, I got the following error:

```
[main] ERROR io.swagger.codegen.AbstractGenerator - Javascript-es6/model.mustache (No such file or directory)
[main] ERROR io.swagger.codegen.AbstractGenerator - can't load template Javascript-es6/model.mustache
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'ApiResponse'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:374)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:697)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:244)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:43)
Caused by: java.lang.RuntimeException: can't load template Javascript-es6/model.mustache
        at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:51)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:713)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:361)
        ... 3 more
```

##### Swagger-codegen version

jar built from master

##### Swagger declaration file content or url

http://petstore.swagger.io/v2/swagger.json

##### Command line used for generation

`./run-in-docker.sh mvn package`

##### Steps to reproduce

`./run-in-docker.sh generate -i http://petstore.swagger.io/v2/swagger.json -l javascript -o gen/api-client-sample-2 -DuseES6=true -DusePromises=true
`
##### Suggest a Fix

 On file `modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavascriptClientCodegen.javafile` line 434:

`embeddedTemplateDir = templateDir = "Javascript-es6";`

should be replaced by:
`embeddedTemplateDir = templateDir = "Javascript/es6";`

**Comment by wing328** [comment]
@oshirohugo Thanks for the fix. The CI should have caught it but it didn't due to a typo in the shell script for generating JS Petstore client (ES6). I'll fix that in another PR.
