### ISSUE TITLE
[Python] Controller generation dependent on matching API tag

### ISSUE THREAD

**Issue by cbwest3** [swagger-api/swagger-codegen#6065]
##### Description

Python controller generation using `x-swagger-router-controller: packageName.controllers.foobar_controller` is dependant on having a `foobar` tag in the swagger API.  If the `foobar` tag does not exist in the swagger API, the following error below generated when trying to execute the generated module.

I expected a new controller to be created for each new `x-swagger-router-controller` attribute, regardless of tags.  I was unable to find any documentation that speaks to this caveat.

```
# java -jar swagger-codegen-cli.jar generate \
		-i swagger.yaml \
		-c config.json \
		-DdebugSwagger=true \
		-DdebugModels=true \
		-DdebugOperations=true \
		-DdebugSupportingFiles=true \
		-l python-flask
  ...command completes successfully, output omitted
# sudo pip3.5 install -r requirements.txt
  ...command completes successfully, output omitted
# python3.5 -m packageName
Failed to add operation for GET /api/v1/endpoint
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/connexion/apis/abstract.py", line 262, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "//anaconda/lib/python3.5/site-packages/connexion/apis/abstract.py", line 215, in add_operation
    pythonic_params=self.pythonic_params)
  File "//anaconda/lib/python3.5/site-packages/connexion/operation.py", line 215, in __init__
    resolution = resolver.resolve(self)
  File "//anaconda/lib/python3.5/site-packages/connexion/resolver.py", line 39, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "//anaconda/lib/python3.5/site-packages/connexion/resolver.py", line 66, in resolve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "packageName.controllers.foobar_controller.endpoint_get"! Import error was 'No module named 'packageName.controllers.foobar_controller''>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "//anaconda/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/samiam/packageName/packageName/__main__.py", line 10, in <module>
    app.add_api('swagger.yaml', arguments={'title': 'API description.'})
  File "//anaconda/lib/python3.5/site-packages/connexion/apps/flask_app.py", line 73, in add_api
    resolver=resolver, resolver_error=resolver_error, pythonic_params=pythonic_params
  File "//anaconda/lib/python3.5/site-packages/connexion/apps/abstract.py", line 168, in add_api
    pythonic_params=pythonic_params)
  File "//anaconda/lib/python3.5/site-packages/connexion/apis/flask_api.py", line 61, in __init__
    pythonic_params=pythonic_params
  File "//anaconda/lib/python3.5/site-packages/connexion/apis/abstract.py", line 152, in __init__
    self.add_paths()
  File "//anaconda/lib/python3.5/site-packages/connexion/apis/abstract.py", line 272, in add_paths
    self._handle_add_operation_error(path, method, exc_info)
  File "//anaconda/lib/python3.5/site-packages/connexion/apis/abstract.py", line 286, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "//anaconda/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "//anaconda/lib/python3.5/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "//anaconda/lib/python3.5/site-packages/connexion/utils.py", line 39, in get_function_from_name
    raise last_import_error
  File "//anaconda/lib/python3.5/site-packages/connexion/utils.py", line 27, in get_function_from_name
    module = importlib.import_module(module_name)
  File "//anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'packageName.controllers.foobar_controller'
```

##### Swagger-codegen version

Tested with swagger-codegen-cli-2.3.0-20170713.173236-24.jar.

##### Suggest a fix/enhancement

1. Create a new controller for each unique `x-swagger-router-controller` attribute.
2. Update the documentation to reflect generated code.

**Comment by wing328** [comment]
@cbwest3 is it correct to say that [Flask Petstore](https://github.com/swagger-api/swagger-codegen/tree/master/samples/server/petstore/flaskConnexion) already has the issues you reported above?

**Comment by wing328** [comment]
@cbwest3 let us know if you still need help on this. Closing it for the time being.
