### ISSUE TITLE
Two resourcepaths with one HTTP verb (e.g. GET) cause StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jfiala** [swagger-api/swagger-codegen#613]
swagger-codegen-2.1.2-M1:

This API-doc with two different paths (search / search2) with HTTP GET

```
{
  "apiVersion": "1.0",
  "apis": [
    {
      "description": "searchUsers",
      "operations": [
        {
          "method": "GET",
          "summary": "search for users by name-part",
          "notes": "search for users",
          "nickname": "searchUsers",
          "produces": [
            "*/*"
          ],
          "consumes": [
            "application/json"
          ],
          "parameters": [
            {
              "allowMultiple": false,
              "defaultValue": "",
              "description": "query",
              "name": "query",
              "paramType": "query",
              "type": "string",
              "required": true
            }
          ],
          "responseMessages": [
            {
              "code": 200,
              "message": "Successful retrieval of user list",
              "responseModel": "array"
            },
            {
              "code": 404,
              "message": "User not found",
              "responseModel": "Void"
            }
          ],
          "deprecated": "false",
          "items": {
            "type": "User"
          },
          "type": "array",
          "uniqueItems": false
        }
      ],
      "path": "/search"
    },
    {
      "description": "searchUsers2",
      "operations": [
        {
          "method": "GET",
          "summary": "search for users by name-part2",
          "notes": "search for users2",
          "nickname": "searchUsers2",
          "produces": [
            "*/*"
          ],
          "consumes": [
            "application/json"
          ],
          "parameters": [
            {
              "allowMultiple": false,
              "defaultValue": "",
              "description": "query",
              "name": "query",
              "paramType": "query",
              "type": "string",
              "required": true
            }
          ],
          "responseMessages": [
            {
              "code": 200,
              "message": "Successful retrieval of user list",
              "responseModel": "array"
            },
            {
              "code": 404,
              "message": "User not found",
              "responseModel": "Void"
            }
          ],
          "deprecated": "false",
          "items": {
            "type": "User"
          },
          "type": "array",
          "uniqueItems": false
        }
      ],
      "path": "/search2"
    }
  ],
  "basePath": "/",
  "consumes": [
    "application/json"
  ],
  "models": {
    "User": {
      "description": "",
      "id": "User",
      "properties": {
        "id": {
          "description": "ID of the user",
          "required": true,
          "format": "int64",
          "type": "integer"
        },
        "bytes": {
          "items": {
            "format": "byte",
            "type": "string"
          },
          "required": false,
          "type": "array"
        },
        "name": {
          "description": "Name of the user",
          "required": true,
          "type": "string"
        },
        "attributeWithoutDocs": {
          "required": false,
          "type": "string"
        }
      }
    }
  },
  "produces": [
    "*/*"
  ],
  "resourcePath": "/",
  "swaggerVersion": "1.2"
}
```
cause the following exception with Swagger-Codegen:

``` Java
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(Unknown Source)
	at com.wordnik.swagger.codegen.DefaultCodegen.snakeCase(DefaultCodegen.java:315)
	at com.wordnik.swagger.codegen.languages.JavaClientCodegen.snakeCase(JavaClientCodegen.java)
	at com.wordnik.swagger.codegen.DefaultCodegen.toApiVarName(DefaultCodegen.java:138)
	at com.wordnik.swagger.codegen.languages.JavaClientCodegen.toApiVarName(JavaClientCodegen.java)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:117)
	at com.wordnik.swagger.codegen.Codegen.generate(Codegen.java)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:107)
```

In Codegen line 132:
 Map<String, List<CodegenOperation>> paths = processPaths(swagger.getPaths());
      for(String tag : paths.keySet()) {
    	  System.out.println("tag: " + tag);

The tag is indicated empty ("") during generating the SearchApi, although it is populated in the api-doc.

**Comment by jfiala** [comment]
The same error occurs with a Swagger 2.0 api-doc (generated also using Spring-Mvc-Swagger):

```
{"swagger":"2.0","info":{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":{"name":"Contact Email"},"license":{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"}},"host":"localhost:8080","basePath":"/","tags":[{"name":"search-services"},{"name":"user-crud-responseentity"},{"name":"user-crud"},{"name":"basic-error-controller"}],"paths":{"/error":{"get":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"post":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"put":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"delete":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"options":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"patch":{"tags":["basic-error-controller"],"summary":"error","description":"error","operationId":"error","consumes":["application/json"],"produces":["*/*"],"responses":{"204":{"description":"No Content"},"200":{"description":"OK","schema":{"type":"object","additionalProperties":{"type":"object"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/search":{"get":{"tags":["search-services"],"summary":"search for users by name-part","description":"search for users","operationId":"searchUsers","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"query","in":"query","description":"query","required":true,"type":"string"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"array","items":{"$ref":"#/definitions/User"}}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/user":{"get":{"tags":["user-crud"],"summary":"read User by ID","description":"pass ID to read user","operationId":"getUser","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"$ref":"#/definitions/User"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}},"post":{"tags":["user-crud"],"summary":"create or update a user name by id","description":"saveUser","operationId":"saveUser","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"},{"name":"name","in":"query","description":"name","required":true,"type":"string"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"$ref":"#/definitions/User"}},"201":{"description":"Created"},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"}}}},"/user_with_responseentity":{"get":{"tags":["user-crud-responseentity"],"summary":"getUserResponseEntity","description":"getUserResponseEntity","operationId":"getUserResponseEntity","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"id","in":"query","description":"id","required":true,"type":"integer","format":"int64"}],"responses":{"404":{"description":"Not Found"},"200":{"description":"OK","schema":{"type":"object"}},"401":{"description":"Unauthorized"},"403":{"description":"Forbidden"},"500":{"description":"Unexpected Error"}}}}},"definitions":{"User":{"required":["id","name"],"properties":{"bytes":{"type":"array","items":{"type":"string","format":"byte"}},"id":{"type":"integer","format":"int64","description":"ID of the user"},"name":{"type":"string","description":"Name of the user"},"state":{"type":"string","enum":["ACTIVE","DISABLED"]}},"description":"User object"},"View":{"properties":{"contentType":{"type":"string"}}},"ModelAndView":{"properties":{"empty":{"type":"boolean"},"model":{"type":"object"},"modelMap":{"type":"object","additionalProperties":{"type":"object"}},"reference":{"type":"boolean"},"view":{"$ref":"#/definitions/View"},"viewName":{"type":"string"}}}}}
```

``` java
 /**
   * error
   * error
   * @return Map<String, Object>
   */
  public Map<String, Object> error () throws ApiException {
...
 String response = apiInvoker.invokeAPI(basePath, path, "GET", queryParams, postBody, headerParams, formParams, contentType);
....

 /**
   * error
   * error
   * @return Map<String, Object>
   */
  public Map<String, Object> error () throws ApiException {
    String response = apiInvoker.invokeAPI(basePath, path, "PUT", queryParams, postBody, headerParams, formParams, contentType);

```

**Comment by fehguy** [comment]
I can't reproduce this when using the develop_2.0 branch.  Can you please retest?

**Comment by jfiala** [comment]
I verified with develop_2.0 branch.
Using this, an api-docs with two GET-paths will be silently not generated without any complaints.

api-docs for http://localhost:8080/api-docs/default/user-codegen-two-get-paths
```
{"apiVersion":"1.0","apis":[{"description":"getUser","operations":[{"method":"GET","summary":"read User by ID","notes":"pass ID to read user","nickname":"getUser","produces":["*/*"],"consumes":["application/json"],"parameters":[{"allowMultiple":false,"defaultValue":"","description":"id","name":"id","paramType":"query","format":"int64","type":"integer","required":true}],"responseMessages":[{"code":200,"message":"Successful retrieval of user detail","responseModel":"User"},{"code":404,"message":"User not found","responseModel":"Void"}],"deprecated":"false","type":"User"}],"path":"/user_get1_read"},{"description":"searchUsers","operations":[{"method":"GET","summary":"search for users by name-part","notes":"search for users","nickname":"searchUsers","produces":["*/*"],"consumes":["application/json"],"parameters":[{"allowMultiple":false,"defaultValue":"","description":"query","name":"query","paramType":"query","type":"string","required":true}],"responseMessages":[{"code":200,"message":"Successful retrieval of user list","responseModel":"array"}],"deprecated":"false","items":{"type":"User"},"type":"array","uniqueItems":false}],"path":"/user_get2_search"}],"basePath":"/","consumes":["application/json"],"models":{"User":{"description":"User object","id":"User","properties":{"id":{"description":"ID of the user","required":true,"format":"int64","type":"integer"},"bytes":{"items":{"format":"byte","type":"string"},"required":false,"type":"array"},"name":{"description":"Name of the user","required":true,"type":"string"},"state":{"enum":["ACTIVE","DISABLED"],"required":false,"type":"User"}}}},"produces":["*/*"],"resourcePath":"/","swaggerVersion":"1.2"}
```

https://github.com/jfiala/swagger-spring-demo/commit/d081190a0bb640dfce6e34c342ccfbd77f0b92b4

**Comment by wing328** [comment]
@jfiala would you please test with the latest develop_2.0 and let us know if the issue persists ?

**Comment by jfiala** [comment]
Successfully verified - there is no exception and both resource-paths are working.
