### ISSUE TITLE
codegen 3.0.0 fails to parse simple schema

### ISSUE THREAD

**Issue by bentheadset** [swagger-api/swagger-codegen#6332]
##### Description

I have a simple swagger spec, which I believe is correct 3.0.0 syntax, which fails to parse with the 3.0.0 generator.  The error is `missing swagger input or config!` and it appears the codegen may be using 2.0 syntax (?) from the message `INFO io.swagger.parser.Swagger20Parser - reading from /input/api.openapi3.json`.

I've bugjar'd this into a trivial example [api_v3.json.txt](https://github.com/swagger-api/swagger-codegen/files/1231402/api_v3.json.txt)  (fails with same error as my larger spec)  and tried both hand-writing it, as well as attempting to convert my (working) 2.0 spec using the `swagger2openapi` tool, and double-checking the json with  `jsonlint-py`.  I also pushed a trivial Docker image/Dockerfile to dockerhub so that my environment is reproducible for you (it just pulls your 3.0.0 generator binaries from `sonatype.org`, see below)

thank you for your help!

```
+ docker run --rm --user 1000 --volume /mydir/generated:/output:rw --volume /mydir/input:/input:ro bentheadset/bentheadset-swagger-codegen-3.0.0  generate --input-spec /input/api.openapi3.json --lang python-flask --output /output --verbose
[main] INFO io.swagger.codegen.config.CodegenConfigurator - 
VERBOSE MODE: ON. Additional debug options are injected
 - [debugSwagger] prints the swagger specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
[main] INFO io.swagger.parser.Swagger20Parser - reading from /input/api.openapi3.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /input/api.openapi3.json
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:685)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```
##### Swagger-codegen version

3.0.0

##### Swagger declaration file content or url

This simplified spec just defines a single endpoint, a GET, which should return/respond a simple class as a json dict.

[api_v3.json.txt](https://github.com/swagger-api/swagger-codegen/files/1231402/api_v3.json.txt)
```json
{ 
  "components" : { "schemas" : { "HealthInfo" : { 
              "properties" : { 
                  "other_health" : { 
                      "description" : "misc stuff",
                      "type" : "string"
                    },
                  "system_up" : { 
                      "description" : "is the system up and ready for requests, or in an error state",
                      "type" : "boolean"
                    }
                },
              "required" : [ "system_up" ],
              "type" : "object"
            } } },
  "externalDocs" : { 
      "description" : "some description",
      "url" : "https://foo.com"
    },
  "info" : { 
      "contact" : { "email" : "foo@bar.com" },
      "description" : "some descriptions",
      "license" : { "name" : "foobar" },
      "termsOfService" : "https://none.com",
      "title" : "openapi 3.0.0 bugjar",
      "version" : "1.0.0"
    },
  "openapi" : "3.0.0",
  "paths" : { "/debug/healthCheck" : { "get" : { 
              "description" : "internal use, returns information about the running system",
              "operationId" : "debugHealthCheck",
              "responses" : { "200" : { 
                      "content" : { "application/json" : { "schema" : { "$ref" : "#/components/schemas/HealthInfo" } } },
                      "description" : "successful retreival of health-check"
                    } },
              "summary" : "allows read access to internal state",
              "tags" : [ "debug" ]
            } } },
  "servers" : [ { 
        "description" : "a local run",
        "url" : "http://localhost:{port}",
        "variables" : { "port" : { "default" : "8080" } }
      } ],
  "tags" : [ { 
        "description" : "debug utilities",
        "name" : "debug"
      } ]
}
```
##### Command line used for generation

I wrapped the published 3.0.0 binaries in a trivial dockerfile, which you run directly, or view the Dockerfile at these links:

- https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/
- `docker run bentheadset/bentheadset-swagger-codegen-3.0.0`
- https://hub.docker.com/r/bentheadset/bentheadset-swagger-codegen-3.0.0/~/dockerfile/
    -- just wget's your published 3.0.0 build, and executes it with no add'l params.
   

```
mkdir generated
mkdir input
# put schema file in ./input/$SCHEMA_FILENAME
docker run                               \
--rm                                               \
--user $(id -u $USER)                      \
--volume $(pwd)/generated:/output:rw         \
--volume $(pwd)/input:/input:ro              \
bentheadset/bentheadset-swagger-codegen-3.0.0   \
generate                        \
--input-spec /input/$SCHEMA_FILENAME                 \
--lang python-flask                                \
--output /output                                   \
--verbose
```
##### Steps to reproduce

attempt to run the generator on the above spec.

From the output it appears to me that the issue is in parsing the spec, not the generation.  If it matters, as you can see above, i'm trying to generate python/flask.

**Comment by FarooqKhan** [comment]
I have same issue, I even tried compiling the codegen repo and use the cli from there no success

**Comment by voidfiles** [comment]
If I'm not mistaken 3.0.0 parsing [shipped in 2.0.0-rc0](https://github.com/swagger-api/swagger-parser/releases)

But if you look here its still pointing at an older version of that package

https://github.com/swagger-api/swagger-codegen/blob/3.0.0/pom.xml#L917

I tried manually bumping that and got this

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ............................ SUCCESS [01:06 min]
[INFO] swagger-codegen (core library) ..................... FAILURE [ 56.017 s]
[INFO] swagger-codegen (executable) ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:15 min
[INFO] Finished at: 2017-09-02T04:54:17+00:00
[INFO] Final Memory: 22M/193M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project swagger-codegen: Could not resolve dependencies for project io.swagger:swagger-codegen:jar:2.3.0-SNAPSHOT: Could not find artifact io.swagger:swagger-compat-spec-parser:jar:2.0.0-rc0 in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :swagger-codegen
The command '/bin/sh -c mvn -am -pl "modules/swagger-codegen-cli" package' returned a non-zero code: 1
```

I'm not a Java dev so that's sort of where I get stuck

**Comment by marcoreni** [comment]
@voidfiles https://github.com/swagger-api/swagger-codegen/pull/6386#issuecomment-325206706

**Comment by MikeRalphson** [comment]
Please see #7003 for an experimental implementation of the generator engine in Node.js which supports OpenAPI 3.0

**Comment by HugoMario** [comment]
@bentheadset there is a `swagger-codegen` implementation that supports `2.0` and `3.0.0` syntax. 
When you have a chance, can you please try it checking out to branch `3.0.0` of `swagger-codegen`?
