### ISSUE TITLE
missing swagger input or config

### ISSUE THREAD

**Issue by chaoshen1024** [swagger-api/swagger-codegen#6442]
##### Description
 io.swagger.parser.Swagger20Parser can not parse "openapi"

##### Swagger-codegen version
3.0.0-SNAPSHOT

**Comment by dariota** [comment]
Please provide more information about what exactly you're trying to do, such as the exact command you're running.

**Comment by chaoshen1024** [comment]
# command
java -jar swagger-codegen-cli-3.0.0-20170904.171256-3.jar generate -l spring -c config.json -i swagger.yaml -o E:\Swagger\demo
# config.json
{
  "sortParamsByRequiredFlag": true,
  "ensureUniqueParams": true,
  "allowUnicodeIdentifiers": false,
  "modelPackage": "com.xxx.xxx.api.open.dto",
  "apiPackage": "com.xxx.xxx.api.open.api",
  "invokerPackage": "com.xxx.xxx.api.open.invoker",
  "groupId": "com.xxx.xxx",
  "artifactId": "api",
  "artifactVersion": "0.0.1",
  "artifactUrl": "",
  "artifactDescription": "",
  "scmConnection": "",
  "scmDeveloperConnection": "",
  "scmUrl": "",
  "developerName": "xxxx",
  "developerEmail": "xxxx@xxxx.com",
  "developerOrganization": "xxxx",
  "developerOrganizationUrl": "http://www.xxxx.com",
  "licenseName": "Apache 2.0",
  "licenseUrl": "http://www.apache.org/licenses/LICENSE-2.0.html",
  "sourceFolder": "src/main/java",
  "localVariablePrefix": "",
  "serializableModel": true,
  "bigDecimalAsString": false,
  "fullJavaUtil": false,
  "hideGenerationTimestamp": true,
  "withXml": false,
  "dateLibrary": "java8",
  "java8": true,
  "title": "xxxx",
  "configPackage": "com.xxx.xxx.api.open.config",
  "basePackage": "com.xxx.xxx.api.open",
  "interfaceOnly": false,
  "delegatePattern": false,
  "singleContentTypes": false,
  "async": false,
  "responseWrapper": "",
  "useTags": false,
  "useBeanValidation": true,
  "implicitHeaders": false,
  "swaggerDocketConfig": true,
  "useOptional": true,
  "library": "spring-boot"
}
# swagger.yaml
openapi: 3.0.0
info:
  title: demo
  description: demo
  version:0.0.1
  termsOfService: 'http://www.xxxx.com'
  contact:
    email: xxxx@xxxx.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://xxxx.xxxx.com'
    description: The url of xxxx
tags:
  - name: Account
    description: Account Info
paths:
  /account/openAccount:
    post:
      tags:
        - Account
      summary: openAccount
      description: openAccount
      operationId: openAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInfoDTO'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultDTO'
components:
  schemas:
    RequestBaseDTO:
      type: object
      properties:
        systemId:
          type: string
          description: System ID
        requestSeq:
          type: string
          description: Request Sequence
        requestTime:
          type: string
          format: date-time
          description: Request Time
      required:
        - systemId
        - requestSeq
        - requestTime
    AccountInfoDTO:
      allOf:
        - $ref: '#/components/schemas/RequestBaseDTO'
        - type: object
          properties:
            username:
              type: string
              description: username
            sex:
              type: string
              description: sex
    ResultDTO:
      type: object
      properties:
        success:
          type: boolean
          description: Is Success?
        errcode:
          type: string
          description: Error Code
        errmsg:
          type: string
          description: Error Message
        data:
          type: string
          description: accountId

**Comment by dariota** [comment]
Sorry, that yaml's a bit broken. Could you send it again in `code formatting`?

**Comment by chaoshen1024** [comment]
# command
java -jar swagger-codegen-cli-3.0.0-20170904.171256-3.jar generate -l spring -c config.json -i swagger.yaml -o E:\Swagger\demo
# config.json
    {
      "sortParamsByRequiredFlag": true,
      "ensureUniqueParams": true,
      "allowUnicodeIdentifiers": false,
      "modelPackage": "com.xxx.xxx.api.open.dto",
      "apiPackage": "com.xxx.xxx.api.open.api",
      "invokerPackage": "com.xxx.xxx.api.open.invoker",
      "groupId": "com.xxx.xxx",
      "artifactId": "api",
      "artifactVersion": "0.0.1",
      "artifactUrl": "",
      "artifactDescription": "",
      "scmConnection": "",
      "scmDeveloperConnection": "",
      "scmUrl": "",
      "developerName": "xxxx",
      "developerEmail": "xxxx@xxxx.com",
      "developerOrganization": "xxxx",
      "developerOrganizationUrl": "http://www.xxxx.com",
      "licenseName": "Apache 2.0",
      "licenseUrl": "http://www.apache.org/licenses/LICENSE-2.0.html",
      "sourceFolder": "src/main/java",
      "localVariablePrefix": "",
      "serializableModel": true,
      "bigDecimalAsString": false,
      "fullJavaUtil": false,
      "hideGenerationTimestamp": true,
      "withXml": false,
      "dateLibrary": "java8",
      "java8": true,
      "title": "xxxx",
      "configPackage": "com.xxx.xxx.api.open.config",
      "basePackage": "com.xxx.xxx.api.open",
      "interfaceOnly": false,
      "delegatePattern": false,
      "singleContentTypes": false,
      "async": false,
      "responseWrapper": "",
      "useTags": false,
      "useBeanValidation": true,
      "implicitHeaders": false,
      "swaggerDocketConfig": true,
      "useOptional": true,
      "library": "spring-boot"
    }
# swagger.yaml
    openapi: 3.0.0
    info:
      title: demo
      description: demo
      version:0.0.1
      termsOfService: 'http://www.xxxx.com'
      contact:
        email: xxxx@xxxx.com
      license:
        name: Apache 2.0
        url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
    servers:
      - url: 'http://xxxx.xxxx.com'
        description: The url of xxxx
    tags:
      - name: Account
        description: Account Info
    paths:
      /account/openAccount:
        post:
          tags:
            - Account
          summary: openAccount
          description: openAccount
          operationId: openAccount
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/AccountInfoDTO'
          responses:
            '200':
              description: ok
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ResultDTO'
    components:
      schemas:
        RequestBaseDTO:
          type: object
          properties:
            systemId:
              type: string
              description: System ID
            requestSeq:
              type: string
              description: Request Sequence
            requestTime:
              type: string
              format: date-time
              description: Request Time
          required:
            - systemId
            - requestSeq
            - requestTime
        AccountInfoDTO:
          allOf:
            - $ref: '#/components/schemas/RequestBaseDTO'
            - type: object
              properties:
                username:
                  type: string
                  description: username
                sex:
                  type: string
                  description: sex
        ResultDTO:
          type: object
          properties:
            success:
              type: boolean
              description: Is Success?
            errcode:
              type: string
              description: Error Code
            errmsg:
              type: string
              description: Error Message
            data:
              type: string
              description: accountId

**Comment by dariota** [comment]
I've tracked the issue to [this line](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser/src/main/java/io/swagger/parser/Swagger20Parser.java#L132) in swagger-parser. Correcting this to openapi let the generator complete successfully with the provided example yaml, so if you want a quick fix you could try that.

The feature/3.0.0-rc2 branch there has thoroughly changed the structure of that directory, so I suspect there are changes made/being made which the 3.0.0 swagger-codegen branch isn't yet synchronised with.

**Comment by chaoshen1024** [comment]
thanks

**Comment by dancrumb** [comment]
Is there any update on when this fix will be available in a snapshot?

**Comment by AaronHarris** [comment]
Still broken as of 1/12/2018

**Comment by soberich** [comment]
Can anyone tell if this is going to be fixed ?
3.0.0 does not work with this exception
2.3.1 works wothout problem
At least, any workaround?

**Comment by globocs** [comment]
any news on this?

**Comment by davidnewcomb** [comment]
Anyone know what the last good version was?
It seems to be broken in 2.4.0 as well.

**Comment by jaya-yellowant** [comment]
Is this still broken?

**Comment by ljnocca** [comment]
I'm getting this same error when trying to use Open Api spec 3. However, it works fine with spec 2. Anyone have this issue as well?

**Comment by riteshkapse** [comment]
still issue

**Comment by RyanBuzzInteractive** [comment]
yeah I just hit this :/

**Comment by jaya-yellowant** [comment]
Try using this experimental openapi codegen instead. It is v light and works for me: https://github.com/Mermade/openapi-codegen

**Comment by RyanBuzzInteractive** [comment]
I tried downloading Swagger codegen 3.0.5 and that 'worked' pretty much, although for some reason it misses out the names of properties in the model constructors and messes up the path to the projects from my sln file although I think these are probably all c# specific. (mentioned here https://github.com/swagger-api/swagger-codegen/issues/9241)

**Comment by suhasIVT** [comment]
Has this worked for anyone ?  OpenApi Spec 3 does not work with io.swagger swagger-codegen-maven-plugin 2.3.1. - I'm getting this error when trying to use Open Api spec 3. However, it works fine with spec 2. 
Error - (**java.lang.RuntimeException: missing swagger input or config!)

**Comment by riteshkapse** [comment]
Download source and generate swagger-codegen-cli.jar jar locally. This worked for me.

**Comment by kireyzambon** [comment]
hello, i have the same error with https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json

**Comment by RugerSR9** [comment]
> Download source and generate swagger-codegen-cli.jar jar locally. This worked for me.

Tried that and still get the same error:

`Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:747)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
`

**Comment by daniilmatafonov** [comment]
I also gettting this error while using swagger-codegen-maven-plugin 2.4.7

**Comment by samheihey** [comment]
I had that error too, but then I realize I made 2 mistakes when setting up the controller:
1) Request Method, I changed the method from Get to Post
2) Setting the correct Http Route

After fixing those 2 errors, and the code is generated

**Comment by Brian611** [comment]
Any update on this?

**Comment by magex9** [comment]
Im getting this error on 2.4.13 as well..

**Comment by beRoberto** [comment]
By default the master branch supports 2.0. The 3.0 support is on the 3.0.0 branch, you have to change to this branch and build again to get it working.
```
git clone https://github.com/swagger-api/swagger-codegen.git
cd swagger-codegen
git checkout 3.0.0
# after this build as you please
mvn clean package
```

**Comment by salvatorevitale** [comment]
Check using single space and not tab!

**Comment by Kolyunya** [comment]
I believe the issue here is that we are using a very old codegen version.

[It turns out](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/tags) the latest published docker image is `2.4.29` which doesn't support OpenAPI v3.

Would the Swagger team be so kind to publish a fresh docker image for us, please?

CC @wing328

**Comment by DanTurco** [comment]
> > Download source and generate swagger-codegen-cli.jar jar locally. This worked for me.
> 
> Tried that and still get the same error:
> 
> `Exception in thread "main" java.lang.RuntimeException: missing swagger input or config! at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:747) at io.swagger.codegen.cmd.Generate.run(Generate.java:285) at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35) `
> 
> Edit: I ended up using @openapitools/openapi-generator-cli and it worked flawlessly.

openapi-generator-cli has issues too

docker run --rm -v C:\dev\client\projects:/local openapitools/openapi-generator-cli generate -i \ /local/temp/swagger.json\ -l typescript-angular -o /local/api-swagger-client/src

Error
```
docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/b5f75883216e4f35f2f9c1e0b1022216f234728ca9ad20eb152856c710f973cc-init/merged: too many levels of symbolic links.
See 'docker run --help'.
```

**Comment by DanTurco** [comment]
I get the same error as well

docker run --rm -v C:\dev\client\projects:/local swaggerapi/swagger-codegen-cli generate -i \ /local/temp/swagger.json\ -l typescript-angular -o /local/api-swagger-client/src
[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/temp/swagger.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/temp/swagger.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:766)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:307)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

**Comment by alteredtech** [comment]
8 years later and still not fixed

```
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
    -i /local/openapi.json \
    -l python-flask \
    -o /local/PetStoreServer
[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/openapi.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /local/openapi.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:766)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:307)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

**Comment by bttfteam** [comment]
Still broken as of today (08/20/2025).

I did checked out the 3.0.0 branch but build failed on nvm clean package with error :
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.014 s
[INFO] Finished at: 2025-08-20T16:40:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project swagger-codegen: Could not resolve dependencies for project io.swagger.codegen.v3:swagger-codegen:jar:3.0.72-SNAPSHOT
[ERROR] dependency: io.swagger.codegen.v3:swagger-codegen-generators:jar:1.0.58-SNAPSHOT (test)
[ERROR]         Could not find artifact io.swagger.codegen.v3:swagger-codegen-generators:jar:1.0.58-SNAPSHOT
```

Anyone figured this out lately ?
Maybe swagger-codegen is not the go to solution ?
