### ISSUE TITLE
Parsing error when a response example is of type `object`

### ISSUE THREAD

**Issue by xhh** [swagger-api/swagger-codegen#646]
From the swagger spec's doc: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#example-object-example

the response example could be an `object`, e.g.
```javascript
{
  "application/json": {
    "name": "Puma",
    "type": "Dog",
    "color": "Black",
    "gender": "Female",
    "breed": "Mixed"
  }
}
```

But when I copied the above example to `modules/swagger-codegen/src/test/resources/2_0/petstore.json` and run the Java codegen, I got this error:
```shell
$ ./bin/java-petstore.sh
reading from modules/swagger-codegen/src/test/resources/2_0/petstore.json
Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.Swagger["paths"]->com.wordnik.swagger.models.Path["get"]->com.wordnik.swagger.models.Operation["responses"]->com.wordnik.swagger.models.Response["examples"])
reading from modules/swagger-codegen/src/test/resources/2_0/petstore.json
Can not deserialize instance of java.lang.String out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.wordnik.swagger.models.Swagger["paths"]->com.wordnik.swagger.models.Path["get"]->com.wordnik.swagger.models.Operation["responses"]->com.wordnik.swagger.models.Response["examples"])
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:54)
        at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:77)
        at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
```

There's a similar error for example of type array as well.

**Comment by xhh** [comment]
it's similar to swagger-api/swagger-parser#27 this one, which is about model example while this one is about operation response example
