### ISSUE TITLE
NullPointerException is occurred during generation

### ISSUE THREAD

**Issue by ssalamatov** [swagger-api/swagger-codegen#6470]
##### Description
Hi, I have following swagger definition
```
/api/v2.0/accounts/{account_id}/rebate_accounts/{rebate_account_id}:  {
post: {
parameters: [
{
description: "New rebate percent",
in: "body",
name: "body",
required: true,
type: "number"
},
{
default: "FBB1234.001",
description: "Account Id",
example: "FBB1234.001",
in: "path",
name: "account_id",
required: true,
type: "string"
}]
…
```

When I run generate command:
```
java -jar ./swagger-codegen-cli.jar generate -i http://localhost/api-docs/swagger.json -l python -o ../swagger-codegen
```

It fails with the following exception:
```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
Tag: accounts
Operation: null
Resource: post /api/v2.0/accounts/{account_id}/rebate_accounts/{rebate_account_id}
...
Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:861)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:764)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:388)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:700)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.isDataTypeBinary(DefaultCodegen.java:2682)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2633)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2191)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:808)
	... 5 more
```

ver. swagger-codegen 2.2.3

**Comment by dariota** [comment]
Your specification is not valid. Refer to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject), or use [a validator](http://bigstickcarpet.com/swagger-parser/www/index.html).

In particular, when a parameter is in the body, the type key is invalid - you *must* use schema instead.
