### ISSUE TITLE
RuntimeException during generation of API which passes validation

### ISSUE THREAD

**Issue by foresightyj** [swagger-api/swagger-codegen#6585]
I validated my api.json before the generation. The validation passes but the generation encountered RuntimeException:

![image](https://user-images.githubusercontent.com/1296736/30945491-402db1ea-a431-11e7-9a7c-dbd859441b21.png)

```
E:\FHT Mobile\Android\swagger_codegen>java -jar swagger-codegen-cli-2.2.3.jar
generate -i fht_api.json -l objc -o ./swaggerObjc -c swagger_objc.config
[main] INFO io.swagger.parser.Swagger20Parser - reading from fht_api.json
Exception in thread "main" java.lang.RuntimeException: Could not generate api fi
le for 'TopicPostApi'
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.jav
a:495)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:70
0)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
        at java.util.TreeMap.compare(TreeMap.java:1294)
        at java.util.TreeMap.put(TreeMap.java:538)
        at java.util.TreeSet.add(TreeSet.java:255)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at java.util.TreeSet.addAll(TreeSet.java:312)
        at io.swagger.codegen.DefaultGenerator.processOperations(DefaultGenerato
r.java:897)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.jav
a:412)
        ... 3 more
```

This is the content of `fht_api.json`:

```
{
    "swagger": "2.0",
    "info":
    {
        "version": "v1",
        "title": "FHT.Core.API"
    },
    "host": "192.168.0.223:9000",
    "schemes": [
        "http"
    ],
    "paths":
    {
        "/v1/topicposts/_delete":
        {
            "post":
            {
                "tags": [
                    "TopicPostApi"
                ],
                "operationId": "TopicPostApi_Delete",
                "consumes": [
                    "application/json",
                    "text/json",
                    "application/xml",
                    "text/xml",
                    "application/x-www-form-urlencoded",
                    "application/vnd.fht360.enumAsString+json"
                ],
                "produces": [],
                "parameters": [
                {
                    "name": "topicPostIds",
                    "in": "body",
                    "required": true,
                    "schema":
                    {
                        "type": "array",
                        "items":
                        {
                            "format": "int64",
                            "type": "integer"
                        }
                    }
                }],
                "responses":
                {
                    "204":
                    {
                        "description": "No Content"
                    }
                }
            }
        }
    }
}
```

And this is `swagger_objc.config`:

```
{
  "coreData": "false",
  "classPrefix": "Fht",
  "podName": "FhtClient",
  "podVersion": "1.0.0"
}

```

**Comment by foresightyj** [comment]
UPDATE:

Just found out that it works with `swagger-codegen-cli-2.2.2.jar` but not `swagger-codegen-cli-2.2.3.jar`

**Comment by wilg** [comment]
Having the same problem with 2.2.3 – not sure where to start looking.

**Comment by wing328** [comment]
I couldn't repeat the issue with the latest master (2.3.0). Please use the SNAPSHOT version to give it a try: https://github.com/swagger-api/swagger-codegen#compatibility
