### ISSUE TITLE
[JavaScript] Bug starting stub server

### ISSUE THREAD

**Issue by mchacon-ml** [swagger-api/swagger-codegen#6604]
##### Description

I generated a JavaScript stub server and I tried to started but I got an error.

##### Swagger-codegen version

latest master

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i swagger.yaml -l nodejs-server -o samples/server/activities/nodejs

##### Steps to reproduce

Created the stub server.
Run npm start based on the subt server screated.
Get the next error:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'draft-mercado-pago-activities' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly fetchPackageMetaData draft-mercado-pago-activities
5 silly fetchNamedPackageData draft-mercado-pago-activities
6 silly mapToRegistry name draft-mercado-pago-activities
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry uri https://registry.npmjs.org/draft-mercado-pago-activities
10 verbose request uri https://registry.npmjs.org/draft-mercado-pago-activities
11 verbose request no auth needed
12 info attempt registry request try #1 at 6:37:11 AM
13 verbose request id 693d7703f24476ea
14 http request GET https://registry.npmjs.org/draft-mercado-pago-activities
15 http 404 https://registry.npmjs.org/draft-mercado-pago-activities
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   'cache-control': 'max-age=0',
16 verbose headers   'content-length': '2',
16 verbose headers   'accept-ranges': 'bytes',
16 verbose headers   date: 'Mon, 02 Oct 2017 09:37:13 GMT',
16 verbose headers   via: '1.1 varnish',
16 verbose headers   age: '0',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-served-by': 'cache-gru17123-GRU',
16 verbose headers   'x-cache': 'MISS',
16 verbose headers   'x-cache-hits': '0',
16 verbose headers   'x-timer': 'S1506937032.956704,VS0,VE1197',
16 verbose headers   vary: 'Accept-Encoding' }
17 silly get cb [ 404,
17 silly get   { 'content-type': 'application/json',
17 silly get     'cache-control': 'max-age=0',
17 silly get     'content-length': '2',
17 silly get     'accept-ranges': 'bytes',
17 silly get     date: 'Mon, 02 Oct 2017 09:37:13 GMT',
17 silly get     via: '1.1 varnish',
17 silly get     age: '0',
17 silly get     connection: 'keep-alive',
17 silly get     'x-served-by': 'cache-gru17123-GRU',
17 silly get     'x-cache': 'MISS',
17 silly get     'x-cache-hits': '0',
17 silly get     'x-timer': 'S1506937032.956704,VS0,VE1197',
17 silly get     vary: 'Accept-Encoding' } ]
18 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/draft-mercado-pago-activities
18 silly fetchPackageMetaData     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
18 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
18 silly fetchPackageMetaData     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
18 silly fetchPackageMetaData     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
18 silly fetchPackageMetaData     at emitTwo (events.js:87:13)
18 silly fetchPackageMetaData     at Request.emit (events.js:172:7)
18 silly fetchPackageMetaData     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
18 silly fetchPackageMetaData     at emitOne (events.js:82:20)
18 silly fetchPackageMetaData     at Request.emit (events.js:169:7)
18 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
18 silly fetchPackageMetaData  error for draft-mercado-pago-activities { [Error: Registry returned 404 for GET on https://registry.npmjs.org/draft-mercado-pago-activities]
18 silly fetchPackageMetaData   pkgid: 'draft-mercado-pago-activities',
18 silly fetchPackageMetaData   statusCode: 404,
18 silly fetchPackageMetaData   code: 'E404' }
19 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/draft-mercado-pago-activities
19 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
19 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:242:14)
19 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
19 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
19 verbose stack     at emitTwo (events.js:87:13)
19 verbose stack     at Request.emit (events.js:172:7)
19 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
19 verbose stack     at emitOne (events.js:82:20)
19 verbose stack     at Request.emit (events.js:169:7)
19 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
20 verbose statusCode 404
21 verbose pkgid draft-mercado-pago-activities
22 verbose cwd /home/mchacon/development/ml/prj/activities/swagger/swagger-codegen/samples/server/activities/nodejs
23 error Linux 4.10.0-35-generic
24 error argv "/usr/bin/nodejs" "/usr/bin/npm" "bugs" "draft-mercado-pago-activities"
25 error node v4.2.6
26 error npm  v3.5.2
27 error code E404
28 error 404 Registry returned 404 for GET on https://registry.npmjs.org/draft-mercado-pago-activities
29 error 404
30 error 404 'draft-mercado-pago-activities' is not in the npm registry.
31 error 404 You should bug the author to publish it (or use the name yourself!)
32 error 404 Note that you can also install from a
33 error 404 tarball, folder, http url, or git url.
34 verbose exit [ 1, true ]
```

Thanks!

**Comment by wing328** [comment]
Does the NodeJS server petstore sample work for you?
```
nodejs|master⚡ ⇒ npm start

> swagger-petstore@1.0.0 prestart /private/tmp/swagger-codegen/samples/server/petstore/nodejs
> npm install

npm notice created a lockfile as package-lock.json. You should commit this file.
added 142 packages in 7.715s

> swagger-petstore@1.0.0 start /private/tmp/swagger-codegen/samples/server/petstore/nodejs
> node index.js

Your server is listening on port 8080 (http://localhost:8080)
Swagger-ui is available on http://localhost:8080/docs
^C


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.0.4 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯



nodejs|master⚡ ⇒ pwd
/tmp/swagger-codegen/samples/server/petstore/nodejs
```
