### ISSUE TITLE
NullPointerException: java.lang.RuntimeException: Could not generate api file for

### ISSUE THREAD

**Issue by shijinkui** [swagger-api/swagger-codegen#6860]
##### Description

Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Job'
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:495)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:700)
	at com.xx.xx.codegen.SDKCodeGen$.main(SDKCodeGen.scala:36)
	at com.xx.xx.codegen.SDKCodeGen.main(SDKCodeGen.scala)
Caused by: java.lang.NullPointerException
	at java.util.TreeMap.put(TreeMap.java:563)
	at java.util.TreeSet.add(TreeSet.java:255)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at java.util.TreeSet.addAll(TreeSet.java:312)
	at io.swagger.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:897)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:412)
	... 3 more

##### Swagger-codegen version

2.3.0-SNAPSHOT

**Comment by wing328** [comment]
Please share the spec so that we can use it to repeat the issue.

**Comment by shijinkui** [comment]
> Please share the spec so that we can use it to repeat the issue.

Company forbidden send outside.
I debug the generating code, found the first element is null in the list

**Comment by wing328** [comment]
Understood. Saw your PR. Will review and merge accordingly.

Btw, please feel free to add "Huawei" to the list: https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen

**Comment by shijinkui** [comment]
@wing328 I only get start to try swagger. When I'm indeed use it in my product, I'll add huawei to the list.

I plan to use swagger to generate SDK in HuaweiCloud Service, hope quickly to fix such problem. If I deploy my own swagger version, it feel not better.
