### ISSUE TITLE
[codegen - java]

### ISSUE THREAD

**Issue by Alex0176** [swagger-api/swagger-codegen#6939]
##### Description

If i generate a java client from https://api.my-clay.com/swagger/ui/index#/ i got a exception with the version 2.2.3.

with Version 2.3.0-20171030.060918-211 and 3.0.0-20171009.075709-6 the code will generated.

##### Swagger-codegen version

2.2.3 - gen error
2.3.0-20171030.060918-211 - code generated but not work
3.0.0-20171009.075709-6 - code generated but not work

##### Swagger declaration file content or url

```json
 HTTP/1.1 200 OK (497ms)
Content-Length: 5259
Content-Type: application/json; odata.metadata=minimal
Server: Microsoft-HTTPAPI/2.0
OData-Version: 4.0
X-API-Version: 1.1.0.338
Date: Sun, 12 Nov 2017 14:09:43 GMT
OkHttp-Sent-Millis: 1510495201090
OkHttp-Received-Millis: 1510495201355

{
  "@odata.context":"https://api.my-clay.com/api/odata/$metadata#tags","value":[
    {
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000001","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Demokoffer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000002","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000003","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000004","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000005","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000006","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000007","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000008","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000009","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000010","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000011","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000012","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Demokoffer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000013","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Demokoffer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000014","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000015","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000016","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000017","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000018","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000019","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    },{
      "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","number":"00000020","blocked_system_ids":[
        
      ],"is_assigned":true,"system":{
        "id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","customer_reference":"Sample Customer"
      }
    }
  ],"@odata.nextLink":"https://api.my-clay.com/api/odata/tags?$skip=20"
 END HTTP (5259-byte body)
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:900)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at io.swagger.client.JSON.deserialize(JSON.java:104)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:669)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:872)
	at io.swagger.client.ApiClient.execute(ApiClient.java:799)
	at io.swagger.client.api.TagsApi.dataapitagsWithHttpInfo(TagsApi.java:134)
	at io.swagger.client.api.TagsApi.dataapitags(TagsApi.java:121)
	at com.Main.main(Main.java:40)

```
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  

##### Command line used for generation

java -jar lib\swagger-codegen-cli-2.3.0-20171030.060918-211.jar generate -i https://api.my-clay.com/swagger/docs/v1 -l java -o .\

##### Steps to reproduce

In the genrated code the type declaration is missing in a lot of points, you have to define via hand final (String/Integer/Boolean) and in every api java file replace the line:

String[] localVarAuthNames = new String[] {   };

with

String[] localVarAuthNames = new String[] {  "BearerToken" };

##### Suggest a fix/enhancement

What can i do to fix the Problems with the paging and the exception?

**Comment by ryandavis84** [comment]
I tried and got the same issue.  However i use this generator a lot for java and never had these issues.  Is there a way you can link me to your swagger.json/swagger.yaml?  I just want to see what the type formats are supplied as for these missing type declarations. 

Also i noticed that there are multiple methods with the same name which are going to give you a method and method_0 name.  If you give your code different method names or use the annotation with nicknames this will avoid that. 

As far as the authentication is, i would also like to view the json / yaml.

**Comment by Alex0176** [comment]
What i have to do for this? 
The server side is not from me and i like only to use the API for use the solution, so i have no access to the server side, only to the api. But the codegen need a oData support for be usefull in this case and this code is missing with 2.3.0 and 3.0.0 or i need to use another option.

**Comment by ryandavis84** [comment]
It all depends on what the server side code was built on.  I will try to look at this later today and see if I can get the swagger doc out of the generator and log it to my screen as json.  My hypothesis is that the format is not supplied so it can not figure out its type.  Which maybe for java at least, it should supply the type of Object in that case.  Just makes the client harder to use and not strong typed.

**Comment by ryandavis84** [comment]
I wrote a quick library that scanned your parameters to find out why the parameters do not have types.  Its because of the way it is reading from the url that you are providing.  I just logged out the name of the parameter, the dataformat and the datatype.  Here is the example from the log:

[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter BaseName: customer_reference
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataFormat: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataType: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter BaseName: system_id
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataFormat: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataType: null
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `dataapiaccessGroups_0`
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter BaseName: customer_reference
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataFormat: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataType: null
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `dataapiaccessGroupsid_0`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `dataapiaccessGroupsid_1`
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter BaseName: lock_id
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataFormat: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataType: null
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `dataapiaccessGroupsidlocks_0`
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter BaseName: id
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataFormat: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataType: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter BaseName: monday
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataFormat: null
[main] INFO io.swagger.codegen.languages.JavaClientCodegen - Parameter DataType: null

As you can see the format and type are both null.  Thus there is no way of knowing what kind of type this is supposed to be.  This may be a bug in the swagger parser when reading from a doc website since in the website it seems to show types.  I would see if there is any way to get the json or yaml from the server side.

As far as the auth i cant seem to figure out how to get that data from the logs.

**Comment by Alex0176** [comment]
What kind of log did you need, i replace the definition in the java code and i can access the api, but the odata did not work and make the error from the first posting.
 
Is in this case swagger the wrong way to generate a client?

If yes, how can i access correcly the odata with paging and filtering? 

if no, whats the correct java libary for this case?

**Comment by Alex0176** [comment]
JSON definition from ,,monday":
`{"name":"monday","in":"body","description":"Whether this timeschedule valid on a Monday between start and end datetimes","required":true,"type":"boolean","default":"true"},`

So a type definition exists.

**Comment by ryandavis84** [comment]
Yeah but i dont think it can get that information from the url you supplied.  It needs to be in the json format for some reason, that someone else can chime in on.

**Comment by ryandavis84** [comment]
The format is for your path parameters is missing somehow i think.

**Comment by ryandavis84** [comment]
I was able to get your swagger json and found multiple areas where the parameters are not set: e.g.

"/api/access_groups/{id}" : {
      "get" : {
        "tags" : [ "access_groups" ],
        "summary" : "Returns single access group.",
        "operationId" : "Data_/api/access_groups/{id}",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/AccessGroupViewModel"
            }
          }
        }
      },


"delete" : {
        "tags" : [ "access_groups" ],
        "summary" : "Deletes an access group.",
        "operationId" : "Data_/api/access_groups/{id}",
        "produces" : [ "application/json" ],
        "parameters" : [ ],
        "responses" : {
          "204" : {
            "description" : "No Content"
          }
        }
      }
    },

Or more or less everywhere.

Other places i see multiple body parameters which i could see resulting in various errors.

"/api/access_groups/" : {
      "post" : {
        "tags" : [ "access_groups" ],
        "summary" : "Creates an access group.",
        "operationId" : "Data_/api/access_groups/",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "customer_reference",
          "description" : "The name or the customer reference for this access group.",
          "required" : true
        }, {
          "in" : "body",
          "name" : "system_id",
          "description" : "The id of the system this access group will belong to.",
          "required" : true
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "schema" : {
              "$ref" : "#/definitions/AccessGroupViewModel"
            }
          }
        }
      }
    },

It looks like everything is a body parameter for some reason instead of a path parameter.  

"/api/access_groups/{id}/time_schedules/{time_schedule_id}" : {
      "put" : {
        "tags" : [ "access_groups" ],
        "summary" : "Updates an existing time schedule of an access group.",
        "operationId" : "Data_/api/access_groups/{id}/time_schedules/{time_schedule_id}",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "id",
          "description" : "ID of timeschedule, ignore if adding to a reservation",
          "required" : true
        }, {...

Where the ID is clearly in the path but it states its in the body.  The body should have a reference to a type.  So it is not completely filled out correctly or the swagger parser has a bug in it.  Considering how many times ive used the java client with all kinds of types, i think the issue may lay in the instrumentation of your code to generate the swagger docs.

**Comment by ryandavis84** [comment]
Also i dont see any data about your authorization strategy so it appears that is why that is not working: https://swagger.io/docs/specification/authentication/

Since that is not supplied thats why it is empty.  

Your exception is with the deserialization of json.  Its looking for an array to come back but there is an object.  I would set the debugger to true and review the actual response to see if its what you expect it to be.

**Comment by Alex0176** [comment]
The Authorization is BearerToken, but this is missing to in the generated code.

**Comment by Clijsters** [comment]
Woulnd't it make sense to give this issue a proper title?
