### ISSUE TITLE
Codegen fails if using a parameter reference from another file

### ISSUE THREAD

**Issue by slarti-b** [swagger-api/swagger-codegen#7176]
##### Description

We are developing several APIs so want to put shared definitions in a central place.  But if I reference a parameter defined in another file then the codegen fail

##### Swagger-codegen version
2.3.0-SNAPSHOT

##### Swagger declaration file content or url

API Definition:
```yaml
swagger: '2.0'
info:
  title: Exmaple API
host: api.example.com
schemes:
  - https
basePath: /
produces:
  - application/json
  - application/xml
paths:
  /bar/{id}:
    get:
      summary: Test
      tags:
        - Test
      parameters:
        - $ref: 'common.yaml#/parameters/foo'
        - name: id
          in: path
          type: string
          required: true
      responses:
        '200':
           description: Success
parameters:
    foo:
        name: baz
        in: header
        type: string
        required: true
```
common.yaml:
```yaml
swagger: '2.0'
parameters:
    foo:
        name: baz
        in: header
        type: string
        required: true
```

config.json (for codegen - I am using spring since that's what I'm trying, but since the error is from  io.swagger.codegen.DefaultGenerator I guess it's generic
```json
{
	"dateLibrary": "java8",
	"java8": "true",
	"async": "true",
	"library": "spring-boot"
}
```

##### Command line used for generation
`java -jar "X:\swagger\swagger-codegen\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar" generate -l spring -i test.yaml -o src/ -v -c config.json`

##### Steps to reproduce

Just run the command above with the files listed.  Output is:
```
[main] INFO io.swagger.codegen.config.CodegenConfigurator -
VERBOSE MODE: ON. Additional debug options are injected
 - [debugSwagger] prints the swagger specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yaml
{
  "swagger" : "2.0",
  "info" : {
    "title" : "Exmaple API"
  },
  "host" : "api.example.com",
  "basePath" : "/",
  "schemes" : [ "https" ],
  "produces" : [ "application/json", "application/xml" ],
  "paths" : {
    "/bar/{id}" : {
      "get" : {
        "tags" : [ "Test" ],
        "summary" : "Test",
        "parameters" : [ {
          "$ref" : "#/parameters/common.yaml#/parameters/foo"
        }, {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Success"
          }
        }
      }
    }
  },
  "parameters" : {
    "foo" : {
      "name" : "baz",
      "in" : "header",
      "required" : true,
      "type" : "string"
    }
  }
}
[main] ERROR io.swagger.codegen.DefaultGenerator - Missing required field info version. Default appVersion set to 1.0.0
[main] ERROR io.swagger.codegen.DefaultGenerator - Missing required field info version. Default version set to 1.0.0
[main] INFO io.swagger.codegen.DefaultGenerator - ############ Model info ############
[ ]
[main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /bar/{id}     ;get io.swagger.models.Operation@56dca9e[null]

[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: get /bar/{id}. Renamed to auto-generated operationId: barIdGet
[main] ERROR io.swagger.codegen.DefaultCodegen - Cannot use Parameter io.swagger.models.parameters.RefParameter@edf4a3a3 as Body Parameter
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
        name: Test
        description: null
        externalDocs: null
        extensions:{}}
  Operation: null
  Resource: get /bar/{id}
  Definitions: {}
  Exception: io.swagger.models.parameters.RefParameter cannot be cast to io.swagger.models.parameters.BodyParameter
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:916)
        at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:791)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:418)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:730)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.ClassCastException: io.swagger.models.parameters.RefParameter cannot be cast to io.swagger.models.parameters.BodyParameter
        at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2594)
        at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2234)
        at io.swagger.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1018)
        at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:864)
        ... 5 more

```

Note that if I use a named parameter definition within the same file then it works.  it's only a reference in another file that fails.  For example, the following yaml will work with the same command line (and it's the same definition, just in one file instead of split up)

```yaml
swagger: '2.0'
info:
  title: Exmaple API
host: api.example.com
schemes:
  - https
basePath: /
produces:
  - application/json
  - application/xml
paths:
  /bar/{id}:
    get:
      summary: Test
      tags:
        - Test
      parameters:
        - $ref: '#/parameters/foo'
        - name: id
          in: path
          type: string
          required: true
      responses:
        '200':
           description: Success
parameters:
    foo:
        name: baz
        in: header
        type: string
        required: true
```

**Comment by wing328** [comment]
Pls note the following output:
```
          "$ref" : "#/parameters/common.yaml#/parameters/foo"
```
Can you try defining as follows instead?
```
        - $ref: './common.yaml#/parameters/foo'
```

Please also use the latest SNAPSHOT, which is using the latest stable version of Swagger Parser.

**Comment by slarti-b** [comment]
Yes!  That works.  My bad, new  to the syntax.  Many thanks

**Comment by wing328** [comment]
@slarti-b no problem. Let us know if you need further assistance.
