### ISSUE TITLE
NPE for Reusable Parameters in 3.0.0_enhancements

### ISSUE THREAD

**Issue by mricken** [swagger-api/swagger-codegen#7186]
##### Description

I'm using the CLI of the 3.0.0_enhancements branch. As soon as I add a $ref for a parameter, I get an NPE.

In the example below, I added a `MyQueryParam` parameter that is being $ref-ed from the `showPetById` operation.

##### Swagger-codegen version

```$ java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar version
3.0.0-SNAPSHOT```

(based on branch 3.0.0_enhancements, 45388247c23c8974852b2ad2390ed1b53a8c173f).

##### Swagger declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: An paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
        - $ref: '#/components/parameters/MyQueryParam'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    MyQueryParam:
      in: query
      name: qp
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 255
```

##### Command line used for generation

```$ java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l java -o output -v -i petstore.yaml```

##### Steps to reproduce

```$ java -jar ./swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l java -o output -v -i petstore.yaml```

results in

```
java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1903)
	at io.swagger.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1051)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:873)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:800)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:414)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:732)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:308)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-1" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: pets
    description: null
    externalDocs: null
}
  Operation: showPetById
  Resource: get /pets/{petId}
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:900)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:800)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:414)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:732)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:308)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1903)
	at io.swagger.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1051)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:873)
	... 5 more
```

**Comment by wing328** [comment]
@mricken thanks for reporting the issue.

cc @HugoMario

**Comment by HugoMario** [comment]
@mricken, can you please check this when you have a chance?

**Comment by mricken** [comment]
Yes, this works now. Thank you.
