### ISSUE TITLE
no viable alternative at input

### ISSUE THREAD

**Issue by nikolaistraessle** [swagger-api/swagger-codegen#7318]
##### Description

Hi,
i tried to generate a php-symfony server from a yaml-definition, but this error occurs also in other languages like php.

```java
Caused by: com.github.jknack.handlebars.HandlebarsException: /php-symfony/model_variables.mustache:15:73: found: '-last', expected: 'no viable alternative at input '{{^-last''
     *   @Assert\Choice({ {{#allowableValues}}{{#enumVars}}{{{value}}}{{^-last}}, {{/-last}}{{/enumVars}}{{/allowableValues}} })
```

Here the full stack trace:
```java
[main] ERROR io.swagger.codegen.Codegen - Could not generate model 'Accommodation'
java.lang.RuntimeException: Could not generate model 'Accommodation'
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:721)
	at io.swagger.codegen.Codegen.main(Codegen.java:117)
Caused by: com.github.jknack.handlebars.HandlebarsException: /php-symfony/model_variables.mustache:15:73: found: '-last', expected: 'no viable alternative at input '{{^-last''
     *   @Assert\Choice({ {{#allowableValues}}{{#enumVars}}{{{value}}}{{^-last}}, {{/-last}}{{/enumVars}}{{/allowableValues}} })
                                                                         ^
	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:308)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportNoViableAlternative(HbsErrorStrategy.java:166)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:145)
	at com.github.jknack.handlebars.internal.HbsParser.elseBlock(HbsParser.java:978)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:678)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:396)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:164)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:72)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:86)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:175)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.Options.fn(Options.java:445)
	at com.github.jknack.handlebars.helper.WithHelper.apply(WithHelper.java:58)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.Options.apply(Options.java:538)
	at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:72)
	at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
	at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:738)
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
	... 2 more
```

##### Swagger-codegen version

I used the swagger [branch 3.0.0](https://github.com/swagger-api/swagger-codegen/tree/3.0.0) (commit 8e169f7dcd565230258b5c6fb7d2924f482cdc72)

##### Swagger declaration file content or url

```yaml
openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/arcade/TourX/1.0.0
info:
  version: "1.0.0"
  title: Sample Implicit Flow OAuth2 Project
  description: >-
    This is an example of using OAuth2 Implicit Flow in a specification to
    describe security to your API.
security:
  - implicit:
      - read
      - write
paths:
  /accommodation:
    get:
      tags: 
        - accommodation
      summary: Server example operation
      description: >-
        This is an example opeartion to show how security is applied to the
        call.
      responses:
        '200':
          description: OK
  /accommodation/{id}:
    get:
      tags: 
        - accommodation
      summary: Get a specific accommodation
      description: >-
        This operation returns a specific accommodation.
      parameters: 
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
               $ref: '#/components/schemas/Accommodation'
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      security: []
      responses:
        '200':
          description: OK
components:
  schemas: 
    Accommodation:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fullTime: 
          type: boolean
        company:
          $ref: '#/components/schemas/Company'
    Company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/oauth/auth'
          scopes:
            write: allows modifying resources
            read: allows reading resources
```

##### Command line used for generation

Command line arguments: `generate -i TourX_1.0.0_swagger.yaml -l php-symfony -o swaggertest/`

Thank you for your support.

**Comment by HugoMario** [comment]
hello @nikolaistraessle 
on 3.0.0 branch we're using handlebars instead of mustache as template engine. That's a syntax error instead "^-last" it should go with "^@last". However, on this branch only "java and inflector" are getting support right now, as a start.
