### ISSUE TITLE
[JAVA] JAXRS-Resteasy-EAP language missing allowableValues.mustache

### ISSUE THREAD

**Issue by k2r79** [swagger-api/swagger-codegen#7421]
##### Description

```
java.lang.RuntimeException: Could not generate api file for 'foo'
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:539)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:746)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: can't load template JavaJaxRS\resteasy\eap\allowableValues.mustache
	at io.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:64)
	at io.swagger.codegen.DefaultGenerator$4.getTemplate(DefaultGenerator.java:767)
	at com.samskivert.mustache.Mustache$IncludedTemplateSegment.execute(Mustache.java:744)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:863)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:852)
	at com.samskivert.mustache.Template.executeSegs(Template.java:114)
	at com.samskivert.mustache.Mustache$IncludedTemplateSegment.execute(Mustache.java:762)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:848)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:848)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:827)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:863)
	at com.samskivert.mustache.Template.executeSegs(Template.java:114)
	at com.samskivert.mustache.Template.execute(Template.java:91)
	at com.samskivert.mustache.Template.execute(Template.java:82)
	at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:773)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:498)
	... 24 more
```

##### Swagger-codegen version

I'm using Swagger Codegen Maven plugin v2.3.0.

##### Swagger declaration file content or url

```
...
- name: bwah
   in: header
   type: string
   enum:
     - foo
     - bar
   required: true
...
```
##### Command line used for generation

`mvn clean package`

##### Steps to reproduce

Just need to run the source generation phase.

##### Related issues/PRs

Couldn't find any...

##### Suggest a fix/enhancement

Maybe add [allowableValues.mustache](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/allowableValues.mustache) to the [**JavaJaxRS/resteasy/eap/** folder](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/)

**Comment by k2r79** [comment]
Just tested with a query parameter instead of a header parameter and the bug doesn't come up.

**Comment by wsalembi** [comment]
It fails in path segments too.

```json
  "parameters" : [ {
          "name" : "type",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "enum" : [ "foo", "bar" ]
        }],
```
