### ISSUE TITLE
[3.0.0] RuntimeException for inline requestBody

### ISSUE THREAD

**Issue by ten0s** [swagger-api/swagger-codegen#7429]
##### Description

[Thread-1] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: post /request. Renamed to auto-generated operationId: requestPost
java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromRequestBody(DefaultCodegen.java:2272)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1850)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:850)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:780)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:423)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:727)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:312)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-1" java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: default
    description: null
    externalDocs: null
}
  Operation: null
  Resource: post /request
  Exception: null

##### Swagger-codegen version

a0d5033a6b69b781008402f0e063ccadd606d535

##### Swagger declaration file content or url

```yaml
openapi: 3.0.0
paths:
  /request:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Request'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Request:
      type: object
      properties:
        request_id:
          type: integer
          format: int64

```

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i inline.yaml -l scala -o out/

##### Related issues/PRs

Looks like it was fixed in 2.x long time ago
https://github.com/swagger-api/swagger-codegen/issues/354

**Comment by ten0s** [comment]
It was a spec issue - missing first forward slash in ref '#/components/schemas/Request'
