### ISSUE TITLE
Provider io.swagger.codegen.languages.java.JavaClientCodegen not found  with maven plugin ver 3.0.0-rc0

### ISSUE THREAD

**Issue by computrade** [swagger-api/swagger-codegen#7518]
##### Description

Maven plugin throw error when using version  3.0.0-rc0 and the following configuration sample :

```
 
			<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>3.0.0-rc0</version>
				<executions>
					<execution>
						<id>swagger-generate-client-code</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>PetSwagger.json</inputSpec>
							<language>java</language>
							<configOptions>
								<sourceFolder>src/main/java</sourceFolder>	
							</configOptions>
							<library>jersey2</library>				
						</configuration>
					</execution>
				</executions>
			</plugin>
	
```
     

##### Swagger-codegen version

        <swagger-core-version>2.0.0-rc2</swagger-core-version>
        <swagger-annotations-version>1.5.18</swagger-annotations-version> 

##### Steps to reproduce

run maven package and got this Exception in build time:
`
Exception in thread "main" java.util.ServiceConfigurationError: io.swagger.codegen.CodegenConfig: Provider io.swagger.codegen.languages.java.JavaClientCodegen not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:19)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:392)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:512)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
`

**Comment by asuka000** [comment]
the JavaClientCodegen 's package in io.swagger.codegen.CodegenConfig is wrong

wrong:
io.swagger.codegen.languages.java.JavaClientCodegen
io.swagger.codegen.languages.java.JavaInflectorServerCodegen

right
io.swagger.codegen.languages.JavaClientCodegen
io.swagger.codegen.languages.JavaInflectorServerCodegen

**Comment by dewijant** [comment]
quick workaround: edit swagger-codegen-3.0.0-rc0.jar/META-INF/services/io.swagger.codegen.CodegenConfig
fix wrong package paths

**Comment by computrade** [comment]
Thanks @dewijant , I have update the io.swagger.codegen.CodegenConfig and it solve the issue!

Now I get this:

`INFO] --- swagger-codegen-maven-plugin:3.0.0-rc0:generate (swagger-generate-client-code) @ openapi-client-java8 ---
[WARNING] Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
[WARNING] Not valid URL: https://{username}.gigantic-server.com:{port}/{basePath}
java.net.MalformedURLException: For input string: "{port}"
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at io.swagger.codegen.utils.URLPathUtil.getServerURL(URLPathUtil.java:30)
	at io.swagger.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:209)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:716)
	at io.swagger.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:534)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NumberFormatException: For input string: "{port}"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
	at java.net.URL.<init>(URL.java:622)
	... 28 more`

because of thes lines in the spec which is not evaluated correctlly:

servers:
  url: https://{username}.gigantic-server.com:{port}/{basePath}

I'm tried to use the below without help:
`		
		<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-codegen</artifactId>
			<version>3.0.0-rc0</version>
		</dependency>
         <dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>2.0.0-rc2</version>
		</dependency>
`

**Comment by HugoMario** [comment]
@asuka000 for codegen 3.0.0, these `io.swagger.codegen.languages.JavaClientCodegen and 
io.swagger.codegen.languages.JavaInflectorServerCodegen` are the correct classes to use. This issue needs to be fixed using keeping those values.

**Comment by marcoreni** [comment]
I was able to work-around this issue by adding a `dependencies` block inside the `plugin` block:

```xml
<plugin>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>3.0.0-rc0</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              [...]
          </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-codegen-generators</artifactId>
            <version>1.0.0-SNAPSHOT</version>
          </dependency>
        </dependencies>
      </plugin>
```

Maybe the dependencies of the maven plugin are not up to date?

**Comment by jmini** [comment]
@marcoreni thank you for your input.

After a quick look at the [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators) repository, I guess that it is better to use the released version of instead of the SNAPSHOT version (ie `1.0.0-rc0` version of the [swagger-codegen-generators](http://www.mvnrepository.com/artifact/io.swagger/swagger-codegen-generators/1.0.0-rc0)).

swagger-codegen-maven-plugin is working for me with this additional dependencies.

**Comment by HugoMario** [comment]
This issue has been fixed, please let me know if you still get it.

**Comment by computrade** [comment]
@HugoMario  OK - thank you very much 👍

**Comment by mhoffman78** [comment]
Hello, I am still receiving this error.  I have updated the jar file several times

![swagger](https://user-images.githubusercontent.com/36509786/36263536-6a2aa96a-1238-11e8-90b6-bfe1c8c881aa.PNG)

**Comment by globocs** [comment]
@HugoMario , @computrade - will this fix be included in an upcoming rc release of the plugin?
The latest version available is 3.0.0-rc0, which doesn't include the fix, and I can't use it.

**Comment by jmini** [comment]
Use `3.0.0-SNAPSHOT`. It should already be fixed. 

(At least `swagger-codegen-maven-plugin` has a dependency on `swagger-codegen-generators`)

**Comment by FuchengLi** [comment]
Could not find artifact io.swagger:swagger-codegen-maven-plugin:jar:3.0.0-SNAPSHOT
