### ISSUE TITLE
[JAVA] Unable to resolve $refs using dot-segments. 

### ISSUE THREAD

**Issue by sfreeman422** [swagger-api/swagger-codegen#7582]
##### Description

When trying to resolve relative references in a $ref that make use of dot-segments, swagger-codegen (specifically, it looks like swagger-parser) is unable to resolve paths that require going up one directory or more. 

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

Existing Folder Structure: 

```
|- apis
  |- hr
    |- api
      |- schema
         - foo.json
  |- core
    |- codeType
      |- bar.json
```
$ref inside of foo.json:

`"$ref": "../../../core/codeType/bar.json#"`

##### Command line used for generation

`swagger-codegen generate -i apis/hr/api/schema/foo.json -l java -o apis/hr/api/java --type-mappings indicatorType=boolean,dateType=Date,dateTimeType=Date --invoker-package schema --model-package schema.model`

##### Steps to reproduce

1. Insert a $ref using dot-segments into the schema.
2. Attempt to use the swagger-codegen to generate Java from JSON that includes a dot-segment $ref.

##### Suggest a fix/enhancement
It looks like swagger-parser may be responsible for this issue as the call stack seems to indicate that the failure is coming from SwaggerParser. It appears that the parser cannot resolve paths that go up a directory, rather than down.

**Comment by sfreeman422** [comment]
```
Exception in thread "main" java.lang.RuntimeException: Unable to load RELATIVE ref: ../../core/codeType/bar.json#
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:146)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:112)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:37)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefProperty(ExternalRefProcessor.java:132)
        at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:102)
        at io.swagger.parser.processors.PropertyProcessor.processRefProperty(PropertyProcessor.java:34)
        at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:21)
        at io.swagger.parser.processors.PropertyProcessor.processArrayProperty(PropertyProcessor.java:52)
        at io.swagger.parser.processors.PropertyProcessor.processProperty(PropertyProcessor.java:23)
        at io.swagger.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:21)
        at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:45)
        at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:101)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:50)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:67)
        at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.RuntimeException: Could not find ../../common/core/simpleIDType_v02.json# on the classpath
        at io.swagger.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:141)
```

Call stack included for more information. Interesting note, the error message appears to only show `../../` whereas the $ref includes `../../../`
