### ISSUE TITLE
swagger-codegen-distribution\2.1.0-M1.jar uploaded to maven repository throws ServiceConfigurationError on code generation

### ISSUE THREAD

**Issue by abhisheksinhacsr** [swagger-api/swagger-codegen#764]
Hi,

We downloaded the swagger-codegen-distribution/2.1.0-M1.jar uploaded to http://mvnrepository.com/artifact/com.wordnik/swagger-codegen-distribution/2.1.0-M1 
We tried generating code with the default jar which throws the following error:

java.util.ServiceConfigurationError: com.wordnik.swagger.codegen.CodegenConfig: Provider com.wordnik.swagger.codegen.languages.PythonClientCodegen could not be
instantiated
        at java.util.ServiceLoader.fail(Unknown Source)
        at java.util.ServiceLoader.access$100(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
        at java.util.ServiceLoader$1.next(Unknown Source)
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at com.wordnik.swagger.codegen.languages.PythonClientCodegen.<init>(PythonClientCodegen.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.lang.Class.newInstance(Unknown Source)
        ... 5 more
Exception in thread "main"

Removing the last entry (com.wordnik.swagger.codegen.languages.PythonClientCodegen) in META-INF/services/com.wordnik.swagger.codegen.CodegenConfig , repackaging the jar and executing it resolves the issue.

Thanks
Abhishek Sinha
CSR India Pvt Ltd.

**Comment by wing328** [comment]
I would suggest you to test with the `develop_2.0` branch to see if the issue persists.

**Comment by fehguy** [comment]
As @wing328 said, please either rebuild from the develop_2.0 branch or grab the snapshot from sonatype:  `2.1.1-M2-SNAPSHOT`
