### ISSUE TITLE
[PYTHON] Bug generating library

### ISSUE THREAD

**Issue by Doldge** [swagger-api/swagger-codegen#7697]
##### Description
I seem to be getting an unhandled exception when attempting to generate python library from my openapi v3 yaml file. It does seem to produce files, but I can't tell if they're functional or not.

Stack Trace:
```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'Date'
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:721)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:312)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.jknack.handlebars.HandlebarsException: /python/model.mustache:9:15: found: '-first', expected: 'id'
{{#imports}}{{#-first}}
               ^
	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:186)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:148)
	at com.github.jknack.handlebars.internal.HbsParser.sexpr(HbsParser.java:919)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:657)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
	at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1012)
	at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:737)
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
	... 3 more
```
##### Swagger-codegen version
swagger-codegen-cli-3.0.0-20180110.222113-18
##### Swagger declaration file content or url
Swagger Decleration is here: https://gist.github.com/Doldge/dcbc4b4066cfc286760c9b30831fc630

##### Command line used for generation
java -jar ../v3/swagger-codegen-cli-3.0.0-20180110.222113-18.jar generate -i api.yaml -l python

##### Steps to reproduce
Seems to occur every time I try build from my document. The doc was previously a v2, and has been upgraded to v3 using https://github.com/Mermade/swagger2openapi ; The v2 version did not have this issue.

##### Related issues/PRs
None
##### Suggest a fix/enhancement
Seems to be something wrong with the mustache file in python. I don't know enough about mustache to know what's going on, but I'm happy to try fix it myself if someone wants to point me in the correct direction.

**Comment by webron** [comment]
Check the [release notes](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0-rc0) - only two generators are supported right now, python is not one of them. Availability of python support depends on community contributions.

**Comment by Doldge** [comment]
@webron Are there issues already open for python generators that I can follow? Is there someone I can co-ordinate with to get these changes into the next release?

**Comment by webron** [comment]
There are no issues for non-existing generators for 3.0 - it wouldn't make sense to start such issues as they don't exist. We have a pending PHP generator PR, and the rest really depends on what else will come in. Having an open issue "there's no Python generator" will not help us move forward.
