### ISSUE TITLE
[swagger-codegen 3.0.0] oneOf Support

### ISSUE THREAD

**Issue by thejjmiller** [swagger-api/swagger-codegen#7715]
##### Description

I have a swagger 3.0 spec that uses a oneOf schema. This causes an exception when trying to generate csharp code. I would suspect that this is not just csharp related though.

##### Swagger-codegen version

3.0.0-rc0

##### Swagger declaration file content or url
```
 "CanonicalTransaction": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/SaleOrReturnTransaction"
          },
          {
            "$ref": "#/components/schemas/ControlTransaction"
          },
          {
            "$ref": "#/components/schemas/CashManagement"
          },
          {
            "$ref": "#/components/schemas/ApexTransaction"
          }
        ],
        "discriminator": {
          "propertyName": "transactionCategory"
        }
      },```



##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i swagger.json -o codegen -l csharp

##### Steps to reproduce

nothing special here.

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

N/A

**Comment by n2ygk** [comment]
See the 3.0.0-rc0 [release notes](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0-rc0) which indicate that the only currently supported languages are `java` and `inflector`.
```
[Thread-1] INFO io.swagger.codegen.languages.CSharpClientCodegen - Generating code for .NET Framework v4.5
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'Error'
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:407)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:722)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:312)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /csharp/model.mustache
	at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
	at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1013)
	at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:738)
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:394)
	... 3 more
```

**Comment by webron** [comment]
As @n2ygk mentioned, csharp is not supported yet. If you're up for the task, we'd appreciate contributions.
