### ISSUE TITLE
[HTML] Can't generate static HTML

### ISSUE THREAD

**Issue by IaroslavR** [swagger-api/swagger-codegen#7819]
##### Description
when i try to generate static html for my yaml specification i got this error
```
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name html Available: java
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-resteasy-eap
jaxrs-resteasy

	at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:93)
Caused by: java.lang.ClassNotFoundException: html
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
	... 1 more
```
```sh
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar langs
Available languages: [java, jaxrs-cxf, inflector, jaxrs-cxf-cdi, jaxrs-spec, jaxrs-jersey, jaxrs-resteasy-eap, jaxrs-resteasy]
```
```sh
ls /home/im/github/swagger-codegen/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages
AbstractAdaCodegen.java               JavaResteasyServerCodegen.java
AbstractCppCodegen.java               JavascriptClientCodegen.java
AbstractCSharpCodegen.java            JavascriptClosureAngularClientCodegen.java
AbstractEiffelCodegen.java            JavaVertXServerCodegen.java
AbstractGoCodegen.java                JMeterCodegen.java
AbstractJavaCodegen.java              KotlinClientCodegen.java
AbstractJavaJAXRSServerCodegen.java   LuaClientCodegen.java
AbstractPhpCodegen.java               LumenServerCodegen.java
AbstractScalaCodegen.java             NancyFXServerCodegen.java
AbstractTypeScriptClientCodegen.java  NodeJSServerCodegen.java
AdaCodegen.java                       ObjcClientCodegen.java
AdaServerCodegen.java                 PerlClientCodegen.java
AkkaScalaClientCodegen.java           PhpClientCodegen.java
AndroidClientCodegen.java             PistacheServerCodegen.java
Apache2ConfigCodegen.java             PowerShellClientCodegen.java
ApexClientCodegen.java                PythonClientCodegen.java
AspNetCoreServerCodegen.java          Qt5CPPGenerator.java
BashClientCodegen.java                Rails5ServerCodegen.java
ClojureClientCodegen.java             RClientCodegen.java
ConfluenceWikiGenerator.java          RestbedCodegen.java
CppRestClientCodegen.java             RubyClientCodegen.java
CSharpClientCodegen.java              RustClientCodegen.java
CsharpDotNet2ClientCodegen.java       RustServerCodegen.java
DartClientCodegen.java                ScalaClientCodegen.java
EiffelClientCodegen.java              ScalaLagomServerCodegen.java
ElixirClientCodegen.java              ScalatraServerCodegen.java
ElmClientCodegen.java                 ScalazClientCodegen.java
ErlangClientCodegen.java              SilexServerCodegen.java
ErlangServerCodegen.java              SinatraServerCodegen.java
features                              SlimFrameworkServerCodegen.java
FinchServerCodegen.java               SpringCodegen.java
FlashClientCodegen.java               StaticDocCodegen.java
FlaskConnexionCodegen.java            StaticHtml2Generator.java
GoClientCodegen.java                  StaticHtmlGenerator.java
GoServerCodegen.java                  SwaggerGenerator.java
GroovyClientCodegen.java              SwaggerYamlGenerator.java
HaskellHttpClientCodegen.java         Swift3Codegen.java
HaskellServantCodegen.java            Swift4Codegen.java
helpers                               SwiftCodegen.java
JavaClientCodegen.java                SymfonyServerCodegen.java
JavaCXFClientCodegen.java             TizenClientCodegen.java
JavaCXFServerCodegen.java             TypeScriptAngularClientCodegen.java
JavaInflectorServerCodegen.java       TypeScriptAngularJsClientCodegen.java
JavaJAXRSCXFCDIServerCodegen.java     TypeScriptAureliaClientCodegen.java
JavaJAXRSSpecServerCodegen.java       TypeScriptFetchClientCodegen.java
JavaJerseyServerCodegen.java          TypeScriptJqueryClientCodegen.java
JavaMSF4JServerCodegen.java           TypeScriptNodeClientCodegen.java
JavaPKMSTServerCodegen.java           UndertowCodegen.java
JavaPlayFrameworkCodegen.java         ZendExpressivePathHandlerServerCodegen.java
JavaResteasyEapServerCodegen.java
```
##### Swagger-codegen version

i tried  with built  with `mvn clean package` command  from `3.0.0` git branch and with downloaded `swagger-codegen-cli-3.0.0-20180311.065628-40.jar` with same results
##### Command line used for generation

```sh
java -jar /home/im/github/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   --i ./spec/openapi.yaml \
   -l html \
   -o ./spec
```
```sh
java -jar /home/im/tmp/swagger-codegen-cli-3.0.0-20180311.065628-40.jar generate \
   -i ./spec/openapi.yaml \
   -l html \
   -o ./spec
```

**Comment by jmini** [comment]
With Swagger V3, the generators are no longer located in `io.swagger.codegen.languages` package in the `swagger-codegen` modules.

New location is in the [swagger-codegen-generators](https://github.com/swagger-api/swagger-codegen-generators/) repository and module.

Folder  [`/swagger-codegen/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages` on the `3.0.0` branch](https://github.com/swagger-api/swagger-codegen/tree/3.0.0/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages) is here to help with the migration. It contains dead code for the moment.

---
As announced in the [v3.0.0-rc0 release notes](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0-rc0), the initial focus is on the `java` and `inflector` generators. For the `html` generator, I have opened a pull request: https://github.com/swagger-api/swagger-codegen-generators/pull/35

Once this pull request is solved, an initial version of the `html` generator will be present on the `3.0.0-SNAPSHOT` version you are using.

**Comment by jmini** [comment]
My pull request was merged, please update to the latest `swagger-codegen-cli.jar` (or build it locally using the `-U` flag to be sure to get the latest version).

Please notice that this is an initial version (not only the generator is new with v3 but also the framework, the templating engine, the spec, the parser...), you might find some regressions that need to be adressed. Feedback is welcomed.

I think this issue can be closed.

**Comment by IaroslavR** [comment]
@jmini  I can confirm, all works now. Thank you

**Comment by jmini** [comment]
Can you close the issue?

**Comment by IaroslavR** [comment]
built from sources `swagger-codegen-cli` works as expected
