### ISSUE TITLE
Exception while running generate on validated format in multiple languages

### ISSUE THREAD

**Issue by haralabidis** [swagger-api/swagger-codegen#7851]
##### Description

While trying to generate code for a valid swagger definition I get the following exception: 

[main] INFO io.swagger.parser.Swagger20Parser - reading from /Users/patrick/Coginitive/Face/FaceSwagger.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: default
	description: null
	externalDocs: null
	extensions:{}}
  Operation: 563879b61984550f30395236
  Resource: post /detect
  Definitions: {}
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:932)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:811)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:431)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:746)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2585)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2213)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:881)
	... 5 more

I get the same exception whether I try to generate code for Swift 4 or C#, I have not tried any other language.

##### Swagger-codegen version

Using Swagger 2.3.1 on a Mac installed via Homebrew.

##### Swagger declaration file content or url

Using the swagger API definition for the following API:
https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236 

I did validate the definition.

##### Command line used for generation

swagger-codegen generate -i  <Local path to json file> -l csharp -o <Path to local folder>

swagger-codegen generate -i  <Local path to json file> -l swift4 -o <Path to local folder>

##### Steps to reproduce

Execute the command above against the supplied definition.

**Comment by thomaxxl** [comment]
Hi,

I have the same issue. First a bunch of warnings

"[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path:" ....

then the exception at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:932)

```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
        name: MyClass
        description: mydesc
        externalDocs: null
        extensions:{}}
  Operation: null
```

**Comment by gururajdori** [comment]
Same issue:

[main] INFO io.swagger.parser.Swagger20Parser - reading from test.yaml
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: default
	description: null
	externalDocs: null
	extensions:{}}
  Operation: 56f91f2e778daf14a499e1fa
  Resource: post /analyze
  Definitions: {}
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:932)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:811)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:431)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:746)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2585)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2213)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:881)
	... 5 more

**Comment by hotmeteor** [comment]
Did anyone figure this one out?
