### ISSUE TITLE
typescript-fetch fails on BOM (may be wider issue than this template)

### ISSUE THREAD

**Issue by jesomm** [swagger-api/swagger-codegen#7856]
##### Description

typescript-fetch codegen is failing on BOM (`0xfeff` in error below)

```
[main] ERROR io.swagger.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('?' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@3570b7; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2397)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:187)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:75)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:731)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

repros with any otherwise valid swagger content returned by server using BOM

##### Command line used for generation

call command:
`java -jar <path/to/swagger-codegen> generate -i <path/to/swaggerJson> -l typescript-fetch -t <path/to/templates> -c <path/to/config> -o <path/to/desired/output>`

which we trigger from npm script that actually defines all those paths:
```
const execSync = require('child_process').execSync;
// code that generates paths and assigns above command to var execString
execSync(execString, { stdio: ['ignore', 'ignore', stdErr] });
```

config:
```
{
    "allowUnicodeIdentifiers" : false,
    "ensureUniqueParams": true,
    "modelPropertyNaming": "camelCase",
    "sortParamsByRequiredFlag": true,
    "supportsES6" : false
}
```

##### Steps to reproduce

repros every time on using a swagger.json returned by a server that sends BOM

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/6971, https://github.com/swagger-api/swagger-codegen/issues/3680

##### Suggest a fix/enhancement

strip BOM before trying to parse JSON?

something like this could be used / forked and rewritten for java/swagger:
- https://github.com/sindresorhus?utf8=✓&tab=repositories&q=strip-bom

**Comment by ParanoikCZE** [comment]
We've run into similar issue. Still investigating root cause. However, I found out that RFC says that
"Implementations MUST NOT add a byte order mark to the beginning of a JSON text."
see https://tools.ietf.org/html/rfc7159#section-8.1
