### ISSUE TITLE
[Python] TypeError: __init__() got an unexpected keyword argument 'encode_multipart'

### ISSUE THREAD

**Issue by jacobweber** [swagger-api/swagger-codegen#7857]
##### Description

When calling a DELETE API that has consumes = "application/x-www-form-urlencoded", I get the error in the subject.

##### Swagger-codegen version

2.3.1

##### Swagger declaration file content or url

```json
...
			"delete": {
				"consumes": [
					"application/x-www-form-urlencoded"
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "successful response",
						"schema": {
							"$ref": "#/definitions/MyResponse"
						}
					}
				},
				"parameters": [
					{
						"description": "User identifier",
						"required": true,
						"type": "string",
						"name": "user",
						"in": "path"
					},
					{
						"description": "List of file names to delete",
						"items": {
							"type": "string"
						},
						"required": true,
						"collectionFormat": "csv",
						"in": "path",
						"type": "array",
						"name": "fileNames"
					}
				],
				"description": "Deletes files for a user",
				"summary": "Delete Files",
				"operationId": "deleteFiles"
			}
```

##### Command line used for generation

swagger-codegen generate -i "https://my-url" -l python -o "/my-path" -DpackageName=my_project -DprojectName=my-project

using python 2.7.10, with urllib3 1.22, on Mac OS 10.13.

##### Steps to reproduce

My code calls something like `user_api.delete_files('johndoe', ['foo'])`. It prints this error:

```
Traceback (most recent call last):
  File "examples.py", line 41, in <module>
    user_api.delete_files('johndoe', ['foo'])
  File "build/bdist.macosx-10.13-intel/egg/my_project/api/user_api.py", line 1245, in delete_tags
  File "build/bdist.macosx-10.13-intel/egg/my_project/api/user_api.py", line 1331, in delete_tags_with_http_info
  File "build/bdist.macosx-10.13-intel/egg/my_project/api_client.py", line 322, in call_api
  File "build/bdist.macosx-10.13-intel/egg/my_project/api_client.py", line 153, in __call_api
  File "build/bdist.macosx-10.13-intel/egg/my_project/api_client.py", line 388, in request
  File "build/bdist.macosx-10.13-intel/egg/my_project/rest.py", line 265, in DELETE
  File "build/bdist.macosx-10.13-intel/egg/my_project/rest.py", line 175, in request
  File "/Library/Python/2.7/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/Library/Python/2.7/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/Library/Python/2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Library/Python/2.7/site-packages/urllib3/connectionpool.py", line 617, in urlopen
    **response_kw)
  File "/Library/Python/2.7/site-packages/urllib3/response.py", line 467, in from_httplib
    **response_kw)
TypeError: __init__() got an unexpected keyword argument 'encode_multipart'
```

##### Related issues/PRs
N/A

##### Suggest a fix/enhancement
N/A

**Comment by cliveseldon** [comment]
This is probably because you have a DELETE method that consumes a multipart/form
See https://swagger.io/docs/specification/describing-request-body/ where is says
`GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics as per RFC 7231.`
