### ISSUE TITLE
[Javascript] NullPointerException when trying to use swagger-codegen 3.0.0

### ISSUE THREAD

**Issue by melissachang** [swagger-api/swagger-codegen#7891]
##### Description

I would like to have an object as a query parameter. This is [not supported in OpenAPI 2.0](https://swagger.io/docs/specification/2-0/describing-parameters/#faq). swagger-codegen-cli-2x doesn't support OpenAPI 2.0, so I'm trying swagger-codegen-cli-3.0.0-rc0.jar. I get a NullPointerException:

```
java -jar ~/swagger-codegen-cli-3.0.0-rc0.jar generate -i api/api3.yaml -l javascript -o ui/src/api -DuseES6=true 
[Thread-1] INFO io.swagger.codegen.languages.JavascriptClientCodegen - Using JS ES6 templates
Exception in thread "Thread-1" java.lang.NullPointerException
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:315)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:722)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:312)
	at java.lang.Thread.run(Thread.java:745)
```

Something is wrong with my yaml, but there's no error message to help me fix it.

##### Swagger-codegen version

3.0.0-rc0

##### Swagger declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Data Explorer Service
  description: API Service that reads from Elasticsearch.
  license:
    name: BSD
    url: 'http://opensource.org/licenses/BSD-3-Clause'
  version: 0.0.1
paths:
  /facets:
    get:
      description: Returns facets.
#      parameters:
#        - name: body
#          description: >
#            May be empty.
#          in: body
#          schema:
#            $ref: '#/definitions/FacetsRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/FacetsResponse'
      tags:
        - Facets
definitions:
  FacetsRequest:
    properties:
      facetFilters:
        type: array
        description: May be empty.
        items:
          $ref: '#/definitions/FacetFilter'
  FacetFilter:
    description: >
      FacetFilter represents what checkboxes have been selected for a facet.
      FacetFilter will be used to filter the Elasticsearch query.
    properties:
      facetName:
        type: string
        description: 'Facet name, for example, "Region"'
      values:
        type: array
        description: >
          Which facet values are selected, for example, "northwest",
          "southwest". At least one facet value must be included. If no facet
          values are included, a 400 will be returned.
        items:
          type: string
  FacetsResponse:
    description: Results from a faceted search.
    properties:
      facets:
        type: array
        items:
          $ref: '#/definitions/Facet'
      count:
        type: integer
        description: >
          Number of entities represented by current facet selection. For
          example, this could be 40, representing 40 people.
  Facet:
    description: >
      A facet. For example, the Gender facet would include the facet name
      "Gender", as well as counts for all possible values.
    properties:
      name:
        type: string
        description: 'Facet name, for example, "Gender".'
      values:
        type: array
        items:
          $ref: '#/definitions/FacetValue'
  FacetValue:
    description: 'A facet value, for example, "Male"/34.'
    properties:
      name:
        type: string
        description: 'Facet value name, for example, "Male".'
      count:
        type: integer
        description: Facet value count.

```

##### Command line used for generation

java -jar ~/swagger-codegen-cli-3.0.0-rc0.jar generate -i api/api3.yaml -l javascript -o ui/src/api -DuseES6=true 

##### Steps to reproduce

Just run command with that yaml.

##### Suggest a fix/enhancement

Provide a more informative error message.

**Comment by HugoMario** [comment]
Hello @melissachang sorry for this late response.

This NPE is fixed on `3.0.0-SNAPSHOT` version, however the `javascript` language is still not supported on `swagger-codegen` v3. So i'm going to close this for now.
