### ISSUE TITLE
Unable to use Patch using patchNamespacedDeployment client-java-1.0.0-beta3-SNAPSHOT.jar of Kubernetes

### ISSUE THREAD

**Issue by HarsimranAvaya** [swagger-api/swagger-codegen#7944]
##### Description
Patch operation fails when passing this structure as body:
`static String PatchStr = "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"com-container\",\"image\":\"xxx/xxx/xxx-xxx:3.0.1.45\"}]}}}}";` .My requirement is to update the container based on its image value.

Getting this error:
 PATCH https://xx.xx.xx.xxx/apis/extensions/v1beta1/namespaces/default/deployments/xxx?pretty=false HTTP/1.1
Content-Type: application/json-patch+json; charset=utf-8
Content-Length: 124
authorization: Token xxxxxxxxxxxxxxxxxxxxxxxxxxx
Accept: application/json
User-Agent: Swagger-Codegen/1.0-SNAPSHOT/java

[{"spec":{"template":{"spec":{"containers":[{"name":"xxx-xxx","image":"xxx/xxxxxxx/xxx-app:3.0.1.45"}]}}}}]
--> END PATCH (124-byte body)
<-- HTTP/1.1 500 Internal Server Error (1257ms)
Content-Type: application/json
Date: Fri, 30 Mar 2018 08:12:57 GMT
Content-Length: 117
OkHttp-Sent-Millis: 1522397577354
OkHttp-Received-Millis: 1522397577559

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unexpected kind: unknown","code":500}

<-- END HTTP (117-byte body)
Exception in thread "main" io.kubernetes.client.ApiException: Internal Server Error
        at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:882)
        at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
        at io.kubernetes.client.apis.ExtensionsV1beta1Api.patchNamespacedDeploymentWithHttpInfo(ExtensionsV1beta1Api.java:5617)
        at io.kubernetes.client.apis.ExtensionsV1beta1Api.patchNamespacedDeployment(ExtensionsV1beta1Api.java:5600)
        at io.kubernetes.client.examples.UpdateExample.main(UpdateExample.java:76)

**Comment by HarsimranAvaya** [comment]
Same works if I supply patch like this `static String jsonPatchStr = "{ \"op\": \"replace\", \"path\":\"/spec/template/spec/containers/1/image\", \"value\":\"XXXXXX/XXXX:3.0.1.45\" }";`.
