### ISSUE TITLE
cannot generated JAVA client from valid YAML file

### ISSUE THREAD

**Issue by blasto333** [swagger-api/swagger-codegen#8028]
##### Description

Cannot generate java code given valid YAML file.

`java -jar swagger-codegen.jar generate -i https://app.swaggerhub.com/apiproxy/schema/file/PHP-Point-Of-Sale/PHP-Point-Of-Sale/1.0/swagger.yaml -l java -o /Users/cmuench/Desktop/api
`
error

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not process model 'PriceRuleResponse'.Please make sure that your schema is correct!
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:363)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.languages.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1265)
	at io.swagger.codegen.languages.java.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:855)
	at io.swagger.codegen.languages.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1177)
	at io.swagger.codegen.languages.java.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:866)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:961)
	at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:358)
	... 3 more

```

##### Swagger-codegen version

3.0.0-SNAPSHOT

##### Swagger declaration file content or url

https://app.swaggerhub.com/apis/PHP-Point-Of-Sale/PHP-Point-Of-Sale/1.0

##### Command line used for generation

`java -jar swagger-codegen.jar generate -i https://app.swaggerhub.com/apiproxy/schema/file/PHP-Point-Of-Sale/PHP-Point-Of-Sale/1.0/swagger.yaml -l java -o /Users/cmuench/Desktop/api
`
##### Steps to reproduce

Run the command above and error will happen as shown above

##### Related issues/PRs

[https://github.com/swagger-api/swagger-codegen/issues/7330](https://github.com/swagger-api/swagger-codegen/issues/7330
)
##### Suggest a fix/enhancement

Not sure how to fix

**Comment by HugoMario** [comment]
thanks @blasto333 , i'm going to check this.

**Comment by blasto333** [comment]
@HugoMario Thanks! Let me know if you need anything from me

**Comment by blasto333** [comment]
Tried from 3.0.0 latest branch (176c5e538b0fabdb958a1ecdc32653ba68f0736a)

`java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i https://app.swaggerhub.com/apiproxy/schema/file/PHP-Point-Of-Sale/PHP-Point-Of-Sale/1.0/swagger.yaml -l java -o /Users/cmuench/Desktop/api`
