### ISSUE TITLE
latest 3.0.0 snapshot missing languages

### ISSUE THREAD

**Issue by chrisdostert** [swagger-api/swagger-codegen#8093]
##### Description

As an example, using the [3.0.0rc build](http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/3.0.0-rc0/swagger-codegen-cli-3.0.0-rc0.jar) javascript is available as a language, but in the [latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180411.134218-60.jar) it's not. 

This is the error:
```shell
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name javascript Available: dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-resteasy-eap
jaxrs-resteasy

        at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:93)
Caused by: java.lang.ClassNotFoundException: javascript
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
        ... 1 more
```
##### Swagger-codegen version

swagger-codegen-cli-3.0.0-20180411.134218-60

**Comment by chrisdostert** [comment]
Appears they [were all deleted](https://github.com/swagger-api/swagger-codegen/commit/c91d3648c9f24c010fbd3666eac22f065929e406#diff-931c345866b0a416a263b881c1a7d829) post rc being cut. Is support being dropped for majority of languages, what's the plan? @HugoMario

**Comment by nerumo** [comment]
Uuhhmm...support is dropped??? Is there a discussion board/ticket about the future of this project? I'm quite confused about the loss of so much functionality

**Comment by HugoMario** [comment]
Hello @nerumo 

Please check this [RC notes](https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0-rc0) 

also these links can give you a guide:

**Comment by HugoMario** [comment]
btw, just to answer your question, support is not dropped.
