### ISSUE TITLE
RuntimeException when "headers" response section is defined

### ISSUE THREAD

**Issue by gchauvet** [swagger-api/swagger-codegen#8139]
Hi,

I'm facing to an issue with codegen when headers response section is defined. Remove it works.
```json
    ....
   "responses":{  
      "200":{  
         "description":"OK",
         "headers":{  
            "X-app-params":{  
               "type":"integer",
               "description":"...................."
            }
         }
      }
   }
   ****
```
Command line output result :
```sh
java -jar swagger-codegen-cli-2.3.1.jar generate -i api-docs.json -l java -o project -c config.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from api-docs.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from api-docs.json
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:731)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

Regards

**Comment by gchauvet** [comment]
Bump,
Maybe more suitable to swagger-parser issues ?
