### ISSUE TITLE
swagger-codegen throwing error when trying to create static html from openapi v3 json file

### ISSUE THREAD

**Issue by vipinvkmenon** [swagger-api/swagger-codegen#8146]
when I run the command 
`swagger-codegen generate -i openapi-pet.json -o Target/ -l html`

I get the error

> Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
> 	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:731)
> 	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
> 	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

I was using the [ petstore V3](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml)

which I converted into its JSON format from the [swagger editor ](https://editor.swagger.io/)

**Comment by tommilligan-plutoflume** [comment]
Please at least reference a tracking issue when closing - came here with the same issue. #6598
