### ISSUE TITLE
NullPointerException when deal with swaggerVersion=1.2

### ISSUE THREAD

**Issue by shibormot** [swagger-api/swagger-codegen#8149]
##### Description
I got NullPointerException, when I try to generate golang client from 
https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources
There is no helpful error message from code generator to resolve problem with source file

##### Swagger-codegen version

Vesion: 2.3.1

##### Swagger declaration file content or url

https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources

##### Command line used for generation

```
$ java -version
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)

$wget http://central.maven.org/maven2/io/swagger/swagger-codegen-cli/2.3.1/swagger-codegen-cli-2.3.1.jar -O swagger-codegen-cli.jar

$ java -jar swagger-codegen-cli.jar validate -i https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources
Validating spec file (https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources)
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.convertProperty(SwaggerCompatConverter.java:225)
	at io.swagger.parser.SwaggerCompatConverter.convertModel(SwaggerCompatConverter.java:214)
	at io.swagger.parser.SwaggerCompatConverter.convert(SwaggerCompatConverter.java:586)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:176)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:87)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:41)
	at io.swagger.codegen.cmd.Validate.run(Validate.java:25)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

```

**Comment by shibormot** [comment]
Finally, with help of converter https://github.com/LucyBot-Inc/api-spec-converter , I got a generated client for yandex.net API. So issue can be closed.
