### ISSUE TITLE
Error java.lang.NullPointerException when generate API for Yandex Disk

### ISSUE THREAD

**Issue by andreevlex** [swagger-api/swagger-codegen#8166]
##### Description
I am want generate client for yandex api.
Use [Swagger Codegen CLI Docker Image](https://github.com/swagger-api/swagger-codegen#swagger-codegen-cli-docker-image)
When run 
```bash
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources -l rust -o /local/v1_disk_resources
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.convertProperty(SwaggerCompatConverter.java:246)
	at io.swagger.parser.SwaggerCompatConverter.convertModel(SwaggerCompatConverter.java:235)
	at io.swagger.parser.SwaggerCompatConverter.convert(SwaggerCompatConverter.java:621)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:182)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:75)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:431)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:283)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

##### Swagger-codegen version
2.3.1 from  [Swagger Codegen CLI Docker Image](https://github.com/swagger-api/swagger-codegen#swagger-codegen-cli-docker-image)

##### Swagger declaration file content or url

https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources

##### Steps to reproduce
```bash
docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i https://cloud-api.yandex.net/v1/schema/resources/v1/disk/resources -l rust -o /local/v1_disk_resources
```

**Comment by bjgill** [comment]
The problems looks to be that the `info.version` field is required, but not provided in that spec. If you add that, it should fix this problem for you.

Of course, it would be nice if `rust`/`rust-server` gave a clearer error message.

**Comment by andreevlex** [comment]
this part of the API is normally generated:
https://cloud-api.yandex.net/v1/schema/resources/v1/disk
