### ISSUE TITLE
File not found after the last merge of today 5 June

### ISSUE THREAD

**Issue by uniprof** [swagger-api/swagger-codegen#822]
writing file /Users/giuseppeporcelli/git/swagger-codegen-original/easyDocs/client/csharp/src/main/csharp/IO/Swagger/Client/ApiClient.cs
java.io.FileNotFoundException: csharp/ApiException.mustache (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.wordnik.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:44)
	at com.wordnik.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:28)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:253)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:102)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
java.lang.RuntimeException: can't load template csharp/ApiException.mustache
	at com.wordnik.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:52)
	at com.wordnik.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:28)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:253)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:102)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
java.lang.RuntimeException: can't load template csharp/ApiException.mustache
	at com.wordnik.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:37)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:253)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:102)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

**Comment by uniprof** [comment]
I found the problem, apiException.mustache need to be remaned to ApiException.mustache, pulling the changes in two minutes.

**Comment by wing328** [comment]
My apologies. It was due to me not using `git mv` to rename the file. Submitted #823 to address the issue.

**Comment by webron** [comment]
Fixed in develop_2.0.
