### ISSUE TITLE
[JAVA] Generated api client doesn't work for plain text body types

### ISSUE THREAD

**Issue by Kiolali** [swagger-api/swagger-codegen#8288]
##### Description

The generated API Client for Java does not work properly for plain string body types. The error message is: 
io.swagger.client.ApiException: Content type "text/plain" is not supported
    at io.swagger.client.ApiClient.serialize(ApiClient.java:749)
    at io.swagger.client.ApiClient.buildRequest(ApiClient.java:994)
    at io.swagger.client.ApiClient.buildCall(ApiClient.java:945)
    at io.swagger.client.api.DefaultApi.addTodoCall(DefaultApi.java:103)

##### Swagger-codegen version

2.4.0

##### Swagger declaration file content or url
```json
  /todo:
    post:
      summary: Add new ToDo
      description: ''
      operationId: addTodo
      consumes:
        - text/plain
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Task'
```

##### Command line used for generation

java -jar .\modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i ..../swagger.json -l java -o outputpath 

##### Suggest a fix/enhancement

add new else if in ApiClient.java in method " public RequestBody serialize(Object obj, String contentType) throws ApiException":

```
 } else if (obj instanceof String) {
            return RequestBody.create(MediaType.parse(contentType), (String) obj);
```

**Comment by sknick** [comment]
I can confirm this is an issue.

**Comment by november1306** [comment]
@HugoMario 
hi, any news about this issue?

@Kiolali 
did you found a suitable workaround to use plain/text in body?

**Comment by Kiolali** [comment]
yes! I used the suggested fix (add new else if in ApiClient.java in method " public RequestBody serialize(Object obj, String contentType) throws ApiException":)

**Comment by HugoMario** [comment]
hey @november1306, i'm really busy right now with other codegen issues. if somebbody else can propose a PR , it would be really appreciated.

**Comment by sknick** [comment]
@HugoMario I don't do swagger-codegen development, so I'm not really set up to run everything, but I've committed a bare bones PR with the change identified in it. Can you grab it and finish it out?

**Comment by HugoMario** [comment]
thanks @sknick, i'll take a look!

**Comment by Kiolali** [comment]
still a bug in openapi-generator 4.0.0

**Comment by roded** [comment]
Would be nice to have this fixed. What assistance is required?

**Comment by sknick** [comment]
@roded Someone just needs to take the MR I already made (https://github.com/swagger-api/swagger-codegen/pull/8697) and make sure it's good for merge.
