### ISSUE TITLE
HandlebarsException in kotlin-client (swagger 3.0.0-rc1)

### ISSUE THREAD

**Issue by kroegerama** [swagger-api/swagger-codegen#8300]
I'm getting the following error when I try to generate a kotlin-client with v3.0.0-rc1:

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'body'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.github.jknack.handlebars.HandlebarsException: /v2/kotlin-client/class_doc.mustache:6:133: found: '}}}', expected: '}}'
{{#vars}}**{{name}}** | {{#is this 'enum'}}[**inline**](#{{datatypeWithEnum}}){{/is}}{{#isNot this 'enum'}}{{#is this 'primitiveType'}}}**{{datatype}}**{{/is}}}{{#isNot this 'primitiveType'}}[**{{datatype}}**](
{{complexType}}.md){{/is}}}{{/is}} | {{description}} | {{^required}} [optional]{{/required}}{{#readOnly}} [readonly]{{/readOnly}}
```

The same file works fine with swagger 2

**Comment by HugoMario** [comment]
Hey @kroegerama, this was fixed for 3.0.0-SNAPSHOT, when you have a chance, can you please check if this issue is still present?

**Comment by kroegerama** [comment]
@HugoMario the issue is still present in `swagger-codegen-cli-3.0.0-20180608.091024-78.jar`

**Comment by kroegerama** [comment]
@HugoMario The problem seems to be fixed, thank you. However, now I'm having the following issue: #8324
