### ISSUE TITLE
Exception while generating java code (swagger 3.0.0-rc1)

### ISSUE THREAD

**Issue by kroegerama** [swagger-api/swagger-codegen#8301]
I'm getting the following error when I try to generate a java client with v3.0.0-rc1:

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'body'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
v2\Java
   ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.escape(Unknown Source)
        at java.util.regex.Pattern.atom(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.lang.String.replaceFirst(Unknown Source)
        at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1014)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:744)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
        ... 3 more
```

My file works fine with swagger 2

**Comment by HugoMario** [comment]
hey @kroegerama this was already fixed for `3.0.0-SNAPSHOT`, can you try and let us know if the issue is still present?

**Comment by kroegerama** [comment]
Hi @HugoMario after updating to version `swagger-codegen-cli-3.0.0-20180608.091024-78.jar`, I get the following error:

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'body'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:729)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: /v2\Java/model.mustache
        at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
        at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1027)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:745)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
        ... 3 more
```

**Comment by HugoMario** [comment]
@kroegerama 
can you please share your definition?

**Comment by kroegerama** [comment]
Sorry, I am not allowed to share the exact definition.

But the following definition:
```yaml
swagger: '2.0'
info:
  version: 1.0.1
host: example.com
basePath: /api/v1
schemes:
  - https
securityDefinitions:
  Token:
    type: apiKey
    in: query
    name: token
paths:
  '/products/home':
    get:
      operationId: getProducts
      tags:
        - Product
      parameters:
        - name: page
          in: query
          required: true
          type: integer
        - name: itemCount
          in: query
          required: true
          type: integer
      responses:
        '200':
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
definitions:
  Product:
    type: object
    title: Product
    properties:
      id:
        type: string
      title:
        type: string
      simmilar:
        type: array
        items:
          $ref: '#/definitions/Product'
```

Generates an exception as well:
```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'Product'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:729)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: /v2\Java/model.mustache
        at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
        at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1027)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:745)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
        ... 3 more
```

**Comment by HugoMario** [comment]
Hey @kroegerama can you please try with this new version: [swagger-codegen-cli-2.4.0-20180613.124022-270.jar](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.4.0-SNAPSHOT/swagger-codegen-cli-2.4.0-20180613.124022-270.jar)

I've testing on windows with this and works pretty fine.

**Comment by kroegerama** [comment]
@HugoMario your new version is 2.4.0, but my bug report was about 3.0.0

**Comment by HugoMario** [comment]
omg, sorry, my bad. @kroegerama please try with this one [swagger-codegen-cli-3.0.0-20180615.112032-79.jar](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180615.112032-79.jar) and let me know how it works for you.

**Comment by kroegerama** [comment]
@HugoMario Seems not to be fixed for me. I'm still getting the same error.

**Comment by HugoMario** [comment]
PR . #8327 should solve this issue, @kroegerama can you please check this when you have a chance?

You can use this version: [swagger-codegen-cli-3.0.0-20180616.164244-81.jar](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180616.164244-81.jar)

**Comment by kroegerama** [comment]
Thanks a lot! Seems to be fixed. @HugoMario

**Comment by PetervLeeuwen** [comment]
I have added a fix for this issue in another GitHub issue which is about the same topic.
[#8273](https://github.com/swagger-api/swagger-codegen/issues/8273#issuecomment-505351284)
