### ISSUE TITLE
RuntimeException (FileNotFound) in kotlin-client (swagger 3.0.0-SNAPSHOT-79)

### ISSUE THREAD

**Issue by kroegerama** [swagger-api/swagger-codegen#8324]
I'm getting the following error when trying to generate **kotlin-client** with version `swagger-codegen-cli-3.0.0-20180615.112032-79.jar`

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate supporting file 'Supporting
        templateFile: README.mustache
        folder:
        destinationFilename: README.md
'
        at io.swagger.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:614)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:736)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: /v2/kotlin-client/v2/kotlin-client/README.mustache
        at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
        at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1027)
        at io.swagger.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:581)
        ... 3 more
```

**Comment by HugoMario** [comment]
hey @kroegerama i added a PR to fix this issue, can you please test with [swagger-codegen-cli-3.0.0-20180616.164244-81.jar](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/3.0.0-SNAPSHOT/swagger-codegen-cli-3.0.0-20180616.164244-81.jar) and let me know if issue is still present?

**Comment by kroegerama** [comment]
Thanks for all your work, @HugoMario. Works fine now! :)
