### ISSUE TITLE
Nullpointer exception in swagger-codegen with java 

### ISSUE THREAD

**Issue by sajhak** [swagger-api/swagger-codegen#8348]
##### Description

When trying to do java codegen with swagger cli, I'm getting a NPE
Swagger json is valid one, has validated using swagger UI

Error log
---------
Exception in thread "Thread-1" java.lang.NullPointerException
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:849)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:827)
	at io.swagger.v3.parser.converter.SwaggerConverter.lambda$convert$11(SwaggerConverter.java:1049)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1048)
	at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:212)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:90)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:19)
	at io.swagger.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:433)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:310)
	at java.lang.Thread.run(Thread.java:748)

##### Swagger-codegen version
Tried in both 3.0.0-rc0 and 3.0.0-rc1

##### Swagger declaration file content or url

Sorry, the swagger cannot be pasted here due to privacy reasons

##### Command line used for generation
I have downloaded the swagger file as a json into my local filesystem
$ java -jar swagger-codegen-cli.jar generate -i swagger.json -l java -o /tmp

##### Steps to reproduce

Downloaded the 3.0.0-rc0 and 3.0.0-rc1 sources from github, and did a local build in Mac, to get the swagger-codegen-cli binary
Then executed following
 $ java -jar swagger-codegen-cli.jar generate -i swagger.json -l java -o /tmp

**Comment by HugoMario** [comment]
hi @sajhak , can you please try with https://github.com/swagger-api/swagger-codegen/releases/tag/v3.0.0 ?
and let me know if the issue is till present?
