### ISSUE TITLE
Python client code is wrong when an endpoint accept multiple MediaTypes

### ISSUE THREAD

**Issue by raubel** [swagger-api/swagger-codegen#8377]
##### Description

My OpenApi 3.0 specification contains an endpoint for which the response media type can be `application/octet-stream` or, if the query cannot be completed, `application/json`.
The generated Python client code builds a query with a MediaType being the concatenation of both: `application/octet-streamapplication/json`

##### Swagger-codegen version

Codegen 3.0.0-rc1

##### Swagger declaration file content or url

Below is my (simplified) OpenApi specification:
```yaml
openapi: 3.0.0

servers:
- url: http://localhost/myapi

info:
  version: "1.0"
  title: My API

security:
- basicAuth: []

paths:

  /download:
    get:
      operationId: download
      responses:
        200:
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        500:
          description: Error
          content:
            application/json:
              schema:
                type: string
```

##### Command line used for generation

I call Swagger Codegen directly from my Java application:
```java
	CodegenConfigurator configurator = new CodegenConfigurator();
	configurator.setInputSpec("spec.yml");
	configurator.setGeneratorName("python");
	configurator.setOutputDir("out");
	new DefaultGenerator().opts(configurator.toClientOptInput()).generate();
```

##### Python test file

Running this script
```python
import unittest
import openapi_client

configuration = openapi_client.Configuration()
configuration.debug = True

# create an instance of the API class
api_instance = openapi_client.DefaultApi(openapi_client.ApiClient(configuration))

class TestModels(unittest.TestCase):
    def test_download(self):
        api_instance.download()

if __name__ == '__main__':
    unittest.main()
```

results in the following output:
```
2018-07-02 15:17:38,841 DEBUG Starting new HTTP connection (1): localhost
send: 'GET /myapi HTTP/1.1\r\nHost: localhost:10080\r\nAccept-Encoding: identity\r\nContent-Type: application/json\r\nAccept: application/octet-streamapplication/json\r\nAuthorization: Basic c2VtYWRtaW46c2VtYWRtaW4=\r\nUser-Agent: OpenAPI-Generator/1.0.0/python\r\n\r\n'
reply: 'HTTP/1.1 406 Not Acceptable\r\n'
...
```

**Comment by poli-granot** [comment]
How are you able to generate a Python client?
I'm running the command -
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i openapi3.yaml -l python -o /outdir
And getting the following:
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name python Available: dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
spring
kotlin-client
kotlin-server
php
swift3
swift4
typescript-angular

	at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:93)
Caused by: java.lang.ClassNotFoundException: python
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.swagger.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
	... 1 more
