### ISSUE TITLE
[ALL] Boolean cannot be cast to Schema

### ISSUE THREAD

**Issue by JDziurlaj** [swagger-api/swagger-codegen#8390]
##### Description

I'm running into an issue where `swagger-codegen` fails to generate files for any generation target when referencing an external schema, with a variant of the following error

```java
Exception in thread "Thread-0" java.lang.RuntimeException: Could not process model 'VRI.RegistrationHelper'.Please make sure that your schema is correct!
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:363)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:724)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: java.base/java.lang.Boolean cannot be cast to io.swagger.v3.oas.models.media.Schema
```

I have no concerns that my external schemas are valid, `swagger-editor` is able to parse and generate documentation for them, they pass JSON schema validation tools, etc.

This schema is quite complex, and I wish I had a simpler example to give you, but I do not. However, I've linked the schemas and OpenAPI file to this issue.

##### Swagger-codegen version

3.0.0-SNAPSHOT. Regression status unknown. Has always been a 3.0.0 target.

##### Swagger declaration file content or url

[gist](https://gist.github.com/JDziurlaj/7c319c34f0fc15b6ec46a83633f4b987)
[linked schema 1](https://gist.github.com/JDziurlaj/de4ec9e98e35ae6f8a257532fb83c148)
[linked schema 2](https://gist.github.com/JDziurlaj/2f48bf5a1f267baf6eacedca3068797a)

##### Command line used for generation

java -jar swagger-codegen-cli.jar generate -i vri.yaml -l java -o ./

##### Steps to reproduce

Run command found in `Command line used for generation`

##### Related issues/PRs

None.

**Comment by bkstorm** [comment]
Same problem. I'm using swagger v3.0.3 to generate client sdk for https://github.com/strongloop/loopback4-example-shopping.
It works fine with swift 4, typescript-angular and java. But when it generates code to kotlin-client, it shows an error:

> Exception in thread "Thread-1" java.lang.RuntimeException: Could not process model 'inline_response_200'.Please make sure that your schema is correct!
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:354)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:719)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to io.swagger.v3.oas.models.media.Schema
        at io.swagger.codegen.v3.generators.kotlin.AbstractKotlinCodegen.getTypeDeclaration(AbstractKotlinCodegen.java:275)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromProperty(DefaultCodegenConfig.java:1621)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addVars(DefaultCodegenConfig.java:2917)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addVars(DefaultCodegenConfig.java:2888)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.addVars(DefaultCodegenConfig.java:2876)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1345)
        at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:951)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:349)
        ... 3 more

Do you have any ideas?

**Comment by le-yak** [comment]
I was unable to use JDziurlaj'files (OP).
bkstorm's JSON file did not pass validation but with `--skip-validate-spec` I confirm that I was able to successfuly generate code (actual output not checked) on master (7cc9f9a).

However, I initially came here to report the same exception when generating from [this OpenApi definition](https://gist.github.com/le-yak/003831f8945211904dba47c939b1231a).
Works fine on [tag v5.3.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.3.0), exception appears from https://github.com/OpenAPITools/openapi-generator/commit/3a667784acab58d5107daf557cd1ba7bb679e0a1 onwards.
