### ISSUE TITLE
Cannot read input from json file

### ISSUE THREAD

**Issue by pcfountain** [swagger-api/swagger-codegen#8408]
##### Description

When I try to generate content using a local swagger.json file, it shows that it attempts to parse the file twice (?), and I get the following output with error message:

`C:\CODE\Projects\swagger-codegen>java -jar swagger-codegen-cli-2.3.1.jar generate -l html2 -i ./swagger.json -o enterprise
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from ./swagger.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:731)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)`

However, the same command works fine, if the input file comes from my local web server:

`C:\CODE\Projects\swagger-codegen>java -jar swagger-codegen-cli-2.3.1.jar generate -l html2 -i http://localhost/INS/swagger/docs/93MR4 -o enterprise
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://localhost/INS/swagger/docs/93MR4
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
[main] ERROR io.swagger.codegen.DefaultCodegen - Swagger object description is empty [InService Network Enterprise]
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `traceTraceUp_0`
[main] WARN io.swagger.codegen.DefaultCodegen - generated unique operationId `traceTraceDown_0`
[main] INFO io.swagger.codegen.AbstractGenerator - writing file C:\CODE\Projects\swagger-codegen\enterprise\index.html
[main] INFO io.swagger.codegen.AbstractGenerator - writing file C:\CODE\Projects\swagger-codegen\enterprise\.swagger-codegen-ignore
[main] INFO io.swagger.codegen.AbstractGenerator - writing file C:\CODE\Projects\swagger-codegen\enterprise\.swagger-codegen\VERSION`

The JSON input is the same in either case, here is the flat file:
[swagger.json.txt](https://github.com/swagger-api/swagger-codegen/files/2181861/swagger.json.txt)

I am using Windows 10.

##### Swagger-codegen version

2.3.1

##### Command line used for generation

[NOT WORKING] `java -jar swagger-codegen-cli-2.3.1.jar generate -l html2 -i ./swagger.json -o enterprise`
[WORKING] `java -jar swagger-codegen-cli-2.3.1.jar generate -l html2 -i http://localhost/INS/swagger/docs/93MR4 -o enterprise`

**Comment by pcfountain** [comment]
Well, something was wrong with my swagger.json file. When I re-generated the file with some different settings, it started working. Still, it seems an error should be produced if Swagger20Parser cannot parse the file.
