### ISSUE TITLE
version 3.0.0-rc1 not working with angular

### ISSUE THREAD

**Issue by scott-ho** [swagger-api/swagger-codegen#8471]
##### Description

upgrading to v3 makes generation failed.

##### Swagger-codegen version

3.0.0-rc1
##### Command line used for generation

```
java -jar .\swagger-codegen-cli-3.0.0-rc1.jar generate `
 -l typescript-angular `
  -i .\xxx-Service-2.0.0-swagger.yaml `
   -o xxx `
     --additional-properties modelPropertyNaming=original
```

##### Output

```
[Thread-1] INFO io.swagger.codegen.languages.typescript.TypeScriptAngularClientCodegen -   (you can select t
he angular version by setting the additionalProperty ngVersion)
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'CreateLocalProfileModel
'
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:409)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:728)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:331)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: /v2\typescript-angular/v2/typescript-angular/model.mustache
        at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
        at io.swagger.codegen.DefaultGenerator.getHandlebars(DefaultGenerator.java:1026)
        at io.swagger.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:744)
        at io.swagger.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:396)
        ... 3 more

```

**Comment by scott-ho** [comment]
it should be swagger 2.0 format for my spec
