### ISSUE TITLE
$ref as last element in allOf causes hidden exception in generator service

### ISSUE THREAD

**Issue by john-french** [swagger-api/swagger-codegen#8475]
Generator service returns `400` when a structure like the one below is used. 

```json
ListOfSomeStuff": {
  "allOf": [
    {
      "type": "object",
      "required": [
        "endDate",
        "startDate"
      ],
      "properties": {
        "startDate": {
          "type": "string",
          "format": "date",
          "example": "2018-07-01",
          "description": "Start Date"
        },
        "endDate": {
          "type": "string",
          "format": "date",
          "example": "2018-07-31",
          "description": "End Date"
        }
      }
    },
    {
      "$ref": "#/definitions/Stuff"
    }
  ]
}
```

The cause of the error is revealed by adding more logging [here](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L374). 

Looks like DefaultCodegen expects that using allOf has a $ref as the first element. In this case, it's the last, and that's causing this error (which is hidden without additional logging at the point mentioned above):

```
Could not generate file: Unable to build target: Could not process model 'ListOfSomeStuff'.Please make sure that your schema is correct!

java.lang.ClassCastException: io.swagger.models.ModelImpl cannot be cast to io.swagger.models.RefModel
	at io.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1249)
	at io.swagger.codegen.languages.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:627)
	at io.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:910)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:290)
	at io.swagger.generator.online.Generator.generate(Generator.java:159)
	at io.swagger.generator.online.Generator.generateClient(Generator.java:55)
```

**Comment by frantuma** [comment]
fixed in #8476
