### ISSUE TITLE
[Windows, nodejs server] Unable to create servers that use DefaultGenerator.java

### ISSUE THREAD

**Issue by wol190** [swagger-api/swagger-codegen#8482]
##### Description
I'm able to build swagger-codegen (mvn clean package), where all tests pass [Windows 8.1, via the regular command prompt]. However, swagger-codegen-cli.jar is unable to build certain server stubs, e.g.:
java -jar swagger-codegen-cli-2.4.0-20180724.120057-301.jar generate -l nodejs-server -i C:\tmp\petstore-simple.yaml -o C:\tmp\nodejs

Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Default'
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:546)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:752)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Unknown Source)
        at java.base/java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.base/java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.base/java.lang.String.replaceAll(Unknown Source)
        at io.swagger.codegen.languages.NodeJSServerCodegen.apiFilename(NodeJSServerCodegen.java:163)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:498)

Same for kotlin-server, but ada-server ok. It points towards the override of apiFileFolder().

##### Swagger-codegen version
2.4.0. Branch: master (cloned 24th July 2018)

##### Swagger declaration file content or url
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-simple.yaml

**Comment by chandrahasan** [comment]
**I am also having the same issue when generating NodeJs-Server,** 

```
$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
> -i http://petstore.swagger.io/v2/swagger.json \
> -l nodejs-server \
> -o F:\Swagger\serverstub\node
[main] INFO io.swagger.parser.Swagger20Parser - reading from http://petstore.swagger.io/v2/swagger.json
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Pet'
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:547)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:754)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
        at java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.lang.String.replaceAll(Unknown Source)
        at io.swagger.codegen.languages.NodeJSServerCodegen.apiFilename(NodeJSServerCodegen.java:163)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:500)
        ... 3 more
```

**Comment by 7opf** [comment]
Can #9272 be merged?

**Comment by HugoMario** [comment]
@7opf done!
