### ISSUE TITLE
[python] cannot import name BoolQuery from import swagger_client

### ISSUE THREAD

**Issue by tarp2699** [swagger-api/swagger-codegen#8483]
##### Description
Hi,
I'm trying to build a python swagger client for Elastic's [ECE API](https://download.elasticsearch.org/cloud/1.1/elastic-cloud-enterprise-API-swagger.json)
A test script that imports swagger_client errors with the following.
```
C:\Python27\python.exe C:/bench/ece/scripts/test-connection.py
Traceback (most recent call last):
  File "C:/bench/ece/scripts/test-connection.py", line 3, in <module>
    import swagger_client
  File "build\bdist.win-amd64\egg\swagger_client\__init__.py", line 19, in <module>
    
  File "build\bdist.win-amd64\egg\swagger_client\api\__init__.py", line 6, in <module>
    
  File "build\bdist.win-amd64\egg\swagger_client\api\clusters_elasticsearch_api.py", line 21, in <module>
  File "build\bdist.win-amd64\egg\swagger_client\api_client.py", line 27, in <module>
  File "build\bdist.win-amd64\egg\swagger_client\models\__init__.py", line 32, in <module>
    
  File "build\bdist.win-amd64\egg\swagger_client\models\bool_query.py", line 19, in <module>
  File "build\bdist.win-amd64\egg\swagger_client\models\query_container.py", line 19, in <module>
ImportError: cannot import name BoolQuery
```
##### Swagger-codegen version
2.3.1
##### Swagger declaration file content or url
https://download.elasticsearch.org/cloud/1.1/elastic-cloud-enterprise-API-swagger.json
##### Command line used for generation

python
  import swagger_client

**Comment by greenpau** [comment]
@tarp2699 , I am seeing the same thing with tag `v3.0.10`.

**Comment by ematta** [comment]
I know this is old, but in case you see this use this codegen instead: https://github.com/openapitools/openapi-generator

**Comment by greenpau** [comment]
@ematta , i switched to openapi. Works well :-)
