### ISSUE TITLE
[Go] codegen doesn't work on WikiPedia's swagger spec

### ISSUE THREAD

**Issue by thekvs** [swagger-api/swagger-codegen#8762]
##### Description

Code generation for Go language fails when I use swaggerapi/swagger-codegen-cli Docker image for WikiPedia's updates stream. I have following error message:

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://stream.wikimedia.org/?spec
[main] INFO io.swagger.parser.Swagger20Parser - reading from https://stream.wikimedia.org/?spec
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:735)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

Codegeneration for Pet Store example works ok for Go language.

##### Swagger-codegen version

2.4.0-SNAPSHOT

##### Swagger declaration file content or url

[https://stream.wikimedia.org/?spec](https://stream.wikimedia.org/?spec)

##### Command line used for generation

`docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i https://stream.wikimedia.org/?spec -l go  -o /local/out/go`

##### Steps to reproduce

`docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate -i https://stream.wikimedia.org/?spec -l go  -o /local/out/go`

**Comment by beardeddragon5** [comment]
The spec shows a lot of errors if you put it in editor.swagger.io
