### ISSUE TITLE
Codegen failing with relative refs

### ISSUE THREAD

**Issue by yausername** [swagger-api/swagger-codegen#8787]
##### Description
Codegen fails for with error
```
[main] WARN io.swagger.codegen.DefaultCodegen - Empty operationId found for path: get /accounts/{name}. Renamed to auto-generated operationId: accountsNameGet
[main] ERROR io.swagger.codegen.DefaultCodegen - Cannot use Parameter io.swagger.models.parameters.RefParameter@5cd7d4e1 as Body Parameter
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: Accounts
	description: null
	externalDocs: null
	extensions:{}}
  Operation: null
  Resource: get /accounts/{name}
  Definitions: {VideoConstantNumber=io.swagger.models.ModelImpl@5d9e4116, VideoConstantString=io.swagger.models.ModelImpl@91ffdbce, VideoPrivacy=io.swagger.models.ModelImpl@98b5a245, Video=io.swagger.models.ModelImpl@42038414, VideoAbuse=io.swagger.models.ModelImpl@2b3f804d, VideoBlacklist=io.swagger.models.ModelImpl@a49aa7d8, VideoChannel=io.swagger.models.ModelImpl@9fe54a8c, VideoComment=io.swagger.models.ModelImpl@10fe31b, VideoCommentThreadTree=io.swagger.models.ModelImpl@9160b880, Avatar=io.swagger.models.ModelImpl@b6fbc89c, Actor=io.swagger.models.ModelImpl@169dd3e1, Account=io.swagger.models.ComposedModel@6b6858e1, User=io.swagger.models.ModelImpl@f0015871, ServerConfig=io.swagger.models.ModelImpl@5e981a59, Follow=io.swagger.models.ModelImpl@7ea55db5, Job=io.swagger.models.ModelImpl@8e425cc6, AddUserResponse=io.swagger.models.ModelImpl@a0a9ce5b, VideoUploadResponse=io.swagger.models.ModelImpl@1aabe269, CommentThreadResponse=io.swagger.models.ModelImpl@a4f4a394, CommentThreadPostResponse=io.swagger.models.ModelImpl@837d1c3, AddUser=io.swagger.models.ModelImpl@7f445e4c, UpdateUser=io.swagger.models.ModelImpl@7bd4c23f, UpdateMe=io.swagger.models.ModelImpl@43a90aeb, GetMeVideoRating=io.swagger.models.ModelImpl@200c57c6, RegisterUser=io.swagger.models.ModelImpl@b609b1c1, VideoChannelInput=io.swagger.models.ModelImpl@501e4666, Video_account=io.swagger.models.ModelImpl@f8e4c0ee, VideoAbuse_video=io.swagger.models.ModelImpl@4ddaa73, VideoChannel_ownerAccount=io.swagger.models.ModelImpl@a0a9ce5b, ServerConfig_signup=io.swagger.models.ModelImpl@652c3cf, ServerConfig_transcoding=io.swagger.models.ModelImpl@ab580235, ServerConfig_avatar_file_size=io.swagger.models.ModelImpl@e4ea870c, ServerConfig_avatar_file=io.swagger.models.ModelImpl@e80b612f, ServerConfig_avatar=io.swagger.models.ModelImpl@119cd72, ServerConfig_video_file=io.swagger.models.ModelImpl@ab07e6ab, ServerConfig_video=io.swagger.models.ModelImpl@db5d890c}
  Exception: io.swagger.models.parameters.RefParameter cannot be cast to io.swagger.models.parameters.BodyParameter
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:932)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:808)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:431)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:746)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.ClassCastException: io.swagger.models.parameters.RefParameter cannot be cast to io.swagger.models.parameters.BodyParameter
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2574)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2213)
	at io.swagger.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1057)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:881)
	... 5 more
```

##### Swagger-codegen version
2.3.1

##### Swagger declaration file content or url
https://raw.githubusercontent.com/Chocobozzz/PeerTube/develop/support/doc/api/openapi.yaml

##### Command line used for generation
`java -jar swagger-codegen-cli.jar generate -i ./openapi.yaml -l java`

##### Steps to reproduce
Get files from https://github.com/Chocobozzz/PeerTube/tree/develop/support/doc/api
and run `java -jar swagger-codegen-cli.jar generate -i ./openapi.yaml -l java`

##### Suggest a fix/enhancement

Changing `$ref: "accounts.yaml#/parameters/name"` to `$ref: "./accounts.yaml#/parameters/name"` fixes it. but should not required as per https://swagger.io/docs/specification/using-ref/

**Comment by TommyLike** [comment]
I guess this is already been fixed, since my version `2.4.0-SNAPSHOT` works well.

**Comment by yausername** [comment]
ok. I tested with version `2.4.0-SNAPSHOT` and it is working. 
Thanks.
