### ISSUE TITLE
[Kotlin] int type results in null pointer exception

### ISSUE THREAD

**Issue by Frozenstep** [swagger-api/swagger-codegen#8813]
##### Description

When generating swagger for our kotlin project, we hit a null pointer exception. After looking into it, it seems to originate from using int as a type (as opposed to Integer, int32, etc)

[main] WARN io.swagger.codegen.DefaultCodegen - Type is NULL for Serializable Parameter: orderDetailId
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: DocumentInfo
	description: null
	externalDocs: null
	extensions:{}}
  Operation: V1DocumentInfoUploadPost
  Resource: post /v1/DocumentInfo/upload

  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:940)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:819)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:439)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:754)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.languages.AbstractKotlinCodegen.toModelName(AbstractKotlinCodegen.java:445)
	at io.swagger.codegen.languages.AbstractKotlinCodegen.getSwaggerType(AbstractKotlinCodegen.java:252)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:1594)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2536)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2241)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:889)
	... 5 more

##### Swagger-codegen version

Master

##### Swagger declaration file content or url

"/v1/DocumentInfo/upload": {
      "post": {
        "tags": [
          "DocumentInfo"
        ],
        "operationId": "V1DocumentInfoUploadPost",
        "consumes": [
          "multipart/form-data",
        ],
        "produces": [

        ],
        "parameters": [
          {
            "name": "orderDetailId",
            "in": "query",
            "description": "OrderDetailId",
            "required": true,
            "type": "int"
          }
        ],
        "responses": {
          "204": {
            "description": "Success"
          }
        }
      }
    }

##### Command line used for generation

swagger-codegen generate -i swagger.json -l kotlin -o SwaggerClient/

##### Steps to reproduce

Have a property with type int as a parameter.

**Comment by Frozenstep** [comment]
@HugoMario

**Comment by Frozenstep** [comment]
We noticed that it seemed to turn the int parameters we were using into strings before, but something in the last few weeks has made it give us null instead.

**Comment by chetansanghi** [comment]
Please let know if in version 3.0.0 of Open API has been fixed.
