### ISSUE TITLE
[Java] NPE while generating Java/Spring code

### ISSUE THREAD

**Issue by springframeworkguru** [swagger-api/swagger-codegen#8859]
##### Description

Getting a NPE while parsing [this OA3 spec](https://github.com/velopaymentsapi/VeloOpenApi/tree/2.6.0-SNAPSHOT). 

I did have this working and generating code. I updated the spec, from the output I cannot determine root cause of error. 

The strange part is error seems to be related to CodegenParameters and not the OA3 spec. I made changes to the OA3 spec, and not the build parameters.

NPE is from the 3rd line of this method:

```java
public boolean isParameterNameUnique(CodegenParameter p, List<CodegenParameter> parameters) {
        for (CodegenParameter parameter : parameters) {
            if (System.identityHashCode(p) == System.identityHashCode(parameter)) {
                continue; // skip itself
            }

            if (p.paramName.equals(parameter.paramName)) {
                return false;
            }
        }

        return true;
}
```

Error:

```bash
  Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:996)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:887)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:489)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:848)
	at org.openapitools.codegen.plugin.CodeGenMojo.execute(CodeGenMojo.java:575)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.DefaultCodegen.isParameterNameUnique(DefaultCodegen.java:2525)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2425)
	at org.openapitools.codegen.languages.AbstractJavaCodegen.fromOperation(AbstractJavaCodegen.java:1130)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:964)
```

##### Swagger-codegen version

Version 3.3.1

* also fails on 3.3.0

##### Swagger declaration file content or url

OA3 Spec is available [here](https://github.com/velopaymentsapi/VeloOpenApi/tree/2.6.0-SNAPSHOT). 

##### Command line used for generation

mvn clean package

Note: I have two profiles defined (resttemplate - Spring 4 / webclient - Spring 5). Error happens with either profile active, or no profiles active.

##### Steps to reproduce

1. checkout project from github.
2. verify on branch 2.6.0-SNAPSHOT
3. run command - mvn clean package

**Comment by springframeworkguru** [comment]
Upgraded to latest release, was able to find root cause & fix syntax error in spec.
