### ISSUE TITLE
Java code gen truncates response body when the json response is large

### ISSUE THREAD

**Issue by jnadaraj** [swagger-api/swagger-codegen#8868]
##### Description

deserializing the response message from rest call truncates the json content and gives below error
===
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 47 column 33 path $.results[0].raw.
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
====
##### Swagger-codegen version
<artifactId>swagger-codegen-project</artifactId>
        <version>2.4.0-SNAPSHOT</version>

##### Command line used for generation

NA

##### Steps to reproduce

NA

##### Related issues/PRs

NA
##### Suggest a fix/enhancement

NA

**Comment by jnadaraj** [comment]
For the Raw fields coveo returns the data in Map object, to support the hashmap below defintion was ammended in SearchAPI.yml with the below properties for serialization.

API : https://platform.cloud.coveo.com/rest/search/v2/

 additionalProperties:
       
   $ref: '#/definitions/Object'
... Object:

    type: object

    properties: {}

The java client generated for Object had issue during deserialization because of empty properties. I have commented out the class Object annd could get the raw items returned in json.
