### ISSUE TITLE
Caused by: java.lang.NullPointerException at io.swagger.codegen.DefaultCodegen.getExamples(DefaultCodegen.java:3827)

### ISSUE THREAD

**Issue by RdeWilde** [swagger-api/swagger-codegen#8912]
##### Description
Generating a client throw an exception
```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Tag {
	name: objects
	description: null
	externalDocs: null
	extensions:{}}
...
  Exception: null
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:940)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:819)
	at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:439)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:754)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.codegen.DefaultCodegen.getExamples(DefaultCodegen.java:3827)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2275)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:889)
	... 5 more
```
##### Swagger-codegen version
`v3.0.2`

##### Swagger declaration file content or url
(just the relevant part, but it is for more post-request/body-params)
```json
        "/recreation/objects/{id}/information-request": {
            "post": {
                "tags": [
                    "objects"
                ],
                "summary": "Create information request on this object for relation",
                "description": "",
                "operationId": "informationRequest",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "minimum": "1",
                        "description": "Object id to request info on",
                        "required": true,
                        "type": "integer",
                        "format": "int64"
                    },
                    {
                        "name": "relation_id",
                        "in": "body",
                        "minimum": "1",
                        "description": "Relation to send information to",
                        "required": true,
                        "type": "integer",
                        "format": "int64"
                    },
                    {
                        "name": "per",
                        "in": "body",
                        "description": "Send information per mail or post",
                        "required": true,
                        "type": "string",
                        "enum": [
                            "mail",
                            "post"
                        ]
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/RecreationRentalType"
                            }
                        }
                    },
                    "404": {
                        "description": "Relation not found"
                    }
                },
                "security": [
                    {
                        "default": []
                    }
                ]
            }
```

##### Command line used for generation
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i https://dev.api.myhost.nl/documentation.json \
   -l php \
   -o ../../ \
   --git-user-id me \
   --git-repo-id "api-client-php" \
   -D packagePath=api-client-php
```

##### Steps to reproduce
Run the command and wait ~1 minute for error to show up

##### Related issues/PRs
Idk

##### Suggest a fix/enhancement
Seems like the param datatype isn't set correctly for body params? In the `DefaultCodegen` `getExamples` the 'object' is empty I'd guess

**Comment by hotmeteor** [comment]
@RdeWilde Did you figure this out?

**Comment by RdeWilde** [comment]
@hotmeteor I can't remember. Maybe there were restriction on having only one body param or something, or not mixing them. I can remember I was surprised and somehow used a workaround. Sorry i dont have the details anymore.
