### ISSUE TITLE
StackOverflowError on DefaultCodegen.isDiscriminatorInInterfaceTree

### ISSUE THREAD

**Issue by jonasbark** [swagger-api/swagger-codegen#8926]
##### Description

`java -jar swagger-codegen-cli-2.3.1.jar generate -i bitbucket.json -l dart -o bitbucket_api -c bitbucket_pr_config.json`

```
[main] INFO io.swagger.parser.Swagger20Parser - reading from bitbucket.json
[main] WARN io.swagger.codegen.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
Exception in thread "main" java.lang.StackOverflowError
	at io.swagger.codegen.DefaultCodegen.isDiscriminatorInInterfaceTree(DefaultCodegen.java:1473)
	at io.swagger.codegen.DefaultCodegen.isDiscriminatorInInterfaceTree(DefaultCodegen.java:1480)
	at io.swagger.codegen.DefaultCodegen.isDiscriminatorInInterfaceTree(DefaultCodegen.java:1480)
	at io.swagger.codegen.DefaultCodegen.isDiscriminatorInInterfaceTree(DefaultCodegen.java:1480)
```

##### Swagger-codegen version

swagger-codegen-cli-2.3.1.jar
also happens with 3.0

##### Swagger declaration file content or url

https://bitbucket.org/api/swagger.json

##### Command line used for generation

`java -jar swagger-codegen-cli-2.3.1.jar generate -i bitbucket.json -l dart -o bitbucket_api -c bitbucket_pr_config.json`

**Comment by wouteroostervld** [comment]
Also with swagger 2.2.3. Probably a loop in the bitbucket spec itself. Is there any lint tooling we could use?

**Comment by SunlightDave** [comment]
Loading the swagger.json into http://editor.swagger.io/#/, will analyse a bunch of Structural error's e.g.

`"/repositories/{workspace}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/test_reports/test_cases/{test_case_uuid}/test_case_reasons": {"get": {}},` => missingProperty: responses.

as well as a ton of Semantic Errors e.g.
`{workspace}` => Declared path parameter "workspace" needs to be defined as a path parameter at either the path or operation level
