### ISSUE TITLE
Type error when reading JSON

### ISSUE THREAD

**Issue by bletail** [swagger-api/swagger-codegen#895]
Hello,

An exception is raised when I try to generate code, with any language in output. Either with master or develop_2.0 branch

`java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:49)
	at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:465)
	at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:205)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:570)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:974)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:816)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:352)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:327)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:153)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)`

But when I use v2.1.0-M2 tag version there is only a warning 

`857 [main] WARN com.wordnik.swagger.codegen.DefaultCodegen - warning!  Property type "ref" not found for parameter "ids", using String`

Here is a JSON example

`{
  "apiVersion": "0.1",
  "swaggerVersion": "1.2",
  "resourcePath": "/tags",
  "produces": [
    "application/xml",
    "application/json",
    "application/octet-stream",
    "text/plain"
  ],
  "apis": [
    {
      "path": "/0.1/tags.{format}",
      "operations": [
        {
          "notes": "",
          "summary": "Delete multiple tags.",
          "nickname": "deleteTags",
          "method": "DELETE",
          "parameters": [
            {
              "paramType": "query",
              "name": "ids",
              "description": null,
              "type": "[Integer]",
              "required": true,
              "allowMultiple": false
            }
          ],
          "type": "void"
        }
      ]
    }
  ]
}`

Is this normal ?

**Comment by wing328** [comment]
May I know how you obtain the swagger spec? 

One thing does not seem right to me is the `"type": "[Integer]"`. Here is how to define an array of primitive types in Swagger Spec 1.2:

```
        "photoUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
```

**Comment by frodrigo** [comment]
This is an issue with tim-vandecasteele/grape-swagger, it generate ruby "type: Array[Integer]"  as swagger "type: '[Integer]'"

https://github.com/tim-vandecasteele/grape-swagger/issues/237

**Comment by wing328** [comment]
@frodrigo Thanks for the information. I hope the issue gets addressed soon in `grape-swagger` as I saw someone provided a fix already.
