### ISSUE TITLE
[RETROFIT2] Problem: com.github.jknack.handlebars.HandlebarsException

### ISSUE THREAD

**Issue by MichalDanielDobrzanski** [swagger-api/swagger-codegen#9053]
##### Description
Cannot generate gradle module because of runtime exception with retrofit2.
Using RxJava2 also.

##### Swagger-codegen version
3.0.1

##### Swagger declaration file content or url
I cannot post API, cause it is internal in the company.

```json
Exception in thread "Thread-0" java.lang.RuntimeException: Could not generate api file for 'Department'
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:523)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:722)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/libraries/retrofit2/api_test.mustache:31:8: found: 'ƒ'
    {{#@ƒirst}}
        ^

	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at com.github.jknack.handlebars.internal.HbsParserFactory$2.notifyListeners(HbsParserFactory.java:148)
```

##### Command line used for generation
 swagger-codegen generate -i openapi.json -l java -c config.json -o /Users/mmdo/apis/test/

##### Steps to reproduce
Just run the script

##### Suggest a fix/enhancement
Probably an injection into the script occured

**Comment by zkdzegede** [comment]
Running  into the same problem for `3.0.3`

**Comment by stawil15** [comment]
I'm also getting this error on 3.0.4

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate api file for 'FILENAME'
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:523)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:722)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/libraries/retrofit2/api_test.mustache:31:8: found: 'ƒ'
    {{#@ƒirst}}
        ^

	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at com.github.jknack.handlebars.internal.HbsParserFactory$2.notifyListeners(HbsParserFactory.java:148)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:168)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:185)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:168)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:152)
	at org.antlr.v4.runtime.Parser.consume(Parser.java:593)
	at org.antlr.v4.runtime.Parser.match(Parser.java:226)
	at com.github.jknack.handlebars.internal.HbsParser.sexpr(HbsParser.java:884)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:657)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getHandlebars(HandlebarTemplateEngine.java:48)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:24)
	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:735)
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:498)
	... 3 more

```

**Comment by kmhughes** [comment]
Same here: 3.0.5-SNAPSHOT

**Comment by DevYoungHulk** [comment]
Same issue with version 3.0.5.
```
15:40:30.621 [Thread-1] DEBUG com.github.jknack.handlebars.internal.HbsParserFactory - About to parse: /handlebars/Java/libraries/retrofit2/api_test.mustache
15:40:30.621 [Thread-1] DEBUG com.github.jknack.handlebars.internal.HbsParserFactory - Building AST
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate api file for 'AppConfigurationController'
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:523)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:722)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/libraries/retrofit2/api_test.mustache:31:8: found: 'ƒ'
    {{#@ƒirst}}
        ^

	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at com.github.jknack.handlebars.internal.HbsParserFactory$2.notifyListeners(HbsParserFactory.java:148)
	at org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:168)
	at org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:185)
	at org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:168)
	at org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:152)
	at org.antlr.v4.runtime.Parser.consume(Parser.java:593)
	at org.antlr.v4.runtime.Parser.match(Parser.java:226)
	at com.github.jknack.handlebars.internal.HbsParser.sexpr(HbsParser.java:884)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:657)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:670)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:336)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getHandlebars(HandlebarTemplateEngine.java:48)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:24)
	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:735)
	at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:498)
	... 3 more
```

**Comment by kmhughes** [comment]
Does anyone know where these handlebar templates exist? I have built the code generator myself and just don't see where the templates are.

**Comment by HugoMario** [comment]
@kmhughes , templates are here https://github.com/swagger-api/swagger-codegen-generators/tree/master/src/main/resources/handlebars

**Comment by kmhughes** [comment]
Cool, thanks. I went looking and never found them, but apparently didn't look hard enough. Sigh.

**Comment by mercuriete** [comment]
same problem

**Comment by bobpf** [comment]
Same issue here

**Comment by simon-maling** [comment]
I experienced the same issues, after some research I found that the issue has already been fixed in swagger generator v1.0.7.
See https://github.com/swagger-api/swagger-codegen-generators/pull/318

**Comment by thanhdt251099** [comment]
i have same issue here :(( help meee
