### ISSUE TITLE
Generate Spring Client - NullPointerException

### ISSUE THREAD

**Issue by EarthCitizen** [swagger-api/swagger-codegen#9101]
##### Description

Generating a spring client fails with NullPointerException and no explanation as to what is wrong.

```
Exception in thread "Thread-1" java.lang.NullPointerException
	at io.swagger.codegen.v3.generators.java.SpringCodegen.preprocessOpenAPI(SpringCodegen.java:421)
	at io.swagger.codegen.v3.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:190)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:713)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
	at java.lang.Thread.run(Thread.java:745)
```

Full output here:

https://gist.github.com/EarthCitizen/9c03901e21ba588a4ce22a6824ff9ac8

##### Swagger-codegen version

3.0.4

##### Swagger declaration file content or url

```yaml
openapi: '3.0.0'
into:
  title: Records OpenAPI document
  version: 1.0.0

components:
  schemas:
    Record:
      type: object
      properties:
        id:
          type: integer
          format: int64
        code:
          type: string
        info:
          type: string

paths:
  /records:
    get:
      description: Get the records
      responses:
        '200':
          description: A list of records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Record'
```

##### Command line used for generation

```
spring-client $ swagger-codegen generate -v -l spring -i ../openapi.yaml
```

##### Steps to reproduce

Execute above command.

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/4625

##### Suggest a fix/enhancement

The output should specify what is missing instead of simply generating a NPE.

**Comment by darshannagaraja** [comment]
I too am facing this problem. Any resolution for this. It's throwing a NPE without any details, despite running with -e option on mvn
