### ISSUE TITLE
[CSHARP] v3.x with csharp generator crashes when schema inheritence has length more than 2

### ISSUE THREAD

**Issue by rjvdboon** [swagger-api/swagger-codegen#9126]
##### Description

When I have a openapi schema where an object has an allOf on another object that also has an allOf, then the cli crashes with an exception when generating csharp, but succeeds when generating java or csharp-dotnet2.
The exception thrown is:
```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not process model 'Detailed'.Please make sure that your schema is correct!
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:354)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:719)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1298)
        at io.swagger.codegen.v3.generators.dotnet.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:515)
        at io.swagger.codegen.v3.generators.DefaultCodegenConfig.fromModel(DefaultCodegenConfig.java:1205)
        at io.swagger.codegen.v3.generators.dotnet.CSharpClientCodegen.fromModel(CSharpClientCodegen.java:519)
        at io.swagger.codegen.v3.DefaultGenerator.processModels(DefaultGenerator.java:951)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:349)
        ... 3 more
```

I noticed it when generating csharp code for [Strava](http://developers.strava.com/swagger/swagger.json)
Many other generators work fine on this spec (tried java, kotlin, php, html, typescript, scala, openapi, openapi-yaml)

##### Swagger-codegen version

Tested with `swagger-codegen-cli-3.0.4.jar` (from http://central.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.4/swagger-codegen-cli-3.0.4.jar) and `swagger-codegen-cli-3.0.5-20190126.183445-23.jar` (from Snapshot).
The csharp generator used to work on 2.4.1.
The attached minimal test unfortunately doesn't work with 2.4.1 (as it is openapi v3), but you can point it to the strava url and observe it as well.

##### Swagger declaration file content or url

See https://gist.github.com/rjvdboon/d6c293a3a93666c41d1def76917b6fb7#file-testapi-json for a minimal sample, or http://developers.strava.com/swagger/swagger.json for a larger spec.

##### Command line used for generation

`java -jar swagger-codegen-cli-3.0.4.jar generate -i testapi.json -l csharp -o testapi\csharp\304`
and
`java -jar swagger-codegen-cli-3.0.4.jar generate -i http://developers.strava.com/swagger/swagger.json -l csharp -o strava\csharp\304`

##### Steps to reproduce

Download any v3.04 or 3.0.5 snapshot jar from https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/
Download the reproduction testapi.json
Generate csharp code

**Comment by rjvdboon** [comment]
The crash seems to be resolved in at least 3.0.16. It still doesn't generate compilable code though, but that is another issue.
