### ISSUE TITLE
[Typescript-Angular] Generate client code with rxjs for Angular6+

### ISSUE THREAD

**Issue by twopelu** [swagger-api/swagger-codegen#9227]
##### Description

**Feature Request**

The client code generated for typescript-angular uses old version of rxjs which is not supported in Angular6+ projects. To make it work you have to manually install rxjs-compat package with npm: `npm install rxjs-compat`.

##### Swagger-codegen version

Swagger Hub

##### Swagger declaration file content or url

Find attached the api definition in yml:

[openapi.zip](https://github.com/swagger-api/swagger-codegen/files/2923331/openapi.zip)

Code generated with Swagger Hub:

[typescript-angular-client-generated.zip](https://github.com/swagger-api/swagger-codegen/files/2923330/typescript-angular-client-generated.zip)

##### Command line used for generation

Error in `ng build`:

```
BUILD ERROR
diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
diary-shit-client-lib/src/lib/api/diary.service.ts(19,10): error TS2305: Module '"D:/DANI/vscode/dairy-shit-libs/node_modules/rxjs/Observable"' has no exported member 'Observable'.

Error: diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
diary-shit-client-lib/src/lib/api/diary.service.ts(19,10): error TS2305: Module '"D:/DANI/vscode/dairy-shit-libs/node_modules/rxjs/Observable"' has no exported member 'Observable'.

    at Object.<anonymous> (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>

diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
diary-shit-client-lib/src/lib/api/diary.service.ts(19,10): error TS2305: Module '"D:/DANI/vscode/dairy-shit-libs/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```

##### Steps to reproduce

0. Generate code with Swagger Hub from yml file (see attached)
1. Download generated code for typescript-angular (see attached)
2. Create new angular project with ng-cli and copy generated code
3. Compile with ng build - see errors in console

##### Suggest a fix/enhancement

Generate the client code with the latest versions of rxjs for Angular6+.

**Comment by Shmarkus** [comment]
the simple fix is to use rxjs-compat library:
```npm i rxjs-compat```

**Comment by twopelu** [comment]
That is a solution, but it may lead to some dependency issues.

Moving to an updated version of rxjs sounds like a good idea.

**Comment by cmalard** [comment]
It works out-of-the-box with codegen-v3, just try it :-)
-> https://gist.github.com/cmalard/26417cf044764885099e2c6f2d927009

**Comment by niblux** [comment]
I had the following error after using swagger codegen.

The swagger was generated using the swagger-cli docker image 
```"docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli:2.4.15 generate -i <your-swagger-api-url> -l typescript-angular -o /local/src/app/core/api"```



running ng build gave a whole bunch of errors many of them like the one below.

```error TS2305: Module '"../../../node_modules/rxjs/Observable"' has no exported member 'Observable'. 19 import { Observable } from 'rxjs/Observable';```

changing ``` 'rxjs/Observable'``` to ``` 'rxjs'``` satisfied the linter and built successfully.

Not sure how much help this would be to this issue, but i did come across this issue feed whilst searching for a resolve to the above error.

**Comment by twopelu** [comment]
> I had the following error after using swagger codegen.
> 
> The swagger was generated using the swagger-cli docker image
> `"docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli:2.4.15 generate -i <your-swagger-api-url> -l typescript-angular -o /local/src/app/core/api"`
> 
> running ng build gave a whole bunch of errors many of them like the one below.
> 
> `error TS2305: Module '"../../../node_modules/rxjs/Observable"' has no exported member 'Observable'. 19 import { Observable } from 'rxjs/Observable';`
> 
> changing ` 'rxjs/Observable'` to ` 'rxjs'` satisfied the linter and built successfully.
> 
> Not sure how much help this would be to this issue, but i did come across this issue feed whilst searching for a resolve to the above error.
> 
> Always worth a try :)

Maybe you are missing the rxjs/compat 
or rxjs dependencies in your project, check that you have them installed.
