### ISSUE TITLE
[Regression 3.0.6] [Java]  CodegenContent cannot be cast to io.swagger.codegen.v3.VendorExtendable

### ISSUE THREAD

**Issue by shoffmeister** [swagger-api/swagger-codegen#9304]
swagger-codegen-cli-3.0.6.jar regresses relative to 3.0.5 and throws an exception "com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/libraries/resttemplate/api.mustache:110:61: java.lang.ClassCastException: io.swagger.codegen.v3.CodegenContent cannot be cast to io.swagger.codegen.v3.VendorExtendable" upon processing a specific file.

Steps to reproduce:
* download attached packaged.tar.gz
* tar xzvf packaged.tar.gz
* "run.bash"

The shell script will download codegen-cli 3.0.6 from the Apache maven repo, then attempt to generate code for a trivial yaml, specifically

```
swagger: '2.0'
basePath: "/"
info:
  version: "1"
  title: "x"

schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /data:
    get:
      operationId: "getData"
      parameters:
      - $ref: '#/parameters/unixTimestampQuery'
      responses:
        '403':
          description: Forbidden
parameters:
  unixTimestampQuery:
    in: query
    name: unixTimestamp
    type: integer
    format: int64
``` 

Result:
```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate api file for 'Default'
        at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:523)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:722)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/libraries/resttemplate/api.mustache:110:61: java.lang.ClassCastException: io.swagger.codegen.v3.CodegenContent cannot be cast to io.swagger.codegen.v3.VendorExtendable
    /handlebars/Java/libraries/resttemplate/api.mustache:110:61
        at io.swagger.codegen.v3.generators.handlebars.ExtensionHelper.apply(ExtensionHelper.java:11)
        at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
        at com.github.jknack.handlebars.Options.apply(Options.java:538)
        at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:72)
        at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
        at com.github.jknack.handlebars.Options.apply(Options.java:538)
        at com.github.jknack.handlebars.helper.EachHelper.apply(EachHelper.java:72)
        at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
        at com.github.jknack.handlebars.Options.apply(Options.java:538)
        at com.github.jknack.handlebars.Options.fn(Options.java:445)
        at com.github.jknack.handlebars.helper.WithHelper.apply(WithHelper.java:58)
        at com.github.jknack.handlebars.internal.Block.merge(Block.java:211)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
        at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
        at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:25)
        at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:735)
        at io.swagger.codegen.v3.DefaultGenerator.generateApis(DefaultGenerator.java:482)
        ... 3 more
Caused by: java.lang.ClassCastException: io.swagger.codegen.v3.CodegenContent cannot be cast to io.swagger.codegen.v3.VendorExtendable
        ... 35 more
```

This is a regression relative to 3.0.5

[packaged.tar.gz](https://github.com/swagger-api/swagger-codegen/files/3006933/packaged.tar.gz)

**Comment by shoffmeister** [comment]
Note that the above steps are exactly the same as the ones that were used to reproduce #8874 - I'd expect #8874 to be fixed now, but can't try because of this new / different regression here.

**Comment by barney2k7** [comment]
This issue seems to have been introduced here: https://github.com/swagger-api/swagger-codegen/pull/9238/commits/9f156bb52bc9c689c765973fa588a322a3a1d1a2

**Comment by HugoMario** [comment]
hi   @shoffmeister @barney2k7 ,  FYI working in a fix right now.

**Comment by HugoMario** [comment]
@shoffmeister @barney2k7 i just added a PR solving this. Can you please check when you have a chance?

**Comment by shoffmeister** [comment]
Very quick response, cool!

So basically `#has this 'more'` morphed into `/hasMore`? Is this the case everywhere? Case in point:

https://github.com/swagger-api/swagger-codegen-generators/blob/d15266c8ef8be8ab80817f2d9bed6eca1a06f421/src/main/resources/handlebars/Java/api_test.mustache#L43

**Comment by shoffmeister** [comment]
With the 3.0.8 release, this problem no longer occurs.

Many thanks!
