### ISSUE TITLE
Python code generation not working when point to external template directory

### ISSUE THREAD

**Issue by wiliamsouza** [swagger-api/swagger-codegen#9363]
##### Description

Python code generation not working when point to external template directory

##### Swagger-codegen version

* 3.0.8-SNAPSHOT
* 3.0.7

##### Swagger declaration file content or url

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml

##### Command line used for generation

```bash
java -jar swagger-codegen-cli-3.0.8-SNAPSHOT.jar generate -t /home/waa/devel/swagger-codegen-generators/src/main/resources/handlebars/python/ -c client.json -l python -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -o pet
```
Tried different paths to template option `-t`:

* -t /home/waa/devel/swagger-codegen-generators/src/main/resources/ 
* -t /home/waa/devel/swagger-codegen-generators/src/main/resources/handlebars/

##### Steps to reproduce

Run `generate` command pointing to template folder cloned from `swagger-codegen-generators` master branch.

##### Suggest a fix/enhancement

Fix the exception:

```
11:51:16.434 [Thread-1] WARN io.swagger.codegen.v3.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
11:51:16.506 [Thread-1] WARN io.swagger.codegen.v3.generators.DefaultCodegenConfig - String to be sanitized is null. Default to Object
11:51:16.522 [Thread-1] WARN io.swagger.codegen.v3.generators.DefaultCodegenConfig - String to be sanitized is null. Default to Object
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'Error'
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:405)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:732)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: handlebars/python/model.mustache
        at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
        at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getHandlebars(HandlebarTemplateEngine.java:48)
        at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:24)
        at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:748)
        at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:392)
        ... 3 more
```

**Comment by torston** [comment]
Same issue for me

**Comment by wiliamsouza** [comment]
@torston  Changing the path do not solve.

```
java -jar swagger-codegen-cli-3.0.8-SNAPSHOT.jar generate -t /home/waa/devel/swagger-codegen-generators/src/main/resources/ -c client.json -l python -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -o pet
```

```
java -jar swagger-codegen-cli-3.0.8-SNAPSHOT.jar generate -t /home/waa/devel/swagger-codegen-generators/src/main/resources/handlebars -c client.json -l python -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -o pet
```

**Comment by edengh** [comment]
Also having this issue with python external templates, and receiving the exact same error.

**Comment by dong-brian** [comment]
seem to be seeing this as well with 3.0.10

**Comment by anselmos** [comment]
Is there any solution for this ? I'm also affected about this and can't move project forward because of this :(

My findings:
- template_dir is not respected
- template_version is required when using template_dir ? (mustache/handlebars ?)

CC @HugoMario

**Comment by anselmos** [comment]
Ok found that there is actually 2 options for templates :  
`--template-version`  and `--template-engine`

And adding `--template-engine "mustache"` works for me.

So calling : 

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -t /home/anselmos/projects/swagger-codegen-generators/src/main/resources/handlebars -c client.json -l python -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -o pet --template-engine "mustache"
```
where you can change `modules/swagger-codegen-cli/target/swagger-codegen-cli.jar ` into path where swagger-code-cli.jar is placed.

cc @wiliamsouza

**Comment by anselmos** [comment]
Unfortunatelly as I've tried to modify files in template_dir - it looks like it's not used by the generator so it ommits some-how without even notice.

Here's a full log: 

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate    -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml    -l python-flask -o /tmp/python-flask -t /home/anselmos/projects/swagger-codegen-generators/src/main/resources/mustache/pythonFlaskConnexion  --template-version v3 --template-engine mustache -s False -v > debug.log

```

[debug.log](https://github.com/swagger-api/swagger-codegen/files/3496861/debug.log)


@HugoMario any ideas why modifying mustache templates and adding them as --template_dir (-t) with --template-engine "mustache" seems to ommit them and generate the files from original templates ?

**Comment by anselmos** [comment]
As a workaround I've builded `swagger-codegen-generators` as a separeted lib with changed tempaltes, then connected it to `swagger-codegen` at pom.xml to use the changed file.


the pom.xml of `swagger_codegen` changed similar to this patch: 

```
diff --git a/modules/swagger-codegen/pom.xml b/modules/swagger-codegen/pom.xml
index e9e45ba22..e9bd70eca 100644
--- a/modules/swagger-codegen/pom.xml
+++ b/modules/swagger-codegen/pom.xml
@@ -311,14 +311,21 @@
         <dependency>
             <groupId>io.swagger.codegen.v3</groupId>
             <artifactId>swagger-codegen-generators</artifactId>
-            <version>${swagger-codegen-generators-version}</version>
-            <scope>test</scope>
+            <version>1.0.11-SNAPSHOT</version>
+            <scope>system</scope>
         </dependency>
     </dependencies>
     <repositories>
         <repository>
             <id>sonatype-snapshots</id>
             <url>https://oss.sonatype.org/content/repositories/snapshots</url>
+            <snapshots>
+                <enabled>false</enabled>
+            </snapshots>
+        </repository>
+        <repository>
+            <id>mylibid</id>
+            <url>file://${project.basedir}/lib</url>
             <snapshots>
                 <enabled>true</enabled>
             </snapshots>
diff --git a/pom.xml b/pom.xml
index 14780232d..06279bd46 100644
--- a/pom.xml
+++ b/pom.xml
@@ -1054,7 +1054,11 @@
             <dependency>
                 <groupId>io.swagger.codegen.v3</groupId>
                 <artifactId>swagger-codegen-generators</artifactId>
-                <version>${swagger-codegen-generators-version}</version>
+                <scope>system</scope>
+                <version>1.0.11-SNAPSHOT</version>
+                <systemPath>
+                    /data/swagger-codegen/lib/swagger-codegen-generators-1.0.11-SNAPSHOT.jar
+                </systemPath>
             </dependency>
             <!-- jackson -->
             <dependency>
@@ -1159,9 +1163,16 @@
                 <enabled>true</enabled>
             </releases>
         </repository>
+        <repository>
+            <id>mylibid</id>
+            <url>file://${project.basedir}/lib</url>
+            <snapshots>
+                <enabled>true</enabled>
+            </snapshots>
+        </repository>
     </repositories>
     <properties>
-        <swagger-codegen-generators-version>1.0.10</swagger-codegen-generators-version>
+        <swagger-codegen-generators-version>1.0.11-SNAPSHOT</swagger-codegen-generators-version>
         <swagger-core-version>2.0.8</swagger-core-version>
         <swagger-core-version-v1>1.5.22</swagger-core-version-v1>
         <swagger-parser-version>2.0.13</swagger-parser-version>

```


After that the "generate" tool is used like this:
```
java -cp modules/swagger-codegen/target/swagger-codegen-3.0.10.jar:modules/swagger-codegen-cli/target/swagger-codegen-cli.jar:lib/swagger-codegen-generators-1.0.11-SNAPSHOT.jar \
  io.swagger.codegen.v3.cli.SwaggerCodegen  generate  -l io.swagger.codegen.v3.generators.python.PythonFlaskConnexionCodegen \
  -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml \
  --template-engine "mustache" \
  -o /tmp/pythontest
```

**Comment by HugoMario** [comment]
hello @wiliamsouza, this issue has been fixed with this [PR](https://github.com/swagger-api/swagger-codegen-generators/pull/445). so i'm going to close this ticket but i'll be attend if you still got the issue.
