### ISSUE TITLE
[html2] template-dir option is not working

### ISSUE THREAD

**Issue by lagebaue** [swagger-api/swagger-codegen#9521]
##### Description
The generator works fine without the template-dir option, but if it is set it crashes with the following error (doesn't even matter if there are any files in the folder or not, as long as the folder exists).

```
Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
        templateFile: index.mustache
        folder:
        destinationFilename: index.html
'
        at io.swagger.codegen.v3.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:636)
        at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:763)
        at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:342)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: handlebars/htmlDocs2/index.mustache
        at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
        at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
        at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getHandlebars(HandlebarTemplateEngine.java:48)
        at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:24)
        at io.swagger.codegen.v3.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:607)
        ... 3 more
```

##### Swagger-codegen version
3.0.8

##### Command line used for generation

```
$ java -jar ./dist/swagger-codegen-cli-3.0.8.jar generate -i docs/openapi.yaml -l html2 -o dist/html2 --template-dir docs/htmlDocs2
```

##### Steps to reproduce

1. execute the above command while template-dir is pointing to an existing directory

##### Related issues/PRs

This seems to be identical to [this problem](https://github.com/swagger-api/swagger-codegen/issues/8964) for the html generator.

**Comment by anselmos** [comment]
As mentioned in https://github.com/swagger-api/swagger-codegen/issues/9363 - try with adding this parameter:  `--template-engine "mustache"
@lagebaue

**Comment by HugoMario** [comment]
@lagebaue , i merge this [PR](https://github.com/swagger-api/swagger-codegen-generators/pull/445) to solve this issue, i'm going to close it, but please let me know if if you still get the error to reopen it.
