### ISSUE TITLE
[Java] swagger-codegen 3.0.8 build failed on archlinux

### ISSUE THREAD

**Issue by Xuanwo** [swagger-api/swagger-codegen#9545]
##### Description

swagger-codegen 3.0.8 build failed on archlinux.

> 3.0.9 has the same problem.

##### Swagger-codegen version

3.0.8

##### Steps to reproduce

Archlinux AUR: https://aur.archlinux.org/packages/swagger-codegen/

Download snapshot: https://aur.archlinux.org/cgit/aur.git/snapshot/swagger-codegen.tar.gz

```bash
cd swagger-codegen && extra-x86_64-build
```

Error log:

```
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 11, Time elapsed: 13.506 s <<< FAILURE! - in TestSuite
[ERROR] setUp(io.swagger.codegen.v3.utils.URLPathUtilTest)  Time elapsed: 1.324 s  <<< FAILURE!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: interface java.util.List.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 12
JVM vendor name    : Oracle Corporation
JVM vendor version : 12.0.1+12
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 12.0.1+12
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.18.5-arch1-1-ARCH


Underlying exception : java.lang.IllegalArgumentException: org.mockito.codegenList$MockitoMock$1159180601 must be defined in the same package as org.mockito.codegen.InjectionBase/package
        at io.swagger.codegen.v3.utils.URLPathUtilTest.setUp(URLPathUtilTest.java:32)
Caused by: java.lang.IllegalArgumentException: org.mockito.codegenList$MockitoMock$1159180601 must be defined in the same package as org.mockito.codegen.InjectionBase/package
        at io.swagger.codegen.v3.utils.URLPathUtilTest.setUp(URLPathUtilTest.java:32)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] io.swagger.codegen.v3.utils.URLPathUtilTest.setUp(io.swagger.codegen.v3.utils.URLPathUtilTest)
[ERROR]   Run 1: URLPathUtilTest.setUp:32 Mockito
Mockito cannot mock this class: interface ja...
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]
[INFO]
[ERROR] Tests run: 15, Failures: 1, Errors: 0, Skipped: 6
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for swagger-codegen-project 3.0.9:
[INFO]
[INFO] swagger-codegen-project ............................ SUCCESS [  4.005 s]
[INFO] swagger-codegen (core library) ..................... FAILURE [04:59 min]
[INFO] swagger-codegen (executable) ....................... SKIPPED
[INFO] swagger-codegen (maven-plugin) ..................... SKIPPED
[INFO] swagger-generator .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:05 min
[INFO] Finished at: 2019-07-05T18:40:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (test-testng) on project swagger-codegen: There are test failures.
[ERROR]
[ERROR] Please refer to /build/swagger-codegen/src/swagger-codegen-3.0.9/modules/swagger-codegen/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :swagger-codegen
```

**Comment by PabloEstevez** [comment]
Still same problem. Any plans to fix it?

**Comment by Xuanwo** [comment]
Closed for no progress.

**Comment by LynxN1** [comment]
it worked for me with java 11
