### ISSUE TITLE
Building swagger-codegen v3.0.9 fails on Windows with OpenJDK 12.0.1+12

### ISSUE THREAD

**Issue by dynawink** [swagger-api/swagger-codegen#9578]
Building swagger-codegen v3.0.9 fails with

```
[ERROR] setUp(io.swagger.codegen.v3.utils.URLPathUtilTest)  Time elapsed: 2.825 s  <<< FAILURE!
org.mockito.exceptions.base.MockitoException:

Mockito cannot mock this class: interface java.util.List.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 12
JVM vendor name    : Oracle Corporation
JVM vendor version : 12.0.1+12
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 12.0.1+12
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0


Underlying exception : java.lang.IllegalArgumentException: org.mockito.codegenList$MockitoMock$905905619 must be defined in the same package as org.mockito.codegen.InjectionBase/package
        at io.swagger.codegen.v3.utils.URLPathUtilTest.setUp(URLPathUtilTest.java:32)
Caused by: java.lang.IllegalArgumentException: org.mockito.codegenList$MockitoMock$905905619 must be defined in the same package as org.mockito.codegen.InjectionBase/package
        at io.swagger.codegen.v3.utils.URLPathUtilTest.setUp(URLPathUtilTest.java:32)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR] io.swagger.codegen.v3.utils.URLPathUtilTest.setUp(io.swagger.codegen.v3.utils.URLPathUtilTest)
[ERROR]   Run 1: URLPathUtilTest.setUp:32 Mockito
Mockito cannot mock this class: interface ja...
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]
```

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: c:\Users\user\AppData\Local\Programs\netbeans\java\maven\bin\..
Java version: 12.0.1, vendor: Oracle Corporation
Java home: C:\Users\user\AppData\Local\Programs\jdk-12.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```

**Comment by frantuma** [comment]
fixed in #9609
