### ISSUE TITLE
Exception in thread "Thread-1" java.lang.StackOverflowError swagger-codegen-cli.jar execution issues

### ISSUE THREAD

**Issue by SAKSBP** [swagger-api/swagger-codegen#9579]
Hi, I am trying to build skd from swagger and I am getting the following error

Exception in thread "Thread-1" java.lang.StackOverflowError
        at ch.qos.logback.classic.layout.TTLLLayout.doLayout(TTLLLayout.java:43)
        at ch.qos.logback.classic.layout.TTLLLayout.doLayout(TTLLLayout.java:23)
        at ch.qos.logback.core.encoder.LayoutWrappingEncoder.encode(LayoutWrappingEncoder.java:115)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:230)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.debug(Logger.java:482)

**Comment by webron** [comment]
Please file a new ticket following the issue template so we can assist.

**Comment by SAKSBP** [comment]
We have fixed that, It was caused due to issue in swagger JSON object. An object is referred inside the same object as parent. Thanks
