### ISSUE TITLE
3.0.10 no config class with name go-server

### ISSUE THREAD

**Issue by dinfyru** [swagger-api/swagger-codegen#9616]
swagger-codegen-3.0.10

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate   -i ../specification-front-affiliate/main.yaml   -l go-server   -o ../go-server
```
error
```
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name go-server Available: aspnetcore
csharp
csharp-dotnet2
dynamic-html
html
html2
java
jaxrs-cxf-client
jaxrs-cxf
inflector
jaxrs-cxf-cdi
jaxrs-spec
jaxrs-jersey
jaxrs-di
jaxrs-resteasy-eap
jaxrs-resteasy
spring
nodejs-server
openapi
openapi-yaml
kotlin-client
kotlin-server
php
python
python-flask
scala
scala-akka-http-server
swift3
swift4
typescript-angular

	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:31)
	at io.swagger.codegen.v3.cli.SwaggerCodegen.main(SwaggerCodegen.java:96)
Caused by: java.lang.ClassNotFoundException: go-server
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.swagger.codegen.v3.CodegenConfigLoader.forName(CodegenConfigLoader.java:29)
	... 1 more
```

**Comment by eqinox76** [comment]
Just discovered the same while following the [wiki](https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#go-server)

**Comment by HugoMario** [comment]
thanks for reporting this, `go-server` generator is in plan to be added

**Comment by HugoMario** [comment]
hey guys, [this PR](https://github.com/swagger-api/swagger-codegen-generators/pull/511) was added to address this ticket. So, going to close, but please try `go-server` generator when you have a chance
