### ISSUE TITLE
ApiClient.php missing in generated client SDK

### ISSUE THREAD

**Issue by danny-cassidy** [swagger-api/swagger-codegen#970]
I get the following error when generating PHP client sdk via the codegen:

```
java.io.FileNotFoundException: php/ApiClient.mustache (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at io.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:51)
	at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:35)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:250)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
java.lang.RuntimeException: can't load template php/ApiClient.mustache
	at io.swagger.codegen.AbstractGenerator.getTemplateReader(AbstractGenerator.java:60)
	at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:35)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:250)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
java.lang.RuntimeException: can't load template php/ApiClient.mustache
	at io.swagger.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:44)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:250)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:124)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
```

I just recently cloned the repository. Is there anything I am doing wrong? Here is the command I running for reference:

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ~/swagger/schema.json -l php -o ~/swagger/sdks/php -v
```

**Comment by wing328** [comment]
@danny-cassidy would you please try the "develop_2.0" branch to see if you get the same issue ?

(develop_2.0 branch contains the latest bug fixes and enhancements)

**Comment by danny-cassidy** [comment]
Thanks, I think it is fixed on that branch. I re-packaged with the develop_2.0 branch, and it worked without issue.

**Comment by wing328** [comment]
Also if your endpoint returns a file, you might find the following PR useful:

https://github.com/swagger-api/swagger-codegen/pull/926 (pending)

**Comment by wing328** [comment]
Fixed in master
