### ISSUE TITLE
Python-flask server stub generation fails using anyOf

### ISSUE THREAD

**Issue by kpoman** [swagger-api/swagger-codegen#9882]
##### Description

Example on a requestbody:

```
                    items: 
                      anyOf:
                        - $ref: '#/components/schemas/FingerPosition'
                        - $ref: '#/components/schemas/CameraPose'
```

this fails on python-flask (not on other server stubs) with the following error:

> Error.There was an error generating the servers python-flask code. Please ensure that the definition and all external refs (inc. domains) are valid.

replacing with, for example:

```
                    items: 
                      type: string
```

works

##### Swagger-codegen version

Swagger Codegen to v. 2.4.9 for OpenAPI 2.0 and 3.0.13 for OpenAPI 3.0.

**Comment by zhanwenchen** [comment]
In my attempt, only 3.0.11 works:

```sh
brew uninstall swagger-codegen
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/97a2d874969562f687e3e3b004abe64c197278aa/Formula/swagger-codegen.rb
```

**Comment by mw-root** [comment]
Is there any update on this one? This seems like a fairly important function and we would love to be able to use in our swagger defs.

**Comment by mw-root** [comment]
Tried this again today using editor.swagger.io and the codegen jar and still have failures.

```
  schemas:
    request:
      type: object
      properties:
        type: 
          type: string
          enum:
          - one
          - other
        parameters:
          anyOf:
          - $ref: '#/components/schemas/one_property_type' 
          - $ref: '#/components/schemas/another_property_type' 
    one_property_type:
      type: object
      properties:
        one_thing:
          type: string
    another_property_type:
      type: object
      properties:
        another_thing:
          type: string
```

The models and imports seem to be malformed
```
(venv) [mike@localhost tempytemp]$ python -m swagger_server
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mike/tempytemp/swagger_server/__main__.py", line 5, in <module>
    from swagger_server import encoder
  File "/home/mike/tempytemp/swagger_server/encoder.py", line 4, in <module>
    from swagger_server.models.base_model_ import Model
  File "/home/mike/tempytemp/swagger_server/models/__init__.py", line 10, in <module>
    from swagger_server.models.request import Request
  File "/home/mike/tempytemp/swagger_server/models/request.py", line 9, in <module>
    from swagger_server.models.object import Object  # noqa: F401,E501
ModuleNotFoundError: No module named 'swagger_server.models.object'
```

My whole swagger:
```
---
openapi: "3.0.0"
info:
  title: "Test"
  description: "test"
  version: "1.0.0"
servers:
- url: localhost:8080
paths:
  /test:
    post:
      summary: test
      requestBody:
        $ref: '#/components/requestBodies/my_request_body'
      responses:
        200:
          $ref: '#/components/responses/success'
        500:
          $ref: '#/components/responses/error'
components:
  requestBodies:
    my_request_body:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/request'
  responses:
    success:
      description: "Successful Response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/success"
    error:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  schemas:
    request:
      type: object
      properties:
        type: 
          type: string
          enum:
          - one
          - other
        parameters:
          anyOf:
          - $ref: '#/components/schemas/one_property_type' 
          - $ref: '#/components/schemas/another_property_type' 
    one_property_type:
      type: object
      properties:
        one_thing:
          type: string
    another_property_type:
      type: object
      properties:
        another_thing:
          type: string
    success:
      type: object
    error:
      type: object
```
