### ISSUE TITLE
[javascript]FileNotFoundException: /javascript/model.mustache 

### ISSUE THREAD

**Issue by virendrasinghpawar** [swagger-api/swagger-codegen#9909]
`swagger-codegen generate -i http://petstore.swagger.io/v2/swagger.json -l javascript`

Exception in thread "Thread-1" java.lang.RuntimeException: Could not generate model 'ApiResponse'
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:455)
	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:783)
	at io.swagger.codegen.v3.cli.cmd.Generate.run(Generate.java:351)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /javascript/model.mustache
	at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:438)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:419)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getHandlebars(HandlebarTemplateEngine.java:48)
	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:24)
	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:799)
	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:442)
	... 3 more

**Comment by mihaigabriel1992** [comment]
Happens to me as well, any suggestions?

**Comment by frantuma** [comment]
fixed in swagger-api/swagger-codegen-generators/pull/562
